### ISSUE TITLE
muliselect attributes are not being indexed

### ISSUE THREAD

**Issue by superdav42** [Smile-SA/elasticsuite#1014]
### Preconditions

Magento Version : 2.2.5

ElasticSuite Version : 2.5.14

Environment : Developer

Third party modules :  AvS_DisableModules Cart2Cart_PasswordMigrationToMagento2 Infortis_Infortis Infortis_Brands Infortis_Cgen Infortis_Dataporter Infortis_Base Infortis_UltraSlideshow Infortis_UltraMegamenu MSP_Common MSP_DevTools Aheadworks_Autorelated BrainActs_RewardPoints Infortis_Ultimo Aheadworks_Sarp Mageplaza_Core Mageplaza_Smtp Pmclain_AuthorizenetCim

### Steps to reproduce
1. Create a muliselect attribute
2. Add some values
3. Add some products with the value
4. Perform site search with query equal to one of the multiselect values

### Expected result
Products with multiselect values select show up in site search

### Actual result
The product does not show up

This is probably related to https://github.com/magento/magento2/issues/13972 but the fix for that did not solve it with elasticsuite. I dug around a while but couldn't find out how the data for attributes is retrieved by the indexer in elasticsuite, it doesn't seem to use the same DataProviders.

**Comment by romainruaud** [comment]
Hello, it's working like a charm on our demo env : http://demo.magento-elastic-suite.io/index.php/catalogsearch/result/?q=polyester ("polyester" is a value of the "material" attribute which is a multiselect)

So I strongly suspect a misconfiguration by your side, or a side-effect due to third party modules.

Can you please ensure that : 

- your attribute is set as "Used in search"
- your catalog is reindexed

Regards

**Comment by superdav42** [comment]
Turns out it was a problem on our site because we were using a custom backend model for our multiselect attribute. I made a PR which should help others in the future https://github.com/Smile-SA/elasticsuite/pull/1017

**Comment by afoucret** [comment]
So I suppose we can close this one in favor of #1017
