### ISSUE TITLE
Unable to Use elasticsuite

### ISSUE THREAD

**Issue by kumarna123** [Smile-SA/elasticsuite#1024]
Unable Install elasticsuite its giving error "[ErrorException] chmod(): Operation not permitted" - Im new to Magento

### Preconditions

Magento Version : 2.2.5
ElasticSuite Version : 2.5.9

### Steps to reproduce
1. Installing using composer via SSH

### Expected result
1. Successful install

### Actual result
1. [ErrorException] chmod(): Operation not permitted
Screenshot: ((https://user-images.githubusercontent.com/42054067/43623526-51218e92-96ff-11e8-8d2f-ae857d3d4592.png)

**Comment by romainruaud** [comment]
Hello @kumarna123 

I'm sorry but the issue you are encountering is mostly related to Magento itself and not Elasticsuite.

Please have a look at the Magento installation guide, especially the part related with permissions : https://devdocs.magento.com/guides/v2.2/config-guide/prod/prod_file-sys-perms.html

Regards,

I close your issue since not related to Elasticsuite.
