### ISSUE TITLE
Infortis Ultimo Version 2.8.0 and elasticsuite

### ISSUE THREAD

**Issue by dmarkos** [Smile-SA/elasticsuite#1028]
Hello,

With great sadness I found out that our theme is incompatible with elasticsuite. Such a bummer! 
However, I just found out that they (infortis ultimo) updated their theme in Version 2.8.0 on July 22, 2018. So, hoping that now I can finally use elasticsuite, does anyone know if the incompatibility issue is resolved?

**Comment by tf25** [comment]
@dmarkos , I think you should ask author of Ultimo to get support.
I found a theme support Elasticsuite:
https://www.magebig.com/martfury-magento-theme.html
Maybe you can like it.

**Comment by dmarkos** [comment]
Well, I have contacted them and they claim that they do not provide support for third-party modules. However, we sadly went with their theme for quite some time now. So a theme-change is not a priority. 

From what I gather the main problem resides in the homepage, right? But isn't elasticsuite a module for the category-view? Is category-view unaffected?

**Comment by tf25** [comment]
I think most themes are incompatible by one of the two issues:
 - They're customized form search or used other search engine.
 - They're used other Layered Navigation extension, so it's conflict with Layered of Elasticsuite.

**Comment by romainruaud** [comment]
Hello fellow users,

last year I dug into Infortis_Ultimo theme to find out what could cause the homepage to break with Elasticsuite, since the engine is not used on the homepage.

Here is what I found : https://github.com/Smile-SA/elasticsuite/issues/330#issuecomment-286827473

I also gave a solution to fix what they do in the "FeaturedProducts" block on the homepage.

Not sure if anyone did communicate this quick fix to them.

There was also an issue with quick-search form that was fixed by @ukomiljon in this comment : 

https://github.com/Smile-SA/elasticsuite/issues/477#issuecomment-376725056


Unfortunately, we do not provide support for third-party modules in our open source support policy, so investigating and providing the first quickfix was already out of my scope.

We can provide commercial support if you really need to properly integrate our two modules. You can contact me by mail if you feel that you'll need such a support.

Regards.

I close the issue since it's out of the scope of Open Source Support we provide here.
