### ISSUE TITLE
Filter Layered Navigation is not display actual result.

### ISSUE THREAD

**Issue by magentounit2** [Smile-SA/elasticsuite#1035]
I have set custom conditions for my requirement and I have created plugin from **\Magento\Catalog\Model\Layer** with `public function afterGetProductCollection(\Magento\Catalog\Model\Layer $subject,$result)
    {
    $getProductUniqueIds = array(1,2,3,4,5);
    $result->addAttributeToFilter('entity_id',array('in' => $getProductUniqueIds)); return $result; }`

Using above conditions, I have display Product collection properly but Layered navigation is not display based on above conditions. Its display old layered navigation without considering filter conditions.

![layer-navigation](https://user-images.githubusercontent.com/28340827/41760155-a9299c3a-760f-11e8-9e20-42ed71eac5a7.png)

Would I need to set above product collection conditions to other files also? or What's the problem with my custom conditions in layer.php with plugins?

Any help regarding above criteria @romainruaud 

Thanks.

**Comment by romainruaud** [comment]
Hello @magentounit2 

you are plugging "too late" because at the step of the "afterGetProductCollection", the request to Elasticsearch has been already made, and the layer filters and toolbar have been already populated according to the result of the ES query.

You should have your plugin on `beforePrepareProductCollection` if you want to apply additional filtering.

Regards

**Comment by romainruaud** [comment]
I close this one since I provided an answer and received no response from more than one week.

Regards
