### ISSUE TITLE
Virtual Categories preview showing empty list.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#104]
This issue seems to occurs on multiple websites instance.

Symptoms : 

- when building a virtual category in back-office, the preview remains always empty "Your product selection is empty".

- the virtual category in front office is fine, displaying products matching the rule that have been set in the back-office.

**Comment by romainruaud** [comment]
I cannot reproduce this issue.

Even in a multiple website/store instance.

@vo1 could you come back to us to give us more details ?

Regards,

**Comment by romainruaud** [comment]
Closed due to 1 week without any update.

@vo1 feel free to reopen this issue if needed.

**Comment by afoucret** [comment]
I was able to reproduce this issue when installing sample data are installed after the module.
The reason is that some category are created with the is_anchor attribute set to false.

It is impossible to have this with ElasticSuite.

A quick patch is to update the is_anchor attribute into the database: 

```
UPDATE catalog_category_entity_int SET value = 1 WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code LIKE '%is_anchor%');
```

If you have custom code (mostly import for categories), check the is_anchor attribute is set to 1.
