### ISSUE TITLE
Product count in layered navigation does not match the product results

### ISSUE THREAD

**Issue by anthonydangbi** [Smile-SA/elasticsuite#1044]
Smile Elasticsuite layered navigation filter pushes incorrect data into Elasticsearch and the count does not match the results displayed. 

### Preconditions

Magento Version : 2.2.5

ElasticSuite Version : 5.5.3

Environment : Both

Third party modules : 

### Steps to reproduce

1. Goto Category page
2. Adjust price slider or other attributes
3. Total Count mismatches Product results

### Expected result

1. Total count matches product results

### Actual result

1. [Screenshot, logs]
![2018-08-19_1724](https://user-images.githubusercontent.com/20453582/44508365-5ea4fc00-a6f1-11e8-96fe-e6b69e2d666f.png)

```
[820] => Array
        (
            [count] => 2
        )

    [923] => Array
        (
            [count] => 1
        )

    [927] => Array
        (
            [count] => 1
        )

    [932] => Array
        (
            [count] => 1
        )
```

**Comment by romainruaud** [comment]
Hello @anthonydangbi 

can you please precise the proper version of the Elasticsuite module ? 5.5.3 is probably your Elasicsearch version, but not the module one.

Is it happening on price slider only ? or with any other attribute ?

What is the "member price" and how is it calculated ?

Regards

**Comment by anthonydangbi** [comment]
Hi Romain,

Thanks for the prompt response!

Elasticuite module is 2.4.0

The issue is happening on the price slider and on clearance.

The "Member" price is calculated as tier pricing.

The "Now" price is special price





--


[image: Logo]

Anthony Dang

Project Manager

1300 624 368 <https://mail.google.com/mail/u/0/#m_9153647613429663611_>

www.balanceinternet.com.au

Melbourne
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

58 Rupert St
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

Collingwood VIC 3066
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

Sydney
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>

59 Marlborough St
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>

Surry Hills NSW 2010
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>


[image: Logo]

**Comment by anthonydangbi** [comment]
Hi Support,

We’ve entered into our final QA / UAT phase and expecting to be go-live
ready within the next 4 weeks.

In order to get to that point we’d need to have validated this
functionality within the next week.

Is there any update on the issue? Thanks



--


[image: Logo]

Anthony Dang

Project Manager

1300 624 368 <https://mail.google.com/mail/u/0/#m_9153647613429663611_>

www.balanceinternet.com.au

Melbourne
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

58 Rupert St
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

Collingwood VIC 3066
<https://maps.google.com/?q=Melbourne+58+Rupert+St+Collingwood+VIC+3066&entry=gmail&source=g>

Sydney
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>

59 Marlborough St
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>

Surry Hills NSW 2010
<https://maps.google.com/?q=Sydney+59+Marlborough+St+Surry+Hills+NSW+2010&entry=gmail&source=g>


[image: Logo]

**Comment by romainruaud** [comment]
@anthonydangbi 

covering deadlines is not something we can provide as part of our Open Source support on this github.

Also, since based only on a screenshot it's steel unclear for me what could cause this behavior, I would need to have access to the server to dig more on several things :

- what is stored in catalog_product_index_price table, since Elasticsuite is relying on these data to build the search index

- what is actually stored in Elasticsearch for the products you are showing in example

- understand better what is the "members price" and how it should (or should not) be used for indexing/filtering

According to the specific use case and the deadline demand we cannot cover this topic as part of our Open Source support, but we can offer you professional service (commercial support) if you are interested.

If this is something that can interest you, feel free to send an email to fabien.gasser@smile.fr and fabrice.dewasmes@smile.fr and they will contact you in return to give you a proposal about how we can work on this topic.

Regards

**Comment by afoucret** [comment]
We were not able to reproduce your issue and you does not answer to give more detail the issue.
It does not seems the bug is caused by ElasticSuite.
I close but feel free to reopen if you can share more detail.
