### ISSUE TITLE
Question / Doc: Right place to add a filter to all category / search queries

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1058]
We want to add a global filter to all search query, essentially filtering out products with the attribute `custom_show != 1`

I have read https://github.com/Smile-SA/elasticsuite/wiki/Querying but something is not yet clear to me.

And as a proof-of-concept I have added

        $this->addFieldToFilter('custom_show', 1);

To \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::__construct

Of course this does not make much sense on the long run.

What is the proposed way to run such global filters?

**Comment by afoucret** [comment]
@romainruaud : let you describe the new filtering mechanism added to the search configuration in our latest release 2.6.0.

**Comment by amenk** [comment]
That sounds good ... otherwise I would go with a load() plugin...

https://magento.stackexchange.com/questions/240751/can-i-call-addfieldtofilter-via-di-xml-set-a-global-filter-on-product-collect

**Comment by amenk** [comment]
thanks @afoucret 
Can't wait to hear how it works @romainruaud

**Comment by romainruaud** [comment]
Hello @amenk 

Since Elasticsuite 2.6.0 we introduced the concept of "Search Context". This allow to define "persistent" filters via XML files, so they will be applied any time a search request is made.

Eg. we are actually managing the "visibility" and "stock status" like this now : 
```xml
<request name="catalog_view_container" label="Category Product View" index="catalog_product" type="product" fulltext="false">
    <filters>
        <filter name="stock">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\Stock</filter>
        <filter name="visible-in-catalog">Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\VisibleInCatalog</filter>
    </filters>
</request>
```

You can see how it's defined in the core here :  https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml

Based on this, you just have to declare your own XML file in one of your modules, and implement your own filter. You can choose to add filtering on all search requests containers or only to specific one (you may want it in categories only, or just in search results, etc...)

You can take a look on our Stock filter which is quite easy to understand : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Search/Request/Container/Filter/Stock.php

You just have to implement the `Smile\ElasticsuiteCore\Api\Search\Request\Container\FilterInterface` which has only one method : `getFilterQuery`.

Since the query filtering is done with Elasticsearch, your field have to exist in the search index.

Once you are sure the field exists, you can implement the `getFilterQuery` like this : 

```php
    /**
     * {@inheritdoc}
     */
    public function getFilterQuery(\Smile\ElasticsuiteCore\Api\Search\ContextInterface $searchContext)
    {
        $query = $this->queryFactory->create(QueryInterface::TYPE_TERM, ['field' => 'custom_show', 'value' => 1]);

        return $query;
    }
```

It should be enough to applicate this filtering any time a collection using the search engine is displayed (autocomplete box, product listing & product search result).

So it was a long story to write but in fact it's just 1 line of XML and a small PHP class to implement, you should be able to do it very quick.

Regards

**Comment by amenk** [comment]
Thanks a lot, basically works.
BUT: This filters out also categories in the quick search, because they do not have this attribute at all.
Is there a solution this way or should I better make a plugin for the product collection only.

In the parameter $searchContext

    public function getFilterQuery(\Smile\ElasticsuiteCore\Api\Search\ContextInterface $searchContext)

I did not find an indicator, that we are searching categories instead of products

**Comment by romainruaud** [comment]
@amenk 

Notice how it's done on our file : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml

Visibility and Stock filter are declared only for "catalog_view_container" and "quick_search_container" but the `category_search_container` remains empty. This way we don't try to apply visibility and stock filtering on categories because they do not have this attribute too.

Could you please show me your XML file so I can figure if you put your filter only on the proper search containers ?

Regards

**Comment by amenk** [comment]
I had it in the category_search_container, which I removed now.

But I am talking about the categories in the quick search - isn't there the quick search container used?


    <request name="quick_search_container">
        <filters>
            <filter name="erpStatusFilter">Example\ErpLogic\Model\Product\Search\Request\Container\Filter\ErpStatusFilter</filter>
        </filters>
    </request>

    <request name="catalog_view_container">
        <filters>
            <filter name="erpStatusFilter">Example\ErpLogic\Model\Product\Search\Request\Container\Filter\ErpStatusFilter</filter>
        </filters>
    </request>

**Comment by amenk** [comment]
okay, sorry it works now :-) Was testing wrongly

**Comment by romainruaud** [comment]
On the quicksearch we do 2 distinct queries to the engine : 

- one on the `quick_search_container` for the products
- one on `category_search_container` for the categories

It's completely distinct here. It's also the only location we use the `category_search_container` for now, whereas `quick_search_container` is also used for product search results pages. Of course `catalog_view_container` is for requests that are processed when navigating through categories.

Regards

**Comment by romainruaud** [comment]
Ok we cross-posted, glad to see it works for you now :)

Best regards and thank you for using our module and contributing to it.
