### ISSUE TITLE
How to: Adding additional product attribute to search collection based on customer attribute. 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1065]
### Preconditions

Magento Version: 2.2.5 (Open Source)

ElasticSuite Version : Latest

Environment : Any 

We have a customer that wants to restrict/add additional earch criteria of a specific attribute based on whether a logged in customer has a specific attribute. 

We'd approach this by populating  a new product attribute of  "competitor_sku" to each product and somehow inject this data into the search builder when a customer is logged in and has an attribute of "is_vip" set to true. 

After reviewing the implementation of elastic, it appears you create a single index that is applicable to all sessions.  Without reindexing on each search, do you have any ideas on the approach?

**Comment by southerncomputer** [comment]
https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog <-- I use this for this specific purpose!

**Comment by duffner** [comment]
Interesting, I'll review!

**Comment by southerncomputer** [comment]
Basically - you can instead of using groups, can pull in a customer attribute to filter the catalog on. I am using it this way since i do not have the b2b module installed. I just pull the catalog sku's into a shared_catalog_item table along with the attribute value to create multiple virtual catalog's that are a subset of the main catalog_product_entity - it's much faster to do it this way than to make multiple store catalogs, then you can apply multiple values in the customer attribute (or just 1) to allow elasticsuite to filter access to those parts - it works quite amazingly well performance wise i've got 2.6M sku's and some customers have access to 1M or 100 sku's - and I allow them to switch between the catalog's using a switch under my account and their default catalog_access and permissible catalog_access rights configured in the backend.

So yeah this works well and is very fast and complete for all types of elasticsuite searches!

**Comment by romainruaud** [comment]
@duffner did you manage to get it working like you wished ? 

Any additional help we can provide here ?

Regards

**Comment by romainruaud** [comment]
Since this one is inactive for too long, I consider it as resolved. Feel free to reopen it if needed.

Regards

**Comment by prince-fledgedigital** [comment]
Hello @all, I have install the Smile-SA/elasticsuite and i want to filter the search with some additional product attribute  like brandsname and the brands are associated with the customer, after that the login of the customer we want allow those products whose associate with customer brands.
Can you please help me for the same.
