### ISSUE TITLE
Multiple Checkbox Selection in layered Navigation Filter

### ISSUE THREAD

**Issue by truelogicapp** [Smile-SA/elasticsuite#1066]
I am using ElasticSuite Version 2.4.6 on my website with Magento EE 2.1 

In my layered navigation not allowed me to select multiple option to filter. How can i do this? 

Also, is it possible to implement AJAX based layered navigation?
### Preconditions

I am using ElasticSuite Version 2.4.6 on my website with Magento EE 2.1 

Magento Version : EE 2.1

ElasticSuite Version : 2.4.6

Environment : Developer

Third party modules : No

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
@truelogicapp 

I close this one since I am now aware that you are running huge customization for frontend, and also using a third party module for layered navigation.

So actually, multiple checkbox is a legacy feature of Elasticsuite, which is probably broken by your third party module, or by your frontend integration. 

Please continue to exchange by email with us since we already get in touch for commercial support.

Regards
