### ISSUE TITLE
Urgent!!! Update Mapping into ElasticSearch

### ISSUE THREAD

**Issue by truelogicapp** [Smile-SA/elasticsuite#1073]
How can i update existing Mapping into ElasticSearch.

I have run the indexer and Sync all Data into ElasticSearch successfully using ElasticSuite Extension. Now after few days later i want to add one more Attribute into my Index result.

Kindly guide me how i can update Mapping with new Attribute and sync Attribute Data without affecting existing index.

### Preconditions
Magento 2 EE 2.1
ElasticSuite 2.4.6

Magento Version : Magento 2 EE 2.1

ElasticSuite Version : 2.4.6

Environment : Developer Mode

Third party modules : No

### Steps to reproduce

1. Add Mapping + Run Index 
2. Data Sync Successfully
3. Update new Attribute into Mapping + Sync Attribute Data with existing index (Please guide step)

**Comment by romainruaud** [comment]
Hello @truelogicapp 

please do not tag issues as URGENT, we are providing Open Source support here and are not due for any deadlines. We can provide commercial support if you have particular deadlines to meet and need us to help you quickly.

That being said, the mapping is automatically updated when you process a full reindex. Don't be afraid to launch a full reindex since the website will continue to be functional during the reindex, new index and mapping are applied and replace the precedent only when they are completely rebuilt (its a switch by alias process).

Regards

**Comment by truelogicapp** [comment]
@romainruaud Thank you so much for immediate response. 

I will take care of this to not tag URGENT. 

Also, please suggest which custom attribute will Map automatic into ElasticSearch. is there any specific settings are required to map them into ElasticSearch. 

I just changed Attribute Property from Use In Search => No to Yes. is this attribute will map ?

Regards
Raman

**Comment by afoucret** [comment]
Such a change should invalidate the indexer and If your Magento setup is correct the cron will reindex the full search engine.

Considered are closed because the question is answered.
