### ISSUE TITLE
How to Map Custom Attributes into ElasticSearch and Show values into Elasticsearch fields

### ISSUE THREAD

**Issue by truelogicapp** [Smile-SA/elasticsuite#1074]
@romainruaud I have number of custom attributes that i want to show into ElasticSearch result

Can you please define the steps how custom attributes will show in Mapping and how data coming from Magento will be converted into Elasticsearch fields.

### Preconditions

Magento Version : Magento 2 EE 2.1.x

ElasticSuite Version : 2.4.6

Environment : Developer Mode

Third party modules : N/a

### Steps to reproduce

1. Which Property is required to map Attribute in Mapping
2. how data coming from Magento will be converted into Elasticsearch fields. 

Please Help

**Comment by truelogicapp** [comment]
I have mapped one Attribute 

badge_bar |  
-- | --
type | "string"
norms |  
enabled | false
fielddata |  
format | "disabled"
copy_to |  
0 | "search"
1 | "spelling"
analyzer | "standard"

But this field Value is not showing into ElasticSearch Result.

**Comment by romainruaud** [comment]
@truelogicapp 

What are you calling "ElasticSearch Result" ? And what are you calling "Custom attributes" ?

When you define a product attribute, and set it as "Used In Search : Yes", or "Is Filterable : Yes", it's automatically added to the Elasticsearch index mapping. There is nothing more to do.

Please give me more details because for now it's unclear for me about what you are trying to achieve.

Regards

**Comment by truelogicapp** [comment]
This issue is resolved. Kindly reply on Email i sent you personally for English and Arabic URL.

Please closed this
