### ISSUE TITLE
Report : Remove display of Facet Attribute when all products have same option.

### ISSUE THREAD

**Issue by mageho** [Smile-SA/elasticsuite#1078]
### Preconditions
Magento Version : Magento CE 2.2.5
ElasticSuite Version : 2.6.1
Environment : Developer
Third party modules : Not related to layered navigation and products lists.

Good afternoon,

This is a report about the issue #1042.
The pull request #1051 doesn't seems to solve the problem.

There are still many filters which have only one option :
![capture d ecran 2018-09-13 a 17 37 58](https://user-images.githubusercontent.com/2975845/45499661-20917a00-b77d-11e8-9cb8-52fc265e7375.png)

Have you tried yourself your new release to know wether it fix this issue or not ?

Ilan

**Comment by romainruaud** [comment]
Hello @mageho 

Please, don't be so salty when submitting an issue ...

PR #1051 will hide a filter if **it has only one value that matches the entire product collection.**

As I can see on your screen, the "Avec rallonge : Oui" is matching **5** products among **6** results.

In this case, the filter is relevant and should not be hidden, because if you apply it, it will remove one article from the list.

So imho, your case is invalid. We'll be glad to dig more if you are able to reproduce it on a proper use case (would be correct if "Avec rallonge : Oui" was matching **6** products here).

Regards,

**Comment by mageho** [comment]
Good morning,

You misundertand me, I was not sure if it was the correct behavior of your extension.
As I know, the field yes/no did not show up the filter No option. 
Which is defined for the last product of this example list.

I have this situation with complementary module of ElasticSuite, Ratings.
Is this related to the core or to the complementary module ? Or is it the expected behaviour ?

![capture d ecran 2018-09-14 a 11 35 46](https://user-images.githubusercontent.com/2975845/45542573-9562c380-b812-11e8-849c-ab298f2dc3a8.png)

Thank you,

Ilan

**Comment by romainruaud** [comment]
Hello, not a surprise to me that the same issue is still present in the rating module.

This module do have its own `Layer/Filter/Attribute` implementation and is therefore not targeted by the fix provided in #1051 

Please open an issue on this module directly.

Regards
