### ISSUE TITLE
Override class collection

### ISSUE THREAD

**Issue by Nix-id** [Smile-SA/elasticsuite#1079]
Magento Version : 2.2.5
ElasticSuite Version : 2.6.1

I try to ovverride some classes
i get some problem

i declare in di.xml
<preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection" type="Vendor\Modul\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection"/>

but this not work everywhere.

./vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Autocomplete/Product/Collection/Provider.php

...
use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection as ProductCollection;
...
public function __construct(ProductCollection $collection, $collectionProcessors = [])..

$collection == Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection
but i expected my Vendor\Modul\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection

**Comment by romainruaud** [comment]
Hello @Nix-id 

First, overriding a class is never a good idea (with Plugins and Observer, there are often better ways to achieve customization).

That being said, can you please : 

- describe what kind of customization you are trying to achieve
- what did you put in your DI (copy-paste your xml please).

Regards

**Comment by ionpan** [comment]
I was having the same issue with this one and I think I hit rock bottom. What I am trying to do is restrict the users to several products based on user and product attributes (fairly custom requirements) and I am trying to override the Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareRequest() in order to add my custom filters. I believe this is not possible using a plugin as the method is private and I see no observers being called in the process.
My frontend di.xml looks like this:
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection" type="Vendor\Module\Model\ResourceModel\Product\Fulltext\Collection" />
</config>`

Keep in mind that Vendor\Module\Model\ResourceModel\Product\Fulltext\Collection extends Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection and I have copied all private attributes and methods that cannot be inherited only adding a few lines of code in prepareRequest().
