### ISSUE TITLE
Catalog Search in Virtual Category doesn't return any products.

### ISSUE THREAD

**Issue by albertomario** [Smile-SA/elasticsuite#1083]
I have a virtual category, which is working when i try to navigate throught catalog. (all products are listed based on conditions set on virtual category option), but when i try to search using default magento category search, using catalogsearch/result/?cat=172&q=bike, no results are returned.
Also i found that in elasticsearch index, magento2_default_catalog_product index, on a product listed in virtual category, the category id is not set in categories array. Tried reindex but nothing work.
![image](https://user-images.githubusercontent.com/1449583/45616026-e541c480-ba76-11e8-9f03-7bb54adc5a64.png)
This product is in virtual category, but category_id for virtual category is not set.

### Preconditions

Magento Version : CE 2.2.3

ElasticSuite Version : 2.6.0

Environment : Developer

### Steps to reproduce

1.
2.
3.

### Expected result
catalogsearch/results with category filter should return results.

### Actual result
No results page is returned.

**Comment by albertomario** [comment]
Also i found that if i set Manual Sorting on Virtual Category options for one product. This product is available for search.

**Comment by romainruaud** [comment]
Hello @albertomario 

It's normal that the association between a product and a virtual category is not stored into Elasticsearch. It's like this by design because for virtual categories, the request to Elasticsearch is processed "on the fly" when the category is displayed.

For now, I am not able to reproduce your issue on Magento 2.2.6 with Elasticsuite 2.6.1.

Could you give me more details ? Where is your category located in the category tree ? Do she have a "Virtual Root" defined ? What is the exact condition of this virtual category ? 

Regards

**Comment by romainruaud** [comment]
Closed for being inactive/unanswered for too long.

Feel free to reopen if you have more details to give.

Best regards
