### ISSUE TITLE
Port to SCSS (snowdog base theme)

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1099]
I am wondering if anybody is using the module in a shop based on https://github.com/SnowdogApps/magento2-theme-blank-sass and their frontools.

I tried converting the LESS automatically to SASS but it does not work out of the box.

So the question is if we manually port it -> does the SASS have a chance to be included here?

Did anybody else approach that yet?

**Comment by amenk** [comment]
https://gist.github.com/amenk/46ef565bb0e9c4e4df934b4809b90f2f

**Comment by romainruaud** [comment]
@amenk thank you for providing this SASS support of Elasticsuite custom LESS code.

However, we did use LESS because it's the legacy way to write stylesheets with Magento2, I'm not sure if Magento2 is able to deal with SASS without any additional third party modules (like the one you pointed out).

Having a SASS version of Elasticsuite stylesheets is cool, but I'm not sure we are willing to maintain it inside the core (duplicate work between LESS and SASS version) of Elasticsuite if it's not supported out-of-the box by Magento.

Regards

**Comment by romainruaud** [comment]
I close this one, since it has been answered. 

Thank you for contributing it, however we will not merge it into the core for the reasons depicted above.

Best regards
