### ISSUE TITLE
Searched Products Not Showing Based On SKU

### ISSUE THREAD

**Issue by JerrodDavenport** [Smile-SA/elasticsuite#1100]
We have a lot of issues with SKU's not showing up when searching.  This issue just started when we updated to 2.4 from 2.3.  We have found hundreds of products showing within their category but are not searchable by SKU.  We have checked all quantities and making sure visibility option was set to "Catalog, Search".  I have re-indexed several times trying to resolve this issue.  I can search for these same products based on title, and they do show.  Why are they not coming up with SKU?

Website in Question:  https://thelifeguardstore.com/swim-shop/swimwear/rise-aquatics-swimwear.html

### Preconditions

Magento Version : 2.1.9 EE

ElasticSuite Version : ElasticSearch 2.4

Environment : Production 

### Steps to reproduce

1. Simplify search for SKU: 170
2. Six products appear, none of which are the right ones.
3. Oddly enough, if I seaerch for the title of the product "Fox 40 Classic Pealess Whistles", it works fine. 

### Expected result

1.  When searching for SKU 170 I would expect the right product to appear.

### Actual result

1. [Screenshot, logs]
![capture2](https://user-images.githubusercontent.com/28022699/46219739-bbf22580-c30d-11e8-9a97-3e08562266a2.JPG)

![capture](https://user-images.githubusercontent.com/28022699/46219742-beed1600-c30d-11e8-8ca7-56deb8f64077.JPG)

**Comment by romainruaud** [comment]
Hello @JerrodDavenport 

This used to be a known issue but was fixed in Elasticsuite 2.5, and improved in 2.6.

You should give a try upgrading to these versions. I know that it also requires to upgrade to latest Magento 2.2.6 version and could involve some work.

Our Open Source Support policy only concern the two latest versions of Elasticsuite. So actually providing support for version 2.4 is not covered here. Backporting features to oldest versions of Elasticsuite is not either.

Regards

**Comment by JerrodDavenport** [comment]
We upgraded and it appears to be working now.
Thanks
