### ISSUE TITLE
After installation : setup:upgrade giving network issue

### ISSUE THREAD

**Issue by sarwarrizvi** [Smile-SA/elasticsuite#1103]
After installation : setup:upgrade giving network issue
Your requested host "localhost" could not be resolved by DNS.

Magento Version : Magento 2.2.5 (CE)

ElasticSuite Version : 6.4.1

Environment : Developer

Third party modules : NA

### Steps to reproduce
1. Installed Elastic Suite 2.6.2
2. Installed elasticsearch 6.4.1
3. localhost:9200
4. bin/magento setup:upgrade

### Expected result
It should work :)

### Actual result
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... <HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (dns_unresolved_hostname)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your requested host "localhost" could not be resolved by DNS.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">

</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>

**Comment by romainruaud** [comment]
Hello @sarwarrizvi 

This is kinda strange but it's mostly not due to Elasticsuite, but rather a misconfiguration on system side for your server.

Please inquire with your VPS/hosting provider about the problem to see if they are able to give you help.

A possible workaround may be to define the location of the Elasticsearch server to `127.0.0.1` instead of `localhost`.

I close this once since it's not something we can fix on Elasticsuite.

Regards
