### ISSUE TITLE
How to use copy_to all for a given field?

### ISSUE THREAD

**Issue by lovemeblender** [Smile-SA/elasticsuite#1129]
How can we use the `copy_to` to copy a certain field to the `all` field? Thanks.

Magento Version : 2.2

ElasticSuite Version : 2.6

**Comment by romainruaud** [comment]
Hello @lovemeblender 

It's not easily doable "as is", because the `copy_to` logic is implemented here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Index/Mapping.php#L297

So it's not quite extensible atm.

But what would be the purpose of your `all` field ? And why do you plan copying other field data into this one ?

**Comment by lovemeblender** [comment]
Thanks @romainruaud. For two reasons: 

1. I was trying to find a work around for the issue I described [here](https://github.com/Smile-SA/elasticsuite/issues/1130). I though if `all` worked it might be easier use just this in the queries. 
2. Pure curiosity on how to achieve this since it can be helpful narrowing and widening the scope of the search like this.

I understand that it's not extensible as you mentioned so I'll close this issue.
