### ISSUE TITLE
How to enforce a field to be included in the search query?

### ISSUE THREAD

**Issue by lovemeblender** [Smile-SA/elasticsuite#1130]
There are certain queries that are not using fields such as name, description and other similar of which I want to **always** search into. These fields are copied to `search` field which I guess is used to return the search results *and* `spelling` field which I guess is used to return the spelling suggestions as the user writes the query. 

The `spelling` works great as it's using all the fields but for some reason `search` is using only a subset of the total fields which do not contain useful information and as a result no results are returned.

Any thoughts on this? Is there a rule that builds the queries each time? 

It looks like it randomly decides to leave out certain fields.
 
### Preconditions

Magento Version : 2.2

ElasticSuite Version : 2.6

Environment : Developer mode

**Mappings (segments of interest)**

> ...
"**name**": {
"type": "text",
"fields": {
"untouched": {
"type": "keyword"
}
},
"copy_to": [
"search",
"spelling"
],
"analyzer": "default",
"search_analyzer": "default_search"
}
...
"**short_description**": {
"type": "text",
"fields": {
"untouched": {
"type": "keyword"
}
},
"copy_to": [
"search",
"spelling"
],
"analyzer": "default",
"search_analyzer": "default_search"
}
...
"**spelling**": {
"type": "text",
"fields": {
"phonetic": {
"type": "text",
"analyzer": "phonetic"
},
"shingle": {
"type": "text",
"analyzer": "shingle"
},
"whitespace": {
"type": "text",
"analyzer": "whitespace"
}
},
"analyzer": "standard"
}
...
"**search**": {
"type": "text",
"fields": {
"untouched": {
"type": "keyword"
}
},
"copy_to": [
"search"
],
"analyzer": "default",
"search_analyzer": "default_search"
}

So what confuses me is that the query is using fields in a way that looks random. For example searching the Greek word "οδοντοκρεμα" (it means toothpaste) I get results as the query is using fields such as name, search, etc. which contain this generic product title. Here's the interesting part:

> "multi_match":
 {
                "query": "οδοντόκρεμα",
                "fields": [
                  "name^1.0",
                  "option_text_brand.sortable^20.0",
                  "option_text_cosmetics_skin^2.0",
                  "option_text_cosmetics_skin.whitespace^20.0",
                  "search^1.0",
                  "search.whitespace^10.0",
                  "short_description^1.0",
                  "sku^1.0",
                  "sku.sortable^20.0"
                ]

However if I search for greeklish (i.e. greek words written in latin characters) it looks like it's using some fallback fields. Matching greeklish with greek shouldn't be a problem and is being taken of a relevant filter. Here's part of the query:

> 
                              "multi_match": {
                                "query": "afros ksirismatos",
                                "fields": [
                                  "option_text_cosmetics_skin.shingle^20.0",
                                  "option_text_cosmetics_skin.whitespace^2.0",
                                  "spelling.shingle^10.0",
                                  "spelling.whitespace^1.0"
                                ]

The problem with the above is that if it had `name` then it would have found the relevant SKUs - it works with my custom queries.

**Comment by romainruaud** [comment]
Hello @lovemeblender 

It's not random, but fields that are having a weight of **1** are not explicitely included in the search queries. Since the **1** multiplier would have no effect, and these fields data is copied into `search`, just using the `search` field should be enough (and have a bit gain of performances).

Can you give me examples of problematic queries with their expected results ? I'd love to also see the mapping of your index to find out more what is happening.

Regards

**Comment by romainruaud** [comment]
You can define field weight via the back-office if there are product attributes : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration

If they are "special" fields (eg. coming from external sources), you can do it via XML file : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#defining-fields-property-via-configuration

**Comment by lovemeblender** [comment]
Awesome, thanks so much. I'll get back with the mappings etc.

**Comment by rbayet** [comment]
Hello @lovemeblender,

Could you provide a bit more about your mapping ? I would like to see the analyzers section too.

Because I'm a bit confused about this part :
> However if I search for greeklish (i.e. greek words written in latin characters) it looks like it's using some fallback fields. **Matching greeklish with greek shouldn't be a problem and is being taken of a relevant filter**. 

Do you mean by looking at the mapping and the declared analyzers, already is there to the best of your knowledge ?
Or do you mean you already customized the analyzers declared in XML to add extra support for Greek transliteration (by doing something quite similar as explain in https://github.com/Smile-SA/elasticsuite/issues/1072#issuecomment-426738685) ?

> Here's part of the query:
> 
>                           "multi_match": {
>                             "query": "afros ksirismatos",
>                             "fields": [
>                               "option_text_cosmetics_skin.shingle^20.0",
>                               "option_text_cosmetics_skin.whitespace^2.0",
>                               "spelling.shingle^10.0",
>                               "spelling.whitespace^1.0"
>                             ]
> ```
> 
> The problem with the above is that if it had `name` then it would have found the relevant SKUs - it works with my custom queries.

According to the segment of mapping you provided, by search into spelling.whitespace, it will also search into name (because name is "copied_to" spelling), and obviously, in your case, fails.
Can you also provide us with those custom queries ?

Regards,
Richard.

**Comment by rbayet** [comment]
Hi @lovemeblender,

Concerning : 
> As you mentioned I am copying name into spelling (it's not clear to me why it picked spelling and not search here) 
and
> Roughly what happens, is that I am getting different search fields and I cannot predict when and why these appear in the query:

Basically, when you perform a search, the module first performs an analysis of your query against the index to determine the type of search request he's supposed to build : 

- if the word(s) is(are) "exactly" present in the index, it will perform an "exact match" or a "most exact match" query
- if the word(s) is(are) determined to be stopwords, it will perform a "pure stop words" query
- if some words are not "exactly" there, he will assume the request to perform must allow for fuzziness : according to your relevance configuration, it will search in dedicated search fields for handling either typos and/or phonetic approximations

This is oversimplified, but if the generated query uses "spelling", it means the module didn't go for an "exact match" or "most exact match" query because of something happening at the analysis phase.

We might have a clearer picture with the full mapping and analyzers definition and the queries you mentioned.

Regards,
Richard.

**Comment by romainruaud** [comment]
Hello @lovemeblender , any update ?

**Comment by romainruaud** [comment]
Ok, thank you for submitting this one.

Please open a new issue if you are still encountering any doubt.

Regards
