### ISSUE TITLE
getCategoryIds() not returning virtual categories?

### ISSUE THREAD

**Issue by jsterling** [Smile-SA/elasticsuite#1133]
We're using some code calling $product->getCategoryIds() to show all the categories which a product is in, but this isn't showing virtual categories. Is there a way to get all virtual categories a product is assigned to by product ID or SKU?

**Comment by romainruaud** [comment]
Hello,

actually, there is no way of returning the virtual categories that match with a given product.

We'll probably not add it to the legacy `getCategoryIds` which is meant to retrieve the categories where a product is explicitely attached, but rather build another API, like `getVirtualCategoryIds()`.

Spoiler : it might include a lot of work since it would require to build a percolation engine first, and then to be able to percolate them

Regards

**Comment by romainruaud** [comment]
Closed as being duplicate of #378
