### ISSUE TITLE
Add CLI tooling?

### ISSUE THREAD

**Issue by shochdoerfer** [Smile-SA/elasticsuite#1134]
Not a bug report, rather a question: In a recent project I created a CLI command to reset all indexes which comes quite handy when testing indexer changes. Is there interest in having that command integrated in this package? Would love to contribute that code if there's interest for that.

**Comment by shochdoerfer** [comment]
Before I implemented the CLI command I tried using `bin/magento index:reset` and realized that the indexes (and data) still exist in ES afterwards. Not sure if this is intended or not. That was the reason behind building the CLI command to completely clear the ES.

**Comment by romainruaud** [comment]
Oh ok, I did not understand that you were meaning "deleting" when speaking about "reset".

You are right, the "reset" command of magento is only invalidating the index, meaning that a full reindex will be triggered next time the cron run (if indexer is set to `index on schedule`).

What's the need under deleting the indexes when you can just invalidate them and process a full reindex ? The logic behind invalidating is simple : on a production environment, you can't delete the index, this would cause no products to appear during the time the index is rebuilt. That was the case on prior Magento versions, and that's why we implemented the following logic : 

invalidate the index -> process a full reindex in background -> switch the old index with the new one -> delete the old index.

So maybe deleting indexes could be useful for developers (but they can also invalidate and reindex), but it's only a nice-to-have for dev purposes, so we do not plan to add such a feature in the core implementation (people could mis-use it and delete their indexes in production, which is something we do not want to happen).

Best regards
