### ISSUE TITLE
Question: Indexing attributes of simples in configurable's (to show "on sale")

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1140]
We have the following use case:

Simple products can be on sale -> so the we have to check if the specialPrice is lower then the regular price and show a sale icon in the product detail page.

But for configurable's the sale-state should be determined from all simple products which are assigned.

Can this module help with this? I am wondering if we have to write a custom indexer for this?

Just would be happy for some general pointers.

**Comment by romainruaud** [comment]
Isn't it already covered by https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php#L71 ?

However, since data in the price index table for composite product has been a mess forever, I'm not sure it's reliable to be used when indexing into Elasticsearch.

It's something we have to dig on Magento 2.3 to see if there was any improvement on their side about how the price index is done (in SQL) for composite products.

Regards

**Comment by amenk** [comment]
> However, since data in the price index table for composite product has been a mess forever, I'm not sure > it's reliable to be used when indexing into Elasticsearch.

But it is, right?

**Comment by romainruaud** [comment]
Yes, it's used, but it's missing many things : 

- min_price & max_price are not always relevant for configurables : https://github.com/Smile-SA/elasticsuite/issues/866

- for a long time, this table was not taking catalogrules into account (not sure if it's fixed Magento side).

- and more that I cannot remember here.

**Comment by amenk** [comment]
@romainruaud May I abuse this issue to point you to the question of my colleague https://magento.stackexchange.com/questions/247097/price-filter-returns-wrong-results-price-ist-stored-as-0-insteal-of-null-and-i -- is this a similar problem?

**Comment by romainruaud** [comment]
Hello @amenk 

I see the stackexchange attached thread has been resolved (vanilla Magento bug).

May I close this question ?

Regards
