### ISSUE TITLE
Question!! Update Attribute Value Programtically into Magento is update ElasticSearch

### ISSUE THREAD

**Issue by truelogicapp** [Smile-SA/elasticsuite#1142]
We have promo message text to show on PLP Page (Product Listing pages) under each product name.

We have created attribute for this and add Promo message on this attribute  value through custom script (CSV Upload). 

This attribute is Map into ElasticSearch. Is the same value will update into ElasticSearch if we update Attribute through Custom Script?
 
### Preconditions
Magento Version : Magento 2.2 EE

ElasticSuite Version : 2.4.6

Environment : Developer

Please reply by today,

**Comment by truelogicapp** [comment]
@afoucret @romainruaud please suggest:


promo_messaging_pdp |  
-- | --
type | "string"
norms |  
enabled | false
fielddata |  
format | "disabled"
copy_to |  
0 | "search"
1 | "spelling"
analyzer | "standard"


promo_messaging_plp |  
type | "string"
norms |  
enabled | false
fielddata |  
format | "disabled"
copy_to |  
0 | "search"
1 | "spelling"
analyzer | "standard"

**Comment by romainruaud** [comment]
Hello @truelogicapp 

If your custom field is modelized by an attribute, it will be indexed into Elasticsearch only if : 

- this attribute is "used in search = true" or "used for sort by = true" or "use in layered navigation = true".

In any other case, it will not be indexed into Elasticsearch. I'm not sure there is a use case for using a promo message for search or filtering or sorting, but anyway, if you set this attribute according to what I said previously, it will be indexed into Elasticsearch.

That being said, there are two ways to update the products into Elasticsearch after their data have been modified : 

- If you are on "Update on Schedule" mode for the Catalogsearch fulltext indexer, Magento will rebuilt updated product data by detecting changes via a DB trigger. So if you edit an attribute value via a script, it should be detected, since the data in the DB table will be modified.

- If you are on "Update on Save" mode, the product data is automatically updated into Elasticsearch when an action involving saving the product is done (like, saving in the back-office). So maybe, if you are doing it via a script which is not using the Repository Api of Magento, or not triggering the catalog search indexing after looping on products for update, you might miss the data update into Elasticsearch.

In any cases, displaying such an attribute on Product Detail Page or Product Listing Page does not involve data fetching from ES. The data is retrieven directly from MySQL.

Regards

**Comment by truelogicapp** [comment]
@romainruaud Thanks for your prompt respone.

You are right data can retrieven directly from MySQL but we are storing most of data into ElasticSearch and using this for Front-end web by using Nodejs API. so that API will be available for Moble App too.

I checked that we are on "Update on Schedule" mode for the Catalogsearch fulltext indexer and its trigger the indexer and product ID.

We have all configurable Products and promo message value updated on Configurable Product. The Indexer running All child Items not parent IDs are showing into catalogsearch_fulltext_cl changelog table. Please guide me if anything wrong or only child Attribute update on DB trigger?

**Comment by romainruaud** [comment]
@truelogicapp as far as I remember, it's not a problem to have only children ids in the `_cl` table, because we automatically try to fetch parent ids when reindexing : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Action/Full.php#L56

That being said, I do not understand if you are encoutering any issue or if this thread was just a question ?

Regards

**Comment by truelogicapp** [comment]
Dear @romainruaud 

Thanks for the information and its really helpful. Its working but the issue is when we do bulk upload through CSV some of child missed to update into catalogsearch_fulltext_cl but Product Attribute Value updated into database. So when indexer run and update Child Parent the missing child not updated their Parent.

Can you please guide via its happening?

Regards
Raman

**Comment by romainruaud** [comment]
Hello,

unfortunately, we cannot provide any support on the mechanism that is automatically populating the `_cl` tables when product data are modified : it's a legacy Magento behavior and Elasticsuite is not modifying it. So you'd better try to investigate by yourself on this one, or ask the Magento community on their github to see if they can provide any help.

=> Elasticsuite will just reindex products that are in the `_cl` table (and their potential parent products). If they are not put into the changelog, we cannot do anything.

Regards
