### ISSUE TITLE
Questions regarding usage of configHash->regenerate()

### ISSUE THREAD

**Issue by berwa** [Smile-SA/elasticsuite#1159]
At the moment we are running into an issue where non of our modified store-configuration (done in config.php) is taken into account on Magento Cloud environment.
On our local development-environment it works if we execute app:config:import first and setup:upgrade there after, but not the other way around, although setup:upgrade should do the config:import at the very end of its execution.

We did some debugging and came up with the behavior that setup:upgrade calls your Recurring-data script
https://github.com/Smile-SA/elasticsuite/blob/8a6424da415031218d9dc6174c83602c460ad2a3/src/module-elasticsuite-core/Setup/RecurringData.php#L51
that causes all hashes to be re-generated but does not actually process the configuration itself.
The Magento core config-processing then "thinks" there is nothing to do anymore and leaves the configuration unchanged.

We could not really guess a reason to execute configHash->regenerate at that very position so it is very hard for us to decide how to process with this issue.

Can you help us out:
Is there a reason known, why configHash->regenerate was added?
Is it really necessary to regenerate all hashes (especially including the scope-hash)?
Can this be changed without breaking the module's functionality?

Thank you and best regards 

### Environment
Magento Version : Cloud (EE) 2.2.6, but also reproducible on regular CE-&EE-editions 
ElasticSuite Version : 2.6.1 (and older versions)
Environment : All Modes
Third party modules : also reproducible on a otherwise clean Magento-installation

**Comment by romainruaud** [comment]
I'm not sure this one is required to be processed during each setup upgrade.

It's probably needed to process this on first module install at least. Did you give a try to disabling it on your MECE environment ?

Regards

**Comment by rbayet** [comment]
Hello @berwa,

Have you tried @romainruaud suggested action ?

Regards

**Comment by berwa** [comment]
Hello @romainruaud,
thank you for your answer and sorry for my late reply.

We played around with a plugin that basically removes "$this->configHash->regenerate();" from RecurringData.php, it worked for us, but we could not determine if that would cause any side effects in other circumstances.

Best regards

**Comment by david-fuehr** [comment]
For our projects this recurring script is problematic for the same reason as mentioned above.

This implemented behavior has two effects:
* The `setup:upgrade` command is no longer able to import application config (`\Magento\Setup\Console\Command\UpgradeCommand::execute` -> `$importConfigCommand->run($arrayInput, $output);`) as the hash is always up to date
* A missing store (`app:config:import`) and a missing table (`setup:upgrade`) may lead to a deadlock where config import fails due to missing table and upgrade scripts prevent the stores from being created. 

This recurring script was introduced with commit [322dfea1769303144c3c90c4a4ad3d180dc7bc9c](https://github.com/Smile-SA/elasticsuite/commit/322dfea1769303144c3c90c4a4ad3d180dc7bc9c#diff-7a3fc3d4fa2feccf4018b77de8e7f789) by @afoucret . Maybe he could tell if this script is still needed or what kind of problem he addressed with this script?

**Comment by romainruaud** [comment]
We will remove this file in next minor release. I close.
