### ISSUE TITLE
[question] Shop By Attributes

### ISSUE THREAD

**Issue by julienanquetil** [Smile-SA/elasticsuite#1172]
### Preconditions

Magento Version : 2.2.6

ElasticSuite Version : 2.6

Environment : dev

### Expected result
I'm working on a custom module for a "shop by" attribute.
In my current sample, i make a custom eav for "brand attribute" like there is several on the market... with image / featured... to display them on custom page and featured in a slider.
Everything in fine on that side.

Right now i'm facing an issue more "architectural".
On my "all brand" page, i display all brand with a link to a collection with all products belong to that brand.
I'm getting the right result.

But now i'm facing an issue with the layered navigation. when I apply a filter (for example price)
I got the right amount of product displayed in the layered
<img width="729" alt="capture d ecran 2018-11-06 a 11 50 59" src="https://user-images.githubusercontent.com/1108170/48059756-54f04800-e1ba-11e8-8768-2ada4c123fe3.png">
but not in the product collection

I made something like :

```
$priceRange = explode('-', $data['price']);
$productCollection->addFieldToFilter('price', ['from' => $priceRange[0], 'to' => $priceRange[1]]);
```
but it's like it's not the right way to do it.

I try to read the wiki but i think i miss the main "concept"...

So what's the best way to achieve it ?
Thanks for your help

**Comment by romainruaud** [comment]
Hello @julienanquetil 

Actually what you are trying to achieve remains quite unclear for me.

How is done your custom "by brand" collection ? Is your "brand" entity indexed inside Elasticsearch ? (can be as additional data like explained here : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#data-sources )

Since you should be using a Fulltext collection for building such pages with layered navigation, it should be the case. 

In my opinion you should have : 

- "brand" data indexed into Elasticsearch (with proper mapping, etc... please refer to the developer's guide in the wiki to achieve it).
- a custom router/controller to achieve something like `http://example.com/all-brands/adidas.hml`
- this should fallback to a page which has the exactly same layout than category navigation, except it's enforcing a filter on `brand` on the current fulltext product collection

**Comment by julienanquetil** [comment]
Hi,
It's what I have in place.
My "brand" attribute is a product attribute (already indexed in elasticsearch)
I made an EAV to "enrich it" with image / description

I have a custom router to handle request like 
/brands for controller to display "all brand" page
/brand/mybrand.html do display custom collection.

It's on that controller I have Issue.
If i well understand you advice is to make a controller with a custom "_getProductCollection" method
with a filter like :
` $collection->addFieldToFilter($brandAttribute, ['eq' => $brand->getIdentifier()]);`

Thanks

**Comment by julienanquetil** [comment]
Got it to work right now. Thanks for your recap :)
