### ISSUE TITLE
Bundle product price is in-correct in autocomplete

### ISSUE THREAD

**Issue by chitra-hirnawale** [Smile-SA/elasticsuite#1182]
### Preconditions
In autocomplete bundle product price is not correct.

Magento Version : 2.2.3

ElasticSuite Version :2.6.0

Environment : Production

When user search for any product, bundle product price is showing in-correct in autocomplete but its correct on product details page.

**Comment by romainruaud** [comment]
Hello @chitra-hirnawale 

Please provide screenshots or more details to describe your issue.

What is "incorrect" ? I strongly suspect this one is already fixed by #1139

**Comment by romainruaud** [comment]
Closed for being inactive more than 2 weeks.

Feel free to open a new issue if still encountering the problem.

**Comment by ibeschastnaya** [comment]
Hello,

We have the same issue.

Preconditions: Bundle product has fixed price.

Steps to reproduce:

Open storefront.
Enter query to the search field to search for your bundle with fixed price
Pay attention to the price of the Bundle in quick search drop-down.
Actual result: Price range is shown.
Expected result: Fixed price should be shown.

This issue probably related to the fact that for product query for Autocomplete doesn't have price_type, so products rendered with range instead of fixed price.
