### ISSUE TITLE
M2.3.x ES2.6.x Category position indexing

### ISSUE THREAD

**Issue by Swahjak** [Smile-SA/elasticsuite#1198]
### Preconditions

Magento Version : 2.3.x

ElasticSuite Version : 2.6.x

Environment : developer

Third party modules : -

### Steps to reproduce

1. Index product fulltext

### Expected result

1. Category position is supplied

### Actual result

1. Category position is not supplied

Side note; We are in the process of migrating from 1.9.3.10 to 2.3.x.

I'm not sure if this is a bug or a migration issue but we're having problem with the category.position index. After migrating the `smile_virtualcategory_catalog_category_product_position` table is empty (is this a migration issue?). In `Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` are two selects; a 'BaseSelect' and a 'VirtualSelect'. To me it does not make sense that the 'BaseSelect' uses `p.position` which is mapped to `smile_virtualcategory_catalog_category_product_position` instead of to `catalog_category_product_index_storex`. Wouldn't it make more sense to set this to `cpi.position` or even to `COALESCE(p.position, cpi.position)`? In our case this select causes the `category.position` to be null and therefore sorting doesn't work.

**Comment by romainruaud** [comment]
Unfortunately, it's by design that products positions are saved into `smile_virtualcategory_catalog_category_product_position` instead of being stored into the legacy table.

So actually, you'd better copy/paste product position data into this table during your migration process if you want to rely on them.

And this table is probably here to stay because we plan to allow to merchandise product position per store view, which is actually not doable with the magento legacy table.

Regards

**Comment by Swahjak** [comment]
> And this table is probably here to stay because we plan to allow to merchandise product position per store view, which is actually not doable with the magento legacy table.

Actually Magento 2.3.x has 'new' tables allowing positions per store (something that is already taken into account in Elasticsuite). As an example we have the following tables:
- catalog_category_product_index
- catalog_category_product_index_replica
- catalog_category_product_index_store1
- catalog_category_product_index_store1_replica
- catalog_category_product_index_store2
- catalog_category_product_index_store2_replica

The store tables are an exact copy of what `catalog_category_product_index` used to be (in terms of columns). `catalog_category_product_index` is empty in 2.3.x. Elastic suite already takes this into account:
```php
/**
     * Get category product index table name.
     *
     * @param integer $storeId Store id.
     *
     * @return string
     */
    protected function getCategoryProductIndexTable($storeId)
    {
        // Init table name as legacy table name.
        $indexTable = $this->getTable('catalog_category_product_index');

        try {
            // Retrieve table name for the current store Id from the TableMaintainer.
            $tableMaintainer = $this->objectManager->get(\Magento\Catalog\Model\Indexer\Category\Product\TableMaintainer::class);
            $indexTable      = $tableMaintainer->getMainTable($storeId);
        } catch (\Exception $exception) {
            // Occurs in Magento version where TableMaintainer is not implemented. Will default to legacy table.
        }

        return $indexTable;
    }
```
I'm not sure if that changes anything about your argument though, I'm not that well read concerning Elasticsuite.

**Comment by rbayet** [comment]
Hello @Swahjak 

> > And this table is probably here to stay because we plan to allow to merchandise product position per store view, which is actually not doable with the magento legacy table.
> 
> Actually Magento 2.3.x has 'new' tables allowing positions per store (something that is already taken into account in Elasticsuite). As an example we have the following tables:
> 
>     * catalog_category_product_index
>     * catalog_category_product_index_replica
>    [...]

The new tables do really not allow positions per store. 
This index table structure merges catalog_category_product data (products assignment to categories + their position) which is defined globally *and* the **visibility** ("Catalog", "Search", "Catalog/Search", etc) of the products which can be defined at the store view level, hence the store_id column in the table structure.
This is the same structure as in Magento 1.

**That being said**, we will have a look at your issue and the PR.
'VirtualSelect' is indeed there to grab data for categories *NOT* referenced in `catalog_product_position` (which were by design and historically only the virtual categories ?) but that does not mean indeed that categories grabbed in the 'BaseSelect' are explicitely referenced in `smile_virtualcategory_catalog_category_product_position` either.
So, in a migration (from legacy to Elasticsuite) context/cold start, the COALESCE would make sense.

On a side note, by 
> After migrating the `smile_virtualcategory_catalog_category_product_position` table is empty (is this a migration issue?).

are you explicitely telling us that somewhere on the migration path from 1.9.x to 2.3.x (using the M1 version of the module in 1.9.x) the content of `smile_virtualcategory_catalog_category_product_position` is lost ?
Or am I just over-interpreting things ?

Regards,
Richard.

**Comment by Swahjak** [comment]
@rbayet I think you can ignore the comment about `smile_virtualcategory_catalog_category_product_position` being empty. I'm pretty sure that is related to the 'order' of things in (our) migration.

> which were by design and historically only the virtual categories ?

This is indeed what I expected the table to be since there is a union on the base select and the virtual select. Whether or not that expectation is correct I leave up to Smile to decide, but it's the origin of my question.

**Comment by rbayet** [comment]
Hello @Swahjak,

**Short version** Actually `Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` works as intended.
The PR you proposed would make what is indexed and what is visible in the product sorter/merchandizer inconsistent.
If in your project, a lot of custom positioning has been applied to products in `catalog_category_product`, then as suggested by @rorua, I would also advise you to migrate them to `smile_virtualcategory_catalog_category_product_position`.

**Long version** Actually `Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` works as intended.
Here is why :
* a lot of positions in `catalog_category_product` are usually default values of "1" for all products assigned to a given category
* the index tables `catalog_category_product_index_*` tables also have rows for all the parent categories of categories a product is explicitely assigned to (because Elasticsuite switches all categories to "is_anchor" = yes)
* * for instance, if a product is assigned to a single category of ID 26 of path 1/2/18/20/26, the index table will have rows for that product and categories 2, 18, 20 and 26
* * those rows existence for categories 2, 18 and 20 are helpful to know under which categories a product is visible (that's why a (right or left) join is performed on that table in the `getXSelect` methods)
* * * but the product position for those categories is computed by Magento and is usually 10000, 10001, etc

Indexing those "default" and "computed" positions would :
* clutter the Elasticsearch index
* relegate products "inherited" by an anchor category to the end of product list
* more importantly, prevent the "Category Product View" optimizers to be applied correctly.

So the approach is of a "clean slate" by making `smile_virtualcategory_catalog_category_product_position` the only reference table for product positions : 
* all products visible in a given category have initially the same *undefined* default position
* so it can be changed by the optimizers (hence the "automatic sort" label visible in the product sorter/merchandizer)
Of course, those that you DO manually position in the product sorter/merchandizer will keep it.

I concur that simply looking at `Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` does not make this self-evident and at least some wording changes/comments might be necessary there.

**Comment by Swahjak** [comment]
@rbayet Thank you for the comprehensive explanation. I understand your argument / explanation and will close the issue.
