### ISSUE TITLE
Price not updated on search pages result vs M2 BO

### ISSUE THREAD

**Issue by Grek1981** [Smile-SA/elasticsuite#1203]
Price not updated on search pages result vs M2 BO

### Preconditions

Magento Version : 2.2.2

ElasticSuite Version : 2.5.12

Environment : Production

Third party modules :

### Steps to reproduce

Price updated for all store views in BO

Clear cache + reindex

### Expected result

Price on pagelist resuls appears as in BO

### Actual result

Previous price is showing

**Comment by romainruaud** [comment]
Hello @Grek1981 

Elasticsuite is - on a legacy base - not responsible of the data which are displayed in front.

To be completely exact, the workflow is the following : 

- we take the current context (current search query, or current category, it depends on the page).
- we process a query to the Elasticsearch engine.
- we get **only the product ids**
- and then a standard Magento collection is initiated, filtered by the product ids.

It's this collection that is displayed to the customers in front-office, so it's not based on any data coming from the Elasticsearch index.

You may have an issue elsewhere : 

- if using Flat Catalog feature for products, they might need to be reindexed too.
- product price index has to be rebuilt because it's used by Magento when displaying prices on frontend.

Best regards

**Comment by romainruaud** [comment]
I close this one since it was not due to Elasticsuite and is now inactive for too long.

Regards
