### ISSUE TITLE
Fatal Error on RSS feed for category

### ISSUE THREAD

**Issue by evilprophet** [Smile-SA/elasticsuite#1213]
When I go to rss for category I got fatal error intead of xml feed.

### Preconditions
Magento Version : 2.2.6, reproduced also on 2.2.2
ElasticSuite Version : 2.6.2, reproduced also on 2.5.14
Environment : Developer and Production

### Steps to reproduce
1. Enable RSS in Stores>Configuration:
```
rss/config/active => 1
rss/wishlist/active => 0
rss/catalog/new => 1
rss/catalog/special => 1
rss/catalog/discounts => 1
rss/catalog/category => 1
rss/order/status => 0
```
2. Disable "Display Out of Stock Products"
```
cataloginventory/options/show_out_of_stock => 0
``` 
3. Go to /rss and open one of the category, for example `rss/feed/index/type/category/cid/45/`

### Expected result
1. I want to see correct XML file.

### Actual result
1. I see fatal error from PHP
```
Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in /var/www/creativeshop/brh/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 74
Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in /var/www/creativeshop/brh/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 74e
```

#### Important hint:
After change `cataloginventory/options/show_out_of_stock => 1` feeds is generated correctly.

**Comment by rbayet** [comment]
Confirmed on 2.6.x, same type of PHP fatal error :

```
Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addSortFilterParameters() in /var/www/m2ce/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 93
 Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addSortFilterParameters() in /var/www/m2ce/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 93
```

**Comment by rbayet** [comment]
Note that I find it strange that in 2.5.x, when `cataloginventory/options/show_out_of_stock => 1`, there is not also a fatal error due to method `addSortFilterParameters` missing.

This only means that :
1. neither `if (!$searchQuery->getQueryText() && $layer->getCurrentCategory())` nor `elseif ($searchQuery->getId())` are satisfied 
2. the magento installation does not have any attributes used for sort by having a source model

Point 2. means that's only a problem waiting to happen.
Point 1. leaves me guessing if the fix is valid in terms of behavior/expected results on the feed

**Comment by evilprophet** [comment]
Confirmed, 2.5.x, after change `cataloginventory/options/show_out_of_stock => 1` errors still aprear.
Will you fix it also on 2.5.x or only on 2.6.x?

**Comment by rbayet** [comment]
Hello @evilprophet,

I'll check with @romainruaud, I don't know if we plan to release additional 2.5.x versions as the 2.7.x (M2 2.3.x compatibility) are coming.

PS: thanks for the report, btw !

Regards,

**Comment by evilprophet** [comment]
@rbayet No problem, if not then I'll prepare a patch for myself ;)

**Comment by rbayet** [comment]
Hi @evilprophet,

The issue has been fixed in both 2.6.4 and 2.7.0 releases that were published today.
Unfortunately, we will not release additional 2.5.x versions.

But I've just tested, you can indeed patch/apply the fix on a 2.5.14 version without issue if you decide to stick with that version on your 2.2.2 install.
But I would recommend to upgrade to 2.6.4 in both your M2 environments.

Regards

**Comment by evilprophet** [comment]
Thanks @rbayet 

We will upgrade environments soon, but good to know that I can apply patch without a problem.

Best regards

**Comment by jameskendy** [comment]
I have seen some good ways to fix RSS feed errors define here https://wpitech.com/how-to-fix-wordpress-rss-feed-errors/ . I have implemented the second option and it works for me as the issue was one of my content feed plugin.
