### ISSUE TITLE
Add additional default sort before entity_id

### ISSUE THREAD

**Issue by mdroidian** [Smile-SA/elasticsuite#1221]
Magento Version : 2.2.3

ElasticSuite Version : 2.59

We tried changing the default 'Product Listing Sort by' to [[custom int attribute]] but ran into the issue where it would override some of our boosts.

IE - Boost (On Sale) 10% should be at the top of Catalog Pages, but based on the [[custom int attribute]] values, this might not be the case.

Product 1 - [[custom int attribute]] = 1
Product 2 - [[custom int attribute]] = 1
Product 3 - [[custom int attribute]] = 2 
Product 4 - [[custom int attribute]] = 2 (On Sale)
Product 5 - [[custom int attribute]] = 2

Expected Results:
Product 4 - [[custom int attribute]] = 2 (On Sale)
Product 1 - [[custom int attribute]] = 1
Product 2 - [[custom int attribute]] = 1
Product 3 - [[custom int attribute]] = 2 
Product 5 - [[custom int attribute]] = 2

Actual Results:
Product 1 - [[custom int attribute]] = 1
Product 2 - [[custom int attribute]] = 1
Product 4 - [[custom int attribute]] = 2 (On Sale)
Product 3 - [[custom int attribute]] = 2 
Product 5 - [[custom int attribute]] = 2

**Is there a place we can add a default sort before entity_id in the code?  I believe this would solve our issue.**
As per https://github.com/Smile-SA/elasticsuite/issues/344#issuecomment-286697672

> In fact, we are sorting products in front office the following way :
> - First comes the products which have been set to "Manual Sort" by the Drag and Drop feature
> - Then the boosts (Catalog Optimizers) if some of them are applicable.
> - If there are no boosts, then all products have the same score (which equals to 1).
> - Finally, all products having the same score are sorted by their entity_id (desc).

We'd like:
- First comes the products which have been set to "Manual Sort" by the Drag and Drop feature
- Then the boosts (Catalog Optimizers) if some of them are applicable.
- If there are no boosts, then all products have the same score (which equals to 1).
- **All products having the same score are sorted by [[custom int attribute]] (desc).**
- **If same [[custom int attribute]] sort by their entity_id (desc).**

Could you direct us to the files we'd need to change to allow this?

**Comment by rbayet** [comment]
Hi @mdroidian, 

The sorts by _score and and entity_id are applied deep down in `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::addDefaultSortOrders`
```
    /**
     * Build sort orders from array of sort orders definition.
     *
     * @param ContainerConfigurationInterface $containerConfig Request configuration.
     * @param array                           $orders          Sort orders definitions.
     *
     * @return SortOrderInterface[]
     */
    public function buildSordOrders(ContainerConfigurationInterface $containerConfig, array $orders)
    {
        $sortOrders = [];
        $mapping    = $containerConfig->getMapping();

        $orders = $this->addDefaultSortOrders($orders, $mapping);
[...]
    /**
     * Append default sort to all queries to get fully predictable search results.
     *
     * Order by _score first and then by the id field.
     *
     * @param array            $orders  Original orders.
     * @param MappingInterface $mapping Mapping.
     *
     * @return array
     */
    private function addDefaultSortOrders($orders, MappingInterface $mapping)
    {
        $defaultOrders = [
            SortOrderInterface::DEFAULT_SORT_FIELD => SortOrderInterface::SORT_DESC,
            $mapping->getIdField()->getName()      => SortOrderInterface::SORT_DESC,
        ];

```

The fact this method is in `Smile\ElasticsuiteCore` means those default sort orders will applied be to any entity (categories, products, etc).
But of course, you can conditionally apply the sort order according to `$mapping`.
Unfortunately, the method is private, so the closest location / solution is an afterPlugin on `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::buildSordOrders`.

Then again, please be careful with https://github.com/Smile-SA/elasticsuite/issues/344#issuecomment-286697672 it describes what happens when a category is navigated and when the selected/default sort order (selected in the toolbar) is "position".
For instance : 
```
  "sort": [
    {
      "category.position": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "keyword",
        "nested_path": "category",
        "mode": "min",
        "nested_filter": {
          "terms": {
            "category.category_id": [
              "43"
            ],
            "boost": 1
          }
        }
      }
    },
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "entity_id": {
        "order": "desc",
        "missing": "_first",
        "unmapped_type": "keyword"
      }
    }
  ],
```

As explained : 
- first `category.position` (the positions defined by the Drag and Drop feature)
- then `_score` (for all the products with the same position ie those with an undefined position)
- then `entity_id` (for all the products with the same score - mostly those unaffected by the optimizers)

Of course, if the explicit sort order selected in the toolbar is another field/attribute, the situation differs.
Here with price + ASC :
```
  "sort": [
    {
      "price.price": {
        "order": "asc",
        "missing": "_last",
        "unmapped_type": "keyword",
        "nested_path": "price",
        "mode": "min",
        "nested_filter": {
          "terms": {
            "price.customer_group_id": [
              0
            ],
            "boost": 1
          }
        }
      }
    },
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "entity_id": {
        "order": "desc",
        "missing": "_first",
        "unmapped_type": "keyword"
      }
    }
  ]
```

- first `price.price` ASC 
- then `_score` (for all the products with the same price)
- then `entity_id` (for all the products with the same score - mostly those unaffected by the optimizers)
=> The positions defined in the Drag and Drop interface are no longer taken into account, but the optimizers still apply locally.

So if you write a plugin for `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::buildSordOrders`, you'll need to 
- certainly limit for which container/mapping (`$containerConfig`) to apply your additional sort order (logically, only for 'catalog_view_container')
- possibly apply it only when sorting by 'position' (according to your needs) ie only when the first sort order field is 'category.position'
- maybe alter the sort order **direction** according to the primary sort order direction

I realize my answer is a bit extensive, but I wanted to cover all bases.

Regards,
Richard.

**Comment by mdroidian** [comment]
Thanks Richard!
