### ISSUE TITLE
Incorrect index pricing when "Special Price from" is specified, but not "special price"

### ISSUE THREAD

**Issue by justinharris1986** [Smile-SA/elasticsuite#1241]
This is actually a Magento bug that I created: [https://github.com/magento/magento2/issues/19915](https://github.com/magento/magento2/issues/19915)

However, I wanted to give you a heads up, in case if you wanted to put in a work around

**Comment by romainruaud** [comment]
Hello @justinharris1986 

you may probably have already noticed, but the issue https://github.com/magento/magento2/issues/19877  has a PR attached in, so this bug will be fixed upon a new Magento minor release.

We do not plan to introduce workaround for this one in ElasticSuite since we consider this is Magento's responsibility to index correct product prices.

Thank you for pointing this to us.

Regards
