### ISSUE TITLE
M2.3.x ES2.7.1 | Performance admin category edit

### ISSUE THREAD

**Issue by Swahjak** [Smile-SA/elasticsuite#1244]
We experiencing some 'extreme' performance issues on the category edit page in Magento 2.3.0 (but I assume this happens in other versions as well).

### Preconditions

* ~10k products
* ~3k categories
* 1 root category

Magento Version : 2.3.0

ElasticSuite Version : 2.7.1

Environment : Developer and production

Third party modules :

### Steps to reproduce

1. See preconditions

### Expected result

1. Category edit page loads within several seconds

### Actual result

1. It takes up to 2 minutes (or more) to load the category page
2. Loading the page costs a staggering ~3600 sql queries

A simple comment in `Smile\ElasticsuiteVirtualCategory\Model\Rule::154` reduces the number of queries from 3670 to 1269 and the load time from 83 to 23 seconds (on a development box, all cache enabled).

`Smile\ElasticsuiteVirtualCategory\Model\Rule::154` causes a recursive call for subcategories AND fires at least one count query. I'm not sure on a solution just yet. The main problem seems to be the amount of categories (~3000) in a single tree, since the loading gets easier the further you go down the tree.

Still doing some further investigation. Could some body elaborate on what the purpose of this function is?

```php
    public function getCategorySearchQuery($category, $excludedCategories = [])
    {
        $query         = null;

        if (!is_object($category)) {
            $category = $this->categoryFactory->create()->setStoreId($this->getStoreId())->load($category);
        }

        if (!in_array($category->getId(), $excludedCategories)) {
            $excludedCategories[] = $category->getId();

            if ((bool) $category->getIsVirtualCategory() && $category->getIsActive()) {
                $query = $this->getVirtualCategoryQuery($category, $excludedCategories);
            } elseif ($category->getId() && $category->getIsActive()) {
                $query = $this->getStandardCategoryQuery($category, $excludedCategories);
            }
            if ($query && $category->hasChildren()) {
                // $query = $this->addChildrenQueries($query, $category, $excludedCategories);
            }
        }

        return $query;
    }
```

**Comment by romainruaud** [comment]
We'll investigate on this one.

But it seems strange, because we have some websites at Smile with much more products and categories than yours, and afaik we did not face this problem.

But maybe something changed on Magento's core since 2.3.0

Regards

**Comment by romainruaud** [comment]
@Swahjak can you post the full stack trace which leads to this specific line of code in your instance ?

Regards

**Comment by romainruaud** [comment]
And of course, @Swahjak , please tell me how much virtual categories you have across all your tree.

Because getCategorySearchQuery is basically : 

- the initial category search query (can be a virtual rule, or a simple category_id matching)
- combination of all virtual categories rules found among children
- non-virtual childrens are ignored, since non-virtual categories are is_anchor = 1, so products in a non-virtual child category is de facto associated to the parent.

=> so, if there are many virtual categories across all your tree, calling `getCategorySearchQuery` on the root category of the tree can cost some resources.

PS : please give me also the stacktrace I asked in previous comment.

Regards

**Comment by romainruaud** [comment]
@GuiltyNL , @Swahjak 

I understand that this issue is pretty annoying, **but** we'll need precise metrics and more details to investigate further.

So please again, can you provide : 

- details about number of categories & virtual categories.
- do you have some virtual categories having a "virtual category root" set ?
- do you have some virtual categories that are having childrens (maybe virtual childrens)
- the stacktrace leading to the `getCategorySearchQuery` 
- anything else that you find relevant.

Regards

**Comment by GuiltyNL** [comment]
@romainruaud I'm willing to give you a backend login if you like.

- We have about 390 categories and about 145 virtual categories.
-140 virtual categories belong to a virtual main category, but it is not the root . We use virtual category 'Brands' and underneath we have all virtual categories per brand.
- I'm not a developer, so I'm not able to do anything with a stacktrace unfortunately.
- We have about 2600 product on our front end and another 2500 products that are EOL

**Comment by Swahjak** [comment]
@romainruaud I'm sorry for not being very responsive, had a little ski incident but I'm up (not yet running) again. Ever since we've been using virtual categories (in Magento 1 using another extension) we consider virtual categories to be the way to go. Currently ~500 out of 1300 categories are virtual, but our aim would be to have 1300/1300 categories. All these categories are part of a single root. That is part of the reason why I asked you about `getCategorySearchQuery` and it being recursive.

> do you have some virtual categories having a "virtual category root" set
Yes, but currently they are all set to the actual root category. The root being the actual root category is a result of migration from M1 since we had no such option in M1. This could be updated though if it improves performance.

> do you have some virtual categories that are having childrens
So yes, we have quite a lot of nested virtual categories.

> the stacktrace leading to the getCategorySearchQuery
Will report back when I get the chance.

**Comment by romainruaud** [comment]
Okay, that's concurrent with what I was guessing.

Several points to note here : 

Virtual categories should have been named "marketing categories", since their initial purpose was to allow our customers to define some "specific" categories based on rules, like "discounted products", "this is blue week, here are all the products having color blue", or even "it's mother's day, take a look at this selection of products based on a rule".

In fact, we designed it for "limited time / marketing events" to benefit their on-the-flight refreshing (since the engine is called directly with the rule when reading the page on frontend, this allow these pages to reflect changes on matched products quickly)

But from what we can often see on projects, many people are using more intensively (should I say "over-using") than what they were built for : 

- they use them to automatically dispatch products into the good categories (most common example of this is the "brand" example given by @GuiltyNL ) when they should have done this dispatching via their catalog import process. Product - Brand relationship is not something that may change often over time, it should just be saved in DB and not based on a "dynamic" computing of a rule.

- people are building complete category trees with virtual categories, modelizing relationships between product & categories even for use cases that are not subject to regular moves.

I'm fine with it, because when you give people a tool, they often push it to the limits, and that's cool to see this intensive usage.

However, I think we reached some limits here, due to how things are done : keep in mind that since there are no materialized product/category association, we **have** to compute each virtual rule, and imbricate them (if there are plenty of them under the same tree entry) to find exactly which product is belonging to each category. 

That goes easy if you stick into the "legacy" usage and create a limited number of virtual categories to support marketing events or commercial operations, but it can also increase heavily the payload when there are many rules to compute and imbricate (even if the result is then put into cache).

I hope you understand what I'm describing here. For now, I see several different ways to handle things : 

- allow to have "materialized virtual categories" : it would be like the legacy visual merchandiser, compute category/product association, and save it on the DB. However, this would involve a reindex step at the cost of flexibility and on-the-fly request processing.

- add a richer entity management, allowing to define "entity" with rich list of attributes (EAV), and several entity pages layout : this would allow to define a "brand" entity, which would then have a nice page, with a picture, a description, and so on.

Regards

**Comment by romainruaud** [comment]
Nope, the so called `smile_virtualcategory_catalog_category_product_position` only contains the product positions for a given category (that can be virtual or not... and for this, this table is very poorly named). 

In fact, this table is filled only when you merchandise a product inside a category (if you drag and drop it, pin it, or blacklist it). Rest of time the table is empty.

About your usecase, I think that yes, it might be a complex chain of misusage (which is often the case on IT projects :) ). In my opinion, you were lacking a tool that could be use to automatically assign products to the proper **fixed** categories : it's an immutable assignment (I could call it a "semantic assignment" which is different from a "marketing / commercial operation assignment") that should be persisted somewhere. You should have probably used a dedicated tool like a PIM (like Akeneo) to define these kind of automatic assignment.

One point that is not in favor of using a "fully virtual" tree, is that you are completely unable to export a properly categorized catalog to third parties (like Google Shopping or things like this) because the link between a product and the "virtual" categories he belongs to is impossible to fetch when exporting.

Of course, I keep this topic open, because it's still an open discussion.

Regards, and thank you for giving me more details about how you use our product.

**Comment by Swahjak** [comment]
Ok, all things considered. Whether or not this should / can / will be part of this repository; To fix this issue we need an indexer that monitors category / product saves and indexes the category => product relations accordingly. Or that would be your initial suggestion. Am I correct? In my mind a 'virtual' tree can actually be materialized without to much trouble. The 'rules' you are talking about when referring to Akeneo are basically the rules we have already configured using ElatiscSuite.

**Comment by Swahjak** [comment]
@romainruaud for now we decided that (for us internally) it makes more sense to develop a separate module to handle "dynamic categories" including the indexer. It has no ties to ElasticSuite. We might publish it at some point, but for now we're keeping it internal until we have done some proper testing. Speaking for myself; this issue can be closed if there is no intention to integrate this feature into ElasticSuite.

**Comment by romainruaud** [comment]
Closing, we won't go further on this one for now.

Regards
