### ISSUE TITLE
Elasticsuite-2.6.0 error after running setup:upgrade

### ISSUE THREAD

**Issue by pioneerathletics** [Smile-SA/elasticsuite#1262]
### Preconditions

Magento Version : Magento CE 2.2.6

ElasticSuite Version :~2.6.0

Environment : Production

Third party modules : ShipperHQ and AvaTax 

### Steps to reproduce

1. composer require smile/elasticsuite ~2.6.0
2. php magento setup:upgrade
3.

### Expected result

1. After running setup:upgrade - module should install correctly

### Actual result

1. Receiving error when running setup:upgrade
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_default_catalog_category_], must not start with '_'","index":"_default_catalog_category_"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_default_catalog_category_], must not start with '_'","index":"_default_catalog_category_"},"status":400}

**Comment by pioneerathletics** [comment]
Hi,
Yes I did run this directly on production. All I did was run composer require smile/elasticsuite ~2.6.0

**Comment by romainruaud** [comment]
Well... it's not recommended to run composer require directly on production. I guess it does not cleanup all the caches properly (especially configuration cache, and things like this).

You should install the module via composer require on your dev environment, then commit the changes into the app (composer.json, composer.lock, app/etc/config.php) and process a deployment on production again.

Regards

**Comment by bbatista** [comment]
Hi I am having a similar issue. I have a testing magento 2.2.6 instance, and I tried to install the version 2.6.0 exactly like described here on the first message. But when I try to run the *setup:upgrade* I am having an issue during the installation, and it is not installing correctly: 
```
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster
```
By the error message seems it is trying to access the ES cluster during the installation, but the ES is not on localhost, that I think should be the default path, and since it is not installed I can't set the configuration path.
Do you have any clue about what might be going on here?

Thanks in advance
