### ISSUE TITLE
Boost Products in QuickSearch

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1299]
So following #1294 I added an optimized.

Turns out I can only optimize the normal search results, quick search is missing here?

![image](https://user-images.githubusercontent.com/1087128/52637620-05639b80-2ed0-11e9-9e10-031610ae5c8c.png)

    smile/elasticsuite 2.6.4 Magento 2 merchandising and search engine built on ElasticSearch 
    magento/product-community-edition 2.2.6 eCommerce Platform for Growth (Community Edition)

**Comment by romainruaud** [comment]
In fact on versions <2.8 (which is the next major, not released yet), the autocompletion container has been removed. I'm not sure why, because it was done by my former teammate.

So on your current version, "Catalog Product Search" will boost the autocomplete box and also the search results.

When you'll update to ElasticSuite 2.8, you'll see a dedicated request type for the autocompletion, allowing to define custom relevancy for autocompletion requests, and also create optimizers dedicated to autocompletion.

Regards

**Comment by amenk** [comment]
I do not have a need to boost autocomplete and search results differently. In fact, this would be confusing to end-users.
But it does not to seem to boost the autocomplete box in my case ...

**Comment by amenk** [comment]
Ah wait, this is related to #1295 - I am talking about my own custom quicksearch-reuse

So the question is how to use the optimizers in an API route

**Comment by amenk** [comment]
@romainruaud but it seems to be a different cause from that in #1295 -> the di.xml of module-elasticsuite-catalog-optimizer is all global `vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/etc/di.xml`

**Comment by romainruaud** [comment]
Yes, they should be triggered in any cases. 

Does your optimizer boost the search results pages ? (if you can access this frontend page).

There was many known issues on 2.6.x versions about wrong cache policy for optimizers (not properly cleared when saving an optimizer, see https://github.com/Smile-SA/elasticsuite/pull/1063 )

Maybe you are in this case, try a complete cache clean and see if it's better ?

Regards

**Comment by amenk** [comment]
Search result page + normal quicksearch is working fine. I did a bin/magento cache:flush several times :-)

**Comment by amenk** [comment]
- Updating smile/elasticsuite (2.6.4 => 2.6.6)

problem persists ..

**Comment by romainruaud** [comment]
Well then check on `Smile\ElasticsuiteCatalogOptimizer\Plugin\QueryRewrite` that you are passing on the aroundCreate (this plugin will rewrite the query to add the optimizers).

If yes, then check `Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\ApplierList` on : 

- applyOptimizers
- getFunctions

where you are losing data.

But when writing this, I'm unsure about what is used as the current store Id when going through your API ...

Check what is stored in $containerConfiguration->getStoreId() on the getFunctions() call.

**Comment by amenk** [comment]
public function applyOptimizers(ContainerConfigurationInterface $containerConfiguration, QueryInterface $query)
    {
        $functions = $this->getFunctions($containerConfiguration);

seems to return the proper one ... let me see what's the executed query

**Comment by amenk** [comment]
![screenshot_auswahl_003](https://user-images.githubusercontent.com/1087128/52648663-2e435b00-2ee7-11e9-954b-2d9e3cc931fe.png)

QuickSearch and my API seem to work completely different ...

I am doing this:

        $productCollection = $this->collectionProvider->getProductCollection();
        $productCollection->setSearchQuery($title);

But maybe it's also the DI config in the background...

**Comment by amenk** [comment]
The rest of the query is identical --- boost function etc. is there

**Comment by amenk** [comment]
I was able to fix that by replacing

        $productCollection->getSelect()->limit(self::MAX_RESULTS);

with

        $productCollection->setPage(1, self::MAX_RESULTS);


Seems that directly accessing the select is a bad idea.

So ElasticSearch wise the correct result was returned, then all messed up

**Comment by amenk** [comment]
Thanks a lot for your support @romainruaud

**Comment by romainruaud** [comment]
Difference between both query is imho explained by the fact that default behaviour of quick_search is to append **several** search terms (because it injects all search terms related with the current term the user is typing). See https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Autocomplete/Product/Collection/Filter.php#L76 which returns always an array.

That's why it's wrapped differently with Bool clauses, but this does not change the final result of the query.

And about the second part : yes, it's not a good idea to directly access the Select, since the engine is managing the limit, pagesize, and so on.

We only process a select at the load time, to fetch data. And you have to keep in mind that it's a **load by id** where we fetch the product by the ids returned by Elasticsearch.

In fact you can't manipulate the Select, if you need to manipulate it (to join on tables or things like this), you should better have the associated data indexed into the ES documents (that's why we index stock status, to be able to filter on it directly with the engine).

Regards
