### ISSUE TITLE
Optimizers : problem with escapement of attribute name

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/elasticsuite#1310]
Hi,

When editing Optimizer from admin, if you add a rule condition on attribute, there is a small problem with escapement of attribute names (capture joined)

![2019-02-18_154823](https://user-images.githubusercontent.com/47741932/52958645-d39d7980-3394-11e9-8c99-edbd9fb3376a.png)

Magento Version : Magento commerce 2.2.5
ElasticSuite Version : 2.6.3

Regards

**Comment by rbayet** [comment]
Occurs both in optimizers and category virtual rules.
Does not occur in native rules (sales rules and widget rules).

**Comment by rbayet** [comment]
As simple as being due to `\Smile\ElasticsuiteVirtualCategory\Block\Adminhtml\Catalog\Category\VirtualRule::_toHtml` and `\Smile\ElasticsuiteCatalogOptimizer\Block\Adminhtml\Optimizer\RuleCondition::_toHtml` (see below) ?
```
    /**
     * @SuppressWarnings(PHPMD.CamelCaseMethodName)
     * {@inheritDoc}
     */
    protected function _toHtml()
    {
        return $this->escapeJsQuote($this->getForm()->toHtml());
    }
```

Comparing `src/module-elasticsuite-catalog-rule/view/adminhtml/templates/product/conditions.phtml` (template of these blocks' renderer  - `\Smile\ElasticsuiteCatalogRule\Block\Product\Conditions`) to `vendor/magento/module-catalog-rule/view/adminhtml/templates/promo/fieldset.phtml` and `vendor/magento/module-catalog-widget/view/adminhtml/templates/product/widget/conditions.phtml` does not give any indication if this escape dating back to 2016 is still relevant or not.

**Comment by romainruaud** [comment]
If legacy rules are not broken, I'd think that this escaping is not relevant anymore.

Can you try to remove it and submit a PR ?

Thanks

**Comment by romainruaud** [comment]
Closed by associated PR. Will be part of next minor releases.
