### ISSUE TITLE
Optimizers: configuration of boolean attributes to be usable in rule conditions

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/elasticsuite#1312]
Hi

There is something weird on boolean attributes that is different from other types of attribute...

To make any attribute visible and usable in Rule condition list, you have to set the Storefront property named **"Use for Promo Rule Conditions"** to **Yes**.
But for boolean attributes, you have to **"Use it in layered navigation"**, that is something you might not want. 

**Steps to reproduce**
- Create a boolean attribute and set "Use for Promo Rule Conditions" to Yes
- Create an new optimizer : the boolean attribute is not available in the list of attributes
- Edit the boolean attribute and set "Use in layered navigation" to Yes, save it
- Reload optimizer edition : the boolean attribute is now available.

Magento Version : Magento commerce 2.2.5
ElasticSuite Version : 2.6.3

Regards

**Comment by romainruaud** [comment]
When building the available attribute lists for rules, we only check if the associated field in the ES mapping is "filterable" or "searchable" : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php#L139

It's wrong because a field can be in the mapping even if not "searchable" or not "searchable" : if it's only "used_for_promo_rules", the field is indexed and is also on the mapping.

Will dig more on this one.

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor releases 2.6.7 & 2.7.5
