### ISSUE TITLE
Category Filtering, Navigation Issue - Feature / Bug

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1320]
One of the weaknesses of ElasticSuites layered navigation is if you’re on a child category you can’t see it’s parents in the left navigation.  As an example, if you have parentCategory -> childCategory -> subChildCategory.  and you go to the subChildCategory, there is no way to go back to childCategory or parentCategory without using Magento's main navigation or the browser's back button.  In stock Magento, this is handled through a URL parameter and anchors to allow a user to click "Clear All" or "delete" the current Category Filter. 

### Preconditions

Magento Version: 2.3

ElasticSuite Version : Latest

Environment : Any 

Third party modules: ElasticSuite

### Steps to reproduce

1. Install Magento's Sample Data 
2. Install ElasticSuite 
3. Go to https://storeurl.com/women/bottoms-women.html
4. Click on Category Pants 

### Expected result

1. You are now "Filtering by" Pants 

### Actual result

1. You are taken to the pants category, which prevents you from going back up the tree. 

I believe there needs to be a way like stock Magento to Traverse back up the Category Tree after you anchor.  

****
@romainruaud and @rbayet, I updated my issue as I compared Stock Magento to Elastic and it appears a feature wasn't considered or lost of Stock Magento when implementing your module.

**Comment by rbayet** [comment]
Hi @duffner,

It's more a design choice than a bug IMHO.

I'm not saying this is perfect, for instance on Luma, if I'm filtering the ["Women > Tops" category to have only blue products in the price range "25 - 66"](http://demo.magento-elastic-suite.io/index.php/women/tops-women.html?color=Blue&price=25-66) and clicking on the category filter item "Tees (5)", I'm not really expecting to reach a page with 12 (instead of 5) products (because I lost both color and price filters).

Granted "in place filtering" could be implemented and it could resolve some other issues the current behavior has, for instance if the selected child category does not display any product list but only CMS blocks, it disrupts the customer navigation/what he was doing.
But the proper way to do it would be to offer the option on a per-category basis, with a dedicated category attribute.
I'll let @romainruaud share his opinion, but we would gladly review any PR going this way.

Regards

**Comment by romainruaud** [comment]
We'll implement this to be working exactly the same as legacy Magento does : no-redirect on category filter usage.

I can bet it was doing a redirect on older Magento 2 versions, that's why we implemented it the same way.

Most probably we did not notice the change.

Regards.

**Comment by romainruaud** [comment]
#1388 will implement your need.

Since we do not want to bother any existing users, it will rely on a Configuration settings : 

** Stores > Configuration > ElasticSuite > Catalog Search > Use URL Rewrites for Category Filter in category navigation**

Default will be "Yes", which means the legacy behavior will remain by default. If set to "No", you'll be able to have a category filter which behave as a "drill down" mechanism.

Regards

**Comment by duffner** [comment]
You rock!  I'll give this a shot.
