### ISSUE TITLE
Mana Dev AJAX Navigation Issues

### ISSUE THREAD

**Issue by codefueluk** [Smile-SA/elasticsuite#1334]
When installing the elastic search module there is a conflict with Mana Dev AJAX Navigation.

### Preconditions

Magento Version : 2.3.0

ElasticSuite Version : 5.2.2

Environment : Developer

Third party modules :  ManaDev

### Expected result

1. PHP Fatal error:  Uncaught Error: Call to undefined method Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor::loadFacets() in /htdocs/app/code/Manadev/LayeredNavigationSeo/Plugins/ContentPlugin.php:65

**Comment by romainruaud** [comment]
Hello @interequipment

Most probably and according to the stacktrace you gave, there is a major incompatibility between your module and Elasticsuite.

It's not that surprising if we consider both modules are working on the same functional parts of the layered navigation.

Since compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do.

However, in such cases, we do provide commercial support to ensure building proper compatibility. If you are interested in such kind of support, send and email to [fabien.gasser@smile.fr](mailto:fabien.gasser@smile.fr) and [romain.ruaud@smile.fr](mailto:romain.ruaud@smile.fr) and we'll be able to handle your request.

Best regards.
