### ISSUE TITLE
Catalog Search indexer and ElasticSuite Category Indexing indexer process unknown error

### ISSUE THREAD

**Issue by hirenrk4** [Smile-SA/elasticsuite#1338]
When run the bin/magento indexer:reindex command got following issue

Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}

### Preconditions

Magento Version :2.3.0

ElasticSuite Version : ^2.7

Environment : production

```
elasticsearch/elasticsearch                                       v5.4.0    PHP Client for Elasticsearch
magento/module-elasticsearch                                      100.3.0   N/A
magento/module-inventory-elasticsearch                            1.0.0     N/A
smile/elasticsuite                                                2.7.4     Magento 2 merchandising and search engine built on ElasticSearch 
```

i have one little confusion i have two sites 
**site 1  smile/elasticsuite: "^2.5.0"** 
**site 2  smile/elasticsuite: "^2.7.0"** 

So as per this https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x

**If i upgrade ElasticSearch on the server, will it cause an issue on the site 2? both sites are on same server**

**elasticsuite 2.5.0  is compatible with So as per this https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x ?**

**Comment by rbayet** [comment]
Hello @hirenrk4,

Can you run the `composer info | grep -i elastic` command for your **site 1** with `"^2.5.0"` too ?
Can you also give me your ElasticSearch server version `curl http://your.es.server:9200` ?
And the Magento versions for **site 1** ?

To sum it up : 
- If you are using a 2.5.x release, you cannot go further than ElasticSearch 5.x but you can still use an ElasticSearch 2.x server
- Support for ElasticSearch 2.x has been dropped from the 2.6.0 release and upward
- ElasticSuite is only compatible with ElasticSearch 6.x from the 2.6.0 release and upward
- ElasticSuite is only compatible with Magento 2.3.x from the 2.7.0 release and upward

The error you gave is usually due to the fact that a **"^2.5.0"** install (with a 2.5.x release) gets upgraded to a 2.6.x release of ElasticSuite which is **no longer compatible with the ElasticSearch 2.x instance he used to communicate with**.
I also suppose your **site 1** is a Magento 2.2.x ?

**If I guessed correctly** and if you **plan to continue using the same ES server instance for both sites**, I would advise to : 
- change your composer requirement on site 1 for `composer require smile/elasticsuite ~2.6.0` : so it will never be upgraded to a 2.7.x version which is only compatible with Magento 2.3.x
- change your composer requirement on site 2 for `composer require smile/elasticsuite ~2.7.0` : so it will never be upgrade to a future 2.8.x version where support for ElasticSearch 5.x and 6.x might be dropped (in favor of supporting ElasticSearch 7.x)
- upgrade your single ElasticSearch server instance to ElasticSearch 6.x (preferably) or ElasticSearch 5.x (absolute not recommanded since its EOL is this month, see https://www.elastic.co/support/eol)

Regards,

**Comment by hirenrk4** [comment]
please check curl https://prnt.sc/msv3ne both site are same configuration.

**actually my question is If i upgrade ElasticSearch ElasticSearch **6.x** on the server, will it cause an issue with smile/elasticsuite: "^2.7.0"?** 

smile/elasticsuite: "2.7.0" compatible with ElasticSearch ElasticSearch **6.x**?

**Comment by rbayet** [comment]
Hello @hirenrk4,

I answered you on the compatibility of smile/elasticsuite 2.5.x and ElasticSearch 6.x : they are **not compatible**.

Regards
