### ISSUE TITLE
Active filters as horizontal buttons

### ISSUE THREAD

**Issue by Zyles** [Smile-SA/elasticsuite#1344]
**Is your feature request related to a problem? Please describe.**

It would be great if you can add a horizontal filter list. It is more user friendly than having it to the left IMO. Consider users who are not tech savy. Having the active filters in their face in the main content area rather than on the side makes it easier for them to notice it.

**Describe the solution you'd like**

A horizontal filter list across the toolbar. See screenshot:

![mag_filters](https://user-images.githubusercontent.com/1741593/53937872-b663ed00-40ae-11e9-8c89-1db86ea53845.PNG)

**Describe alternatives you've considered**

None.

**Comment by romainruaud** [comment]
I agree that on an UX point of view, it's better to display filters like this.

However, for now we did just rely on the Magento's legacy way to display filters and we'll probably not go any further on this topic. 

We do not want to constraint our users to have a different display from legacy Magento and since such a behavior is easy to customize, we won't introduce it but rather let Elasticsuite end users do this customization by themselves if they feel like they need to.

Best regards,

**Comment by Zyles** [comment]
You could support both. The sidebar filters don't have to be replaced nor disabled while having this functionality.

**Comment by romainruaud** [comment]
Yes we could. But we won't, because : 

- we don't want to tie customers on "our" design implementation (if you notice, we provide nearly nothing for frontend, except the autocomplete, and our custom slider filter).

- implementing this would then require putting a config setting to enable/disable horizontal layered navigation filter (disabled by default for legacy customers), which is kinda bloaty.

- it's easy to implement and customize by end users without any knowledge of ElasticSuite (pure Magento layout).

Regards,
