### ISSUE TITLE
Autocomplete need complete word ?

### ISSUE THREAD

**Issue by Pigau** [Smile-SA/elasticsuite#1413]
Hi,
I'm trying to configure elasticsuite autocomplete on one of my project, and I notice a behaviour that seem strange to me when I start to search for a product : 

On the demo site :  [http://demo.magento-elastic-suite.io/](http://demo.magento-elastic-suite.io/)
I search for a product named "Impulse Duffle"
I start to type 'Impul' and no product appear
![question_es](https://user-images.githubusercontent.com/17846838/58266563-30d50c80-7d82-11e9-976e-63a670fc5e93.png)
I finish the first word and my product appear
![question_es2](https://user-images.githubusercontent.com/17846838/58266647-6548c880-7d82-11e9-9fcd-b3df0a71c7bf.png)
I start to type the second word "Impulse Du" and the product disappear from autocomplete
![question_es3](https://user-images.githubusercontent.com/17846838/58266737-8f9a8600-7d82-11e9-8911-af65cf06d031.png)
And when I finish the second word, the product appear
![question_es4](https://user-images.githubusercontent.com/17846838/58266756-9de8a200-7d82-11e9-8460-026b5669aa57.png)

Is this a normal behaviour ? I think it was not the case on previous versions of the module ?
On previous versions, when you type new letter or new word the previous results were not hidden. I don't understand why some research have results and others more precise don't.

Thank you for your precisions
Pierre

**Comment by romainruaud** [comment]
if by "previous", you mean "Magento 1", yes !

On Magento 1 we used a filter which is called "edgengram" which allow to index the beginning of each word. "impulse duffle" would have been indexed as im, imp, impu, impul,  and so on...

It's useful for "search as you type", but it dramatically slows the indexation, and increase the size of the index.

On magento 2, the autocomplete works like this :  

For now (but we may refactor this part on a near future), autocomplete is "self-learning", according exactly to the scenario you describe.

First type, you type "impul", no results, because it's unable to expand "impul" to a previously used search term (that could be "impulse").

Once someone has already searched for "impulse", this record will be put (it's legacy Magento code here) in the search terms table, allowing to expand an user typing "impul" to "impulse" search term, and retrieving associated results inside the autocompletion bar.

Regards
