### ISSUE TITLE
Add custom attribute in autocompete template

### ISSUE THREAD

**Issue by artmediastudio** [Smile-SA/elasticsuite#1416]
Autocomplete miniform show title, thumb and price for products. Now I' d like to insert a custom attribute suche author.

I create app/design/frontend/Mytheme/Smile_ElasticsuiteCatalog/web/template/autocomplete/product.html and I 
change in this way
<div class="product-primary"><div class="product-name"><%= data.title %> - <%= data.author %></div></div>

So now I see after title -.

I created app/code/Mycompany/ElasticsuiteCatalog/etc/frontend/di.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
<type name="Mycompany\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig">
    <arguments>
            <argument name="additionalSelectedAttributes" xsi:type="array">
                <item name="author" xsi:type="string">author</item>
            </argument>
    </arguments>
</type>
</config>
But there are no results.
Where is my mistake ?

**Comment by scanjko** [comment]
I have same issue, trying to add custom attribute in same way by adding it in frontend/di.xml, and rendering in product.html. But with no luck.

**Comment by romainruaud** [comment]
Hello guys,

you should also add your attribute so that he will be explicitely fetched from the DB : 

This can be done by injecting your custom attribute code in this array (which is empty by default) : 

https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Autocomplete/Product/AttributeConfig.php#L70

It will then be loaded and computed by the ItemFactory later.

https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Autocomplete/Product/ItemFactory.php

Please let us know if it helps you,

Regards

**Comment by scanjko** [comment]
Thanks @romainruaud for this, after adding attributes to $additionalSelectedAttributes array it is now displaying them in autocomplete!

**Comment by romainruaud** [comment]
Great ! @artmediastudio & @scanjko can we close ?

**Comment by scanjko** [comment]
Yes thanks

**Comment by artmediastudio** [comment]
Thanks for solution
