### ISSUE TITLE
1 Column layout - Category filter does not get set, all categories show same products

### ISSUE THREAD

**Issue by nthurston** [Smile-SA/elasticsuite#1483]
### Preconditions

Magento Version : Magento CE 2.2.8

ElasticSuite Version : 2.6.9

Environment : Default

Third party modules :

### Steps to reproduce

1. Use a 1 column layout for category view page
2. Set manual sort on any product in any category
3. Go to front end any category

### Expected result

1. Should see that category's products

### Actual result

1.  All categories show the same products

![image](https://user-images.githubusercontent.com/4097064/61833901-da4c8300-ae43-11e9-9cb0-55264ed1e03d.png)
![image](https://user-images.githubusercontent.com/4097064/61833958-0405aa00-ae44-11e9-8732-1517752f7588.png)
![image](https://user-images.githubusercontent.com/4097064/61834119-a7ef5580-ae44-11e9-82d3-e749061b7326.png)
![image](https://user-images.githubusercontent.com/4097064/61833937-f3553400-ae43-11e9-9f81-e346e182e8c9.png)
![image](https://user-images.githubusercontent.com/4097064/61833945-fbad6f00-ae43-11e9-9c0d-d6ea59db44d7.png)

**Comment by romainruaud** [comment]
Hello,

you are using an old version of ElasticSuite (and Magento) which is out of scope of our Open Source support policy here on Github.

This is a known bug, due to Magento legacy layout (see https://github.com/Smile-SA/elasticsuite/issues/864 for a potential workaround) which has been fixed on recent versions of Magento.

Regards
