### ISSUE TITLE
Elastic search dont look too fast as page loads on any filterable value

### ISSUE THREAD

**Issue by sumitgithub** [Smile-SA/elasticsuite#149]
Page load on every filter value dont look like fast result process. Can't we do ajax loading of catalog on value change.

**Comment by afoucret** [comment]
AJAX is not something we want to do (too far from Magento standard).

Commit 9cfb355 address the performance issue you have noticed at least partially.
It will be part of the next release (2.3.0) and we will continue to work on performance.
You can test it by using the 2.3.x branch.

Last but not least, Magento uses Full Page Cache, that make loading of categories without filter very fast. We will never achieve such performance on non cached pages.

I close the issue since we will not move forward on AJAX and performance are a too general point to be an issue.

BR

**Comment by sumitgithub** [comment]
Sir can you please provide me code in your plugin so that the product list
can be load through ajax after filters selection.


On Thu, Sep 29, 2016 at 12:57 PM, Aurélien FOUCRET <notifications@github.com

**Comment by afoucret** [comment]
As explained before AJAX loading is not something that we want to achieve and that is in our roadmap.

So we had not written any piece of code and we do not plan to do so. As a consequence we can not provide any piece of code to you. 

At least this kind of service is not part of our Open Source support policy but we could work in the context of our commercial support of the module.

But we are open minded to the code take a look at any contribution of the community on this if you want to contribute to the module.
