### ISSUE TITLE
Not able to search by SKU for newly added product after integrated Smile Elastic Search

### ISSUE THREAD

**Issue by ezest-rajesh** [Smile-SA/elasticsuite#1506]
We have implemented Smile Elastic search module, after implementation all the old products search is working fine with search by SKU.

But recently we have added a few new products, Search by SKU is not working with the newly added product.

We are facing this issue on production, we can't update Magento version as well as Smile Elastic Version, we need a patch that fix this issue.

Please provide a patch file you can reproduce this issue at your end.

Thanks
Rajesh

### Preconditions

We are using production ENV

Magento Version : 2.1.9

ElasticSuite Version : 2.3

Environment : Production

Third party modules : No

### Steps to reproduce

1. Implement/Install Smile Elastic search
2.Add new product
3.Search by SKU with new product
![screenshot-abbottstore com-2019 08 16-15-36-13](https://user-images.githubusercontent.com/46890683/63160857-69f8e200-c03c-11e9-821a-3eca293bd48d.png)

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by androshchuk** [comment]
Hello @ezest-rajesh 

Did you reindex (bin/magento indexer:reindex) after adding new products?

**Comment by ezest-rajesh** [comment]
Hi Dmytro,

Yes, I have done re-index multiple time, search by product name is working perfect but, search by the same product sku is not working.

**Comment by androshchuk** [comment]
Can you give me some problem and normal products? You can only provide SKU for these products.

**Comment by ezest-rajesh** [comment]
Yes,

The SKU = 6744211, sku is in numeric formate.

**Comment by rbayet** [comment]
Hello @ezest-rajesh,

As you might have already read if you searched in the past SKU related issues ([there](https://github.com/Smile-SA/elasticsuite/issues/868#issuecomment-381570489) or [there](https://github.com/Smile-SA/elasticsuite/issues/1166)) we have implemented many fixes in later releases beginning from releases 2.4.0 and 2.5.2.

As searching by SKU really depends on the SKU formats used and each site goals (exact search vs fuzzy search), we end up writing a two parts guide explaining what is [supported out of the box](https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuBasics) by ElasticSuite and [how to tweak it](https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuDetailled) by configuration.
**But** this guide having been written in march of 2019, it applies only from the last 2.6.x versions and upward.

You are using an outdated version of Elasticsuite, which is not considered by our Open Source support commitment anymore.
We can offer you professional service (commercial support) if you are interested.

If this is something that can interest you, feel free to send an email to fabien.gasser@smile.fr and fabrice.dewasmes@smile.fr and they will contact you in return to give you a proposal about how we can work on this topic.
Please take into consideration though, that due to this being summer holiday period on our side, we might not be able to get back to you until a couple of weeks.

Best regards,
