### ISSUE TITLE
No mapping found for [relevance] in order to sort on

### ISSUE THREAD

**Issue by HannesJa** [Smile-SA/elasticsuite#1512]
Sometimes the search landing page shows "Your search returned no results.", even though the autocomplete shows results.

### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.0

Environment : production

Third party modules : Mirasvit SearchAutocomplete (Not affecting the landing page)

### Steps to reproduce

1. Search for any query
2. hit enter to proceed to the search landing page

### Expected result

1. Results should show, if the autocomplete indicates results

### Actual result

1. "Your search returned no results."
*var/log/system.log* shows a lot of these errors:
```
main.ERROR: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [relevance] in order to sort on","index_uuid":"<uuid>","index":"mage2_test_default_catalog_product_<timestamp>"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mage2_test_default_catalog_product_<timestamp>","node":"<node>","reason":{"type":"query_shard_exception","reason":"No mapping found for [relevance] in order to sort on","index_uuid":"<uuid>","index":"mage2_test_default_catalog_product_<timestamp>"}}]},"status":400}
```

### Notes

I enabled debugging mode on the elasticsuite on our test environment, and noticed that some of the queries were trying to sort by 'relevance':
```json
"size":20,
  "sort":[
    {
      "relevance":{
        "order":"asc"
      }
    },
    {
    "_score":{
      "order":"desc"
    }
    },
    {"entity_id":
      {"order":"desc"}
    }
  ],
  "from":0,
  "query":{
...
```
And sometimes, without the 'relevance', but with 'search_query.position':
```json
"size":20,
  "sort":[
    {
      "search_query.position":{
        "order":"asc",
        "nested_path":"search_query",
        "mode":"min",
        "nested_filter":{
          "terms":{
            "search_query.query_id":["8269"],
            "boost":1
          }
        }
      }
    },
    {
      "_score":{
        "order":"desc"
      }
    },
    {
      "entity_id":{
        "order":"desc"
        }
      }
    ],
    "from":0,
    "query":{
...
```

This did not happen, when we were using Elasticsearch 2.3.11, and Magento 2.1.9.
Now with these later versions of both, this has occurred quite often. Not always (which makes the debugging difficult), but a lot.

I've tried to find out how this should behave: should the query sorting be based on **_score**, but the query is trying to use relevance, or based on **_relevance**, but the _score is just mapped to elasticsearch instead?

**Comment by rbayet** [comment]
Hello @HannesJa,

I haven't been able to reproduce your issue on a fresh Luma CE / EE 2.3.1 with ElasticSuite 2.8.0.

The **_score** field is the automatically computed at query time by ElasticSearch given a search request query components (classic match query, phrase matching, phonetic matching components, search optimizers and so on).
The higher the score, the better the relevance of a document/product given the search request.

With ElasticSuite, when you perform a fulltext search, the implicit "Sort By: Relevance" sort order of the toolbar is thus expressed in the ElasticSearch request as a 
```
    {
      "_score":{
        "order":"desc"
      }
    },
```
sort component.
It is achieved by `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::addDefaultSortOrders` :
```
        $defaultOrders = [
            SortOrderInterface::DEFAULT_SORT_FIELD => SortOrderInterface::SORT_DESC,
            $mapping->getIdField()->getName()      => SortOrderInterface::SORT_DESC,
        ];
```

For a given search query, **if** you have used the [search terms merchandizer](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#manual-product-sorting-in-search-results) to set specific positions for products, then the sort components will be 
```
    {
      "search_query.position":{
        "order":"asc",
        "nested_path":"search_query",
        "mode":"min",
        "nested_filter":{
          "terms":{
            "search_query.query_id":["8269"],
            "boost":1
          }
        }
      }
    },
    {
      "_score":{
        "order":"desc"
      }
```
where 
- the `search_query.position` component will apply the fixed position (1, 2, 3...) in ascending order for products which have been positionned in the search merchandizer for your query (here the query of id "8269")
- and then sort the remaining products (those without a fixed position in the search merchandizer) by descending score

This mechanism is handled by the `\Smile\ElasticsuiteCatalog\Plugin\LayerPlugin` plugin 
```
        } elseif ($searchQuery->getId()) {
            $sortFilter = ['search_query.query_id' => $searchQuery->getId()];
            $collection->addSortFilterParameters('relevance', 'search_query.position', 'search_query', $sortFilter);
        }
```
You can see that the `addSortFilterParameters` method first parameter value used is 'relevance' but it's just an internal name.

IMHO, somewhere (maybe in the Mirasvit SearchAutocomplete module or elsewhere in your modules/themes) in the code, something enforces the "relevance / asc" sort order, maybe by calling
- `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::setOrder`
- or `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::addAttributeToSort`  
with `relevance` as parameter.

If the given fulltext search query has **search merchandizer** position, then this explicitly applied sort order is probably overriden by the `search_query.position` component.
But this means that fulltext searches should always fail (due to the explicit sorting on `relevance`) unles it is for a search query with merchandized positions.

I would advise to 
- disable Mirasvit SearchAutocomplete module and see if the problem persists (if not, then report this behavior to Mirasvit)
- try to debug at key locations 
  - `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::setOrder`
  - `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::addAttributeToSort`  
  - or simply in `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::buildSordOrders`

On a side note, concerning 
> Sometimes the search landing page shows "Your search returned no results.", even though the autocomplete shows results.
It is **bound to happen** if you use two differents search engine for the autocomplete (Mirasvit SearchAutocomplete) and the fulltext search (ElasticSuite).

Best regards,

**Comment by romainruaud** [comment]
@HannesJa 

You have a more than exhaustive technical answer below.

I did not dig into the Mirasvit extension source code (and I cannot, since it's not open source), but it's likely unprobable that you can have both this one and Elasticsuite on your website.

Especially considering their extension is providing the same thing as the Elasticsuite autocomplete box.

That being said, supporting third party paid extension is not part of our community support commitment. You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards

**Comment by HannesJa** [comment]
Hello,

Thank you for the detailed response.
We tried to disable the Third party autocomplete module, but it did not affect the result, the error still comes up occasionally. The autocomplete is mostly used because of its looks, and because it seems to handle the *typeahead* functionality quite fast. It is independent of the search engine implementation.

Upon further investigations, it seems that the 
`vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php->setCollection()` always seems to set an order by relevance for the collection (here the getCurrentOrder returns 'relevance`):
```php
if ($this->getCurrentOrder()) {
    if (($this->getCurrentOrder()) == 'position') {
        $this->_collection->addAttributeToSort(
            $this->getCurrentOrder(),
            $this->getCurrentDirection()
        );
    } else {
        $this->_collection->setOrder($this->getCurrentOrder(), $this->getCurrentDirection());
    }
}
```

When the query propagates through the code, it gets prepared within the elasticsuite module, which handles also preparing of the sort orders:
`vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php->prepareSortOrders()`
Here the `relevance` gets turned into `search_query.position`:
```php
if ($useProductuctLimitation && isset($this->_productLimitationFilters['sortParams'][$attribute])) {
    $sortField  = $this->_productLimitationFilters['sortParams'][$attribute]['sortField'];
    $sortParams = array_merge($sortParams, $this->_productLimitationFilters['sortParams'][$attribute]);
}
```
Because it is set in `vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php->beforePrepareProductCollection()`:
```php
} elseif ($searchQuery->getId()) {
    $sortFilter = ['search_query.query_id' => $searchQuery->getId()];
    $collection->addSortFilterParameters('relevance', 'search_query.position', 'search_query', $sortFilter);
}
```

However, this is not always set, so the `relevance` stays unmapped and thus causes an exception in the Elasticsearch.

This seems to be weird, but I am yet to find a reason for this behavious. Since the setting of the `ProductList/Toolbar`'s currentOrder (which seems to be `relevance`) seems standard Magento behaviour, and shouldn't cause any issues?

Could there happen a mapping: `relevance` => `_score`? You mentioned that you implement this in `\Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::addDefaultSortOrders`, but it merely adds the `_score`, it does not map an existing `relevance` into `_score` if such field already exists.

With best regards

**Comment by HannesJa** [comment]
Hello,

Could these diffs be a solution?
```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/<html>SortOrderBuilder.php (<b>Aug 9, 2019 3:04:53 PM</b>)</html>
+++ b/<html><b>Current File</b></html>
@@ -130,6 +130,12 @@
             }
         }

+        // Map `relevance` into `_score`
+        if (in_array(SortOrderInterface::DEFAULT_MAGENTO_RELEVANCE_FIELD, array_keys($orders))) {
+            unset($orders[SortOrderInterface::DEFAULT_MAGENTO_RELEVANCE_FIELD]);
+            $orders[SortOrderInterface::DEFAULT_SORT_FIELD] = ['direction' => SortOrderInterface::SORT_DESC];
+        }
+
         foreach ($defaultOrders as $currentOrder => $direction) {
             if (!in_array($currentOrder, array_keys($orders))) {
                 $orders[$currentOrder] = ['direction' => $direction];
```
and
```diff
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/<html>SortOrderInterface.php (<b>Aug 9, 2019 3:04:53 PM</b>)</html>
+++ b/<html><b>Current File</b></html>
@@ -41,6 +41,7 @@
    const DEFAULT_SORT_NAME     = 'relevance';
    const DEFAULT_SORT_FIELD     = '_score';
    const DEFAULT_SORT_DIRECTION = self::SORT_DESC;
+    const DEFAULT_MAGENTO_RELEVANCE_FIELD = 'relevance';

    /**
     * Sort order name.
```

I tested these ones on local environment, and they seem to map the `relevance` into `_score`, if there comes such a sort field in the query.

With best regards
