### ISSUE TITLE
Are indices supposed to be automatically deleted ? How ?

### ISSUE THREAD

**Issue by Chacalbis** [Smile-SA/elasticsuite#1538]
We recently noticed on one of our server that with a reasonable amount of indexes (less than a thousand), we were running out of RAM for an ES cluster.

After taking a look at wiki, indices and their horodated pattern, we asked ourselves if horodated pattern's only purpose is to garantee uniqueness of its index. 

From our side, ES is indeed creating unique **stacking** indices based on horodated pattern. We clearly are missing something there, because when reindexing these keep being created. In a production context we can't manually purge (by executing `curl -XDELETE 'http://localhost:9200/*'` for instance) and reindex.

The question is the following : **Are indices supposed to be periodically deleted ? If they do, how does it work ?**

**Comment by romainruaud** [comment]
Hello,

there are two types of indices : 

- indices containing objects data : product, categories, CMS page (if using the module dedicated to this), and thesaurus.

- indices containing users interactions (used to draw the Search Analytics dashboard in the BO).

**Data related indices :**

There is supposed to be always **one index per store view and per entity type**. This index **is deleted during reindex** (at the end of reindexing) and **a new one is created**. After this, we proceed to an alias switch between the old and the new index so that Magento is still able to query the proper index. Considering this, they should be **unique**.

As an example, for a Magento 2 instance with two stores (fr and english), you'd have : 

- magento2_en_catalog_product
- magento2_fr_catalog_product
- magento2_en_catalog_category
- magento2_fr_catalog_category
- magento2_en_catalog_thesaurus
- magento2_fr_catalog_thesaurus
- ( magento2_en_catalog_cms_page )
- ( magento2_fr_catalog_product )

It can happens that a reindexing fails, and since it does not reach the end, an index partially filled remains (forever). That's a known issue, but should not happen often.

**User interaction indices :** 

For these indices (named **tracking_log_event** and **tracking_log_session**), there will be one index per day, containing all customer's related actions.

These indices are automatically cleaned according to this configuration field (**retention_delay**) : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-tracker/etc/config.xml#L23

By default we keep 365 days of user interactions, which can be huge if you have a lot of people browsing your website. It could be too much if you do not have a _big_ Elasticsearch cluster.

You can reduce this delay if you still want to benefit from Analytics Dashboard, or completely disable the tracking feature to get rid of these indices.

Regards

**Comment by Chacalbis** [comment]
Thank you Romain for the quick and detailed answer 

As regards data related indices, we had reindexing errors recently, which may indeed explains why indices were not cleared.

Concerning user interaction indices, our elasticsuite module version is 2.6.9 (with Magento 2.2.9), so it seels we don't have access to this configuration field.

After further investigations on our side, i will certainly update this issue.

Regards

**Comment by romainruaud** [comment]
You're right, on ElasticSuite 2.6.9 you'll not have the configuration field for retention delay, but you'll not have the search analytics feature either. So if you are not considering upgrading to latest ElasticSuite for now, you can shutdown the tracking feature once and for all, and re-activate it later when you'll update.

We're waiting for the result of your investigations,

regards

**Comment by romainruaud** [comment]
Did you process additional investigations @Chacalbis ?

**Comment by Chacalbis** [comment]
Unfortunately i didn't because i got myself away from Magento 2 projects. I'm closing this question/issue and will update this when the team will spare some time to investigate.
