### ISSUE TITLE
Ability to hide a filter with only 1 value

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1542]
**Is your feature request related to a problem? Please describe.**

On Decathlon Pro website, we have some pages with a filter with only one value, example:

MARQUE
 - Nabaiji (7)

The reason is that the page shows 8 products and there is 1 product with the an empty attribute "brand".

It's a problem because the filter "brand" is not really relevant in that case.

**Describe the solution you'd like**

A nice feature would be to add a new setting on the product attribute
"Allow displaying the filter with only one value =  Yes / No" with "Yes" the default value.

It would be a nice improvement because it's difficult to have a perfect quality on the product database, this setting would help to hide this problem.

**Additional context**

![Capture d’écran 2019-09-16 à 10 27 01](https://user-images.githubusercontent.com/20048184/64943638-9470d180-d86c-11e9-9e21-ad02b95bcd51.png)

**Comment by romainruaud** [comment]
For me, this is not an issue.

We already have a mechanism to hide non-relevant filters : this mechanism is triggered when clicking on a filter would result in an unchanged product list. It could be the case if the 8 products were from the brand Nabaiji.

But on your example, the brand filter is relevant : you have 7 Nabaiji products, and 1 which has a different brand. So it could be relevant to filter between both brands. The problem is that one product does not have any brand, which is, as you said, a data quality.

And also, you could face another situation where you have 1 Nabaiji product, and 7 products without any brand : would it make sense to also hide the Brand filter in this case ? Probably not.

I'm not sure we should provide such workaround for data quality problems as part of our extension.

**Comment by PierrickOlivier** [comment]
ok !
