### ISSUE TITLE
Disabling Categories Merchandising

### ISSUE THREAD

**Issue by datasolution75** [Smile-SA/elasticsuite#1557]
Hi, 

I would like to know if you added an option to disable the Categories Merchandising feature as it's replacing the Magento one : https://docs.magento.com/m2/ee/user_guide/marketing/visual-merchandiser.html

It would be nice to be able to use the standard one.

**Comment by datasolution75** [comment]
No news ?
Anything wrong with my issue ? I can update if needed.

**Comment by rbayet** [comment]
Hello @datasolution75,

We have noticed your question and discussed it briefly internally, but we haven't managed to get the time to offer a proper answer, because it is a tricky matter.

The simple way to disable Elasticsuite categories merchandising feature would be to disable the `smile/module-elasticsuite-virtual-category` module, but of course you're losing the benefit of Elasticsuite Virtual Categories everywhere.
You would also lose (well, actually, they would still be present in the database, but ignored completely) products position and blacklist status that you would have previously set for virtual and non-virtual categories through the Elasticsuite categories merchandiser.

Could you clarify which feature(s) of the Magento EE Visual Merchandiser you miss the most for wanting to be able to use it ?

Regards,

**Comment by datasolution75** [comment]
There are quite a few fonctionalities wich are interesting :

- A larger choice of options to sort the products in the category.

![image](https://user-images.githubusercontent.com/39830829/67218163-32d0f380-f426-11e9-8630-85a8eb61b2f5.png)

- The list system is very simple and intuitive.

![image](https://user-images.githubusercontent.com/39830829/67217787-9c043700-f425-11e9-8ac9-88fb95baafbb.png)

- The grid is also very intuitive : 

![image](https://user-images.githubusercontent.com/39830829/67219055-acb5ac80-f427-11e9-954e-b1d3782bbb0b.png)


And it's something my client is asking. He does not want to have to sort all the products one by one.

**Comment by rbayet** [comment]
Hello @datasolution75,

`smile/module-elasticsuite-virtual-category`  overrides the `category_form.xml ` container node 'assign_products_container' of `magento/module-visual-merchandiser`, so it's not possible at this point to have both components in the admin.

Moreover `smile/module-elasticsuite-virtual-category` stores products positions and blacklist status in a dedicated table `smile_virtualcategory_catalog_category_product_position` without interfering with `catalog_category_product`, so disabling the module allows you to re-start "from scratch" with the native Magento visual merchandiser.

So the simplest way is as stated before to disable `smile/module-elasticsuite-virtual-category` :
```
php bin/magento module:disable smile/module-elasticsuite-virtual-category
```

Regards,

**Comment by datasolution75** [comment]
Ok thank you, but in doing so we will not be able tu use virtual categories anymore ? 

Are you planning to make an update in order to allow the usage of both Magento Visual merchandiser and virtual categories ?

**Comment by romainruaud** [comment]
@datasolution75 : I'm not sure how we could allow the usage of both components. We do not plan to do it for now at least.

I don't understand what you mean by "He does not want to have to sort all the products one by one"

**Comment by datasolution75** [comment]
I don't see a way to sort products inside the category except from using manual sort and sort them one by one (like all the default sorting Magento ee provide in the list). Maybe there is an other way i did not saw.

And you could add an option to just disable the virtual merchandiser without having to disable virtual categories.

**Comment by romainruaud** [comment]
If you want to achieve things like "Put the special price on top", you can do it by creating Optimizers instead of locking products to the top of the list manually (or by fixing them to a specific position like the visual merchandiser is doing).

Maybe I'm wrong but if I remember correctly, the Visual Merchandiser is setting "hardcoded" position to products. So that if you select "special price on top", a product will be pinned to position 1, and if tomorrow this product doesn't have any special price anymore, he might remain in position 1 anyway until someone change his position.

With the optimizers, the scoring is applied real time and will reflect accordingly to product data.

So with Elasticsuite, the drag&drop merchandiser is for fixing particular positions to a limited set of products, and the rest of merchandising should better be done with Optimizers.

Regards
