### ISSUE TITLE
Categories not displayed in the right order in the filters

### ISSUE THREAD

**Issue by LilyBergonzat** [Smile-SA/elasticsuite#1569]
The values of the category filter won't respect the order defined in the category_id attribute administration (for example: number of results).

Magento Version : 2.3.2
ElasticSuite Version : 2.8.1
Environment : Production
Third party modules : None (tested in a vanilla Magento, with just ElasticSuite enabled, and Luma theme)

### Steps to reproduce
1. Set the category_id attribute values sort order (facet sort order) to "Result count"
2. Load a category page that display the category filter with multiple values

### Expected result
1. The values are displayed in the set order, starting with the one that has the most results, ending with the one that has the least results.

### Actual result
1. The values are displayed following the admin manually set order.

**Comment by LilyBergonzat** [comment]
@romainruaud I created a new issue :) !

**Comment by rbayet** [comment]
Hello @LilyBergonzat,

The issue is that even though `category_ids` is visible in the product attributes admin grid, we ignore it completely (as does pretty much any search engine implementation) as an attribute when building the layered navigation.
Whatever value you switch `is_filterable` / `is_filterable_in_search` to, the category filter **will** be there (provided the current category has children categories).
And it will always be at the first position.

I see you need, so I can imagine it could be done to pull the `category_ids` attribute configuration from within the layer filter model to decide to post-sort the filter items/sub-categories.

But it will not be possible to choose, per category, the filter sort order as it can be done from the category edit form section "Display settings /  Layered Navigation Filters" for regular filterable attributes.

I'll look into it.

Regards

**Comment by rbayet** [comment]
Hello @LilyBergonzat,

The crux of this subject is that the category filter [loops on the current category children categories](https://github.com/Smile-SA/elasticsuite/blob/d683099601c45db323bee07cf1b4690804091230/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php#L134) (hence in the relative children categories order) and picks data from the categories aggregation. 

So, if the actual corresponding request aggregation sent to Elasticsearch was to be modified to take into account the `category_ids` attribute facet sort order defined in admin, whether or not the buckets would actually be returned in the desired order in the response would be of no use as long as [that \Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category::_getItemsData method](https://github.com/Smile-SA/elasticsuite/blob/d683099601c45db323bee07cf1b4690804091230/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php#L134) is unchanged.

Besides, if the `Smile_ElasticsuiteVirtualCategory` module is enabled, the category aggregation is a no longer a [termBucket](https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/Term.php) aggregation but a [queryGroup](https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/QueryGroup.php) aggregation which does not accept a **sortOrder** parameter.
So a smart approach of altering the behavior of 
- [\Smile\ElasticsuiteCatalog\Search\Request\Product\Attribute\Aggregation\Category::getAggregationData](https://github.com/Smile-SA/elasticsuite/blob/d683099601c45db323bee07cf1b4690804091230/src/module-elasticsuite-catalog/Search/Request/Product/Attribute/Aggregation/Category.php#L31)
- and/or [\Smile\ElasticsuiteVirtualCategory\Search\Request\Product\Attribute\Aggregation\Category::getAggregationData](https://github.com/Smile-SA/elasticsuite/blob/d683099601c45db323bee07cf1b4690804091230/src/module-elasticsuite-virtual-category/Search/Request/Product/Attribute/Aggregation/Category.php#L71)
through plugins to include the correct 'sortOrder' parameter is not valid and sufficient at the same time.

The alternative, which you might find sufficient, is to post-sort the items of the category filter 
- it can be done with a single plugin
- it can support 3 out of 4 sort orders 
   - "admin sort" : default behavior of having children categories displayed in the their admin relative order
   - "name" : categories are sorted according to their name / label
   - "result count" : categories with the most products are listed on top

The "relevance" sort order cannot be achieved by this method, though.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category">
        <plugin name="companyname_modulename_layer_filter_category_plugin"
                type="CompanyName\ModuleName\Plugin\Elastic\Layer\Filter\CategoryPlugin" />
    </type>
</config>
```

```
namespace CompanyName\ModuleName\Plugin\Elastic\Layer\Filter;

use Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category as CategoryFilter;
use Magento\Catalog\Model\Config as CatalogConfig;
use Magento\Catalog\Model\Product;
use Magento\Framework\Exception\LocalizedException;
use Smile\ElasticsuiteCore\Search\Request\BucketInterface;
use Magento\Catalog\Model\Layer\Filter\Item as FilterItem;

/**
 * Class CategoryPlugin
 *
 * @category CompanyName
 * @package  CompanyName\ModuleName
 */
class CategoryPlugin
{
    /**
     * @var CatalogConfig
     */
    private $config;

    /**
     * Array of sorted filter items
     *
     * @var array
     */
    private $items;

    /**
     * CategoryPlugin constructor.
     *
     * @param CatalogConfig $config Catalog config.
     */
    public function __construct(CatalogConfig $config)
    {
        $this->config = $config;
    }

    /**
     * Around filter - Get all filter items.
     *
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     *
     * @param CategoryFilter $filter  Layer category filter
     * @param \Closure       $proceed Original method
     *
     * @return FilterItem[] Filter items.
     */
    public function aroundGetItems(CategoryFilter $filter, \Closure $proceed)
    {
        if ($this->items === null) {
            /** @var FilterItem[] $items */
            $items = $proceed();

            if ($categoryAttribute = $this->getCategoryIdsAttribute()) {
                /*
                 * Values are by default in BucketInterface::SORT_ORDER_MANUAL (by relative position of children categories.
                 * Re-ordering the items if sort order is by count (number of products) or term (name of the category).
                 * Sorting by (products) relevance is not supported.
                 */
                if ($categoryAttribute->getFacetSortOrder() == BucketInterface::SORT_ORDER_COUNT) {
                    $sortValues = [];
                    foreach ($items as $categoryItem) {
                        $sortValues[] = (int) $categoryItem->getCount();
                    }
                    array_multisort($sortValues, SORT_DESC, SORT_NUMERIC, $items);
                }

                if ($categoryAttribute->getFacetSortOrder() == BucketInterface::SORT_ORDER_TERM) {
                    $sortValues = [];
                    foreach ($items as $categoryItem) {
                        $sortValues[] = $categoryItem->getLabel();
                    }
                    array_multisort($sortValues, SORT_ASC, SORT_LOCALE_STRING, $items);
                }
            }

            $this->items = $items;
        }

        return $this->items;
    }

    /**
     * Get category ids product attribute
     *
     * @return \Magento\Eav\Model\Entity\Attribute\AbstractAttribute|null
     */
    private function getCategoryIdsAttribute()
    {
        $attribute = null;

        try {
            $attribute = $this->config->getAttribute(Product::ENTITY, 'category_ids');
        } catch (LocalizedException $e) {
            ;
        }

        return $attribute;
    }
}
```

**WARNING** If the `Smile_ElasticsuiteVirtualCategory` is enabled and the site is in **developer** mode, the plugin will seem to work only on the search results page.
That is because the `Smile_ElasticsuiteVirtualCategory` declares and uses a virtualType extending `\Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category` and in developer mode, plugins applicable to the parent or ancestor class of a virtualType do not work.
In production mode, though, the plugin works as expected.

**WARNING** Please note that I have tested the behavior of the "Name" sorting (which uses the `SORT_LOCALE_STRING` parameter of array_multisort) and it may or may not accurately reflect the (Magento 2) store actual locale behavior in languages with diacritics/accents.
I'm thinking about any fr_* locales here, obviously.
Here are the results for 4 Luma-derived categories named "Cear", "Çear", "Femmes" and "Fémmes" on a "fr_FR" store :
![French_Locale_possible_problem](https://user-images.githubusercontent.com/2353374/67226707-e2619200-f435-11e9-9870-26a964f6c48f.png)

Regards,

**Comment by LilyBergonzat** [comment]
Thank you @rbayet, that solution works perfectly :D !
