### ISSUE TITLE
Is it possible to have indexes based on customer group?

### ISSUE THREAD

**Issue by robbertstevens** [Smile-SA/elasticsuite#1577]
**Is your question related to a problem? Please describe.**

Is it possible to index the products based on customer group, for example if there a products not available for certain customer groups, or if prices differer per customer group?

**Comment by southerncomputer** [comment]
Elasticsuite does load prices per customer group already!

But I had to modify their shared_catalog module to support per-group product availability to exclude items in 1 store to specific users. 

It is not functionality that is currently supported with CE edition but is supported with B2B modules if you want to go with EE+B2B version of Magento!

**Comment by gewaechshaus** [comment]
Hey,

@southerncomputer - do you have any informations how you did realize this in detail? We wan't to have a small amount of items to be visible only for one customer group in a B2C scenario.

Thanks + Cheers
Jan

**Comment by southerncomputer** [comment]
Since we don't use EE B2B - we had to create a table 👍 `describe shared_catalog_product_item;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| entity_id         | int(11)      | NO   | PRI | NULL    | auto_increment |
| sku               | varchar(255) | YES  | MUL | NULL    |                |
| customer_group_id | int(11)      | YES  |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
`
and then neuter the the plugin CollectionPlugin.php to remove the shared_catalog requirements and replace them with plain old customer_group_id .. mainly

  $customerGroupId = $this->companyContext->getCustomerGroupId();

to local user get customer group ..

then 
 $isMasterCatalogAvailable = $this->customerGroupManagement->isMasterCatalogAvailable($customerGroupId);

hardcode this to a value usable for your groupid to be true or false..

Since we sideload all of our products directly into the database using direct sql the table above is not a problem we deal with user interface..

**Comment by romainruaud** [comment]
Two things to consider : 

- this is doable with Magento B2B Shared Catalog modules, out of the box, and if you use the elasticsuite shared catalog module : https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog

- otherwise, you'll have to go with a custom solution (like @southerncomputer suggested). Smile can provide you technical assistance or guidance through customer services if you need to, just reach me out by mail at romain.ruaud@smile.fr if you are interested.

I close because that's not something that could be fixed as part of our Open Source commitment here.
