### ISSUE TITLE
Collision with another 3rd-party extensions

### ISSUE THREAD

**Issue by ityetti** [Smile-SA/elasticsuite#1582]
**Is your feature request related to a problem? Please describe.**
I use your extension with another 3rd-party extensions, and got collision in the file vendor/smile/elasticsuite/src/module-elasticsuite-catalog/etc/frontend/di.xml

If any another extension use node **virtualType** with the same name **categoryFilterList** you will get error like ```Type Error occurred when creating object: CompanyName\ModuleName\Helper\Data, Argument 6 passed to CompanyName\ModuleName\Helper\Data::__construct() must be an instance of CompanyName\ModuleName\Model\Layer\FilterList, instance of Smile\ElasticsuiteCatalog\Model\Layer\FilterList given```

**Describe the solution you'd like**
The simple solution for fix this problem - assign unique name for the node virtualType.
I just replaced name from **categoryFilterList** to **categoryFilterListSmile** in node virtualType and in all the references and it's work perfect.

**Additional context**
I hope this simple solution will be added in one of the updates)

**Comment by ityetti** [comment]
@rbayet CompanyName\ModuleName\Model\Layer\FilterList extends Magento\Catalog\Model\Layer\FilterList

**Comment by rbayet** [comment]
ok @ityetti, **if I wanted to get cheeky**,  I'd say that `CompanyName\ModuleName\Helper\Data` contructor could simply accept a `Magento\Catalog\Model\Layer\FilterList` parameter instead of a `CompanyName\ModuleName\Model\Layer\FilterList` parameter. :imp: 
Of course, it would not solve at all your problem because that helper would probably not work at all like expected.

I can't promise we will look into very soon, as 
- it can be addressed externally by a 3rd module solving the collision through the DI (basically re-declaring the offending virtualType and changing the classes parameters)
- it would be a BC break for anybody extending Elasticsuite and altering `categoryFilterList`

So should it happen, it would definitely be in a major version.

Regards

**Comment by ityetti** [comment]
@rbayet Thank you. I send similar request to the 3rd module team too. They said that will be investigate how to fix this problem.

**Comment by romainruaud** [comment]
Supporting third party paid extension is not part of our community support commitment. Especially considering this extension is providing something similar to ElasticSuite by plugging (badly) into the same legacy piece of code. You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards

**Comment by NateSwanson7** [comment]
@ityetti I ran into a similar issue with a very popular vendor (Amasty) and their Shopby module. I just created a custom module that changes the file that Smile\ElasticsuiteCatalog\Model\Layer\FilterList extends from to the FilterList in Amasty's extension and that fixed the conflicts I was running into.
