### ISSUE TITLE
Can `elasticsuite_tracker_log_event` be truncated without consequences?

### ISSUE THREAD

**Issue by xpoback** [Smile-SA/elasticsuite#1588]
We've recently got a project with tracking enabled. 
The size of the database is arount 5.5Gb where over 4.5Gb is just one table: `elasticsuite_tracker_log_event`. 

I cannot see the oldest entry, because it has almost 5 millions entries, date is not indexed and the IDs don't seem to be ordered by date. By I suppose it has never been cleaned.
It's basically impossible to work with it dues to the huge size - any query, even with a limit takes ages. 

Where are no foreign keys, no indices. So it's hardly possible to find any info there except for iteration through every entry. It looks like a huge grave of not exactly processable data.

So here are my questions:

- **What is the function of that table**? 
- Is it just a log (as the name implies) and **can it be truncated without consequences**?
- How can we make it smaller? 
- **What is responsible for cleaning it?** How often? Could not find anything in the code.

**Comment by rbayet** [comment]
Hello @xpoback,

Not knowing which version of the module you are using, here are answers considering the recent releases (2.8.x), your actual mileage may vary.

- The function of that table is to temporarily (not kidding) hold the JS tracker hits which tracks searches, product views, category views, product added, etc before the dedicated cronjob comes and consolidates the data in dedicated Elasticsearch indices (with "event" data and "session" data)
- It is in essence, just a log, yes. It can be truncated without any consequence if you do not care about that behavioral data which fuels, for instance, the "Elasticsuite / Analytics / Search Usage" dashboard
- If there are indeed 5M entries in that table, the cronjob may indeed have issues indexing them even with the default 10K pagination size it is supposed to use
- the `elasticsuite_index_log_event` cronjob is. It is configured to run every minute / everytime it can (its schedule is `* * * * *`)

The table has no FK because it is self sufficient nor indices probably to have the best writing performance possible.
But I guess recovering from a situation where the table has more than 1M records (and possibly being still written constantly ?) should Magento 2 cronjobs be disabled has never been tried.

Everything is located in the `smile/module-elasticsuite-tracker` module : 
- it provides the `Stores > Configuration > Elasticsuite > Tracking > Global Configuration > Enabled` which allows you to disable the tracker
- it provides the controller `\Smile\ElasticsuiteTracker\Controller\Tracker\Hit` which writes to the `elasticsuite_tracker_log_event` table
- the 3 associated cronjobs are declared in `vendor/smile/elasticsuite/src/module-elasticsuite-tracker/etc/crontab.xml`
 - elasticsuite_index_log_event / `Smile\ElasticsuiteTracker\Cron\IndexLogEvent` which indexes (and cleans) the database events
 - elasticsuite_anonymize_log_event / `Smile\ElasticsuiteTracker\Cron\ExpireCustomerLink` which anonymizes (if enable) relationship between logged events and customer ids
 - elasticsuite_purge_log_event / `Smile\ElasticsuiteTracker\Cron\CleanTrackingData` which cleans up the **Elasticsearch indices** to avoid accumulating too many indices in your Elasticsearch instance (by default, it keeps only the last 365 days of events and sessions)
- please note that you use the DI to change the default value for the `chunkSize` parameter of the elasticsuite_index_log_event cronjob

Regards,

**Comment by xpoback** [comment]
@rbayet Thank you very much such a quick and full answer.

The version of the module is 2.6.9, so there are some differences, like no data purge.
But I now can see where the problem is: `elasticsuite_index_log_event` appears to be not running at all (for some not yet know reason) and therefore the data is never processed and deleted.
I guess the whole tracking can be disabled, since there has been no complaints from the customer, that tracking is not working, it's probably just not used.  ¯\_(ツ)_/¯

Thank you very much again.
I'm completely satisfied with the answers, so I close the issue
