### ISSUE TITLE
Use of Magento\Catalog\Block\Product\ProductList\Random

### ISSUE THREAD

**Issue by bernd-reindl** [Smile-SA/elasticsuite#1589]
Like in the block Magento\Catalog\Block\Product\ProductList\Random i have added a "random sort" expression to my product collection.
But in Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext the sort order will be changed in _afterLoad(). This might be correct for an query whitch is not random. But for an random query this destroys the random order.

### Preconditions

Magento CE 2.3.3
Elasticsuite 2.8.0
Product Collection with random sort order

Magento Version : CE 2.3.3

ElasticSuite Version : 2.8.0

Environment : developer

Third party modules : also in vanilla M2

### Steps to reproduce

1. Extend \Magento\Catalog\Block\Product\ListProduct and override _getProductCollection to return an random sorted collection (My file is attached)

### Expected result

1. return random sorted product items

### Actual result

1. items sorted by entity id 

My random product block an the modified Collection with my solution for this problem. Maybe there is an better way, but it works for me.
[Files.zip](https://github.com/Smile-SA/elasticsuite/files/3766209/Files.zip)

Same problem might be in Smile\ElasticsuiteCatalog\Model\ResourceModel\Category\Fulltext\Collection

**Comment by romainruaud** [comment]
Hello,

first of all, you have to remain that the workflow when retrieving a product list from the engine is : 

The workflow here is actually the following :

    1 : aggregating all filters (if any) and all sort orders (if any)
    2 : compute this into the Elasticsearch query
    3 : ask Elasticsearch for matching product Ids
    4 : put these product Ids into the SQL query filter
    5 : return the collection

So the sorting must be sent to the ElasticSearch server. Like any other sorting mechanism, the search engine should do this and this cannot be done in SQL (like with `getSelect()->setOrder('rand')`) because the SQL query will alway be filtered with the first page of product Ids matching the query : it would only randomize this list of product ids. That's also what you are doing with your proposal.

But there is actually no support in Elasticsuite to add a random sorting. This could be achieved on an elegant manner with a `function_score` using a random seed like this : 

```
{
  "query": {
    "function_score" : {
      "query" : { "match_all": {} },
      "random_score" : { "seed" : 1376773391128418000 }
    }
  },
  "size": 25,
  "from": 0
}
```

But it would have to be injected in the query assembling part like as a particular case : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php#L72

We'll probably not introduce such a mechanism of random sorting. But if anyone want to propose a Pull Request on this one, I'd be happy to review.

**Comment by bernd-reindl** [comment]
Hello,

 

But „$collection->getSelect()->order('rand()');“ is also used in core code like in Magento\Catalog\Block\Product\ProductList\Random (Row 67) and breaks this too.

 

I'm not familiar enough with elasticsearch to change such things.

Mit freundlichen Grüßen

Bernd Reindl
Engineering & Development

 <https://www.2mountain.com/> logo

Gewerbestraße 10
A-4963 St. Peter am Hart

 <tel:+4377226427720> +43.7722.64277-20
b.reindl@2mountain.com

 <http://www.2mountain.com/> www.2mountain.com

 <https://www.2mountain.com/live-chat.html> live_chat

 

Von: Romain Ruaud [mailto:notifications@github.com] 
Gesendet: Donnerstag, 24. Oktober 2019 14:55
An: Smile-SA/elasticsuite
Cc: bernd-reindl; Author
Betreff: Re: [Smile-SA/elasticsuite] Use of Magento\Catalog\Block\Product\ProductList\Random (#1589)

 

Hello,

first of all, you have to remain that the workflow when retrieving a product list from the engine is :

The workflow here is actually the following :

1 : aggregating all filters (if any) and all sort orders (if any)
2 : compute this into the Elasticsearch query
3 : ask Elasticsearch for matching product Ids
4 : put these product Ids into the SQL query filter
5 : return the collection

So the sorting must be sent to the ElasticSearch server. Like any other sorting mechanism, the search engine should do this and this cannot be done in SQL (like with getSelect()->setOrder('rand')) because the SQL query will alway be filtered with the first page of product Ids matching the query : it would only randomize this list of product ids. That's also what you are doing with your proposal.

But there is actually no support in Elasticsuite to add a random sorting. This could be achieved on an elegant manner with a function_score using a random seed like this :

{
  "query": {
    "function_score" : {
      "query" : { "match_all": {} },
      "random_score" : { "seed" : 1376773391128418000 }
    }
  },
  "size": 25,
  "from": 0
}

But it would have to be injected in the query assembling part like as a particular case : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php#L72

We'll probably not introduce such a mechanism of random sorting. But if anyone want to propose a Pull Request on this one, I'd be happy to review.

**Comment by romainruaud** [comment]
I close this one, nobody did propose any PR for this in a so long period, I consider it not relevant.

regards
