### ISSUE TITLE
Optimizer Rule - Special Price treated as String versus Number, like Price

### ISSUE THREAD

**Issue by KholdenSP** [Smile-SA/elasticsuite#1605]
When attempting to create a new optimizer, I was trying to move items with a special price to the bottom of a category. When I selected "Special Price", the value is treated as a string, rather than a numerical value.

### Preconditions
Magento Version : 2.3.1
ElasticSuite Version : 2.8
Environment : Production

### Steps to reproduce
1. Create a new Optimizer
2. Select Category Product View
3. Apply to any category with any boost value
4. Apply a rule utilizing Special Price

### Expected result
1. Special Price should function as a numerical value, like Price (is, greater than, less than, etc)

### Actual result
1. Special price options are "Contains" and "Does Not Contain"
![image](https://user-images.githubusercontent.com/53538134/67903192-33edd900-fb28-11e9-9ef4-9514c99a914c.png)

**Comment by romainruaud** [comment]
Hello @KholdenSP 

if you plan to boost (or bury) products that are actually discounted, you'd rather use the "Only discounted product" sub-rule.

That being said, I have the same issue as yours with special price being treated as a string BUT the "Special Price" should not be used (and available) in any cases here because it is simply not indexed into the Elasticsearch server : we only have a "price" field containing either the base price, or the special price if there is one. And we have a flag "is_discount" which is set either to true or false depending the fact that a special price is existing or not.

So, if you plan to do a rule like "target all products having a special price", use the "Only discounted product" condition.

If you plan to do a rule like "target all products having a special price under 50$", use a rule on Price like "Price is less than 50" (Price attribute should be treated as a numeric).

Regards

**Comment by rbayet** [comment]
> Hello @KholdenSP
>  [...]
> If you plan to do a rule like "target all products having a special price under 50$", use a rule on Price like "Price is less than 50" (Price attribute should be treated as a numeric).
> 
That is, use an "AND" combination ("ALL those rules ...") with both a rule on "Only discounted products" and a rule "Price is less than 50".

**Comment by KholdenSP** [comment]
Makes a ton of sense. If the attribute is not indexed, what's the point of keeping it in the optimizer selection? Are any others in the list not actually indexed?

**Comment by romainruaud** [comment]
Nope, if an attribute is shown here, it's indexed and available for rules.

Only price & special_price do have this kind of "strange" things embedded.

Regards

**Comment by KholdenSP** [comment]
Thanks a lot.
