### ISSUE TITLE
Exact SKU matching with one result redirect is enabled does not work for some SKUs

### ISSUE THREAD

**Issue by stb** [Smile-SA/elasticsuite#1607]
**Is your question related to a problem? Please describe.**
> If you have a product visible in search, searching exactly for its SKU should either redirect you to the product page (if one result redirect is enabled) or lead you to a search results page with only that product.

On some SKU's the onepage redirect does not work even though the SKU is the same as the search input. 
Example SKU: `COS4101` 
Search Entry: `COS4101`
Result: Page Listing with COS4101 first but then other products with SKU COS4100, COS4011 or C**A**S 4101 in the product name. And the message appears `No exact results found for: 'COS4101'. The displayed items are the closest matches.`
Any ideas what could be causing the issue?

Thanks!

**Comment by southerncomputer** [comment]
I had this problem with a disabled sku matching the search term doing this same thing!

**Comment by stb** [comment]
> I had this problem with a disabled sku matching the search term doing this same thing!

Interesting, although we do not have any disabled SKUs.

**Comment by southerncomputer** [comment]
I suppose it could be a matcher for another store as well? What happens when you manually search for that sku in the fields they may come from in backend? Any more than 1 product hit?

**Comment by rbayet** [comment]
Hello @southerncomputer, I don't think [your issue](https://github.com/Smile-SA/elasticsuite/issues/1573), which has been addressed, is relevant here.
Elasticsuite is perfectly able to mess with SKU searching on its own ;)

@stb, SKU matching is a tough subject and not one where we claim the same relevancy as for "standard" search, because it's absolutely not related to language analysis.
We have written a short [wiki page](https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuBasics) to explain which valid behaviours you can expect and which quirks you might encounter.
There is also a [more technical wiki page](https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuDetailled).

From the look of it (even though you did not provided which versions of Elasticsuite/Magento 2 you are using, please do) I would say that having SKUs in the product name adds a layer of complexity.

Regards,

**Comment by stb** [comment]
Single instance (Apache2, Percona, Elasticsearch), 14 CPU's | 64GB RAM | SSD
Magento Version : 2.3.2 CE
PHP: 7.2
Elasticsearch min_heapsize: 16 GB
1.6M simple products

ElasticSuite Version : 2.8.2

Yeah my simple idea would have been for the redirect that if the search term is 100 %  the value in the field sku, then redirect. But I guess it's not that simple. The name in this example `C**A**S 4101 ` is a name of the product not an actual sku but is spelled nearly the same, which is obviously not ideal. But what also is interesting is why the message appears `No exact results found for: 'COS4101'. The displayed items are the closest matches.` I would guess it tried so some of SKU matching but... Could changing the the indexed fields / search weight have any impact on that? (obviously excluding name might help but that is not an option...)

Regards!

**Comment by stb** [comment]
Any ideas?

**Comment by stb** [comment]
For us we solved it by disabling phonetic search, as this as giving us to maybe "random" search results
