### ISSUE TITLE
Splitting Category Facet

### ISSUE THREAD

**Issue by davidsiemers** [Smile-SA/elasticsuite#1609]
So, I've got an odd one.

This web store I'm working on has two different category groupings: kits and parts. While are they both stored underneath the same root category, they are to be handled very differently from a user experience stand point. The kit grouping is so customers can filter down and buy parts specific to the kit they already own and the parts grouping is more of a catch-all for generic categories.

For example, you could have:
Default Category/Kits/Awesome Kit/Subkit of Awesome Kit/Part of that Awesome Kit
Default Category/Parts/Cool Parts/A Different Part

Someone would know they have the 'Awesome Kit' or 'Subkit of Awesome Kit' and do their searches based on that, and would have a UX tailored to that OR someone could be looking for 'Cool Parts' and find something in there that would work, which would also have a custom UX tailored for that.

Because both of these flows have different user experiences, having everything jammed together in a 'Category' facet doesn't make sense. Instead of 'Category' it'd be better to have 'Kits' and 'Parts' as separate facets, essentially splitting the two and limiting the searches to those.
But, unfortunately, I'm a bit stumped on how to achieve that within elasticsuite.

Can anyone give me some insight or point me in the right direction? Maybe this is too wacky and I need to think of another way to build out these taxonomies. 

Any help is greatly appreciated!

Thanks!

**Comment by rbayet** [comment]
Hello @davidsiemers,

So I imagine a random product would belong to at least one category under both Default Category/Kits and Default Category/Parts ?
Is one of those category trees "hidden" somehow in the catalog navigation ? Or can the visitor browse either categories under Kits or Parts ?
If so, that would complicate things a bit.

Are both your kit/part taxonomies hierarchical ?
The reason for that question is that **if** one of your taxonomy is flat and does not have that an insane amount of values (I'd say between a few hundreds to a few thousand) there would be an option to change plans completely and :
- keep one of your category trees as your it is
- use our modules https://github.com/Smile-SA/magento2-module-custom-entity and https://github.com/Smile-SA/magento2-module-custom-entity-product-link to implement it as that second taxonomy.
The usage of https://github.com/Smile-SA/magento2-module-custom-entity is usually huge catalogs where a simple "brand" attribute is not practical anymore because of its sheer volume.

**Anyway, about splitting the category filter :** 
For the fulltext search, **conceptually**, splitting the category filter into two distinct filters should not be too complicated, the idea is just to "duplicate" the category layer filter model (`\Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category`) and have 
- one working with the default request var ("cat")
- one working with an alternative request var ("kit" or "part")

Now, **technically**, the category layer filter relies on a data provider `\Magento\Catalog\Model\Layer\Filter\DataProvider\Category` of which you would also need two flavours in order for them to not interfere with each others.
I'm thinking about that line : 
```
$this->coreRegistry->register('current_category_filter', $category, true);
```

It will also not possible to have both "current category" (as per `\Magento\Catalog\Model\Layer::getCurrentCategory`) and it will not be possible to have category-restricted search optimizers be applied on both "current filtered categories" (because of that line `$this->searchContext->setCurrentCategory($category);` in `\Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category`).

In catalogsearch, I guess it would mean for you to elect a "main line" (between both categories trees) to act as "regular categories" and the other being your "taxonomy categories".

But in catalog navigation, if you want category-restricted search optimizers, I imagine you would have to switch roles according to which the current category the visitor is browsing, depending on your settings for **smile_elasticsuite_catalogsearch_settings/catalogsearch/category_filter_use_url_rewrites**.
If it set to yes, the default behavior for a category filter item is to expose that category URL without any other currently applied filters.
For instance from http://demo.magento-elastic-suite.io/index.php/men/bottoms-men.html?climate%5B0%5D=Hot&climate%5B1%5D=Cool if you click on one of the items of the Category filter, you're redirected to that sub-category: you are not applying an additional category/taxonomy filter "in place" and you lose the applied values for the "Climate" filter.

To include your additional "Category/Taxonomy" you will 
- either need to write a plugin for \Magento\Catalog\Model\Layer\FilterList::getFilters and add unconditionnally that filter (like it is already done for the native category filter)
- or change the behavior of the FilterList models argument `filterableAttributes` (Smile\ElasticsuiteCatalog\Model\Layer\Category\FilterableAttributeList and Smile\ElasticsuiteCatalog\Model\Layer\Search\FilterableAttributeList) to pass it off as a regular attribute related filter

Feel free to add details about where you've managed to go so far, and what is still nagging you.

Regards,

**Comment by davidsiemers** [comment]
@rbayet 

Thank you so much for your reply!
That makes so much more sense now, can totally see how having them actually being two separate taxonomies can get messy :).
Thankfully, after reading through your response, I realized I may be approaching this from the wrong angle, as these different taxonomies aren't quite as separate as I thought.
They are more-so two different visual paths for selecting a category you want to filter by.
I don't think I need to change any of the functionality on how the categories function from a model perspective, just visually. You would never see the categories 'Kits' and 'Parts' underneath 'Category' section in the layered navigation, instead, you would have the various kits shown underneath a layered navigation section called 'Kits' and the same for 'Parts'. And, generally speaking, you won't see 'Kits' if you're in a 'Parts' category and vice-versa, just like a normal category :).

So, for a category layout that looks like this:

Default Category/Kits/Awesome Kit
Default Category/Kits/Cool Kit
Default Category/Kits/Fantastic Kit

Default Category/Parts/Long Parts
Default Category/Parts/Short Parts
Default Category/Parts/Featured Parts

Instead of the layered navigation looking like this, when you're at the very top level of search results(barring there are matches for each category type):

**Category**
 - Kits
 - Parts

It would be like:

**Kits**
 - Awesome Kit
 - Cool Kit
 - Fantastic Kit

**Parts**
 - Long Parts
 - Short Parts
 - Featured Parts


Now, there are four different views that change how this data is laid out slightly:

1. The search results view. Basically what I showed above. This would function very similar to how it does now, but any matching categories would be split up whether they belong to the 'Kits' category or the 'Parts' category. If there are no matches in 'Kits', it wouldn't show, and the same for 'Parts', much like how a normal category would under the current 'Category' section.

2. When someone is browsing in one of the 'Kits' categories, such as through a link from the menu or home page, it will no longer show the 'Parts' section for any matching categories, it'll instead be more-so a navigation section that will link the user to one of the direct child categories underneath 'Parts'. So, basically just a menu that doesn't get filtered. I'm thinking this one will be the easiest as could be a separate layout that just shows those 'Parts' categories, with no real concern for any matching parts. T

3. The exact same as number 2 but for 'Parts'.  'Kits' would be the menu navigation.

4. The predictive search. Similar to number number 1, instead of showing 'Categories' matches, it'll be 'Kits' and 'Parts' matches for those categories.

Hopefully that makes more sense!

Now, the real question is: how would I go about doing that visual split?
Is something like that even realistically possible?

At the very least for number 1? 

Thanks!

**Comment by rbayet** [comment]
Hello @davidsiemers,

My previous long comment pretty much covers your point number 1 : at the very least, you need a category layer filter model that is de-correlated from 'current_category'. 

2. and 3. : if those blocks' content is not generated by a facet (ie by the products currently shown) then any random PHP navigation block would do. But for the correct products to be show on your page products list, you will still need to have the category filter model from being loaded, even if the block is invisible.

4. I don't get what you mean by predictive search. Do you mean the autocomplete search ?

Regards,

**Comment by romainruaud** [comment]
Hi @davidsiemers 

I'm afraid we've already been much further than what we can provide as part of our (free) open source support here.

If you feel the need to customize more the extension to fit your project needs, we can provide you commercial support as part of our support policy. If this is something you are interested in, please send us an email directly at romain.ruaud@smile.fr

Best regards
