### ISSUE TITLE
Stability and Performance on Magento Cloud environments

### ISSUE THREAD

**Issue by sdaugherty** [Smile-SA/elasticsuite#1613]
There are two major issues which affect stability of Elasticsuite under Magento Cloud environments.

First is the default configuration of shards and replicas. While the defaults work well for Magento Starter environments, on a Magento Pro staging or production environment, a 3 node high-availability cluster is used to deliver all of the backing services. The default configuration of 1 shard and 0 replicas will cause both steadily increasing heap memory usage and steadily increasing replication traffic, which grow with traffic, index sizes, and uptime, ultimately killing Elasticsearch and with it, rendering the Magento application unusable. On Magento Pro staging/production environments, 3 shards and 2 replicas is the optimal, stable configuration.

Second are the tracking logs, the default retention period for these logs appears to be 365 days (see #1538 ) This is far too long to use on Magento Cloud - if it's a Starter environment or an integration environment for a Pro cluster, the environment simply doesn't have the resources. If it's a Pro environment, the tracking logs grow over time, and massively increase the replication overhead, again, filling up the heap memory and increasing network traffic between the Elasticsearch services running on the nodes, and eventually leading to Elasticsearch crashes. Turning off the tracking logs or selecting a much shorter period (7 days to 30 days would probably be ideal) is necessary to maintain stability.

### Preconditions

Magento Version : All supported by Magento Cloud

ElasticSuite Version : All versions supported by Magento Cloud

Environment : Happens regardless of Developer or Production mode

Third party modules : Happens with only Elasticsuite installed.

### Steps to reproduce

1. Install Elasticsuite on Magento Cloud
2. Leave the replication settings and tracking log settings at defaults
3. Expose to production loads
4. Wait for Elasticsearch to start crashing. This typically takes anywhere from a few days to two months.

### Expected result

1. Elasticsuite should be installed with settings that are appropriate for Magento Cloud environments

### Actual result

1. Elasticsuite is installed with settings which result in severe instability under Magento Cloud environments.

**Comment by romainruaud** [comment]
Hello @sdaugherty 

First of all, which version of ECE Tools are you using ? Since the .19 version, the Magento Cloud team added a configuration wrapper for Elasticsuite : 

https://github.com/magento/ece-tools/blob/develop/src/Config/SearchEngine/ElasticSuite.php

This wrapper will inject Magento Cloud cluster configuration (which seems hardcoded right now) into the ElasticSuite configuration.

For now, this helps a lot, but it has counterparts : 

- it lacks some flexibility (I may be wrong here but for me this configuration cannot be edited).
- according to Magento Cloud team, it will use 2 shards with 3 replicas, which is for us **incorrect for a 3 node cluster** : nuber of replicas should be (number of node - 1), so 2 replicas. This can cause some issues with Elasticsearch perpetually trying to allocate the 3rd replicas.

About the retention delay of 365 days, you are able to lower it to 7 days if you want, through the configuration, as you were saying. Taking that into consideration, you can create a configuration per environment for this specific setting.

There is not much more we can provide here as part of our extension, since all the parameters you described are already configurable for the end users. 

Most probably, everything we are saying here should be put into the Magento Cloud Documentation, which will be the case very soon : I've worked with their team about putting these details into their documentation.

Best regards

**Comment by sdaugherty** [comment]
Hmm. I think some signals may be crossed within the cloud team then, There should be one shard for each node (3 in pro, 1 in starter/integration), and one less replica than the number of nodes (2 in pro, 1 in starter/integration) for a correct setup, however I've still seen 1 shard / 0 replicas occasionally on pro clusters that have updated to ece-tools .19 or .20.

I'll see if I can raise a bug with ece-tools to address the tracking log retention, as it usually tends to start inducing crashes somewhere around 30-60 days of accumulated indexes on cloud.

**Comment by romainruaud** [comment]
I close this one since it's related to third party hosting provider (Magento Cloud) and not to the application by itself : 

- problem is known but only occurs on Magento Cloud
- numerous users reported migrating on AWS and getting rid of this issue despite having smaller infra
- application is providing a way to cleanup index data based on retention period
