### ISSUE TITLE
Include custom product or category attributes in Indexing

### ISSUE THREAD

**Issue by sunilkumar707** [Smile-SA/elasticsuite#163]
I have added few custom attributes to product and category. How I can make ES to index those attributes also, so that we can use for result filtering.
For example: Product has custom field called EAN, but indexed ES don't have this field in _source. so customer can't search product by EAN code.

Also please let me know, why product name coming in array it should be string.
```
"name": [
"parle g 500 gm "
]
```

**Comment by afoucret** [comment]
@sunilkumar707 :

In the attribute configuration (**Store > Attributes > Product**), you have to edit your attribute.
There is a **Storefront Properties** tab where you can find an **Use in Search** select (just like a standard Magento install would do)

Fulltext reindexing is needed (it is automatic in minutes if your cron setup is correct) for the change to be applied. 

About, using array or string, they are actually equivalent in ES. We choose to use array only since it makes attributes homogeneous (multivaluated (like multi-select, array backend, ...) or not (like select, varchar, ... ). Some attributes are simple select but when indexed they have multiple values (e.g. size on clothes configurable attributes). It is a lot easier to use array only.

@romainruaud : the attribute search related configuration is missing into the documentation. Can you please update it and then close the issue if my response is ok for @sunilkumar707

**Comment by sunilkumar707** [comment]
Thanks @afoucret for contributing this extension and giving me solution with such a awesome explanation.

**Comment by afoucret** [comment]
@romainruaud : can you fix the doc and close this issue please ?

**Comment by romainruaud** [comment]
See the wiki page : https://github.com/Smile-SA/elasticsuite/wiki/Attribute%20configuration

I close the issue now.
