### ISSUE TITLE
Multiselection of attributes before reloading 

### ISSUE THREAD

**Issue by Kees-kees** [Smile-SA/elasticsuite#1675]
Normally after selecting one attribute value (e.g. Color Blue) the page would automatically refresh showing all products matching the selected attribute vale (e.g. All blue coloured products).

I was then wondering if it’s possible to select more than one attributes in a row (e.g Color Blue, Size M, Genre Man, etc.) so that the page would refresh showing all products matching the previously selected attributes (or maybe a submit button that would refresh the page showing all products matching all selected attributes?)

Is such a solution easy to implement? I’d love to know about your ideas

**Comment by romainruaud** [comment]
Hi,

this could be easy to do with a little frontend development.

However, I do not recommend this, because it's easy to end with a combination that will not match any products, and that could be deceptive for the end user.

The interest of reloading the page each time a filter is selected, is that the newly displayed list of filter is really taking into account what the user has previously chosen as a filter, to refine his selection.

That's not something we plan to implement in Elasticsuite by ourselves, but I'll gladly review a PR containing this feature if you want to contribute it.

Regards
