### ISSUE TITLE
How to create "all products" page ?

### ISSUE THREAD

**Issue by yanncharlou** [Smile-SA/elasticsuite#1678]
I cannot figure how to create an all products page that show all products from the root category with layered navigation.

This really simple module, for example, shows an empty list : https://github.com/php-cuong/magento2-one-page-products
I've tried adding this in etc/module.xml to ensure it is loaded after elasticsuite but don't solve anything.
```
<sequence>
     <module name="Smile_ElasticsuiteCatalog"/>
</sequence>
```
Any idea ?

**Comment by androshchuk** [comment]
Hello @yanncharlou 

If I understand your problem correctly - you can do it with our module.
Create a new category. Make it virtual and select Default Category for Virtual Category Root http://joxi.ru/nAyMzQQFjQGNkA. Also, you may not include this category in the menu if you wish.
Result: http://joxi.ru/12MN144i0KXnMA

Regards

**Comment by yanncharlou** [comment]
Hi androshchuk, thank you for this tip. 
It's exactly what I do actually waiting for better solution.

The problem with virtual category is that you can't browse other subcategories.

I try to create a page wich was a starting point where you can filter whole catalog with layered navigation AND at the same time filter down into catalog subcategories.

That's my I've started with my own module to call standard catalog page starting from root category.

**Comment by romainruaud** [comment]
Hello Yann,

we won't be able to provide you more support here as part of our Open Source support (free) policy since you are trying to achieve complex customisation on top of our extension.

Shall you be interested in more support from us as part of our Commercial support (paid) policy, feel free to reach me directly by email at romain.ruaud@smile.fr

Best regards
