### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1685]
### Preconditions
Huge Catalog around 4,00,000 products and 600 categories
Separate Elastic server from aws and instance type is t3.xlarge
Elasticsearch version = 6.8.6
Elasticsuite module setting on admin
Server Connection Timeout = 1
Number of Shards per Index = 1
Number of Replicas per Index = 0
Index mode: Update by schedule (recommended by magento)

Magento Version : 2.3.3 CE

ElasticSuite Version : 2.8.3

Environment : Production

Third party modules :
Potato_Zendesk
RedChamps_Core
RedChamps_ShareCart
Mgt_DeveloperToolbar
Mgt_Varnish
Klarna_Kco
Klarna_Ordermanagement
Aheadworks_Autorelated
Amasty_BannersLite
Amasty_Base
Amasty_Conditions
Amasty_CommonTests
Amasty_CommonRules
Amasty_CronScheduleList
Amasty_CrossLinks
Amasty_CustomerLogin
Amasty_Feed
Amasty_Geoip
Amasty_GdprCookie
Amasty_Gdpr
Amasty_Meta
Amasty_ProductAttachment
Amasty_ProductAttachmentApi
Amasty_Promo
Amasty_Rgrid
Amasty_Rma
Amasty_SalesRuleWizard
Amasty_SeoHtmlSitemap
Amasty_SeoToolKit
Amasty_SeoSingleUrl
Amasty_SeoRichData
Amasty_ShippingArea
Amasty_ShippingTableRates
Amasty_Shiprestriction
Amasty_ShopbyBase
Amasty_ShopbyBrand
Amasty_XmlSitemap
Unirgy_SimpleUp
Unirgy_SimpleLicense
Unirgy_Rapidflow
Unirgy_RapidflowPro

### Steps to reproduce

1.Create Virtual categories from admin or add/update attributes values which are used on layered navigation or searchable attributes , then itself magento start "Category Products" and then "Catalog Search" index
2. When "Catalog Search" index running, same time category listing page on frontend started to throw error There has been error processing your request and Error log record number displayed.
3. Report mentioned error like "No alive nodes found in your cluster", same time if we check elastic connection through ssh like "curl -XGET 172.30.41.17:9200" then its say "curl: (7) Failed to connect to 172.30.41.17 port 9200: Connection refused" (172.30.41.17 is IP of elastic server)

### Expected result

1. category listing page should not throw any error during catalog search index running on backend.

### Actual result

1. Aws elastic server CPU spike very high.
2. Elastic server lost the connection
3. Frontend loading and loading
![image_2020_01_27T14_22_04_163Z](https://user-images.githubusercontent.com/49389320/73423830-40661580-4353-11ea-92d6-6cbe92c47e5e.png)
![image_2020_01_28T11_32_50_861Z](https://user-images.githubusercontent.com/49389320/73423834-43610600-4353-11ea-8fe3-caa4d82ada5c.png)
![report ](https://user-images.githubusercontent.com/49389320/73450017-7d013380-438a-11ea-9fb6-0b39e07d184e.png)

**Comment by rbayet** [comment]
Hello @davidandersson1,

> Huge Catalog around 4,00,000 products and 600 categories
Is this 4 millions products or 400K products ?
How many virtual categories do you have ?

Is Elasticsuite tracker enabled ?
That will impact the total number of shards on your Elasticsearch instance (seeing that you have only one node, but then again, you only have one shard per index).
What is the total number of shards of the instance and the average shard size ?

>  Separate Elastic server from aws and instance type is t3.xlarge
According to https://aws.amazon.com/ec2/instance-types/t3/ that would mean 4 vCPUs and 16 GB memory.
What are your `Xms` and `Xmx` jvm options ?
You should [not allow more than 50% of available RAM to the heap](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/heap-size.html), that would be 8GB.
Even if we stick to the catalog product index, that's a bit rough for 400K products depending on your number of customer groups, use of the merchandising options, etc : you're probably at around 700K to 1M documents per catalog index

All on a single shard... that's a bad idea.
For a 400K to 4M products production server, you should really go at least a 3 nodes cluster to allow for smaller shards and load sharing.

Regards,

**Comment by davidandersson1** [comment]
@rbayet thanks a lot for your reply, please have a look below

1) is this 4 millions products or 400K products ?
around 400K products.
2) How many virtual categories do you have ?
Currently we have only 7 virtual categories.
3) Is Elasticsuite tracker enabled ?
No, its disabled from admin configuration.
4) What is the total number of shards of the instance and the average shard size ?
Regarding this, I have asked our server team(once i get response from server team, definitely will let you know here) for same but also little bit confusion to get it. you meant "total number of shards and average shard size" of the elasticsearch instance(t3.xlarge) right? or let me know if I am wrong here to understand you.

5) What are your Xms and Xmx jvm options ?
- Xms6g
- Xmx6g
They are both 6Gb.

You said "you should really go at least a 3 nodes cluster to allow for smaller shards and load sharing." that means we have to create 3 nodes on our elastic server instance and according to that nodes we have to configure on elasticsuite module setting (Number of Shards per Index = 3) or please let me know if I am wrong to understand you here.

**Comment by davidandersson1** [comment]
Hello @rbayet 

For above point 4, I got details from our server team. Currently, The number of cluster nodes is 1. there are 51 shards and the average shard size is 460,258 Mb.

Please share your view.

**Comment by davidandersson1** [comment]
Hello @rbayet 

can you please share your view for above!

**Comment by davidandersson1** [comment]
Also we are facing below one error on magento2 var/log/system.log file

{"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [100000] but was [171064]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_default_catalog_product_20200220_034645","node":"3zhzzEsfSs-DBybCyC2t2w","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [100000] but was [171064]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500} [] []


Please check attached screenshot for reference. can you please help and give you view for same as really its important for us.
![Screenshot from 2020-02-20 14-25-26](https://user-images.githubusercontent.com/49389320/74917133-0be2f800-53ed-11ea-99ed-70815d853427.png)

**Comment by rbayet** [comment]
Hello @davidandersson1,

Sorry about the delay.

**Concerning your last issue**, it means some pages are generating paginated queries when the sum of values for "size" (pagination size) and "from" (starting point / page number) is bigger than Elasticsearch setting "index.max_result_window" (which we [set at 100K instead of the default 10K in Elasticsuite](https://github.com/Smile-SA/elasticsuite/blob/371736f31dea5af4ee9c1e5315989eb12b4093bb/src/module-elasticsuite-core/Helper/IndexSettings.php#L41)).

If in your catalog, you capped your product lists max pagination size to something reasonable (like 50) then :

- there is probably a page listing almost all your products (for 400K products, it would be a page with a pagination of 8000 pages)
- there is "someone" crawling all those pages

For instance, displaying the 7000th page of such a (category, most probably) page would generate a query with "size: 50, from: 350000" where "from + size = 350050" (give or take 50) exceeds your index.max_result_window of 100K.

It could simply be an external search engine indexing bot (Google, Bing, Yandex.ru, etc) following the pagination links.
Such "deep paging" is very costly in memory and cpu, because, to [simplify](https://discuss.elastic.co/t/deep-pagination-vs-scroll-api/29782/2), Elasticsearch needs to load in memory [all pages up until the one you requested](https://discuss.elastic.co/t/deep-pagination-vs-scroll-search-after/89971/2).

Considering your single node infrastructure and existing stability issues, I could definitely not recommend changing this value of index.max_result_window to something still higher.
I would advise either forbidding crawlers / visitors to go beyond a certain page number (either with a rewrite rule, a plugin on the front controller) or override your theme to cut that pagination to something manageable.
Not many human in their right mind would paginate beyond the 20th or 50th pages anyway.

Regards,

**Comment by rbayet** [comment]
Hi @davidandersson1,

Concerning your initial issue, if you have disabled the Elasticsuite tracker and deleted the tracker indices ("*_tracking_log_event" and "*_tracking_log_session") and you still have 51 shards, this means you are hosting ~17 store views on the same Elasticsearch server ? [*]
If not, you can conserve memory by deleting the tracker indices.

[*] My reasoning here is that as your shards configuration is "1 / 0" (one primary shard and no replica) and as each store view needs 3 indices (categories, products and thesaurus), hence, 51 / 3 = 17.

You are below the limit of [20 shards per GB of heap memory](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/scalability.html#it-depends) (since you allowed at max 6 GB, 120 shards would be your upper limit).
Your single-node cluster is probably suffering from the deep pagination issue pointed above.

To add reliability, with a 3 nodes cluster, you could stick with 1 primary shard and 2 replicas but that would be overkill : each node of your cluster would hold every index/shard.

The ideal situation you want to reach is to have a balanced cluster, which can handle the loss of one node and still have all the required data on the remaining two.
If my theory about your 17 store views holds ground, you might be able to have 1 primary shard and 1 replica and your shards would be evenly shard amongst the nodes : no single node would have all 17 product index, but each couple of them would.

Of course, don't take what I say for granted, read [about primary shards and replicas](https://www.elastic.co/guide/en/elasticsearch/guide/current/replica-shards.html) and also [shard allocation problems](https://www.datadoghq.com/blog/elasticsearch-unassigned-shards/) and [cluster health](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/cluster-health.html) and adapt with regard to your actual situation.

Regards,
