### ISSUE TITLE
Swatch multi-select

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1688]
How does swatch multi-select work that is outlined in the README?

1. We have a Visual Swatch attribute, but it does not seem to show in the layered nav. We have reindex, cleared cache, item is set to show in layered nav, product data is set accordingly. When I disable ES module, the attribute shows. We use ES 2.8.4 on M2.3.3
2. Visual Swatch seems to only support one value. For example, we have a product that is black and white stripe. We want the product to show when the user selects black, white or black and white together. Since the field only supports a single value, say black, how can the item also show if the user selected only white?

**Comment by romainruaud** [comment]
Hi,

it's working with several values in the demo env : http://demo.magento-elastic-suite.io/index.php/men/tops-men/jackets-men.html?color%5B0%5D=Blue&color%5B1%5D=Red

"Blue" OR "Red" products are properly fetched. 

I'm not sure to understand properly what is the scenario you are trying to achieve, can you give us more details : the scenario with expected behavior, and current behavior on your website.

Regards
