### ISSUE TITLE
Multiselect Attribute, OR/AND

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#1698]
Hey there,

imagine you have a multiple select attribute called color, which has the values _green, blue, red and yellow._ 

A frontend user did select the value _green and red_ in the layered navigation. 

Within the "standard" behaviour the generated query looks like: Select all products which have the attribute values green **OR** red setup in the color attribute. In conclusion, all red and green products will be displayed. What would be the easiest way, to modify this on attribute base to have a query which uses **AND** instead of **OR** (Select all products which have green **AND** red set in color attribute) to display only products that are green and red at the same time.

Cheers,
Jan

**Comment by rbayet** [comment]
Hello @gewaechshaus,

The standard behaviour is indeed to perform a logical **OR** between the different values selected for a given attribute (being it a brand, a color, etc).
For colors, it suits well with an attribute which designates the "dominant" color.

In your case, if you indeed have products with two dominant colors, why not create a color option "red/green" (or even more stating the obvious "red and green") ?

Otherwise, you'll indeed have to create a custom layer filter model to enforce the **AND**.

Regards,
