### ISSUE TITLE
Date attributes (<> days) in Virtual Categories

### ISSUE THREAD

**Issue by sivasdescalzo** [Smile-SA/elasticsuite#1706]
I cannot figure how to use date attributes inside conditions of virtual categories.

Furthermore in case is possible, I would like to know how to use conditions for date attributes with days periods, instead of fixed dates.

**Comment by romainruaud** [comment]
Hello @sivasdescalzo 

I'd say that using a combination of "lower than" and "greater than" with dates attributes should allow you to define a range peiod, did you give it a try ?

**Comment by sivasdescalzo** [comment]
Hi @romainruaud,
I couldn't find the way to add attribute dates in virtual category rules.
Is it a limitation from the module?

**Comment by rbayet** [comment]
Hello @sivasdescalzo,

Which version of Magento2 and Elasticsuite are you using ?

Regards,

**Comment by sivasdescalzo** [comment]
Hi @rbayet.
Magento 2.3.3-p1
Elasticsuite 2.8.4

**Comment by rbayet** [comment]
Hello @sivasdescalzo,

I'm going to look into it.
Granted, I don't remember having ever seen a "date / datetime" based layered navigation filter, but the backend model `Magento\Eav\Model\Entity\Attribute\Backend\Datetime` is explicitely supported and I see a specific case for frontend_input=date attributes in rules model.

For your second question

> Furthermore in case is possible, I would like to know how to use conditions for date attributes with days periods, instead of fixed dates.

No, unfortunately, it will be pretty basic, like @romainruaud pointed out.
But you may be able to create a special rule condition through the `\Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttributesProvider` (which handles the "Only [something]" rules).
Unfortunately (yet again !), I'm pretty sure it's complicated to have a rule with an operator and a parameter if you go this way. I probably broached that in another ticket.

Regards,

**Comment by sivasdescalzo** [comment]
Thank you!
That was super helpful, we will try to make date attributes work with elastic suite.

I just found why DateTime attributes are not available in virtual category rules:
Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList
see getAttributeCollection()

There is a ->addFieldToFilter('backend_type', ['neq' => 'datetime']);

**Comment by rbayet** [comment]
> I just found why DateTime attributes are not available in virtual category rules:
> Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList
> see getAttributeCollection()
> 
> There is a ->addFieldToFilter('backend_type', ['neq' => 'datetime']);

Yes, I did too, so that explains why there are not visible in the rules widget.
The code dates back from the implementation of virtual categories back in 2016, it might be related to the fact that date input handling vs Admin locale was still a bit wonky in Magento2.

So if you plan conditions on a number of (elapsed) days, you can have a look at [this example of having a "is new" condition](https://github.com/Smile-SA/elasticsuite/pull/595#issue-149569496), based on news_from_date and news_to_date.
**Warning 1:** there is no operator and value to the condition.
**Warning 2:** [this might not work out of the box in 2.3.x](https://github.com/Smile-SA/elasticsuite/pull/595#issuecomment-506288751)

If you indeed manage to make date attributes work seamlessly in a generic way in Elasticsuite catalog rule engine, don't hesitate to push us a PR !

Regards,

**Comment by sivasdescalzo** [comment]
thank you.
We are working on it right now.
It think with all the information that you provided plus what magento commerce already provides OOO, I think we will do it without problems.
You will see our PR at some point.

**Comment by peterjaap** [comment]
@sivasdescalzo did you ever get it working?

**Comment by sivasdescalzo** [comment]
Nope,I had to create a new rule implementing \Smile\ElasticsuiteCatalogRule\Api\Rule\Condition\Product\SpecialAttributeInterface
