### ISSUE TITLE
If search query doesn't containt X, exclude products containing X in the title

### ISSUE THREAD

**Issue by grzmotek** [Smile-SA/elasticsuite#1709]
Hi.
So, I have many accessories for the mobile phones in my catalog. Some phone models have similar names (ie. Apple iPhone 11, Apple iPhone 11 Pro, Apple iPhone 11 Pro Max). 

Quering for "iphone 11" returns the results including "iphone 11 pro" and so on.

I've tried to set up optimizers, they're kinda working (not removing from search results, but moving them to the bottom), but aren't very convenient. Let's say I've set -99% "boost" for search term "iphone 11" and products not containing "pro".
![image](https://user-images.githubusercontent.com/51317624/74329574-5aaae500-4d90-11ea-881b-1537e1b40790.png)
I'd have to set up dozens of rules, since they're exact matches (the rule above wouldn't apply to "apple iphone 11" nor "iphone 11 case").

Do you have any idea how to achieve this?

**Comment by rbayet** [comment]
Hello @grzmotek,

Sorry for the delay.
Yep, what you want to achieve is pretty complicated to get out-of-the-box.

Eliminating "iPhone 11 Pro" and "iPhone 11 Pro Max" related products from search results when searching for "iPhone 11 Pro [accessory]" is not possible through Magento2 admin configuration alone.
Reducing their score / positions in the search results can be done with the help of optimizers like you did, but you can see that it is cumbersome / not generic enough.

You could try having a custom "optimized name" product attribute which would be : 
- searchable
- with a higher search weight than any other attributes, including **name**

We no longer use phrase_match queries with multiple words but we rely on shingles.
So having an aggressive phrase_match "slop" is out of the question, but you can nonetheless try to boost the **Phrase Match Boost Value** (Elasticsuite > Search Relevance > Relevance Configuration > Phrase Match Configuration) by a factor of 2 or 3 (so setting it at 20 or 30).

> Eliminating "iPhone 11 Pro" and "iPhone 11 Pro Max" related products from search results when searching for "iPhone 11 Pro [accessory]" is not possible through Magento2 admin configuration alone.

The ideal solution would be that "iphone 11, "iphone 11 pro" and "iphone 11 pro max" are indexed into totally different non-overlapping words "_iphone11_", "_iphone11pro_" and "_iphone11promax_", while making sure the inbound searches apply the same transformation.
But the default analysers configuration would not permit that at the moment : 
- thesaurus rules alone won't help
- having [dedicated stemmer rules](https://github.com/Smile-SA/elasticsuite/issues/1742) won't help either because they don't work on multiple terms
- adding a _synonym_ token filter in the analyser chain would not be easy because of change in Elasticsearch 6.x. 

So the answer might be to have a dedicated analysis chain like we do for the sku, applicable on your "optimized name" attribute.

On a side note, I invite you to look at what happens on the analysers with a tool like [cerebro](https://github.com/lmenezes/cerebro).
Look for instance what happens on a Magento 2.3.4 EE with Luma the impact of our _word_delimiter_ default configuration - which will split word according to case change, on a term like _iPhone_ :
```
        <filter name="word_delimiter" type="word_delimiter" language="default">
            <generate_word_parts>true</generate_word_parts>
            <catenate_words>true</catenate_words>
            <catenate_numbers>true</catenate_numbers>
            <catenate_all>true</catenate_all>
            <split_on_case_change>true</split_on_case_change>
            <split_on_numerics>true</split_on_numerics>
            <preserve_original>true</preserve_original>
        </filter>
```
![Sélection_869](https://user-images.githubusercontent.com/2353374/76228087-8a7aca80-6220-11ea-9e95-6e48ed3c912d.png)

![Sélection_870](https://user-images.githubusercontent.com/2353374/76228097-8ea6e800-6220-11ea-8c19-268b95fbb39e.png)

Regards,
