### ISSUE TITLE
Number of results obtained in the search

### ISSUE THREAD

**Issue by elisei** [Smile-SA/elasticsuite#1710]
The module seems to work well however the results of the search page do not have the expected result.

On my localhost using magento v2.3.4 with sample catalog and ES v6.8.6 when searching for the query "short women" the total number of products found is only 3 items different from your demo which presents the expected value of 19 items.

Result obtained:
![Search results for   shorts women ](https://user-images.githubusercontent.com/1786389/74342723-b2455280-4d88-11ea-9345-49fe698e5f3f.png)

Expected result:
![Search results for   short women ](https://user-images.githubusercontent.com/1786389/74342708-ad809e80-4d88-11ea-9890-4ab003f9c8b8.png)

**Comment by romainruaud** [comment]
Are you sure the sample datas were imported without any issues in your environment ? They tend to fail to import very often ...

**Comment by elisei** [comment]
@romainruaud, there was no error, reindexing is happening successfully, there are no logs of execeptions or even systems being generated.

**Comment by elisei** [comment]
@romainruaud ,
any other suggestions?

**Comment by rbayet** [comment]
Hello @elisei,

Keep in mind that we sometimes use our demo version to show features like thesaurus, optimizers, etc to people interested in the module.
So our configuration is not always as "pristine" as a blank new magento2 installation.

That being said, currently, on our demo, we indeed have other products than "shorts for women" when searching for "short women", because some "top" products (available under the "Women" category whose name is indexed with those products) reference "short" in their description which is indexed.
For instance : http://demo.magento-elastic-suite.io/index.php/elisa-evercool-trade-tee.html ("Short-sleeves" is indexed as "short sleeves" and "short_sleeves").

**Conclusion**: your mileage may vary according to how well the sample data was imported (especially the stock data from simple products), if you're filtering out products out of stock, etc.
I'll try to reproduce the issue.

Are you using a EE/Magento Commerce or CE/Magento OpenSource version of Magento2 ?

Regards,

**Comment by rbayet** [comment]
Hello @elisei,

I haven't been able to reproduce your issue with Magento 2.3.4 CE/OpenSource or EE/Commerce editions, either with ES 6.8.3 or 6.8.6.
As on the demo version, "short women" indeed produces 19 results.

I would advise you to look for changes in your theme and in your catalog, maybe in Elasticsuite configuration.
Enabling [Elasticsuite debug mode](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#configure-elasticsearch-server-) and replaying the raw ES queries into your Elasticsearch with [Cerebro](https://github.com/lmenezes/cerebro) might help you understand what is happening.

Failing that, you can also look in the Elasticsearch server logs during/after a full reindex to see if any document is rejected (for instance if you created an attribute of invalid type with a Magento2 setup).

Feel free to re-open the ticket if you identify a specific issue.

Regards,
