### ISSUE TITLE
Preview don't use the readHandler for virtual_rule

### ISSUE THREAD

**Issue by Jouby** [Smile-SA/elasticsuite#1712]
Some data about my environment : 

- Magento Version : 2.2.7 CE
- ElasticSuite Version : 2.6.9
- Environment : Developer and Production mode

I got an issue on backend category page:

The issue is caused by the Preview Model _(1)_ which call `$query = $this->category->getVirtualRule()->getCategorySearchQuery($this->category);` but `$this->category->getVirtualRule()` not an object but a string.

The `virtual_rule` value is stored in database in json format and we need to pass in a readHandler _(2)_ to be transform into a Rule _(3)_.

To fix my issue, I just override the Preview Model _(1)_ and use the ReadHandler _(2)_ to transform my `virtual_rule` text into a Rule _(3)_.

I would like to know if it's a common issue and if there is an other way to fix without using an override?

Thanks for your help.

_(1) Smile\ElasticsuiteVirtualCategory\Model\Preview
(2) Smile\ElasticsuiteVirtualCategory\Model\Category\Attribute\VirtualRule\ReadHandler
(3) Smile\ElasticsuiteCatalogRule\Model\Rule_

**Comment by romainruaud** [comment]
Hi @Jouby 

this used to happen sometimes, but it was in frontend, especially when having third party modules conflicting on how the category object is loaded, and with the modules load order.

However, since Magento 2.2 has reached EOL, we do not maintain anymore our 2.6.9 version as part of our Open Source support policy here.

So basically there are two options if you want to go further on this one : 

- upgrade to Magento 2.3.x and if the issue is still happening we'll have a look on it (but it's not happening on our demo env or in a raw Magento with ElasticSuite)

- contact us directly by mail through romain.ruaud@smile.fr if you want to purchase us some commercial support, which is something we provide for EOL versions.

Regards
