### ISSUE TITLE
3rd party AJAX Layered Navigation module not working with smile elasticsuite

### ISSUE THREAD

**Issue by test4295** [Smile-SA/elasticsuite#1717]
Preconditions
Magento Version : CE 2.3.2
ElasticSuite Version : 2.8.3

**Expected result**
1 We want  AJAX Layered Navigation with smile elasticsuite

**Actual result**
1 3rd party AJAX Layered Navigation module not working with elasticsuite

**Comment by rbayet** [comment]
Hello @test4295,

We don't provide full support for third party modules integration as part of our Open Source (free) support policy.

We sometimes go the extra mile anyway if something Elasticsuite does prevents another extension from working correctly. We may have done it once or twice and it usually involves the user submitted a detailed explanation of the problem and the possible solution.

You would agree this is not the situation here ;)
=> A quick Google search points me to 3 or 4 different vendors offering an "AJAX Layered Navigation" non-free module.
Please provide at least the exact name of the extension (including the vendor) so we know of the incompatibility.

Keep in mind that "layered navigation" centric or "search" centric third party extensions are bound to have issues with Elasticsuite since the same native features are extended.
It's like installing two different modules providing features for the catalog inventory...

Regards,
