### ISSUE TITLE
Installing data... No alive nodes found in your cluster

### ISSUE THREAD

**Issue by chenghuili** [Smile-SA/elasticsuite#1720]
When I run bin/magento setup:upgrade, it always display "Installing data... No alive nodes found in your cluster"
my elasticsearch at another server.
'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'http://ec2-*******************.compute-1.amazonaws.com:9200',
                    'enable_https_mode' => '0',
                    'enable_http_auth' => '0',
                    'http_auth_user' => 'user',
                    'http_auth_pwd' => '************************'
                ]
            ]

**Comment by rbayet** [comment]
Hello @chenghuili,

Please use the search feature before creating an issue.
That is indeed a frequent misconfiguration error.

In your case, change 
<pre>
'enable_https_mode' => '0',
'enable_http_auth' => '0',
</pre>
to
<pre>
'enable_https_mode' => 0,
'enable_http_auth' => 0,
</pre>
and clean your cache before attempting again setup:upgrade.

[Your '0' string is actually interpreted as "true"](https://github.com/Smile-SA/elasticsuite/issues/1002#issuecomment-427361145).

Regards,

**Comment by chenghuili** [comment]
I changed these both options, but it still doesn't work.
<img width="398" alt="Screen Shot 2020-02-25 at 17 31 29" src="https://user-images.githubusercontent.com/14212956/75233973-b6478a80-57f4-11ea-891f-1b173e422395.png">

**Comment by chenghuili** [comment]
this is my elasticsearch.yml

**Comment by rbayet** [comment]
OK, I've tested locally on a 6.8.6, with your configuration for network.host/bind_host/publish_host and the service is still accessible from outside.

It looks like your Elasticsearch service is accessible from anywhere (which is not a good idea), so try to confirm it's the case using curl (`curl http://[PUBLIC_IP]:9200`) or an Elasticsearch client [like Cerebro](https://github.com/lmenezes/cerebro).
If not, well just check that your Elasticsearch server is up and running :/

Regards,

**Comment by rbayet** [comment]
@chenghuili just to be sure, try to remove the `'http://'` in your **es_client/servers** setting.
It's actually not required and may be a source of error.

**Comment by chenghuili** [comment]
thank you for your help, I changed configuration file and clean cache, but it still doesn't work

**Comment by chenghuili** [comment]
system' => [
        'default' => [
            'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'elasticsearch:9200',
                    'enable_https_mode' => 0,
                    'enable_http_auth' => 1,
                ]
            ]
        ]

**Comment by rbayet** [comment]
Hello @chenghuili,

This is not the kind of issue that can be easily solved remotely without sensitive information disclosure.
Besides, this is going a bit everywhere : at first you pasted a server address is somewhere on amazonaws.com (so supposedly outside of your main Magento architecture), in your last message, it's simply an "elasticsearch" local alias.

To [paraphrase the docs](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#elasticsearch-client) :
* **servers** should contain the hostname and port of where the service is accessible at
* **enable_https_mode** determines if you need (1) or not (0) access the service with https (instead of http)
* **enable_http_auth** determines if you need (1) or not (0) provide a username and a password to access the service. enable_http_auth=1 is ignored if you do not provide both a value for http_auth_user and http_auth_pwd

Those settings should reflect how you can connect to your Elasticsearch server **from your Magento server** using a command-line client like curl.
* **If enable_http_auth=0**
   *  **If enable_https_mode=0**
`curl http://[one value of servers]/`
   *  **If enable_https_mode=1**
`curl https://[one value of servers]/`
* **If enable_http_auth=1 (and http_auth_user and http_auth_pwd are both provided)**
   *  **If enable_https_mode=0**
`curl -u http_auth_user:http_auth_pwd http://[one value of servers]/`
   *  **If enable_https_mode=1**
`curl -u http_auth_user:http_auth_pwd https://[one value of servers]/`

If you want us to provide more support on this one, you can contact us by mail at romain.ruaud@smile.fr to purchase professional support services which will allow us to provide you more coaching or development workforce to achieve your needs.
