### ISSUE TITLE
Can not change product position in categories after installing elasticsearch

### ISSUE THREAD

**Issue by chenghuili** [Smile-SA/elasticsuite#1734]
Can not change product position in categories after installing elasticsearch, 
I customized extension to sort by most viewed, it always work well before, but when I installed elasticsearch, the position in categories restore to default.
I don't know where is mistake?

**Comment by rbayet** [comment]
Hello @chenghuili,

Please be aware that I don't know which extension you speak of when you say 

> I customized extension to sort by most viewed, it always work well before

I'll assume its a third party extension which automatically computes product positions and store them into the **catalog_category_product** DB table.

Please read first [this comment](https://github.com/Smile-SA/elasticsuite/issues/1579#issuecomment-545964118) which explains why computed positions stored in **catalog_category_product** might "not work" anymore after installing Elasticsuite due to the **smile/module-elasticsuite-virtual-category** module.

Once you digested that lengthy comment, you will see that you have two options :

- disable **smile/module-elasticsuite-virtual-category** : you will lose both the virtual categories feature, and the categories merchandising features, but you will _maybe_ see you "based on product views" product positions appear again
- keep **smile/module-elasticsuite-virtual-category** (because you want to use virtual categories and the merchandising features on categories) **but** you will need to re-implement your "please sort products by default according to product views"

For that second option, you can easily replicate the behavior with the following approach : 

1. create a [datasource ](https://github.com/Smile-SA/elasticsuite/wiki/Indexing#data-sources)that would index for each product its number of views
2. create a "based on attribute value" [search optimizer](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers) (please be aware the doc is obsolete: there is now another model besides the "Constant") applicable only to category view pages

With that in place, when displaying a category whose default sort order is still "position", Elasticsuite will sort products by 

1. category.position = the manually set position in the category merchandiser
2. _score = the fulltext score of products, which in that category view, will default to 1 for products **unless** they are boosted by the search optimizer you created
3. product entity_id

If you didn't sticked any product to a particular position in your category with the merchandiser/drag and drop feature, then all your products will be nicely sorted according to their index products views number again.

Regards,

**Comment by chenghuili** [comment]
Thanks for your help, but when I disable smile/module-elasticsuite-virtual-category, there is error in cagegories page
"0":"Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in \/vendor\/smile\/elasticsuite\/src\/module-elasticsuite-virtual-category\/Helper\/Rule.php on line 67","1":"<pre>#1 call_user_func_array() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-virtual-category\/Helper\/Rule.php:67

**Comment by chenghuili** [comment]
for the second option, it seems difficult for me. I don't know how to implement it totally.

**Comment by romainruaud** [comment]
I close this issue for being answered.

If you need help for implementation in your particular context, that's not something we can provide as part of our Open Source support policy here.

Shall you be interested in having some help from us as part of our professional services policy, send me an email directly at romain.ruaud@smile.fr

Best regards
