### ISSUE TITLE
Introduce a stemmer override step in the analysers

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/elasticsuite#1742]
**Is your feature request related to a problem? Please describe.**
Sometimes the automatically selected language specific stemmer has some edge issues, either failing to detect singular/plural form (seen with italian) or assigning the same root to words that, although sharing an etymologic ancestry, are now quite distinct (seen in french on an old Solr project).

Using the thesaurus to fix those issues is a bad idea, because it denatures its intended usage which **is not to fix analysis issues**, but apply **business specific synonyms and expansions**.

**Describe the solution you'd like**
Introduce a basic support for language/locale dependant [stemmer_override token filter](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-stemmer-override-tokenfilter.html) in the _standard_ analyser chain.
At the moment, supporting the simpler "_rules_" parameters should be enough.

**Additional context**
Problem historically seen with old versions (Solr 3.x based project) of the _french_ and _light_french_ stemmer which would reduce both _collectivités_ (collectivities) and _collections_ to _collect_.
Which was annoying considering the user was mainly selling books and almost all of them had a "collection" attribute in the format "Collection [XYZ]" : searching for "droit des collectivités" ("Collectivities law") would return all books.

Problem also seen recently with an italian user selling among other things power tools : the _italian_ stemmer would reduce _trapano_ and _trapani_ (drill and drills) to different stem.
=> Searching for "drills" would not return fewer products than search from "drill".

**Comment by walkwizus** [comment]
Hi all,

Since this update I've an error with indexer process.

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"stemmer override filter requires either `rules` or `rules_path` to be configured"}],"type":"illegal_argument_exception","reason":"stemmer override filter requires either `rules` or `rules_path` to be configured"},"status":400}`

I has try to add the following configuration but without success:

`
<filter name="standard_override" type="stemmer_override" language="de">
    <rules>[]</rules>
</filter>
`

When I remove all line of associated commit indexer process work fine.

Any idea ?

Thanks !
