### ISSUE TITLE
Layered navigation filters

### ISSUE THREAD

**Issue by VivekM296** [Smile-SA/elasticsuite#1759]
### Preconditions
Nginx AWS Ec2 instance

Magento Version : 2.3.3 CE

ElasticSuite Version : 

Environment : Yes

Third party modules : 

### Steps to reproduce

We're facing an issue with layered navigation when there's checkbox.
We've created brand attribute which is type as checkbox and used for filters.
When Navigate to category page customer wants to apply 2 or more filters at a time it wont allow, Like as soon as customer checks one checkbox it will reload page then he can apply second filter.
This case is very big issue with when browsing website using mobile, At category page customer have to click filters menu to open filters and as soon as checks one brand page will reload and have to click to filters menu to apply new filter to brand.
THis seems very odd for customer.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Well it looks like the default behavior.

Do you see anything different on a stock instance ? Like on http://demo.magento-elastic-suite.io/ ?

Regards

**Comment by rav-redchamps** [comment]
Hi @VivekM296 

We have observed that the details you described in the issue is actually a usability problem in the native ElasticSuite extension. 

So, we have developed a paid add-on for the extension https://redchamps.com/elasticsuite-improved-layered-navigation.html it will allow the selection of multiple options without reloading the page by offering a APPLY button. Clicking APPLY button after the selection of options will apply multiple options in one go.
