### ISSUE TITLE
Manual sort not working on custom attribute order

### ISSUE THREAD

**Issue by tbaltissen** [Smile-SA/elasticsuite#1784]
When using a custom attribute order the manual sort order doesn't work. It sorts the products by the custom attribute, but does not put the manual sorted products in front. When switching to position ordering everything works fine.

Magento Version : 2.3.3 CE
ElasticSuite Version : 2.8.4
Environment : Developer and Production

### Steps to reproduce

1. Set custom attribute as standard sorting order
2. Put products in front manually
3. Open category page

### Expected result

1. Manually sorted products should be in front

### Actual result

1. Manual sorted products are in their normal sorting spot

**Comment by romainruaud** [comment]
Yes, that's working like this by design.

"Manual Sort" is equivalent to "fixing products positions". So it does apply only on the "position" order.

It would be counter-intuitive to enforce product's position for every other sort orders : if you sort by "price ASC", you want the cheapest products first, not the 10 products that were pinned to top by the admin for merchandising purposes.

Regards
