### ISSUE TITLE
[feature] elasticsearch host in config.xml to admin config instead?

### ISSUE THREAD

**Issue by peec** [Smile-SA/elasticsuite#180]
Hello,

Thanks for creating elasticsearch compability for Magento 2.X. This is a big thing missing in Magento 2.X CE.

We have custom deploy scripts where we deploy only composer.json/lock files to production.

I see that after installing elasticsuite I get this warning that it can't connect to elasticserver, however we use dynamically allocated elasticsearch client so I have to use a script to get the hostname of the elasticsearch server.

It means that i'm stuck on elasticsuite trying to connect to localhost:9200 when deploying. Is it possible to not require this configuration at install time - but rather configurable in e.g. admin ?

I see that you support creating a custom config.xml with configuration in a separate module, however I think just admin configuration would fit better?

**Comment by afoucret** [comment]
Hi @peec,

config.xml file is only a way to override default configuration of the module. Settings are still available in admin and you can change the value as explained in the wiki : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#configure-elasticsearch-server-

We can not avoid to index search during the install (especially catalogsearch_fulltext a.k.a. product indexing) since the indexation is not triggered by our own code but by the setup of the Magento_CatalogSearch module.

Hope it made everything clear for you.

**Comment by afoucret** [comment]
To complete my last response, you can put a short hostname into the config of you custom module (eg: `es:9200`) and put this one into the `/etc/hosts`file of your front server. This brings the ability to have a config that is consistent across environments and not having to reconfigure.
