### ISSUE TITLE
If the Description of default store view not set, Other store views Description is empty. 

### ISSUE THREAD

**Issue by kanishkanihal** [Smile-SA/elasticsuite#1804]
I have created a new simple product with the required fields only. 
I have two store views(default, india). I have inserted description for the second store view (india). After running a full re-index I cannot see the description in any product index (ce23_in_catalog_product or ce23_default_catalog_product). 
Then I have updated the 'All store view' 'description' & 'short description'. Then I could find the Description in both store indexes.

Same thing is happening for new attributes  as well.
### Preconditions

I have two websites, stores, store views
![image](https://user-images.githubusercontent.com/4750233/81534263-62752800-9385-11ea-9708-03bb9cf7cdeb.png)

Magento Version : CE 2.3.4

ElasticSuite Version : 6.8.7
![image](https://user-images.githubusercontent.com/4750233/81534516-cbf53680-9385-11ea-9e86-1acb1cfb91aa.png)

Environment :

Third party modules : Developer

### Steps to reproduce

1. Fresh Magento Installation. Create a new "Website", "Store", "Store View" as per above image. 
2. Create a New Simple product With out touching the Description or Short Description. Make sure  to select Both websites under "Product in Websites"
3. After creating the product, Change it's "Scope" to the the new "Store View", In My case "india".
4. Insert Description or Short Description.
5. Run full reindex
6. Find the product in elastic search for both default & new (india) store views. Cannot find the Description in none of them. 
![image](https://user-images.githubusercontent.com/4750233/81535590-b41eb200-9387-11ea-89e9-e92e89a15107.png)
![image](https://user-images.githubusercontent.com/4750233/81535607-bc76ed00-9387-11ea-9eb3-f002d15d3b1d.png)

7.  Change it's "Scope" to the the new "All Store View" & Update the "Description" & "Short Description".
8. Run full reindex
9. Now I can find "Description" 
![image](https://user-images.githubusercontent.com/4750233/81535811-18da0c80-9388-11ea-92f5-71ad666d7bb5.png)
![image](https://user-images.githubusercontent.com/4750233/81535872-31e2bd80-9388-11ea-8e1b-5a1ebff689c5.png)

### Expected result

1. Even without inserting "Description" & "Short Description" for all store views ES should index the "Description" & "Short Description" on store view levels.

### Actual result

Without inserting "Description" & "Short Description" for all store views "Description" & "Short Description" cannot be found on other store indexes.
1. Have a look on "Smile\ElasticsuiteCatalog\Model\ResourceModel\Eav\Indexer\Fulltext\Datasource\AbstractAttributeData" function "getAttributesRawData"

**Comment by romainruaud** [comment]
@androshchuk can you check if you reproduce this one and try to propose a fix ?

**Comment by francescosalvi** [comment]
Hello people
just want to add: I too reproduce this issue, on v2.8.6, although the function that I tracked downs as responsible for generating the "impropert" SQL is still unchanged in v2.9.x.
I'm referring to `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Eav\Indexer\Fulltext\Datasource\AbstractAttributeData::getAttributesRawData` ([link](https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-catalog/Model/ResourceModel/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php#L105))

A typical generated SQL query from the above method looks like this:

```
SELECT
	`entity`.`entity_id`,
	`t_default`.`attribute_id`,
	COALESCE(t_store.value,
	t_default.value) AS `value`
FROM
	`catalog_product_entity` AS `entity`
INNER JOIN `catalog_product_entity_varchar` AS `t_default` ON
	entity.row_id = t_default.row_id
LEFT JOIN `catalog_product_entity_varchar` AS `t_store` ON
	t_default.row_id = t_store.row_id
	AND t_default.attribute_id = t_store.attribute_id
	AND t_store.store_id = '6' -- the store view we are currently indexing
WHERE
	((t_default.store_id = 0)  -- default store for values fallback
	AND (t_default.attribute_id IN (
        123 -- the list of attribute id for the current backend type, in this case varchar
        ...
    ))
	AND (entity.entity_id IN (45))) -- the product entity id being indexed
	AND (entity.created_in <= 1)
	AND (entity.updated_in > 1)
```

The issue is with the first inner join (on default store values), upon which depends the second one (on specific store view): if records are not found in the default scope, then the store-specific ones are not even joined

**Comment by androshchuk** [comment]
Hello people. 
Can you look at my [solution](https://github.com/Smile-SA/elasticsuite/pull/1817) in your environment?

Regards

**Comment by francescosalvi** [comment]
@androshchuk I might be mistaken but I think that using such condition you'll end up having duplicate matches in case an attribute has a value in _both_ the default and the specific store?

**Comment by androshchuk** [comment]
I was checking this case.
If field short description for default store is not empty and short description for the specific store is empty:
![image](https://user-images.githubusercontent.com/5081718/82642609-de3d6300-9c16-11ea-9443-5b6d2c3088fa.png)
If field short description for default store is empty and short description for the specific store is not empty:
![image](https://user-images.githubusercontent.com/5081718/82642947-61f74f80-9c17-11ea-97fa-d4f674ca19bc.png)
If field short description is different in both stores:
![image](https://user-images.githubusercontent.com/5081718/82643175-c3b7b980-9c17-11ea-8117-6f54eeeb4881.png)

**Comment by francescosalvi** [comment]
@androshchuk my comment was about the cleanness/efficiency of the query/query-builder-core, rather than about the final result (that indeed looks legit).

One thing though - this is something I have also noticed in my local tests trying to update the query, regardless of the approach: if you look at the screenshots on the right (new_store_catalog_product) you can see that in the field `indexed_attributes`, the item `short_description` appears twice (whereas on the left in the default store document it appears only once)
I couldn't figure the reason and if this even constitutes an issue at all..

**Comment by francescosalvi** [comment]
Just for reference, this is a working solution I've been fiddling with that seems to get rid of the duplicate `indexed_attribute`(s)
https://gist.github.com/francescosalvi/dc2cad38eeed00f496afd66de9b11715
I uses an additional join on the `eav_attribute` table though. but I havent run any performance test.

**Comment by androshchuk** [comment]
@fabiengasser thank you for your help. 
I fixed my solution.

Could you make your code in PR. 
We'll consider it as well.

Regards

**Comment by francescosalvi** [comment]
@androshchuk I created https://github.com/Smile-SA/elasticsuite/pull/1822
i actually got rid of the extra join and moved the attribute-ids list within the ON clause, but in order to fix the duplicate entries within "indexed_attributes" I also had to fix `\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\AttributeData::addIndexedAttribute` like you di

**Comment by romainruaud** [comment]
@rbayet can you look at this one and the attached PR.

**Comment by rbayet** [comment]
Identical PR for 2.8.x (#1843) and 2.9.x (#1842).
Non-noticeable to minimal index speed decrease : 

- 5% slower for `medium_msite` performance template
- 3% slower for `large` performance template
