### ISSUE TITLE
Facet Management by category Input variables exceeded 1000

### ISSUE THREAD

**Issue by ryanisn** [Smile-SA/elasticsuite#1831]
### Preconditions

Magento Version : EE 2.3.3

ElasticSuite Version : 2.8.7

Environment : Production

Third party modules :

### Steps to reproduce

1. create 1000 custom attributes and make them filterable for layered navigation
2. create a new category with no products
3. edit and save the category

### Expected result

1.category being saved

### Actual result

1. [Screenshot, logs]
"Invalid form key" error returned and category was not being saved
![image](https://user-images.githubusercontent.com/53449841/83450147-b9b96600-a422-11ea-9597-108a29f0e8f8.png)

### root cause
category edit form is being flooded with filter settings

**Comment by rbayet** [comment]
Hello @ryanisn,

This is to be expected if you add 1000 custom attributes that are all filterable.
This is due to the UI component responsible for the "**Facet Management by category**" feature.
![image](https://user-images.githubusercontent.com/2353374/84385203-7499ee80-abef-11ea-8e1c-07e8b7cdea52.png)

Same thing would happen in the attribute edit form if you decided to add programmatically more than 1000 options to an attribute.
I'm pretty sure the error log message was pretty self-explanatory : you need to change the value in your PHP configuration (php.ini or php-fpm spool configuration file) for `max_input_vars`.

If that is not an option for you, you can try tweaking the parameters (or completely remove it, but I cannot guarantee the end result) of the `facet_config` UI component in src/module-elasticsuite-catalog/view/adminhtml/ui_component/category_form.xml

Regards,

**Comment by ryanisn** [comment]
I understand but I don't think we should be forced to change `max_input_vars` for this reason nor it is a good practice security wise. 
What do you think if we add a toggle button (non form element)  disable/enable form inputs in each row, or serialize this big form into one field (like how magento implode list of product IDs in category form) ?

**Comment by rbayet** [comment]
I understand the security threat, but you could minimize it by 
- having either a dedicated php-fpm pool or a dedicated server handling /admin requests
- have an access restriction on /admin (or your custom admin URL)
This way, you can only change `max_input_vars` for the admin interface.

Concerning your alternative suggestions, the serialized approach might be indeed a valid workaround.
Feel free to submit a PR and we'll review it.

Regards,
