### ISSUE TITLE
[2.8] Synonym indexation error with ES > 5

### ISSUE THREAD

**Issue by Wohlie** [Smile-SA/elasticsuite#1834]
Hi, we are using module version 2.8.4 with Magento 2.3.3. Since ES upgrade from 5.X to 6.8.5 we have issues with the indexing of synonym indexation that produces the following errors:
```
ElasticSuite Thesaurus Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"failed to build synonyms"}],"type":"illegal_argument_exception","reason":"failed to build synonyms","caused_by":{"type":"parse_exception","reason":"Invalid synonym rule at line 15","caused_by":{"type":"illegal_argument_exception","reason":"term: foo. bar analyzed to a token (foo._bar) with position increment != 1 (got: 0)"}}},"status":400}
```

We can limit the problem to characters like
* `.`
* `-`
* `+`
* and may be more

that are surrounded by a space.

For example the following synonyms will not work and prevents the update of the synonyms in ES:
* `foo. bar`
* `foo .bar`

**Comment by androshchuk** [comment]
Hello @Wohlie 
We have already fixed this bug in version 2.8.5.
This issue is a duplicate of https://github.com/Smile-SA/elasticsuite/issues/1728
You can update yours ElasticSuite to 2.8.5 or fix a problem like this https://github.com/Smile-SA/elasticsuite/commit/e68f9c669839f3f6585991bd175edb531093e8a0

Regards
