### ISSUE TITLE
Sub category in layered navigation

### ISSUE THREAD

**Issue by alexsmith2709** [Smile-SA/elasticsuite#1849]
Is elasticsuite able to only show the sub categories that the product results are actually in instead of the parent category and then having to click each sub category to get to the bottom level?

I have been able to do this by browsing to the category pages and have attached a screenshot to show what i mean. The screenshot from the search results page shows "Shop (6)" where shop is the parent category of all my products.
What i would like displayed is the actual sub categories these 6 products are in so the user can click straight through to narrow down if they are only looking for products from the "Ink Cartridge" sub category for example.
I have also attached a screenshot from my one of my category pages so show more like how i want it to display

I have the "Use category name in search" set to off and this sorted the same issue i had when browsing to the category page, but doesnt solve it for an actual search,

Thanks

**search results page screenshot**
![search1](https://user-images.githubusercontent.com/10212208/84573765-84a20180-ad9a-11ea-8aa3-f066baced8a8.JPG)

**category page screenshot**
![category](https://user-images.githubusercontent.com/10212208/84573828-ca5eca00-ad9a-11ea-892d-bfdc0e72c720.JPG)

**Comment by rbayet** [comment]
Hello @alexsmith2709 
> Is elasticsuite able to only show the sub categories that the product results are actually in instead of the parent category and then having to click each sub category to get to the bottom level?
> 
> I have been able to do this by browsing to the category pages and have attached a screenshot to show what i mean. The screenshot from the search results page shows "Shop (6)" where shop is the parent category of all my products.
> **search results page screenshot**
> ![search1](https://user-images.githubusercontent.com/10212208/84573765-84a20180-ad9a-11ea-8aa3-f066baced8a8.JPG)
> 

Well according to me, your issue might be that your category tree is 

- Default (root) / Shop / Sub-category 1
- Default (root) / Shop / Sub-category 2
- Default (root) / Shop / Sub-category 3

What you could do is simply change the configuration of your "Store" (in "Website / Store / Store View" sense) to change the [root category of your catalog to be "Shop" instead of "Default"](https://docs.magento.com/user-guide/catalog/category-root.html).

On the other hand, if Sub-category 1, Sub-category 2, Sub-category 3 are not those visible on that screenshot 
> **category page screenshot**
> ![category](https://user-images.githubusercontent.com/10212208/84573828-ca5eca00-ad9a-11ea-892d-bfdc0e72c720.JPG)

and **are actually** deep / leaf categories, in this sense 

- Default (root) / Shop / Main category 1 / **Sub-category 1**
- Default (root) / Shop / Main category 2  / Subdivision category 2.1 / **Sub-category 2** 
- Default (root) / Shop / Main category 3 / **Sub-category 3**

**then, no, Elasticsuite cannot do that out-of-the-box**. The category layer filter only works one node/category depth at a time and cannot collect deep / leaf categories.

> I have the "Use category name in search" set to off and this sorted the same issue i had when browsing to the category page, but doesnt solve it for an actual search,

"Use category name in search" has no impact whatsoever on the behavior of the category layer filter, it only apply to fulltext search, ie if the name of the categories a product is **visible** (and not only attached to) should be taken into account when searching.

Another thing, if you do no want customers to "change category page" and lose their (other) filter values (price, color, brand, etc) when clicking on a category in the category layer filter, look at the settings `Stores > Configuration > Elasticsuite > Catalog Search > Use URL Rewrites for Category Filter in category navigation` and set it to "No".

Regards,
