### ISSUE TITLE
Recover the sorting of a category

### ISSUE THREAD

**Issue by shak18** [Smile-SA/elasticsuite#1851]
This is  the thing, before installing elastic suite inside a category i have a table with the products of that category and a field to  apply the sorting by numbering the products 1,2,3...,n, now it shows the product grid with the feature of drag, drop and the manual and automatic sort flag, but the question is

Is there a way to recover the sort order previously applied to the products in a category or i just need to reorder everything after elasticsuite is up and running???

**Comment by rbayet** [comment]
Hello @shak18,

Please look at my answer to https://github.com/Smile-SA/elasticsuite/issues/1579, specifically the section **II / Where are the product positions actually used by Elasticsuite ?**.

You *should* be able to recover your positions with a smart insert into ... select between the two tables `catalog_category_product` and `smile_virtualcategory_catalog_category_product_position`.
That may not be possible if categories have been saved in admin, though.

Regards,

**Comment by shak18** [comment]
Yes that kinda does the trick, i have to run this:

`INSERT INTOsmile_virtualcategory_catalog_category_product_position
('category_id','product_id','store_id','position','is_blacklisted')
select category_id, product_id, '0', position+1, '0' from catalog_category_product`

the only weird stuff is that after running this it shows as expected in the admin but i need to 'save' the category from the admin for the sorting be effective in the store frontend, even after clear cache, the save part is a must

**Comment by rbayet** [comment]
Hello @shak18,

Saving the category is not actually required. 
It will just make sure the category and (most importantly) the associated products are re-indexed.
I failed to mention that because it was evident (but maybe just to me): that new data needs to be re-indexed into Elasticsearch (positions are present in the `category` field of indexed products).

So if you do this site wise, a `bin/magento indexer:reindex catalogsearch_fulltext` is indeed mandatory.

Regards,
