### ISSUE TITLE
Magento Admin Panel shows the full product list in the preview for categories

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1903]
The Magento admin panel shows the full product list in the preview for categories. I believe there was a "show more" button earlier.

Is this a known issue?

### Preconditions

Magento Version : 2.3.4-p2

ElasticSuite Version : 2.8.6

Environment : Both

Third party modules :

### Steps to reproduce
1. Open for example the root category in the admin panel

### Expected result
1.. Quick loading time

1. Only few products are shown in the preview / sorting list

### Actual result

1. Very long loading time
1. All products are shown

**Comment by romainruaud** [comment]
@vahonc can you investigate and try to reproduce this one ?

**Comment by vahonc** [comment]
@romainruaud of course, I'll try to investigate this

**Comment by Bashev** [comment]
Can you try this #1914, im not sure this is related to admin shows, but sound like same issue.

**Comment by amenk** [comment]
This is caused by https://github.com/Smile-SA/elasticsuite/pull/1862

**Comment by romainruaud** [comment]
@amenk please upgrade to 2.8.10 which contains the fix

**Comment by amenk** [comment]
Thanks --- @romainruaud Any chance this is not a regression for what @DanieliMi  tried to fix in https://github.com/Smile-SA/elasticsuite/pull/1862 ? i.e. will both scenarios work?

**Comment by romainruaud** [comment]
I don't know, I did not test changing the layout order due to the need of releasing this fix quickly, only the "standard" scenario.

That being said, this "pagination/sorting issue when moving the block" is known for a long time as described in our FAQ here : https://github.com/Smile-SA/elasticsuite/wiki/FAQ#i-have-problems-with-the-pagination--sorting

And ... the legacy Magento bug is still open, 4 years later : https://github.com/magento/magento2/issues/7253
