### ISSUE TITLE
How can i configure synonymous (multi-words)?

### ISSUE THREAD

**Issue by gihovani** [Smile-SA/elasticsuite#1933]
**I dont know, how can i configure synonymous (multi-words).**

Ex :
Face shield and protetor facial are synonymous? (Multi words)
Already tried to put the terms in quotes, but doesnt works.

**Additional context**
Add any other context or screenshots about your question here.
![Captura de Tela 2020-08-29 às 09 56 27](https://user-images.githubusercontent.com/2844128/91637387-697c8080-e9de-11ea-8895-e8eb3fd74423.png)
![Captura de Tela 2020-08-29 às 09 55 53](https://user-images.githubusercontent.com/2844128/91637389-6c777100-e9de-11ea-80f9-ab807a354be7.png)

**Comment by mvenghaus** [comment]
Wanted to ask the same question :)

In my understanding the problem is that when .. face shield .. is saved in ES the space is converted to "_" (prepareSynonymFilterData). But when I'm searching he's looking for synonyms for "face shield" but only have one for "face_shield". I don't unterstand why the space is converted!?

I found some examples where people are using this style:
"synonyms": [
      "spider man, spiderman => spider man, spiderman"
]

But "prepareSynonymFilterData" destroys this too.

**Comment by duffner** [comment]
@rbayet, have you had an opportunity to investigate this issue?  We have the same issue but have been ignoring it for a while.

**Comment by rbayet** [comment]
Confirmed on a 2.9.x / ES 6.x
Indeed the synonym rule is not found when using the multi-word expression or the hyphenated form of the word ("spider man" or "spider-man" vs "spiderman").
That's not totally critical for the hyphenated form because it will be split in two words by the catalog product index "whitespace" and "standard" analyzers.

Weirdly enough, I don't find any "smoking gun" evidence about code changes in Elasticsuite or the associated Elasticsearch features that could explain this suddenly not working anymore.
It could mean this has never really work as intended... seems strange considering into https://github.com/Smile-SA/elasticsuite/commit/e47029877f11aaa7fde5a7287fac5b7d4cf797f9
This one will require a bit of time travel.

**Comment by jeremybouvet** [comment]
Hi !

As there been any evolution on this ? We are still getting the issue on the latest version of ES.

Thank you !
