### ISSUE TITLE
Do I need the Category Product Index when using Virtual Categories?

### ISSUE THREAD

**Issue by mvenghaus** [Smile-SA/elasticsuite#1940]
The Category Product Index is very slow. Do I need it when using virtual categories?

Regards
Marcus

**Comment by romainruaud** [comment]
Well, if you are using **only** virtual categories (which is something we **don't recommend**) you could _probably_ disable the Category Product Index.

But what do you mean by "very slow" ? How much product and categories do you have ? We'll not be able to provide much help on this topic since the Category Product Index is a completely legacy Magento feature, but I'm interested in having more details about this.

Regards

**Comment by mvenghaus** [comment]
Why don't you recommend not to use only virtual?

I have 15 stores, ~900 categories each store .. and ~35k products each store.

Product Flat Index needs .. ~10 min
Catalog Category Product .. ~80 min
Catalogsearch Fulltext .. ~15 min

I've tried to disable the category product index, but there are some dependencies. For example the fulltext index needs the categories as filter for the product collection.

**Comment by romainruaud** [comment]
Well it does not seem _that_ slow at first sight, considering the amount of data. But if that's on a production environment it's of course slower than what could be expected.

However, as I said previously, there's not much we can provide here, since we do not interfere on the Category Product index with Elasticsuite, and hopefully, the Catalogsearch fulltext seems to run quite well.

I'm afraid you'll have to submit your issue directly into the Magento2 github repository.

Regards

**Comment by romainruaud** [comment]
An about why we do not recommend to use only virtual categories : 

Keep in mind that when computing category/product association for a high-level category, the engine will build a complex query to assemble all the products belonging to the currently viewed category : 

- products belonging to non-virtual children of the current category
- products matching one of **any virtual children** of the current category

The resulting query could end up being quite complex and adding pressure to the computation mechanism done by Elasticsearch. That’s why, due to the current situation, we recommend to lower the number of virtual categories.

Another important point to consider is that the virtual categories are designed to build ephemeral categories, such as dynamic corners : “special father day”, “actually discounted products”, “new products” and so on.

**They are not a tool to automatically attach products to categories but a merchandising mechanism.** 

Let’s take a common misconception  as an example : using some field that will never change to build virtual categories based on that. The most often occurring is the “create virtual categories based on brand”. A brand will never change, a Weber barbecue will alway be a Weber : if you want to define brand categories, it should be done either during the import process (with a brand/category mapping), or even earlier into the Product Management system.

Virtual categories are here to help the merchants to create either an ephemeral category, or a category based on something that will often change : discount, stock, total number of sales, etc…

**Comment by romainruaud** [comment]
I close, since Category Product performances are not managed by Elasticsuite as detailed above.

Regards

**Comment by mvenghaus** [comment]
I don't want you to optimize the category product index .. but it would be nice if your module doesn't depend on it. If I only use virtual categories your module doesn't need the category product index (maybe for filter).

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php#L122

That could be changed to another logic.

@virtual categories .. i disabled the children logic .. so there is no problem. It would also be nice if this can be an option in the admin panel.
