### ISSUE TITLE
Filters do not support multi configurable attributes

### ISSUE THREAD

**Issue by PascalBrouwers** [Smile-SA/elasticsuite#1943]
Filters do not support multi configurable attributes.

### Preconditions

Magento 2 with Sample data

Magento Version :
Magento 2.3.5

ElasticSuite Version :
6.8.12

Environment :
developer

### Steps to reproduce

1. Install Magento 2 with sample data.
2. Remove the Proteus Fitness Jackshirt XL Black
3. Remove all Montana Wind Jacket XL so size filter will show up
4. go to /men/tops-men/jackets-men.html
5. filter on size black
6. filter on color black
7. Proteus Fitness Jackshirt should not show up

### Expected result

1. Proteus Fitness Jackshirt should not show up

### Actual result

![Screenshot 2020-09-11 at 16 20 06](https://user-images.githubusercontent.com/17834386/92936716-bc2c5280-f44a-11ea-9010-65d964a01edd.png)
1. Proteus Fitness Jackshirt shows up

**Comment by romainruaud** [comment]
Correct, since children data are aggregated into the parent product, the Jacket is probably considered as having black and XL (I did not check, feel free to copy-paste the content of the ES document), so therefore it will be displayed when filtering on these two values, even if it has no children "combining black AND XL".

**Comment by PascalBrouwers** [comment]
Also no way to do this in the module?

**Comment by romainruaud** [comment]
on a legacy basis, I'd say no, it cannot work like this out of the box.

It would require to index all possible (and available) combination of children of each configurable products, and, in such case (user filtering on two attributes used for configurable products), proceed to filter on these combinations instead of the standard attributes fields.

But then, we'd have to deal with the fact that some simple (or bundle) products can also be part of the listing pages, and would have to be filtered with the legacy mechanism.

It's not undoable, but would add some overhead and complexity.

Regards

**Comment by PascalBrouwers** [comment]
ok, good to know
