### ISSUE TITLE
Error during indexing on Magento Cloud Pro

### ISSUE THREAD

**Issue by clicks-kodet** [Smile-SA/elasticsuite#1945]
Indexer throws an error
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [title]"}],"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [title]"},"status":400}
``` 
during reindex

### Preconditions

Magento Version : EE 2.3.5-p1

ElasticSuite Version : 2.9.1

Environment : production

Third party modules :

### Steps to reproduce

1. run `bin/magento indexer:reindex`

### Expected result

1. All indxer should pass without any error message

### Actual result

1. above mentioned error appears

According to Adobe Support (they tried to solve this issue for couple of weeks) the infrastructure is ok.

**Comment by romainruaud** [comment]
"string" type was replaced by "text" since ElasticSearch 5 if I'm correct. You should not have any field with this type since a long time (and a lot of Elasticsuite releases) ago.

Can you search for "string" into all your ``elasticsuite_indices.xml`` files located in your projects (the legacy ones, and maybe some other custom files) and copy-paste anything you find here ?

Regards

**Comment by clicks-kodet** [comment]
@romainruaud thanks for the hint. Yes, this was really the problem in this case.
