### ISSUE TITLE
Selected filter with a special html character can't be removed

### ISSUE THREAD

**Issue by Melleschepers** [Smile-SA/elasticsuite#1978]
### Preconditions

Magento Version : CE

ElasticSuite Version : 2.9.3 

Environment : Developer / Production

### Steps to reproduce

1. Give an attribute (for example 'material') an option with a name with an special character, like "Polyester & Nylon" or "Polyester's"
2. Apply 2 filters on a category page (one of them need to be the option with the special character). So for example apply the filters: (material = "Polyester & Nylon)  &  (material = Cotton).
3. Remove the filter with the special character. So remove the material = "Polyester & Nylon" filter.

### Expected result

1. The filter with the special character is no longer applied. So only the material = Cotton filter is applied

### Actual result

1. Both filters stay applied. (material = Polyester & Nylon)  &  (material = Cotton).

### Cause
When comparing the arrays (https://github.com/Smile-SA/elasticsuite/blob/c8e6cbb75c5bfd7dab2e22d596f6a5fd5ed458d8/src/module-elasticsuite-catalog/Model/Layer/Filter/Item/Attribute.php#L50)

.. special characters in $this->getLabel() are converted to html entities. In the function $this->getApplyValue() the special characters are not converted. So comparing them doesn't work.. And so it doesn't give the right "remove url".

**Comment by rbayet** [comment]
It's logically no longer necessary to escape the label for the layer state since it's done in the layer/state.phtml template since 2.3.3 (see https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/LayeredNavigation/view/frontend/templates/layer/state.phtml vs https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/LayeredNavigation/view/frontend/templates/layer/state.phtml).
This was done for #1211 in #1271. 

But our 2.8.x releases cover up to 2.3.4, so I'll probably fix this in two different ways.

**Comment by rbayet** [comment]
Fixed by #1997 in 2.9.x, 2.10.x
Fixed by #1999 in 2.8.x
