### ISSUE TITLE
Quicksearch issue

### ISSUE THREAD

**Issue by matt-grech** [Smile-SA/elasticsuite#1991]
Is there any way to reduce the delay of the quicksearch to allow users to see results from when they start typing rather than when they stop or pause?

When they are typing the ajax call is cancelled and when they stop or pause it then goes through.
![Capture](https://user-images.githubusercontent.com/3309503/99065780-cf20e780-259f-11eb-8c5c-6352fdfed4c7.JPG)

**Comment by rbayet** [comment]
Hello @matt-grech,

You can try change the value of the `suggestionDelay` option (which defaults to 300 (ms)), but i don't think you'll find an improvement towards what you want to achieve as long as the pending ajax calls are cancelled.

Having a delay is to avoid spamming the server with similar and partial queries :
vendor/magento/module-search/view/frontend/web/js/form-mini.js
```
            this.element.on('focus', this.setActiveState.bind(this, true));
            this.element.on('keydown', this._onKeyDown);
            // Prevent spamming the server with requests by waiting till the user has stopped typing for period of time
            this.element.on('input propertychange', _.debounce(this._onPropertyChange, this.options.suggestionDelay));
```

And the ajax call cancellation is to avoid having a "terminal input" quickly shown list of results overwritten by a "previous input" list of results that took twice or 3 times more time to get through.
vendor/smile/elasticsuite/src/module-elasticsuite-core/view/frontend/web/js/form-mini.js 
```
                this.currentRequest = $.ajax({
                    method: "GET",
                    url: this.options.url,
                    data:{q: value},
                    // This function will ensure proper killing of the last Ajax call.
                    // In order to prevent requests of an old request to pop up later and replace results.
                    beforeSend: function() { if (this.currentRequest !== null) { this.currentRequest.abort(); }}.bind(this),
```

Imagine the user is search for jackets, but you also sell vegetables and home appliances 
* he's typing "ja" : loading
* he's typing "jacket" : loading
* results for "jacket" come first : he has the results he wanted
* results for "ja" arrive : he's now presented with jackets, japalenos and jacuzzis (because those search terms exist in your database)

Elasticsuite only enhances the native autocomplete search form which shows his age due to the server side rendering.

Regards,
