### ISSUE TITLE
Inaccurate search results with bundle products when searched by child product SKUs

### ISSUE THREAD

**Issue by Neos2007** [Smile-SA/elasticsuite#2025]
Currently, we have a problem with Magento cloud production and staging environments that on search results page withs bundle products searched by SKU of the related simple product displayed a message "No exact results found for: "term". The displayed items are the closest matches.". Search results contain the needed bundle product (at the first position) along with some other products. This happens not for all SKUs: for some child product SKUs in search results displayed only one correct bundle product, but for other displayed mentioned warning message and next to "searched" bundle also displayed some other bundle products.
![image](https://user-images.githubusercontent.com/17883826/102199903-dc95fe00-3ecc-11eb-9cfe-0233f6931d56.png)

Tried to perform reindexing (on staging and production) but this did not help.
I did not find helpful information in logs (tried also enable debug for elasticsuite in config).
Notes:
- In shops, we display only bundle products, related child simple products are not visible on frontend.
- As a search engine we using elasticsuite module version 2.10.1, version of elasticsearch server: 7.7. Magento version: 2.4.0.
- I tried to disable fuzziness and spellcheck on elasticsuite configuration. But this did not help - in search results, I had "needed" product but the warning message still appeared.
- **Problem appears on cloud staging and production environments**. I also tested locally (fetched database from staging) **and locally I did not have such problem** (search by mentioned SKUs always returned correct results without a warning). On my local server, I'm using the same version of elasticsuite module and elastic search service. So I cannot reproduce this bug locally which is very strange.

Maybe someone has an idea what could be the reason why this issue can happen and how to fix it?

**Comment by romainruaud** [comment]
Hi @Neos2007 

how much shards do you use for your production environment ? 

You might be on an edge-case where Elasticsuite tries to find if something exact is existing for your search. If that's not the case, the engine will trigger a fuzzy search. If an exact match is found during this "pre-flight" query, no fuzziness is applied.

Since SKU are basically unique, and this test (which is done with [Term Vectors](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html)) is performed on a single-shard, it's possible that sometimes the engine concludes that "nope, nothing exists exactly with this token" despite the fact that an unique product is containing it, but in an other shard than the one that was used for testing against.

That could explain why it's not the case on a development environment, especially if this environment has only one shard.

**Comment by Neos2007** [comment]
Yes, @romainruaud . You are right.
On my local environment configured 1 shard and no replicas for the index, and on servers (this is Magento cloud hostig) automatically configured 3 shards for index with 2 replicas.
So what will be the best way to avoid such search issues?
![image](https://user-images.githubusercontent.com/17883826/107011128-e981f000-679f-11eb-93f7-750c6eb78b27.png)

**Comment by romainruaud** [comment]
@Neos2007 you can see my comments here : https://github.com/Smile-SA/elasticsuite/issues/2000

Most probably, you don't need to have 3 shards/2 replicas, and 1 shard/2 replicas is enough (if you catalog is not too large).

What is the size of your catalog actually ?

**Comment by Neos2007** [comment]
@romainruaud we have similar issues on different websites (Magento installations) on the magento cloud.
With catalog size from 500 to 3800 products.

**Comment by romainruaud** [comment]
with 3800 products maximum, you don't need more than one shard.

Can you try switching to 1 shard / 2 replicas and see if things are better after a reindex ?

**Comment by Neos2007** [comment]
@romainruaud  Thanks for the help. Will try.

**Comment by abecker87** [comment]
The same problem occurred with one of our pages in the Magento Cloud, but switching to 1 shard and 2 replicas did not solve the problem for us. 
@Neos2007 Could you resolve the problem in the meantime?
