### ISSUE TITLE
How does elasticsuite delete entities from the index?

### ISSUE THREAD

**Issue by killoff** [Smile-SA/elasticsuite#2041]
**Is your question related to a problem? Please describe.**
The documentation clearly describes how documents are indexed.
However, I haven't found how products/categories are being removed from the index.
For example, if some product got disabled or category got inactive.

It's clear when full reindex - elasticsuite just creates a new index.
But would be nice to know how it works for partial updates.

**Comment by killoff** [comment]
Apparently, it just follows the approach of Magento.
So, first of all it deletes the entities and then create new ones if they need to be in the index.
https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext.php#L86

```
public function execute($ids)
    {
        $storeIds = array_keys($this->storeManager->getStores());

        foreach ($storeIds as $storeId) {
            $dimension = $this->dimensionFactory->create(['name' => 'scope', 'value' => $storeId]);
            $this->indexerHandler->deleteIndex([$dimension], new \ArrayObject($ids));
            $this->indexerHandler->saveIndex([$dimension], $this->fullAction->rebuildStoreIndex($storeId, $ids));
        }
    }
```

**Comment by Quazz** [comment]
@killoff There are also some mview indexation techniques.

Smile\ElasticsuiteCatalog\Plugin\Indexer\AbstractIndexerPlugin.php gets extended by the plugins

**Comment by vahonc** [comment]
Hello @killoff,

Yes, you are right here https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext.php#L96 you can see what happens when we do a full reindex, and here https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Category/Indexer/Fulltext.php#L80 when we do a partial reindex. And for a better understanding of what happens when we delete some index or in other words documents (products/categories) you can look at this code https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Indexer/GenericIndexerHandler.php#L139. 

And finally, you can go to this link to browse the official Elasticsearch docs about Delete API: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete.html

Best regards
