### ISSUE TITLE
Possible causes for "Diff indexing is not supported for synonyms. Invalidate the index instead"

### ISSUE THREAD

**Issue by jaxtheking** [Smile-SA/elasticsuite#2047]
We're using an external third-party software to manage products in bulk (Product Manager for Magento by Benabee).
The software uses a bridge (php script uploaded to the server) to sync up any changes.

Lately, when using the software, a lot of the following messages have been showing up in the logs:
```
PHP Fatal error:  Uncaught Exception: Diff indexing is not supported for synonyms. Invalidate the index instead. in /vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Indexer/Thesaurus.php:84
Stack trace:
#0 /vendor/magento/framework/Interception/Interceptor.php(58): Smile\ElasticsuiteThesaurus\Model\Indexer\Thesaurus->executeList(Array)
#1 /vendor/magento/framework/Interception/Interceptor.php(138): Smile\ElasticsuiteThesaurus\Model\Indexer\Thesaurus\Interceptor->___callParent('executeList', Array)
#2 /vendor/magento/framework/Interception/Interceptor.php(153): Smile\ElasticsuiteThesaurus\Model\Indexer\Thesaurus\Interceptor->Magento\Framework\Interception\{closure}(Array)
#3 /generated/code/Smile/ElasticsuiteThesaurus/Model/Indexer/Thesaurus/Interceptor.php(32): Smile\ElasticsuiteThesaurus\Model\Indexer\Thesaurus\Interceptor->___callPlugins('executeList', Ar in /vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Indexer/Thesaurus.php on line 84
```

I'm trying to understand what does it mean. Would you know under which circumstances this error would be triggered?

Thanks,
Luca

**Comment by romainruaud** [comment]
Hi @jaxtheking your third party module is probably (wrongly) calling the `executeList` method on all indexers, which is unsupported for our Thesaurus indexer.

I guess it's doing this in a try to be sure that "everything possible related to product is reindexed at the end of the import", but there are several drawbacks doing this : 

- it's unsupported for ElasticSuite Thesaurus, which would be, in any case, completely useless since they do not contain product information.
- it's probably dangerous to call arbitrary any potentially "unknown for them" indexer, especially if they are passing product ids as parameter => I wonder if that's calling also the "Category fulltext indexer" ?

That being said, we cannot provide open-source support for third-parties extensions here. If you want us to provide professional support, you can reach us at elasticsuite@smile.fr .

Regards

**Comment by jaxtheking** [comment]
Thank you @romainruaud, I truly appreciate you taking the time to write these notes.
I'm not too fund on using this external tool but it does help automating bulk editing for the shop admins.
Should I need further support, I'll contact your professional support.

Regards
