### ISSUE TITLE
Main categories showing products of sub category attributes filters also.

### ISSUE THREAD

**Issue by muksSoni** [Smile-SA/elasticsuite#2070]
### Preconditions

Magento Version : 2.3.3

ElasticSuite Version : 2.1.0

Environment : production

Third party modules :

### Steps to reproduce

1.  We have a "Mens" main category in this we adding virtual category enable and adding products with "clothing" attribute set.
2. This "Mens" category have sub categories "Footwear" and it have virtual category with Footwear attribute set.
3. "Mens" category listing products with footwear and clothing attribute instead of only products with clothing attribute set.

### Expected result

1. Mens (main category) should display only products with rules set for this category not its sub categories also.

### Actual result

Main category is listing products of its sub categories selected rule set also instead of rules defined for this category.
1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Hi,

this is by design.

All categories are considered as being anchor when using Elasticsuite, meaning they will always display any product belonging to one of their childrens.

You should not use virtual categories for sorting products into different categories, that's something that should be done during product import or even before in a dedicated tool (like a PIM).

Our virtual categories mechanism is here to define "marketing" categories and create easily content pages that will display dynamically product according to criterias (bargain of the month, discounted products, etc...), it's not intended to be use to "cleanup" a messy catalog.

Regards
