### ISSUE TITLE
Multiselect for category filters

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#2071]
While it is possible to have attributes filter by multiple choice it is not for category filters.
Once I select a category in the list of filters the subsequent page will only show the current categories subcategories. If there are none the category filter will disappear entirely.

This is just terrible UX design. Filters are supposed to give orientation and guidance. They will fail this task if their appearance is conditional. Why have attributes multiselect possible but stop a category filters? The USER doesn't know the technical difference and doesn't care.

I know this is magentos default behaviour and it has been right from the start. I think it would be a win for this module if it could have categories multiselectable as well.

**Comment by romainruaud** [comment]
Hi @OvalMedia 

That's something we already analyzed previously for some of our customers but that was finally never made due to the amount of required work versus the return on investment.

That's also something really tied to the "legacy" frontend of Magento and that would require more work to get it working compared to the graphql implementation.

So it's unlikely that we'll add such a feature anytime soon, but that being said, there are now several roads you can choose to have it in elasticsuite : 

- you can do it yourself and submit a pull request, I'll be glad to review and merge it into the core
- if this feature is asked by some of your customers, we can probably agree alltogether to build it as part of our professional services policy. If that can be interesting for you, you can contact us as elasticsuite@smile.fr

Best regards

**Comment by OvalMedia** [comment]
I would do it if knew how. This is something I have been struggeling with magento from the very start. Some modules I purchased in the past are capable of doing it but looking at the code I never figured out how they did it. Unfortunately those modules would not be compatible with yours. Given that your module has so much more to offer this is something we will have to live with.

**Comment by OvalMedia** [comment]
A possible workaround (with limits) for anyone who needs this: you could create a separate attribute which syncs with the categories. With plugins and observers you could automate the synchronization between the two. Since attributes CAN have multiple choice this would act as a category filter.

Of course this would only work with one category level.

**Comment by sevka** [comment]
I would like to have such a feature as well.
