### ISSUE TITLE
SEO friendly URLs for filter options

### ISSUE THREAD

**Issue by GeryPHPro** [Smile-SA/elasticsuite#2091]
**What?**
When selecting filters on a category page the URL is displayed SEO friendly instead of with parameters.

**Example**
When selecting the color filter red in the T-shirt category the URL will display as:
/tshirts/color/red instead of /tshirts/?color=red

**Comment by romainruaud** [comment]
It's likely something that we'll never do, because : 

- for years I've asked people wanting this to show me an official document from Google stating that URLs like that are "performing better" than the other ones. I never saw something like this, so, until proven otherwise, I consider this kind of features as being an SEO mantra with no real impacts.

- there are as much as SEO "best practices" as the number of SEO agencies/experts : it's impossible to implement a one-size-fits-all mechanism, and people would still need to customize things on top of Elasticsuite.

- Luma theme / legacy frontend will be deprecated soon and considering the amount of people that are building headless Magento's website right now, we don't find that much value in adding support for Luma theme.

Regards
