### ISSUE TITLE
Conflict with Amasty_Shopby

### ISSUE THREAD

**Issue by Nielex** [Smile-SA/elasticsuite#210]
When I'm using ElasticSuite in combination wiht the Amasty_Shopby module. I got an error:

"Fatal error: Uncaught Error: Call to undefined method Amasty\Shopby\Model\ResourceModel\Fulltext\Collection::addIsInStockFilter() in /home/experius/domains/whitelabelb2b.elastic.dev21.xpdev.nl/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 56" 

When I enable the "show_out_of_stock" option. I got an other error:

"Fatal error: Uncaught Error: Call to undefined method Amasty\Shopby\Model\ResourceModel\Fulltext\Collection::getProductCountByAttributeSetId() in /home/experius/domains/whitelabelb2b.elastic.dev21.xpdev.nl/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php on line 155"

I don't know if this is a real issue related to this module. But when I disable the Amasty_Shopby module everthing works fine. It would by really nice if I can use both modules together.

**Comment by afoucret** [comment]
Hi @Nielex,

There is no way to ensure both modules works well together, since features implemented by both modules are overlaping.

Additionally, the Amasty_Shopby module is proprietary and we don't have access to their implementation. It make me think that it is more their responsability than ours make their module compatible.

**Comment by ivanaugustobd** [comment]
First of all, thanks for the module, it's freaking insane how many features it provides for free.

Naturally I'm here because I've also faced this issue, but I believe that the responsibility to solve this kind of conflict is primarily mine as a Magento store developer, so I'm not asking for you guys to do such a thing. 

Instead, I just want to leave a suggestion: **_for a future release, please consider refactoring it into multiple smaller modules_**, with a core engine as a common dependency between them. This would assure that existing stores could benefit from the enhanced engine, while also keeping their own already existing customizations 😉
