### ISSUE TITLE
Disabled search by sku, still showing sku's

### ISSUE THREAD

**Issue by janssensjelle** [Smile-SA/elasticsuite#2100]
In the file module-elasticsuite-catalog/etc/elasticsuite_indices.xml

it is possible to search isSearchable for SKU to false. After having done this, and reindexing, it is still possible to search skus. Any idea why this happens?

**Comment by vahonc** [comment]
Hello @janssensjelle,

If I correctly understand you did all that needed, but anyway please read our [Wiki](url https://github.com/Smile-SA/elasticsuite/wiki/Indexing#defining-fields-property-via-configuration)

Also, please provide more details, for example a code from your file `module-elasticsuite-catalog/etc/elasticsuite_indices.xml` and mapping of fields. This will help us better understand where exactly the problem is and if it really is a bug.

BR,
Vadym
