### ISSUE TITLE
Disable Search by SKU

### ISSUE THREAD

**Issue by aljuarismi** [Smile-SA/elasticsuite#2136]
The attribute SKU was configured to not searchable, but still relation in search result.
### Preconditions

Magento Version :
CE 2.3.5-p1

ElasticSuite Version :
2.9

Environment :
Developer and Production mode

Third party modules :
N/A
### Steps to reproduce

1. Set SKU attribute value Searchable -> No
2. Full reindex
3. The search results do not change, it continues to relate the SKU to the search term

### Expected result

1. Don't search any relation by SKU on search term

### Actual result

Irrelevant results for the user of the store, because the SKU attribute has no direct relationship with the product since it is for internal use of the company

**Comment by romainruaud** [comment]
That's by design, because *the xml configuration file has precedence over DB changes* 

And by default, the SKU is searchable according to this line : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L33

Can you try to change this line (you can do this in another module), clear the cache and then reindex ?

Regards

**Comment by aljuarismi** [comment]
Solved! thank you very much.
