### ISSUE TITLE
catalog_product index does not exist yet. Make sure everything is reindexed.

### ISSUE THREAD

**Issue by maureyz** [Smile-SA/elasticsuite#2151]
We using ElasticSearch in a Magento Cloud environment.

Using many indices, Magento Support told us we need delete them using a Magento dictionary comman. We did...
But they reporting us this:

`{"0":"catalog_product index does not exist yet. Make sure everything is reindexed.","1":"#1 Smile\\ElasticsuiteCore\\Search\\Request\\ContainerConfiguration->getIndex() called at [vendor\/smile\/elasticsuite\/src\/module-elasticsuite-core\/Search\/Request\/ContainerConfiguration.php:94]`

and this:

```
| elasticsuite_categories_fulltext | ElasticSuite Category Indexing  | Processing | Schedule  | idle (0 in backlog)       | 2021-05-28 16:11:12 |
| elasticsuite_thesaurus           | ElasticSuite Thesaurus Indexing | Processing | Schedule  | suspended (0 in backlog)  | 2021-05-27 19:18:12 |

```
They recommend us reaching out to you (Smile ElasticSuite) for assistance in optimizing the index process, and minimizing the total amount of indices, to resolve this issue.

### Preconditions
Magento Cloud EE 2.4.0

Magento Version : EE 2.4.0 Cloud-Environment

ElasticSuite Version : 2.10.1

Environment : Production

Third party modules : 

### Steps to reproduce

1. Happening when is reindexing command has been launched
2.
3.

### Expected result

1. there should not be any reindex incomplete.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
hi @maureyz 

I'm afraid I do not understand the issue you are facing actually.

What was the original issue ?

Which command did you run exactly ?

Regards

**Comment by maureyz** [comment]
Hi there.
It was my fault that I didn't explain myself better.

I don't know why our cloud environment has several fails related with ElastiSearch.
To replicate this, we only we been using index:reindexer, that's it.

We have some environmental issues that depends to magento, but they sent us to you to require your help.

Here's a image of a magento support comment:
![image](https://user-images.githubusercontent.com/82602868/120221193-937c0100-c203-11eb-92d7-b5a293c7e423.png)

**Comment by vahonc** [comment]
Hi @maureyz,

The error `No alive nodes found in your cluster` usually means that something is wrong with ElasticSearch or its configuration.

Have you previously experienced similar or any other problems with ElasticSearch and ElasticSuite in your environment? Has anything changed/updated since then?

Could you check if everything is good with ElasticSearch in your environment?
<pre>curl localhost:9200</pre>

Also, please check our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall)

BR,
Vadym

**Comment by maureyz** [comment]
> Hi @maureyz,
> 
> The error `No alive nodes found in your cluster` usually means that something is wrong with ElasticSearch or its configuration.
> 
> Have you previously experienced similar or any other problems with ElasticSearch and ElasticSuite in your environment? Has anything changed/updated since then?
> 
> Could you check if everything is good with ElasticSearch in your environment?
> 
> curl localhost:9200
> Also, please check our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall)
> 
> BR,
> Vadym

Hi @vahonc 

The `curl localhost:9200` returns: `curl: (7) Failed to connect to localhost port 9200: Connection refused`

**Comment by vahonc** [comment]
Hello @maureyz,

"Connection refused" is as verbose as it can be: it's not something related to the Elasticsuite module, but rather due to infrastructure/hosting issues.

This way, we are not able to provide any help, since we are only providing support for the module. You should ask Magento Cloud team to investigate more and to escalate to the appropriate level of support (you will need to have an infrastructure expert to work on your issue).

Also, you could ask the Magento Cloud team how you could get proof that with ElasticSearch everything is OK in Cloud environment, in a local environment it usually did via output of the command `$ curl localhost:9200 or $ curl -i localhost:9200`

BR,
Vadym

**Comment by words2mahi** [comment]
Hi Team,

 I am also facing issues while reindexing
**catalog_product index does not exist yet. Make sure everything is reindexed.**

Magento Version:Magento EE ver 2.4.1
Elastic search Version:7.7.1
smile/elasticsuite ~2.10.0

kindly support to fix this issue

**Comment by vahonc** [comment]
Hello @words2mahi,

We need more details about your environment. So please answer on my questions.

Have you also used Cloud Environment?

Have you environment with multistore websites?

Have you enabled a Debug Mode for ElasticSuite?

Have you tried to run a full re-index, what's the output of this command?

BR,
Vadym

**Comment by romainruaud** [comment]
@words2mahi @maureyz any update on this one ?
