### ISSUE TITLE
Install documentation issue

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2164]
![Capture d’écran 2021-06-08 à 15 49 15](https://user-images.githubusercontent.com/1633463/121196907-260a4900-c871-11eb-83d1-51b326f0df48.png)

Config paths in table are wrong : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

Also, Elasticsearch 7.x should be added to supported versions list.

**Comment by romainruaud** [comment]
That's true, the "smile/" part in the table is incorrect, as long as the supported versions.

@vahonc can you edit the wiki ?

**Comment by vahonc** [comment]
It's done!

BR,
Vadym

**Comment by Nuranto** [comment]
@vahonc you forgot `es_client/`

**Comment by vahonc** [comment]
Updated. Thanks!

BR,
Vadym

**Comment by fritzmg** [comment]
Also `-l` is deprecated, you should use `-e`/`--lock-env`.

**Comment by vahonc** [comment]
> Also -l is deprecated, you should use -e/--lock-env.

Thanks, @fritzmg for this one. Yep, according to the Magento [devdocs](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-config-mgmt-set.html#config-cli-config-set) now we should use `-le` or `--lock-env` instead of `-l` when we try to set up the system-specific configuration values, example:

<pre>$ bin/magento config:set [--scope="..."] [--scope-code="..."] [-le | --lock-env] [-lc | --lock-config] path value</pre>

Therefore I've added the changes to our [docs](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-already-installed-).

BR,
Vadym

**Comment by Nuranto** [comment]
Also, ES 7.x is missing in Requirements part

**Comment by vahonc** [comment]
> Also, ES 7.x is missing in Requirements part

**Fixed!**
