### ISSUE TITLE
Optimizer adding rule leads to "Invalid security or form key. Please refresh the page."

### ISSUE THREAD

**Issue by diybook** [Smile-SA/elasticsuite#2176]
While adding a new optimizer and after selecting an attribute or any other rule value for the rule conditions the ajax call ends with an 403. 

Magento backend goes to dashboard and the message "Invalid security or form key. Please refresh the page." is shown.

The error log is not very specific:

[2021-06-17 07:34:21] main.DEBUG: Request validation failed for action "Magento\Framework\App\Action\Forward\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at .../vendor/magento/module-backend/App/Request/BackendValidator.php:152)"} []

### Preconditions
Want to add a condition to the Optimizer.

Magento Version : 2.4.2
ElasticSuite Version : 2.10.4
Environment : Development

Third party modules :

### Steps to reproduce
1. Add new or open existing Optimizer Entity
2. Click plus and select one of the shown attributes or values of the list
3. => redirtect to dashboard with error message

### Expected result
1. Attribute Options should be shown

### Actual result
![1](https://user-images.githubusercontent.com/3702595/122353747-a3f4e100-cf50-11eb-9fa6-a7c81902f63e.png)
![2](https://user-images.githubusercontent.com/3702595/122353758-a7886800-cf50-11eb-978c-7cfa7e1b34d0.png)
![3](https://user-images.githubusercontent.com/3702595/122353769-a9522b80-cf50-11eb-9478-81c50abec559.png)
![4](https://user-images.githubusercontent.com/3702595/122353777-ab1bef00-cf50-11eb-9f8e-a670bb5275e3.png)

Is there a known bug? How to debug this behaviour? The form keys are ok.

BR Gerald

**Comment by diybook** [comment]
I found out, that the problem are the rights. _isAllowed gives back false. But as administrator _isAllowed should give access to this resource. Any ideas? 

BR Gerald

**Comment by diybook** [comment]
Hi Vadym, 

I've changed the following part, and everything works now. There seems to be an issue with access rights. I've tried with another user and by setting the right manually. But that did not work either.  
```
    /**
     * @SuppressWarnings(PHPMD.CamelCaseMethodName)
     * {@inheritDoc}
     */
    protected function _isAllowed()
    {
        $isAllowed = true; // former false 
        foreach ($this->acls as $acl) {
            $isAllowed = $isAllowed || $this->_authorization->isAllowed($acl);
        }
        return $isAllowed;
    }
```

**Comment by vahonc** [comment]
As I told above, there shouldn't be any issues with access to the editing of the optimizer from the box. Unless if you have changed some settings according to your requirements.

If you use the custom resource access, please check rights in Magento BO:

![06-17-2021 administrators roles permissions system magento admin](https://user-images.githubusercontent.com/67791361/122397805-fac6de80-cf81-11eb-83ca-f26774d7fbed.png)

BR,
Vadym

**Comment by diybook** [comment]
Hi,

the rights are set as follows:

Admin:
![6](https://user-images.githubusercontent.com/3702595/122468011-75602000-cfbb-11eb-82f2-8506b8074e43.png)

Other User:
![5](https://user-images.githubusercontent.com/3702595/122468030-7b560100-cfbb-11eb-98a4-9c52a0dd6914.png)

In both cases it did not work. With $isAllowed = true; everything is ok and I don't think this should be a damatic security issue. 

BR Gerald

**Comment by romainruaud** [comment]
I'm not sure actually which acl is assigned exactly to the ```Smile\ElasticsuiteCatalogRule\Controller\Adminhtml\Product\Rule\Conditions```

Maybe there's a hole here by our side and we should either setup a specific ACL that can be explicitely allowed/disallowed, or fallback to $isAllowed = true.

We'll investigate.

**Comment by diybook** [comment]
Thanks

**Comment by vahonc** [comment]
Hi Gerald,

I have involved more deeper to investigate the ACL issue in order to your problem.

I'm still don't understand why under your Admin User you can't add the Rule Conditions to the new or existing Optimizers.

I've checked again it on my test environment and again didn't notice any problems with it. Perhaps you should re-save a Role for your Admin User.

Here's a screenshot of Role Resources for my default Administrator User:

![06-22-2021 administrators roles permissions system magento admin](https://user-images.githubusercontent.com/67791361/122938817-bec5bc00-d37b-11eb-802b-5d134b75d7b2.png)

However, I was able to reproduce your problem when I start testing this issue under my Custom Admin User. But I didn't add any changes in the code, so for my test case as before `$isAllowed = false;` in `Smile\ElasticsuiteCatalogRule\Controller\Adminhtml\Product\Rule\Conditions`. So I've changed `Role Resource Access` for my Custom Admin user to `Custom`. 

Indeed if we added access only for the ElasticSource Resources we have a problem when we try to add new Rule Conditions.

![Screenshot from 2021-06-22 16-19-03](https://user-images.githubusercontent.com/67791361/122941300-f0d81d80-d37d-11eb-8d9a-f106ec500e3b.png)

The most strange that after granted access for `Manage Search Optimizers` my Custom Admin User was able to edit Rule Conditions of the existing optimizers but only when I try to delete some conditions, and when I try to add a new condition I get an error and was redirected to Dashboard.

Therefore I thought that this problem could be linked to some additional access so I start to test various combinations. And finally, I have found it:

![06-22-2021 elasticsuite roles permissions system magento admin (1)](https://user-images.githubusercontent.com/67791361/122942904-3cd79200-d37f-11eb-830f-a2af2256f318.png)

After granted access for `Catalog->Inventory->Categories` my Custom Admin User was able to add a new Rule Conditions to the new or existing Optimizers without any errors and redirection.

Could you please check it out on your environment with your Custom Admin User? You could try to create a test optimizer according to our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#creating-an-optimizer) and then try to edit/update it or you could use your optimizers.

I hope my comment will be helpful to you, I will discuss with my team if we can add some fixes for this issue.

BR,
Vadym

**Comment by romainruaud** [comment]
@diybook did you test to add the ACL that was indicated by Vadym ? Did it help ?

**Comment by diybook** [comment]
I'll can check it tomorrow. I'll give you feedback then. Sorry for the delay. 
BR Gerald

**Comment by diybook** [comment]
I've tested as recommended. I wonder the screen Vadym has sent. Because I do not have "Role Scopes". Is there anything messed up with my installation? 

The problem is, that it do not work with resource access "all" either. It's not only with a custom role. 

Any ideas?

BR Gerald

**Comment by vahonc** [comment]
Hi Gerald,

Sorry if my screenshot confused you. On it ElasticSuite it's just a Custom User Role and my Custom Admin User is `elastic`.

![Screenshot from 2021-06-30 11-18-09](https://user-images.githubusercontent.com/67791361/123927328-6acb6080-d995-11eb-84a9-32cd48c12fcc.png)

![Screenshot from 2021-06-30 11-18-38](https://user-images.githubusercontent.com/67791361/123927345-6f901480-d995-11eb-8452-7314f42ff90d.png)

As for this:

> The problem is, that it do not work with resource access "all" either. It's not only with a custom role.

Could you tell which version of the Magento you are using (CE, EE)? 

It's a local or staging or development environment? 

Also please check if there no any overrides of the Admin access. Maybe something is wrong with the configuration of your Magento instance. As I showed above, from the box for my default Admin User and his Administrators Role with resource access "all" and without any changes in the code all is working.

BR,
Vadym

**Comment by diybook** [comment]
Hi Vadym, 

thanks for your fast reply. I'm using magento 2.4.2. the problem exist on dev as well as on production. I'll check if there are any overwrites. Can you give me a hint what files I have to check. I'm sure I did not implement any overwrite, but I'll check 3rd party modules.

BR Gerald

**Comment by vahonc** [comment]
@Gerald, are you using Magento 2.4.2 EE or CE version?

It's hard to say where exactly could be a problem in the code. But you are right, firstly you should check 3rd party modules.

Also if it's suitable for you, you could fix your problem with the hack that you showing above:

<pre>
 /**
     * @SuppressWarnings(PHPMD.CamelCaseMethodName)
     * {@inheritDoc}
     */
    protected function _isAllowed()
    {
        $isAllowed = true; // former false 
        foreach ($this->acls as $acl) {
            $isAllowed = $isAllowed || $this->_authorization->isAllowed($acl);
        }
        return $isAllowed;
    }
</pre>

BR,
Vadym

**Comment by vahonc** [comment]
Also according to this error message:

> [2021-06-17 07:34:21] main.DEBUG: Request validation failed for action "Magento\Framework\App\Action\Forward\Interceptor" {"exception":"[object] (Magento\Framework\App\Request\InvalidRequestException(code: 0): Invalid request received at .../vendor/magento/module-backend/App/Request/BackendValidator.php:152)"} []

try to remove an old generated files on your dev env. using `$ rm -rf var/generation/*` command (rm -rf generated/* for the Magento >=2.2) from the magento root directory and maybe also remove the `page_cache, cache, view_preprocessed, static folders`, because magento pre-generates all class files with their constructors.

Then run this commands:
<pre>
$ bin/magento setup:upgrade
$ bin/magento cache:flush
$ bin/magento setup:di:compile
$ bin/magento setup:static-content:deploy
$ bin/magento indexer:reindex
</pre>

BR,
Vadym

**Comment by diybook** [comment]
We use 2.4.2 CE. Sorry that I forgot that. 

Caches and genereted files were all deleted. But I'll check the third party modules. If noone else do have this problem it has to do with my installation and modules enabled. Very strange. 

In the meantime I leave it with the little hack. Thank you for your really really  good support. 

with best regards, 
Gerald

**Comment by braders** [comment]
Hi all,

I have just started using ElasticSuite of 2.4.1 on Commerce (enterprise). So far the module seems great, but I am also experiencing this issue. I am logged in as a full admin user, and have seen the issue on multiple environments. I'll try and work around the problem and will update this ticket if I find anything of relevance.

**Comment by braders** [comment]
Ok, I seem to be getting somewhere. It seems to be some sort of issue in the order in which Magento is loading modules.

If I copy the following code from `vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/etc/di.xml` to my own module's `di.xml` the issue is resolved

```php
<type name="Smile\ElasticsuiteCatalogRule\Controller\Adminhtml\Product\Rule\Conditions">
        <arguments>
            <argument name="acl" xsi:type="array">
                <item name="manage_categories" xsi:type="string">Magento_Catalog::categories</item>
            </argument>
        </arguments>
    </type>
```

Having dug deeper, I'm slightly worried that other classes are suffering in the same way. For example, running ` bin/magento dev:di:info 'Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\QueryBuilder'` gives me the wrong result (nestedFilters as an empty array, not including category). This class is defined in the same `vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/etc/di.xml`.

It looks like the issue may be when `module-elasticsuite-virtual-category` tries to setup DI for `module-elasticsuite-catalog-rule`. Unfortunately I'm on leave next week and can't spend any more time on this today, but hopefully this will help the Elasticsuite maintainers make some progress on this issue.
