### ISSUE TITLE
Magento 2.3.7 with PHP 7.4 Support

### ISSUE THREAD

**Issue by harrigo** [Smile-SA/elasticsuite#2177]
Just wondering if this module has support for 2.3.7 using PHP 7.4. Believe it was working ok with 2.3.7 and 7.3 however updated to 7.4 and noticed at some point since my category pages now fail with below error.

`"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."`

The issue seems to be the virtual category grid not loading via ajax because of another error below:

`{"error":true,"message":"You entered an invalid Secret Key. Please refresh the page."}`

Just wondering if this is a known issue and if so is there another version of the module I should be using / a patch available for this?

**Comment by vahonc** [comment]
Hello @harrigo,

We need more details about your environment.

Which version of ES are you using?
Did you use local or Cloud hostings?
Have you noticed any other issues related to Secret Key on other pages of Magento BO?
Did you check the logs of Magento?

BR,
Vadym

**Comment by harrigo** [comment]
This is for the backend category edit page.

Which version of ES are you using?
2.9.0
Did you use local or Cloud hostings?
Local
Have you noticed any other issues related to Secret Key on other pages of Magento BO?
No not yet.
Did you check the logs of Magento?
Didnt see anything in logs there.

**Comment by vahonc** [comment]
Hello @harrigo,

I'm not sure if we actually checked if the 2.9.0 version is directly compatible with PHP 7.4. But we added a lot of fixes to the 2.9.x branch.

So here're what you can do in this case:

1. Check again which version of the ES module you are using with this command:
`$ composer show smile/elasticsuite | grep "versions"`

2. If it really is the 2.9.0 version try to remove our module:
`$ composer remove smile/elasticsuite`

3. Then install the latest version of the ES module (for now it's 2.9.5):
`$ composer require smile/elasticsuite ~2.9.0`

4. Clean your environment with the next commands:
<pre>
$ bin/magento setup:upgrade
$ bin/magento cache:flush
$ bin/magento indexer:reindex
</pre>

And then check again if your issue is still occurring and let us know about these results.

BR,
Vadym

**Comment by romainruaud** [comment]
I think #2156 was the only fix to be merged : it was required for PHP 7.4 compatibility with magento 2.4.2

You should be able to give it a try by using the 2.9.x branch locally, until we publish the next 2.9 stable release.

Thank you

**Comment by vahonc** [comment]
@harrigo,

We've added a [fresh release](https://github.com/Smile-SA/elasticsuite/releases/tag/2.9.6) of our module that includes a fix for compatibility with PHP 7.4.

BR,
Vadym
