### ISSUE TITLE
Product sort by price with optimizer to boost in stock products

### ISSUE THREAD

**Issue by aniruddharay** [Smile-SA/elasticsuite#2178]
### Preconditions
Magento 2.3.4 CE
Elasticsuit 2.8.0
### Requirement
1. I have a category which has its first 10 products set as manual sort. 
2. I have added an optimizer to boost the in stock products and to show the out of stock products at the bottom.
3. I have set default sort by Price _( Catalog > Catalog > Storefront > Product listing sort by )_ 

### Expected Outcome
On category page
- First the manual sorted products will be visible. 
- Then in stock products will be visible based on price. 
- At the end out of stock products will be visible.

### Actual outcome
1. Manual sort products showing first as they should. 
2. Products showing sorted by Position, including out of stock products. 

### UPDATE
I tried adding a plugin `afterSetCollection` on `Magento\Catalog\Block\Product\ProductList\Toolbar` and set the default sort to price. The sort is working, but the optimizer is not. Shwoing out of stock products amidst others.

**Comment by aniruddharay** [comment]
@vahonc Is this a genuine problem I am having or there is something I have missed ?

**Comment by vahonc** [comment]
@aniruddharay,

Could you please provide us more details (screenshots) for setting up your Optimizer rule?

BR,
Vadym

**Comment by aniruddharay** [comment]
Hello @vahonc ,

I am using the following optimizer. 
![screenshot-loopify local-2021 06 28-14_47_38](https://user-images.githubusercontent.com/69155933/123612325-0fc42d00-d820-11eb-8d5a-59fea2b25b50.png)

**Comment by vahonc** [comment]
It could be some conflict with manual sort in the case when products go to Out of stock. 

I'll discuss it with my team and come back to this later.

BR,
Vadym

**Comment by romainruaud** [comment]
That's not doable : **optimizers are applied only when the default _Position_ sort order is used in frontend**.

We do like this to avoid any confusion : 

- if an end user sort by price, he expects to see cheapest products first, not some promoted product
- the same does apply for alphabetical order of course.

**Comment by aniruddharay** [comment]
@romainruaud  My basic requirement is to show out of stock products at the end, irrespective of the sort option. If there are any other way to do this other than optimizers, please do let know. Thanks

**Comment by romainruaud** [comment]
I'm afraid that's hard to do, optimizers are used to influence products "scores", which is the internal field used for sorting when no particular sort order is set (or when the current sort order can be missing for some products, like sorting by category position).

Considering that all products have a price, when you sort by price, the engine will never fallback to the "score" sorting. 

Maybe you could try enforcing a different way to sort products when using "price" to sort, by using directly the stock.is_in_stock field.

Instead of having : 

- price asc/desc
- score asc
- entity_id (which is used a tie breaker)

Maybe the following could work : 

- stock.is_in_stock desc
- price asc/desc (this will tie-break for equal score and sort products by price)
- entity_id

**Comment by aniruddharay** [comment]
@romainruaud  I tried your suggestion , and it works! Thank you so much. 
Created plugin `aroundSetCollection` on `Magento\Catalog\Block\Product\ProductList\Toolbar` as subject. Changed the `_current_grid_order` is_in_stock, and `_current_grid_direction` desc. After proceed , I set order by price. 

This changes the listing, all products appear by their price, and out of stock products shows at last. This is exactly what I wanted.
