### ISSUE TITLE
Grouped products filter by custom attribute not working properly.

### ISSUE THREAD

**Issue by ganeshp29** [Smile-SA/elasticsuite#2182]
All items in a grouped product are registered as filter options, instead of just the grouped product itself.

it's the Kid's Beds page with Bed Accessories chosen as the category filter. It's pulling in grouped products that include bed accessories instead of just bed accessories by themselves.

### Preconditions

Magento Version : 2.3.3-p1 EE
ElasticSuite Version : 2.8.0
Environment : Developer
Third party modules : Amasty Improved Sorting

### Steps to reproduce

1. Under "Category" (Custom attribute) filter option, We will see all the values of the attribute assigned to products.

### Expected result

1. We want the grouped product to filter which has the actual category attribute value assigned with it, (Not depends on their child products attributes)
2. Those categories should be filtering to simple, grouped, and configurable products. They should not be showing grouped products by the categories of their associated pieces.
3. As an example - this grouped product - Signature-Design-B446-TLBWS should only show up in Beds, the category associated with the grouped product itself. It should not be showing up in Bed Accessories, the category associated with it's parts.

Another example - grouped product - Signature-Design-B376-TSB - should only be showing up under the Beds category filter. It should not be showing up as Headboards and Footboards, or Bed Accessories.

### Actual result

1. ![image](https://user-images.githubusercontent.com/33414084/123276571-e99e4480-d522-11eb-9e32-1e3074f2f4cc.png)

In the screenshot, we will see the attribute values come under the filter option. (Attribute value assigned to grouped product and their associated products )

Currently, if we filter any products by category, the simple and configurable products get filtered as per their own category, but grouped products get filtered on basis of the associated simple product category. When filtering through bed accessories category, we see grouped products containing bed accessories as well as simple products bed accessories.

**Comment by romainruaud** [comment]
Hello @ganesh-ecsion 

What is "categories" ? Is this an attribute ? I guess this attribute is defined for parent products bu also for children products, right ?

If that's the case, your issue is due to the fact that **children attributes are merged in parent data when indexing**, that's happening here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L146

**Comment by ganeshp29** [comment]
HI @romainruaud 
Yes "categories" is the custom attribute defined for Parent and child products. 

I have checked the link you shared, As you stated that, children attributes are merged in parent data when indexing, and that is happening due to the code defined in line 146. So for testing, I have commented out the code defined in "addRelationData" function and re-run the indexing. But still it not working. The Parent and child attribute value still display in the category filter.

 Previously I had followed the solution given in the below link, which does not include child attribute value with the parent on Category filter.
Here is the link - https://magento.stackexchange.com/questions/62994/manufacturer-filter-parent-product-only

I had overridden `Magento_Catalog_Model_Resource_Product_Indexer_Eav_Abstract::_prepareRelationIndex()` to do nothing, so that related products are not included in the filter index.

Also overridden `Magento\Catalog\Model\ResourceModel\Product\Indexer\Eav\Source` with an empty `_prepareRelationIndex()`. and did the reindexing.

The above solution works for me without Elastic Suite, But now it is not working once I enabled Elastic Suite (Elastic Search) for my store. 

Could you please suggest any solution that will help us to fix this issue?

**Comment by romainruaud** [comment]
Sorry, the merge of child data into parent data is occuring in "addChildData" : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L116

In "addRelationData" we only add data that modelizes the relation between parent and child.

So, if you do not want the merge at all, you can override and replace the "addChildData" by nothing.

If you do not want to merge your "categories" attribute, you just have to override the class to add "categories" into the `forbidenChildrenAttributeCode`

We won't go any further on this issue since it's related to customization, and cannot be covered for free as part of our Open Source support policy here.

Shall you need additional (paid) support by our side, feel free to write an email to elasticsuite@smile.fr

Regards
