### ISSUE TITLE
Allow Single Select Layered Navigation to Specfic Attribute

### ISSUE THREAD

**Issue by TheRealHunzik** [Smile-SA/elasticsuite#2184]
- We are using smile elasticsuite in our Magento site, it is allowing multi-select in layered navigation but now I can only one attribute to restrict to single select not multi select  how I can do this please help me thank you

if any fellow developer or core team help to locate where i can override this feature please let me know Thank You

**Comment by vahonc** [comment]
Hello. @TheRealHunzik,

Sorry, but your issue is a little bit blurry for me. Could you please add more details (version of Magento and ElasticSuite, screenshots, steps for reproducing)?

At this moment I can only suggest to you check the configuration (properties) of your attribute like Catalog Input Type, etc in Magento BO, and check if all is reindexed.

BR,
Vadym
