### ISSUE TITLE
All products showing on category pages

### ISSUE THREAD

**Issue by aardalich** [Smile-SA/elasticsuite#2220]
When viewing a category page, all products are retreived.
Looking on similar issues I can find, all categories have is_anchor set to 1
Display category filter is set to Yes in Layered Navigation, and changing this to No has no effect.

Magento 2.4.2_p1 CE and 2.10.5 of ElasticSuite, both in dev and production

I have found if I comment out this within module-elasticsuite-catalog/etc/di.xml

`    <virtualType name="Magento\CatalogSearch\Model\Layer\Category\Context" type="Magento\Catalog\Model\Layer\Category\Context">
        <arguments>
            <argument name="collectionProvider" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Layer\Category\ItemCollectionProvider</argument>
        </arguments>
    </virtualType>
`

Then the correct number of products are retrieved, and the method addCategoryFilter is hit within vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php to add the category filter, where if the above virtualType is not commented out, is not hit.

**Comment by refueledinc** [comment]
As it turns out, this was a Anowave extension issue for me.

**Comment by vahonc** [comment]
@aardalich, please provide more details about your environment.

Are you using third-party extensions or custom theme?

BR,
Vadym

**Comment by MikeDevs** [comment]
We are observing the same exact issue and commenting out the collectionProvider in `module-elasticsuite-catalog/etc/di.xml` 
like @aardalich mentioned fixes it for us. I'd throw up a demo repo but we use proprietary plugins that I can not add in. The issue is reproducible across several dev and staging environments. Here is our setup:

### Environment

- Ubuntu 20.4
- NGINX 1.18
- MariaDB 10.4.x
- PHP FPM 7.4.x
- Redis 6.0.x
- ElasticSearch 7.9.3 

### Magento, Extensions, Themes

- Magento 2.4.3
- Porto Theme 4.0.1
- Elasticsuite 2.10.8.1
- mageplaza/module-smtp
- cloudinary/cloudinary-magento2
- mailchimp/mc-magento2
- shipperhq/module-shipper

We have tested our usage of functionality in elasticsuite we will actually use and everything seems ok with that block commented out. So for now we are just going to run with it! Let me know if you have any additional questions about our setup.

**Comment by bmelman** [comment]
> As it turns out, this was a Anowave extension issue for me.

From anowave F.A.Q.: 
Pagination not working after recent update
This is all due to the new Elastisearch engine introduced in Magento 2.4 onwards. Our module is compatible with it, but there is a configuration change that needs to be done.

Go to Stores -> Configuration -> Anowave Extensions -> Google Tag Manager -> Enhanced Ecommerce Tracking preferences (section) and set Impression payload model to "Set dataLayer[] impressions AFTER Pageview". Once done, flush cache and everything should be back to normal. You may also notice a slight performance gain in categories as well.

This works for me :)
