### ISSUE TITLE
Virtual category string filter

### ISSUE THREAD

**Issue by gerrits-ecommerce** [Smile-SA/elasticsuite#2227]
One of our customers extensively uses the virtual category features of Elasticsuite to create filtered brand categories. They do this by creating new Virtual categories based on the category they wish to filter and applying a virtual rule where the brand attribute should contain a certain value.

Since brand is a text attribute the virtual rule only gives the contains and does not contain options. This filtering seems to be fuzzy however, and we regularly see brands like "Bose" contain products of the "Boss" brand (Or "Rode" containing products with the brand "Rod").

Is there a way to make an "Equals exactly" virtual rule on a text attribute?

**Comment by vahonc** [comment]
Hello @gerrits-ecommerce,

It's the default behaviour for the attribute with inputType like `text`. As an easy solution, you could try to play a workaround by changing a type of your attribute to `Dropdown` or `Multiple Select` and then create a virtual category based on it.

On the other hand, it's not easy to implement as a core feature of our module because it required a lot of customizations and have low priority for us.

BR,
Vadym

**Comment by gerrits-ecommerce** [comment]
Hey @vahonc 

Too bad this won't become a core feature. I've looked into it and found a workaround that works for us. By extending the getDefaultOperatorInutByType function in src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php and adding the '()' operator to the string input type we get access to the 'is one of' operator for strings. The name is a bit clunky as we do not enable this field as an array input type so you can only insert one string, but this operator does enable strict comparisons on strings without having to change our attribute type.

Thank you for the quick reply anyway!

BR,
Rik van der Heijden,
Gerrits e-commerce
