### ISSUE TITLE
searching across store views

### ISSUE THREAD

**Issue by ioweb-gr** [Smile-SA/elasticsuite#2251]
**Is your question related to a problem? Please describe.**
I would like to know if it's possible to use elasticsuite to search for a product accross store views. Here's my use case

I have a website in 2 languages Arabic / English (2 store views under the same website) 

I would like my search to provide results whether the user is searching in english product names or arabic product names. Currently when I'm in Arabic store I have to search for the product in Arabic only for the product to be shown in search results. If I use the English product name it's not found. 

Can elasticsuite help me in this?

**Comment by vahonc** [comment]
Hello @ioweb-gr, 

That's not possible, we create an index per each store view in the case of a multistore website. And elasticsuite searches for the data across the current store view.

BR,
Vadym

**Comment by ioweb-gr** [comment]
I see so to have this functionality only a workaround can be employed. Thank you for clarifying

**Comment by romainruaud** [comment]
Yes, maybe you'll want to add a loop for all store views here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L45

This would allow you to merge data across all store views into each separate store index.

That's not the most elegant but it will allow you to have arabic and english values duplicated on both indices.

I've explored the path that would consist in searching across both indices instead of one, and it appears to be way more difficult.

Best regards
