### ISSUE TITLE
error in GraphQL queries #1531

### ISSUE THREAD

**Issue by mohdaali27** [Smile-SA/elasticsuite#2280]
We are getting the internal error in graphql query in version 2.10.x . It seems the issue is fixed in previous version 2.8.x .
We are installing the extension in magento 2.4.3 and getting the same issue as - 
"fix: prevent internal error in GraphQL queries #1531"

**Comment by romainruaud** [comment]
Agreed, I think that PR #2236 is causing this.

This can be seen in integration tests also, at the "[Test] GraphQl : Schema" step like here (but it was failing silently :cry:  ): 

https://github.com/Smile-SA/elasticsuite/runs/3757737474?check_suite_focus=true

Moving the associated DI from the "webapi_rest" context to the global one seems to bring back the initial issue #1531.

Imho : 

- the GraphQL type locator should not be aware of this DI because it's causing failure. (to fix #1531)
- the REST Api type locator should be aware of this DI to avoid failure with REST API calls. (to fix #1298)

BUT : 
- adding this type locator in webapi_rest context only also causes some issues.

Maybe there is an other path we can take to have both GraphQL and REST working. Maybe we could just add a dummy field into the GraphQL schema.

@igorwulff do you have some insight about it ?

**Comment by romainruaud** [comment]
last release contains the fix. I close
