### ISSUE TITLE
Product with large description missing from search and categories

### ISSUE THREAD

**Issue by timpea** [Smile-SA/elasticsuite#2320]
Products with very large descriptions are missing from search results.  Works as expected with elasticsearch7, doesn't work when enabling elasticsuite.

Magento Version : 2.4.3 CE

ElasticSuite Version : 2.10.8

Environment : Both

### Steps to reproduce

1. Create product with a very large description, used lipsum.com to generate 100 paragraphs.
2. Search on front end for product

### Expected result

1. Should be visible in search and categories.

### Actual result

1. No results

**Comment by rbayet** [comment]
Hello @timpea,

Indeed, the issue is that text attributes have a subfield with a "keyword" analyzer which transmits the content "as is" to the search engine. For very large content, it might exceed a Lucene hard limit of 32766 bytes for a given token and the whole document is rejected at indexing time, hence why a product might go missing.

The fix contained in https://github.com/Smile-SA/elasticsuite/pull/2377 limit those text + keyword subfields to a length of 8192 characters (to accomodate with the fact that UTF-8 characters are multibyte, with the number of bytes varying according to language/alphabet).

Please note that the fix **does not** alter the ability to search for text located after that 8K limit in a description.

Regards,

**Comment by rbayet** [comment]
Note: not *really* needed in 2.8.x since the base field for text attributes **is not** using the keyword analyzer.
