### ISSUE TITLE
Add support/example of configuring elastic servers via env.php

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#233]
Hello!

Proposed sollution https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#optional--installing-the-module-when-using-a-custom-elasticsearch-server-location is not perfect - we hardcode server name inside module settings. It is better to configure it via env.php.

**Also add note that my module should be loaded after yours in config.php file, because config override wouldn't work otherwise.**

**Comment by Koc** [comment]
Another approach is not execute `$this->getIndexer('elasticsuite_categories_fulltext')->reindexAll()` inside setup. Allow install module, then configure via admin panel and run reindex after this.

**Comment by romainruaud** [comment]
Hello @Koc 

I dont understand why you consider adding values to the config.xml as "hardcording".

The purpose of config.xml is to **set default values**, which can be overriden later via the Store > Configuration panel.

This is not "hardcoding" for me, whereas putting config directly in the env.php is, because it cannot be changed by the administrator later, and need to deploy this file again.

The 'elasticsuite_categories_fulltext' is not alone to be guilty. Magento does process a fulltext reindex of the 'catalogsearch_fulltext' index when running a setup, which could crash too if the location of the elasticsearch server is wrongly configured.

For us, the config.xml is the best approach. 

But you are right, if using our workaround, your module must depend on our, to override properly the config default values. I will add this on the wiki today.

But for the main purpose of your issue, for me, it's a wontfix. I'll let @afoucret confirm.

Regards,

**Comment by Koc** [comment]
@romainruaud thank you for explanation. Have you consider do not connect to index when server is not yet properly configured (on installation step)?

**Comment by afoucret** [comment]
Hi @Koc,

The policy of connecting to ES, is consistent with Magento one.
Actually, even if we don't connect for our custom indices (categories, ...), Magento will trigger an full reindex while installing catalog search and the problem will remain. I have not looked very carefully, but I think the same problem is present in Magento EE ElasticSearch implementation ...

**Comment by Koc** [comment]
Some example of the using deployment config for locating connection credentials https://github.com/renatocason/magento2-module-mq-amqp/blob/master/Model/Client.php#L35

**Comment by Koc** [comment]
ref #692
