### ISSUE TITLE
Build layered navigation by id values instead of text values

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#238]
instead of filering by `option_text_pol.untouched`, `option_text_size_prostin1.untouched` and making aggregation by `option_text_dopolnit_komplekt_postel` we can use plain id attributes like `pol`, `size_prostin1`, `dopolnit_komplekt_postel`. It could be faster

```json
        "option_text_dopolnit_komplekt_postel": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "terms": {
                                "option_text_pol.untouched": [
                                    "\u041c\u0430\u043b\u044c\u0447\u0438\u043a\u0438",
                                    "\u0423\u043d\u0438\u0441\u0435\u043a\u0441"
                                ]
                            }
                        },
                        {
                            "terms": {
                                "option_text_size_prostin1.untouched": [
                                    "150\u0445214",
                                    "180\u0445240",
                                    "160\u0445240"
                                ]
                            }
                        }
                    ],
                    "must_not": [],
                    "should": [],
                    "minimum_should_match": 1,
                    "boost": 1
                }
            },
            "aggregations": {
                "option_text_dopolnit_komplekt_postel": {
                    "terms": {
                        "field": "option_text_dopolnit_komplekt_postel.untouched",
                        "size": "10",
                        "order": {
                            "_count": "desc"
                        }
                    }
                }
            }
        },
```

**Comment by afoucret** [comment]
We won't change our design for this feature for several reasons.

* The aggregation engine of ES is quite speedy even when aggregating text label with high cardinality. We have some catalog with millions of products and very high cardinality attributes. There is not really a perfomance bottleneck here.

* In the end, building facet on option_text grant the ability to have easily labels of the attributes in the filters URLs in front. It is better for SEO (?color=Red is better than ?color=12). 
If faceting was done on the id, we could rewrite the URL, but it would require to load the options of the attribute when building the facet. On high cardinality attributes catalog we would suffer from performance isssue. Additionnaly, we would have to proceed to a reverse mapping of the attribute label to option id to apply the filter, what is quite costly too.

I close the issue, since we will not move forward on it.
