### ISSUE TITLE
Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by Morgy93** [Smile-SA/elasticsuite#2393]
### Preconditions

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.8.1

Environment : production

Third party modules : Yes, many, any way to get a list easily?

### Steps to reproduce

1. Installed it
2. Enabled tracking
3. Used it
4. Throws error
5. I don't know much more currently, might update later

### Expected result

1. No exception

### Actual result

1. Sometimes an exception is thrown:
```
URL: https://domain.de/elasticsuite/tracker/hit/image/h.png
Error:
Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded

Trace:
#1 Magento\Framework\App\PageCache\Kernel->process() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:78]
#2 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#3 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#5 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#6 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#7 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

Any idea? I did not dig into this yet. Probably have to deploy some debugging code along with it. It does not trigger very often.

**Comment by vahonc** [comment]
Hello @Morgy93,

It is normal behavior that when some kind of conflict situation arises it generates an error throw. But I think that first of all, you should analyze if your environment does not contain any malware code, which may be somehow change all URLs or links.

Or maybe it linked to the wrong crypt key that decrypted some of the credentials into malformed characters, so please check the config with encryption, for example: token, password, etc.

BR,
Vadym

**Comment by rbayet** [comment]
Hello @Morgy93, 

Let me dial back down a bit the panic that @vahonc's last message might have provoked.

I fully support the first sentence : it is a good thing data containing Invalid/Malformed UTF-8 characters and generates an error that stops the normal process of an application.

Because, yes, *sometimes* it may be the sign of a penetration test. But it can also be the sign of invalid data that somehow has made his way into the application/database (corrupted Magento cache, truncated data imported in Magento from CSV data that lost things between charsets conversion, etc).

In this case, as the Elasticsuite tracker records the current URL and/or the referrer URL, any invalid UTF-8 character in a malformed URL (for instance a query parameters), but it could also be linked to truncated / invalid extra context query parameters.

The cautious approach is still the one that I would require : try to track the original of those call (by looking at the complete payload of the elasticsuite/tracker/hit/image/h.png), for instance in your Nginx/Apache logs.
That's the first step to determine if those calls are
- internal (a displayed web page on your site calling the tracking), that would tend to say that the invalid data is provided by the Magento app (but it still could have been injected there)
- or external (a bot calling the tracker on its own from the outside) : that's more fishy.

Feel free to report your findings here.

Regards,

PS: Even if you decide to disable the tracker to be "better safe than sorry", I would still advise to look into the origin of the calls and understand why they happen, other Magento controllers could be the "target" if it is indeed the original of the calls are malicious.

**Comment by Morgy93** [comment]
I just quickly checked the logs and 99% of the time it is triggered by the Google Image Bot:
```
"GET /elasticsuite/tracker/hit/image/h.png HTTP/1.1" 500 2829 "-" "Googlebot-Image/1.0" - ""
```

Just a single time a (probably) normal user triggered the error:
```
"GET /favicon.ico HTTP/2.0" 404 24662 "https://domain.de/elasticsuite/tracker/hit/image/h.png" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.45 Safari/537.36 Edg/97.0.1072.34" - ""
```

I'll take a deeper look, but since it's only Google, it doesn't bother me as much anymore. 😅

**Comment by Morgy93** [comment]
@vahonc @rbayet Any idea where I can add some debug code to get useful information out of it?

I tried the trace at `Magento\Framework\App\PageCache\Kernel->process() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:78]` and the `InvalidArgumentException` at `vendor/magento/framework/Serialize/Serializer/Json.php:26` but that did not help at all.

**Comment by Morgy93** [comment]
The url generates some strange non uft8 output:

![image](https://user-images.githubusercontent.com/7961978/151558556-133d1353-f409-4772-9784-90baaefd3d0e.png)

This is processed by `vendor/magento/framework/App/PageCache/Kernel.php` line 152:
```
$this->serializer->serialize($this->getPreparedData($response)),
```

Which throws the `Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded` error.

Now I just need a solution for this. Seems to be some cache issue?!

**Comment by romainruaud** [comment]
The tracking url is not supposed to display UTF-8 valid content but an empty pixel, like this : http://demo.magento-elastic-suite.io/index.php/elasticsuite/tracker/hit/image/h.png?page[store_id]=1&page[cms][identifier]=home&page[cms][title]=Home%20Page&page[type][identifier]=cms_index_index&page[type][label]=CMS%20Home%20Page&session[uid]=d834b94c-00e1-d740-7d71-13b480b75995&session[vid]=f1584913-ca93-b34d-539b-69a078233e33&page[site]=demo.magento-elastic-suite.io&page[url]=%2F&page[title]=Home%20Page&page[resolution][x]=1920&page[resolution][y]=1053

Which url are you opening in your web browser ? Can you give us more details ?

**Comment by Morgy93** [comment]
@romainruaud For example:

```
https://domain.cloud/elasticsuite/tracker/hit/image/h.png
?page[store_id]=1
&page[type][identifier]=catalog_product_view
&page[type][label]=Catalog%20Product%20View%20(Any)
&page[locale]=de_DE
&page[domain]=domain.cloud
&page[product][id]=6522
&page[product][label]=Somename%20II.Wahl%20-%2030mm%20Dach%20Anthrazit
&page[product][sku]=100596
&session[uid]=somehash123-8c46-d94f-7eb1-0628c13060fe
&session[vid]=somehash123-9-b2ea-643f-0e34011ccee4
&page[site]=domain.cloud
&page[url]=%2F21-72-m-somename-ii-wahl-30mm-dach-anthrazit.html
&page[title]=Somename%20II.Wahl%20-%2030mm%20Dach%20Anthrazit
&page[referrer][domain]=domain.cloud
&page[referrer][page]=%2Fsomename
&page[resolution][x]=1440
&page[resolution][y]=813
```

Results in:

![image](https://user-images.githubusercontent.com/7961978/154274472-80e1a21b-66f9-472f-9b54-32f6c080c973.png)

**Comment by rbayet** [comment]
Hello @Morgy93,

The result that you show in your exemple is the "body" of the expected response, which is the base64 decoded value of the invisible pixel of the tracker (https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-tracker/Controller/Tracker/Hit.php#L55), see below 
![image](https://user-images.githubusercontent.com/2353374/156336669-17d0db84-38f0-4574-add8-ecd9e1146f08.png)

I managed to reproduce your issue and it seems a third party module or a configuration option I haven't found is responsible because I had to pretend the HTTP response provided by the controller had a "public[...]max-age[...]"  `Cache-Control` header in \Magento\Framework\App\PageCache\Kernel::process 
```
    public function process(\Magento\Framework\App\Response\Http $response)
    {
        if (true || preg_match('/public.*s-maxage=(\d+)/', $response->getHeader('Cache-Control')->getFieldValue(), $matches)) {
            // $maxAge = $matches[1];
            $maxAge = $matches[1] ?? 400;
```
instead of 
```
    public function process(\Magento\Framework\App\Response\Http $response)
    {
        if (preg_match('/public.*s-maxage=(\d+)/', $response->getHeader('Cache-Control')->getFieldValue(), $matches)) {
            $maxAge = $matches[1];
```

On a Luma derived frontend, the "public" Cache-Control is only supposed to be set on "cacheable" pages (if the layout does not contain a "cacheable=false" block), see 
* \Magento\PageCache\Model\Layout\LayoutPlugin::afterGenerateElements
* \Magento\Framework\App\Response\Http::setPublicHeaders

Considering the elasticsuite/tracker is a layout-less controller, there should be no reason, on a native Magento, for  \Magento\Framework\App\Response\Http::setPublicHeaders to be called.
This method is also explicitely called for cacheable GraphQL queries and ESI blocks, see 
- \Magento\GraphQlCache\Controller\Plugin\GraphQl::afterRenderResult
- \Magento\PageCache\Controller\Block\Esi::execute

So my guess is either a third party module or a custom setting somewhere is responsible, you will likely find what the culprit by putting a debug breakpoint on \Magento\Framework\App\Response\Http::setPublicHeaders and backtracking from there.
But please let us know if it is tied to a native feature.

Regards,

**Comment by Morgy93** [comment]
@rbayet Thanks for your detailed feedback!

I can confirm that it seems to be something cache related, after several reloads it suddenly works.

It's not Luma, it is a [Hyvä](https://hyva.io/) frontend - maybe that's the issue here? (Even though ElasticSuite is said to be 100% compatible)

I'll try the breakpoint thingy and report back if I can get more information.

**Comment by Morgy93** [comment]
I found the culprit: https://github.com/yireo/Yireo_LinkPreload

Disabling the `Yireo\LinkPreload\Plugin\ResponsePlugin:beforeSendResponse` makes the page load fine.
Trace:
- Yireo\LinkPreload\Link\LinkParser:addLinkHeadersFromLayout
- Yireo\LinkPreload\Link\LinkParser:parse
- Yireo\LinkPreload\Plugin\ResponsePlugin:beforeSendResponse

I just don't know what the issue is exactly. 😅

**Comment by romainruaud** [comment]
I've opened an issue on their repo as well to check which side should improve :) 

regards
