### ISSUE TITLE
RFC: Provide custom sources

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#240]
For example we have blog and we want also add search inside blog. This is relevant for autocomplete and search results page. See example of architecture https://mirasvit.com/doc/ssu/2.3.4/ssp/indexes/custom from similar extension for M1

**Comment by romainruaud** [comment]
Hello @Koc and thank you for this question.

We are glad to see that you are planning to extend our module.

In fact, this is already possible to add additional content inside ElasticSearch via the module.

If you look closely on how is done the categories fulltext index, you'll see that it needs to add index settings via the elasticsuite_indices.xml file, like this : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L68

You will then have to add a custom indexer for your content, and also a custom collection relying on Elasticsearch for fulltext search (you can take a look on the Category Fulltext Collection and on its indexer).

I think we will add a more detailed "how-to" about creating a new index and adding custom content into it on the wiki. We will probably write the guide based on the indexing of CMS Pages example, so that it will be understandable by our fellow users.

I keep the issue assigned as a reminder to write this on the wiki.

Best regards, and thank you for asking this question.

**Comment by afoucret** [comment]
Hi @Koc,

As a complement of @romainruaud response, you can find an example of implementing additional sources (CMS page search) : https://github.com/Smile-SA/module-elasticsuite-cms-search.
It is quite old code and maybe not fully compatible with Magento 2.1.x and ElasticSuite last version.
We should write a developper oriented doc on this when we will have more time.

**Comment by Koc** [comment]
> We will probably write the guide based on the indexing of CMS Pages example
Awesome! thank you

**Comment by southerncomputer** [comment]
@afoucret 

https://github.com/kalenjordan/clean-elastic-search

I'd love to see this for backend search too!

**Comment by romainruaud** [comment]
Now covered in the Indexing part of the documentation : https://github.com/Smile-SA/elasticsuite/wiki/Indexing

Regards

**Comment by Koc** [comment]
Ooh, not so easy. Will try to add own indexer.

Thank for detail explanation.

Can you also cover inside docs how add to autocomplete provider? https://github.com/Smile-SA/module-elasticsuite-cms-search/blob/master/etc/frontend/di.xml#L17

**Comment by LiamKarlMitchell** [comment]
Wiki/docs say ```You can declare a new elasticsuite_indices.xml file in your module if you plan to index other entities.``` but does not give an example of how to do this.

I assume we make a file with the same name in the etc directory.
