### ISSUE TITLE
The elastic suite is not working with two projects on the same server.

### ISSUE THREAD

**Issue by mgoswamirave** [Smile-SA/elasticsuite#2406]
The elastic suite is not working with two projects on the same server.

### Preconditions

Magento Version : 2.3.7-p2 EE (B2B)

ElasticSuite Version : 2.9.0 

Environment : Production

Third party modules : No

### Steps to reproduce

1. Configure Elasticsuite for the first project which is working fine and we getting the expected result.

![image](https://user-images.githubusercontent.com/87437246/147493568-d06eea11-5e7a-485e-81ac-ea278a779629.png)

2. But the second project Elasticsuite is stopped working once the first project Elastisuite is working fine.
![image](https://user-images.githubusercontent.com/87437246/137255448-4f13716b-a2e1-4246-8675-884164dfc679.png)

### Expected result

1. Elasticsuite should work for both projects on the same server.

### Actual result

1. Elasticsuite is only working for one project, not for both projects on the same server.

**Comment by vahonc** [comment]
Hello @mgoswamirave,

This issue is a little bit blurry for me. What do you mean when you say "two projects on the same server", these are two different projects with different URLs (databases, admin panel, etc), or these are two websites (multi websites) under one project.

BR,
Vadym

**Comment by mgoswamirave** [comment]
Hello @vahonc,

Thanks for the help.

These are two different projects with different URLs (databases, admin panel, etc) but the Elasticsuite is working only for either project.

**Comment by vahonc** [comment]
@mgoswamirave,

Elasticsuite it's not a global tool like for example Elasticsearch. So you need to install and configure our module on each of your projects.

BR,
Vadym

**Comment by mgoswamirave** [comment]
Hello @vahonc,

We have installed the Elasticsuite for both the projects and have configured each project separately but we are getting search results in either of the projects, not for both the projects.

**Comment by vahonc** [comment]
@mgoswamirave,

Well, at this moment it's hard to say what exactly caused your issue because it could be anything. So we need more details (screenshots) about your configuration.

Are you sure that on the second project the Elastisuite is properly installed and configured and everything is reindexed?

Please check logs or try to enable Debug mode in the Elasticsuite configuration. 

It also could be linked with a configuration of Elasticsearch on your server.

BR,
Vadym

**Comment by mgoswamirave** [comment]
Hello @vahonc,

We checked the Magento logs but we did not get any error related to Elasticsuit. We are sharing the configurations of both projects. Please check and let us know if any other information is required.


Project 01 :
![image](https://user-images.githubusercontent.com/87437246/147777661-604fe3b8-1943-4d53-8df8-96084af45cf1.png)
 


Project 02 :
![image](https://user-images.githubusercontent.com/87437246/147777745-4b82e0b3-2f50-439f-90dc-575d1ce0cef6.png)

**Comment by vahonc** [comment]
@mgoswamirave,

Please provide the configuration of Elasticsearch Client as it shows on the screenshot below:

![Screenshot from 2021-12-31 12-48-51](https://user-images.githubusercontent.com/67791361/147819349-b0a32eaf-d027-4e87-86a6-a18f755a7732.png)

Also, check if your ElasticSearch is properly installed and running on both projects:

`curl -XGET 'http://localhost:9200' //or paste your alias name`

Check ElasticSearch Logs: `/var/log/elasticsearch/`

Provide config files for ElasticSearch for both projects: `cat /etc/elasticsearch/elasticsearch.yml`

Also, you could enable logging ES queries in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode` and the queries will be logged into the `system.log`

BR,
Vadym

**Comment by rbayet** [comment]
Hello @mgoswamirave,

**If you have two Magento2 projects/environment sharing the same Elasticsearch server**, please check that you have two different indices prefix/alias names configured in "Stores > Configuration > Elasticsuite > Base Settings > Indices Alias Name", otherwise you risk one project overwriting the index data of the other.

![image](https://user-images.githubusercontent.com/2353374/147907094-31b64491-005b-4562-8c86-ee017fb1639d.png)

The Indices Alias Name is used as a prefix for naming the indices, for instance on a default Luma installation, the catalog indices will be named 
- magento2_default_catalog_category_[timestamp] (index alias: magento2_default_catalog_category)
- magento2_default_catalog_product_[timestamp] (index alias: magento2_default_catalog_product)
("default" being the store code)

So there is the possibility your issue is that 
- you have a single Elasticsearch server/cluster for both Magento2 projects
- both Magento2 projects are in a single store mode with a similar default store code
- you have not changed the Indices Alias Name value

See also https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings

Regards,
