### ISSUE TITLE
manual sort not reflecting on frontend

### ISSUE THREAD

**Issue by joebassi** [Smile-SA/elasticsuite#2420]
### Preconditions

Centos 7, Apache 2, MariaDB, Redis cache on aws cloud

Magento Version :2.4.2-p1

ElasticSuite Version : 2.10.4

Environment : Production Mode

Third party modules :
Amasty: Google Invisible Captcha
Amasty: Custom Forms
Thai_S3, LiveChat

### Steps to reproduce

1. In admin, we set couple products to manual sort (pushing them to first 2 in list) on a particular category and save, in admin it saves fine, but on frontend it does not show the order that we see in admin
2. We have re-indexed, flushed cache, but still the frontend does not reflect admin
3. This category has 2 children categories as well, and we have tried manually sorting the children products as well and same issue

### Expected result

1.  The sorting order of the products on frontend should reflect how we have them in admin.

### Actual result

1. 
![image](https://user-images.githubusercontent.com/3721939/149030239-90d7dba0-69b6-4e1f-8de4-dcd84a32593c.png)

**Comment by vahonc** [comment]
Hello @joebassi,

Usually, manual sorting works in the frontend as we would expect, at least when using the default Magento theme like Luma. Therefore, the first possible cause of your issue may be using a custom theme, in this case, if it's possible, try switching to the default Luma theme and check if the problem is still present. Also, another reason for this problem may be the setting of sorting products in a category by Name or by Price, by default the sorting should be by Position.

BR,
Vadym

**Comment by romainruaud** [comment]
@joebassi what is you sort order in frontend ? Manual sorting only applies when products are sorted by "position".

Considering the fact that even the other products seems to be different, I suspect the sort order that is applied in frontend is not "position" but something else.

Regards

**Comment by joebassi** [comment]
It is set to sort by position and we also tried switch back to default Luma theme, but the issue still exists
![ElasticSuiteSortByPosition](https://user-images.githubusercontent.com/3721939/150585132-de0481c1-183d-452d-97aa-41c89ae5287e.png)
.

**Comment by romainruaud** [comment]
According to our offline email exchanges, this seems to be a project specific issue.

Exchanges are expected to be pursued by mail.
