### ISSUE TITLE
Optimizer is not working on image contains

### ISSUE THREAD

**Issue by Viinz** [Smile-SA/elasticsuite#2435]
On the optimizers I want to boost products with real images and no placeholder, but it's boosting all products even with placeholder. 

### Preconditions

Magento Version : 2.4.2 Commerce cloud

ElasticSuite Version : 2.10

Environment : Production and developer mode

Third party modules :
        "smile/elasticsuite": "^2.10",
        "smile/module-elasticsuite-cms-search": "^2.2",
        "smile/module-elasticsuite-quick-order": "^2.10",
        "smile/module-elasticsuite-shared-catalog": "^2.10",
        "smile/module-retailer": "1.2.9.1",
        "smile/module-store-locator": "^2.0",

### Steps to reproduce

1. Create a new optimizers
2. Boost products that not contains placeholder name (in my example :  `zz_Master_6e52.jpg`)
I also tried with `* zz_Master_6e52.*` and `% zz_Master_6e52%`.
I also tried with negative boost on image containing zz_Master_6e52.jpg
I also tried with `Only products with image`
3. Preview
![image](https://user-images.githubusercontent.com/3815871/152191710-b90fe943-e7fe-4522-b503-346e14e4ecd4.png)

### Expected result

1. Product with real images should be first

### Actual result

1. Product with placeholder is boosted
![image](https://user-images.githubusercontent.com/3815871/152193675-5c4f6bf1-6bdf-442f-b91f-7c00a312d0f3.png)

**Comment by vahonc** [comment]
Hello @Viinz,

Firstly, if you are using the version of ElasticSuite 2.10 I recommend to you update it to the latest version (2.10.9), cause always better to have an up-to-day version.

Also, according to your screenshot, I guess that you are using some custom attribute for Image. In your case, it's **Image (image)**, but default attribute is **Base (image)**. It's true?

However, I tried to reproduce your issue by creating an optimizer for boosting products with real images. I use a custom placeholder image and try to add a rule condition that uses or doesn't use the name of this placeholder. In this case, I also can't get the expected result.

Then I tried to add a condition like `Only products with image` and as a result product with a placeholder appears at the end of the products list. Here are some screenshots from my test environment.

- I create two test products, one with a real image and one without a real image, so for this product was used a custom placeholder from **Product Image Placeholders** configuration:

![Screenshot from 2022-02-07 14-52-07](https://user-images.githubusercontent.com/67791361/152797224-f1b2815b-ee67-44f2-9a20-546313ff22e6.png)

As you can see, since these products are new, they appear at the top of the products list.

- After that, I create an Optimizer and use condition like `Only products with image`:

![Screenshot from 2022-02-07 14-53-14](https://user-images.githubusercontent.com/67791361/152797665-e575caf2-b2f2-40a0-a476-1ea2e2d26bfb.png)

- Finally, I checked the result on the frontend:

![Screenshot from 2022-02-07 14-53-48](https://user-images.githubusercontent.com/67791361/152797876-47940a3d-aa1b-4ae6-af80-e72bdb84fa64.png)

And product with the real image appears at the top of the products list and product with a placeholder goes to the end of the list.

Therefore try to use condition like `Only products with image` in your Optimizer and check results on the frontend.

BR,
Vadym
