### ISSUE TITLE
 Custom attribute filterable with no result

### ISSUE THREAD

**Issue by webcreative24** [Smile-SA/elasticsuite#2439]
Hello. I'm trying to add a custom attribute to the f filter with the 'filterable with no results' option, dropdown type. It must be visible in the filter even if it is not set in any product. 

If in any product from this category I select any option from my custom attribute then this filter and the selected option will be visible. the task is to force the output of the filter and all options. 
Is it possible to do this with your module?

**Comment by vahonc** [comment]
Hello @webcreative24,

First of all, to be able to work with any custom attributes, you need to add your attribute to some existing Attribute set that is designed for a particular category or add it to the Default set.

![Screenshot from 2022-02-10 13-11-24](https://user-images.githubusercontent.com/67791361/153395749-194d2ec9-e9ca-4abb-93d2-cef2fea12762.png)

However, in order to display your attribute on the frontend, you need to assign your attribute options to specific products. At the moment, our module does not have the ability to display those attribute values/options that are not assigned to products.

![Screenshot from 2022-02-10 13-23-27](https://user-images.githubusercontent.com/67791361/153398655-2182c88e-c895-4eff-987f-717201c34238.png)

![Screenshot from 2022-02-10 13-35-50](https://user-images.githubusercontent.com/67791361/153401225-01acc1a2-828b-4b09-8b91-5438228fedd7.png)

![Screenshot from 2022-02-10 13-26-13](https://user-images.githubusercontent.com/67791361/153398900-42e8a884-0d2b-4472-8b89-ab91e70182e4.png)

Feel free to ask more questions if my explanations are not clear enough for you.

BR,
Vadym
