### ISSUE TITLE
Search & Autocomplete Optmizers based on Grouped Product Attribute Value not working

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#2456]
We are experiencing an issue when we are trying to create an optimizer that promotes products that contain a specific string to the top of the search results.  In this case, we have a cup store, that also sells straws, so anytime a user searches any of the search terms relating to straws, we want to promote products that have "Short Straws" in their name.    However, upon making the update, the preview and subsequently the front-end are not affected.  

### Preconditions

Magento Multi website - Not sure if it's relevant 
Adobe Cloud 

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.9.1

Environment : Production 

Third party modules : Hyva Themes, Blue Jalapeno Tiered Pricing, and a few others.  However, we were able to reproduce the issue in clean Magento only with ElasticSuite installed 

### Steps to reproduce

1. Create Products "Standard Straw, Curly Straw, Short Straw, Pet Hamster" 
2. All Products should be of the "Grouped Product Type" and contain a few child items. **Edited - the issue was that the child items of "Short Straw" had the name of "Small Straw", but I believe the Grouped Product's weight should be considered in addition to the child. 
2.  Create an Optimizer for all search terms that contain "Straw" 
3. Set mode to Catalog Search / Search Auto Complete 
4. In Actions, select "Product Name" "contains" "Short Straw" 
5. Click Preview after entering the search term "Straws" 
6. Boost Value is set to 100% / Any change here does not impact the result. 

### Expected result

1. I'd expect to see all "Straws" at the top of the list, but specifically I'd expect to see "Short Straw" first since it was targeted with the rule. 
2. Edited I believe that grouped products attribute data should impact sort order in conditions where "product name" is used and it's an exact match. 

### Actual result

1. https://watch.screencastify.com/v/muABUYbP6vpXZTDMHECd
2. No Change occurs 

As an important note, I changed the type from Search / Autocomplete to Catalog and tested the preview and everything worked as expected.  This appears to be an issue specific to the search optimizer.   

### Edited
We found the issue, however, I believe the bug is still valid just slightly different.  Attribute data of Grouped Products are not considered within optmizers.  Only their associated children, when only Grouped products are available in search, essentially makes the "Preview Feature" inaccurate.

**Comment by duffner** [comment]
Ok, I wanted to add what I believe is a second bug that I've discovered during this process.  I just found out that, not only was there a grouped Product issue, but when using the selected Search Terms from the list, they are not case sensitive, but the preview feature is.   So the search term "Straws" was selected from the list, but I was using the term "straws" in the preview and I guess they don't match.  If someone agrees that this is another issue, I'll file a separate ticket.

**Comment by vahonc** [comment]
Hello @duffner,

Your problem is a little blurry for us, especially after your edit. Yes, we have some issues related to Optimizers based on Grouped Product at the moment we take into account values from child products, but not from parent products.

We are working on fixing this and it will be included in future releases.

BR,
Vadym

**Comment by rbayet** [comment]
Hello @duffner,

I'm trying to understand the issue through your edits and it's a bit blurry, for instance, I think there is at least a verb/word missing in your last sentence
>  Only their associated children, when only Grouped products are available in search, essentially makes the "Preview Feature" inaccurate.

I will backtrack a bit and try to summarize what happens with regards to composite products (bundle, grouped and configurable products) : 
- Elasticsuite indexes **enabled** children product data into the parent product 
- **but** we exclude certain child attributes to avoid generating too much noise

The list of excluded child attributes of the children of a composite products is defined statically in [\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\AttributeData](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L34) : 
- visibility,
- status,
- price,
- tax_class_id
- **name**

So, logically, the situation you described where a grouped product was not matched by the optimizer "Name contains X" where X was present **only** in the name of one of the child product of that grouped product is the expected behavior of Elasticsuite as it stands.

The fact that the 'name' attribute is ignored might be a "configurable product" centric approach 
- children of configurable products are usually not visible individually and usually share most of the same name as the parent product 
- children of grouped and bundle products are usually visible individually and there is a high chance that searching for a term of their name might also perform a hit on their 'description' attribute (if indexed) which **will** be collected into their parent product indexed data, hence increasing the likelyhood of showing both the individual product and the composite product containing it

[A current issue](https://github.com/Smile-SA/elasticsuite/issues/2438) being worked on will likely lead to the avaibility to change by DI the hardcoded (and in a private var) list of "forbidden children attributes".
If you need more flexibility (for instance, differenciating the behavior/list of forbidden children attributes according to the product type) the \Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\AttributeData class is declared as a datasource and thus [can be overriden through the DI mechanisms](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/di.xml#L319).

Regards,
