### ISSUE TITLE
Virtual Category Preview does not work in certain cases

### ISSUE THREAD

**Issue by TiEul** [Smile-SA/elasticsuite#246]
Hey,

we have some cases where the preview in the Magento 2.1 back-end shows that "Your product selection is empty.", yet the virtual category actually works fine and contains products as expected on the end-user front-end. 

For example, we have one case where the virtual rule is:

```
If ALL of these conditions are TRUE: 
    Product Name contains gloves
```

On the front-end, all products fitting this description are shown, but the back-end claims that there are no such products to be found.

**Comment by romainruaud** [comment]
Hello @TiEul 

This is a known limitation (and we have already answered it for your project). 

This is due to the fact that, when previewing a virtual category on admin, with the scope set to "Default Store View", the module tries to use "Default Store View" for rendering (but if the Default Store View is available : if the current category exists on this store view).

If the Default Store View is not available for the current category, an other store view is chosen randomly between all the store view the current category is associated too.

Are you using "Default Store View" as scope when previewing the category ? If it's the case, you should switch to the dedicated store view you are trying to preview.

Regards,

**Comment by TiEul** [comment]
Hey @romainruaud,

thanks, that works indeed, I was not aware of this. Maybe as a suggestion, the error message should be changed from "Your product selection is empty." to something like "Your product selection is empty for the selected store view.", that would probably help avoid some confusion for users.

Regards,
Tim

**Comment by afoucret** [comment]
Hi @TiEul,

@romainruaud and me will have a look at this one in the early of January.

Maybe should we write a better guide about Virtual Category feature and multi-store setup.
Especially when using localized (eg store view scoped) attributes. As virtual category are global attributes, our preconisation will be to use separate categoriy trees for such a setup (one per website).

Having a better "notification message" and a pointer to the documentation can definitely be helpful for the admin users ...

BR,

**Comment by romainruaud** [comment]
The wiki entry was added in last release : https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories#previewing-virtual-categories-on-a-multi-store-setup

 So does the "explicit message".

I close this issue then.
