### ISSUE TITLE
Pagination doesn't work if change order of block rendering

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#249]
Hello! I am using version 2.3-dev

Steps to reproduce issue:
1. change block order in layout: make layered navigation render before product list
2. go to page 2
3. when layered navigation starts render it produces query to elastic with limit 20, offset 0 (AFIK this occurs because `ListProduct::_beforeToHtml`, `Toolbar::setCollection` haven't called on this state)
4. we got an error like "no products found for your query".

**Comment by Koc** [comment]
Not sure that this problem is caused by your module, looks like Magento limitation ( https://github.com/magento/magento2/issues/7253 ), but can you check and suggest a workaround, please?

**Comment by romainruaud** [comment]
Hello @Koc and thank you for submitting this question.

I'm afraid but as it is clearly due to coupling between ProductList and Toolbar block in Magento's core, and has nothing related to ElasticSuite (it fails on a raw Magento2 instance too) we won't be able to provide any workaround or fix for this one.

Since the issue is already tracked by Magento all we can do is to wait for them to provide a fix.

Best regards,

**Comment by Koc** [comment]
As workaround I can suggest only cnahging markup or moving blocks using JS :(
