### ISSUE TITLE
Product attributes cannot be edited

### ISSUE THREAD

**Issue by leedyche** [Smile-SA/elasticsuite#2536]
In the backend of magento I cannot edit any product attributtes, this is down the the file 

src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml

Causing a javascript error on page load. I do not know if this is due to customisation on my site or if it is a general problem for version 2.4.3 but im posting here as it might help others.

I have created a fix that works on my site, you can see the change I made here:

https://github.com/leedyche/elasticsuite/commit/3b760d31ad20406a130f2adc89ba5f12403f404c

### Preconditions

Magento Version :2.4.3 (cloud)

ElasticSuite Version :2.10.9

Environment :Production

Third party modules :

### Steps to reproduce

1. Login to the backend
2. Go to Stores -> Attributes -> Product
3. Edit any Attribute or try to add a new one
4. The page loads, but a javascript error is on the console and the save buttons do not work

### Expected result

1. should be able to edit and create new attributes

### Actual result

Console error 
![image](https://user-images.githubusercontent.com/19292907/164456712-cd274751-21d1-4241-bfc4-4f44c6c28919.png)

**Comment by vahonc** [comment]
Hello @leedyche,

I was not able to reproduce your issue on my test environment with fresh Magento 2.4.3-p1 and ES 2.10.9. I didn't notice any error in Dev Tools Console during creating or updating product attributes.

Maybe your issue is related to some third-party modules that have some conflicts with ES. Could you please share a list of installed modules? Also provide some screenshots of how to look Creating/Updating page in Magento BO. Maybe there are some extra tabs or fields on those pages.

BR,
Vadym

**Comment by romainruaud** [comment]
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml#L39

We only copy-pasted this part from legacy Magento code.

Please provide the details asked by Vadym. Regards

**Comment by rbayet** [comment]
Hello @leedyche,

In particular, did you disable the Magento_Swatches module ?

Regards,
