### ISSUE TITLE
Price Filter showing wrong minimum prices

### ISSUE THREAD

**Issue by ollyijb** [Smile-SA/elasticsuite#2559]
The Price filter doesn't appear to be working with configurable products.  Sometimes the minimum price is display -£2 or more commonly £0.  If I restrict the filters to lower prices than available products are still showing.  It looks like these are the configurable products.  Perhaps it is getting the price of the parent which is "null" instead of the configurable's simple product?

### Preconditions

Magento Version : 2.4.3-p1 CE

ElasticSuite Version : 2.10.9.1

Environment : Production

Third party modules :

        "aheadworks/module-advanced-reports": "2.11.0",
        "aheadworks/module-coupongenerator": "1.2.7",
        "aheadworks/module-followupemail2": "2.2.5",
        "amasty/adminactionslog": "~2.0.2",
        "amasty/promo": "~2.10.0",
        "amasty/shippingtablerates": "1.9.2",
        "amasty/shiprestriction": "~2.5.5",
        "clearpay/module-clearpay": "3.4.3",
        "fooman/pdfcustomiser-m2": "8.6.0",
        "loqate/tag": "~2.0.10",
        "magefan/module-blog" : "~2.10.3",
        "mageants/module-fastorder": "2.0.7",
        "magepal/magento2-googletagmanager":"~2.7.0",
        "mageplaza/module-gift-card": "4.1.1",
        "mageside/module-subscribe-at-checkout": "1.1.6",
        "sirv/magento2": "~5.0.0",
        "outeredge/edge-magento-module-reportunsoldproducts": "~2.0.1",
        "outeredge/magento-base-module": "~2.6.34",
        "outeredge/magento-lead-sources-module": "~1.0.0",
        "outeredge/magento-reviews-module": "~1.0.5",
        "outeredge/magento-structured-data-module": "~2.2.23",
        "smile/elasticsuite": "~2.10.3",
        "snowdog/theme-blank-sass": "~1.5.0",
        "stripe/module-payments": "2.7.5",
        "web200/magento-elasticsuite-autocomplete": "~0.4.6",
        "wyomind/datafeedmanager": "~11.20.0",
        "xtento/orderexport": "2.14.6",
        "xtento/module-stockimport": "2.11.7",
        "amasty/xnotif": "~1.13.2",
        "olegkoval/magento2-regenerate-url-rewrites": "~1.6.0",
        "snowdog/module-menu": "~2.18.0",
        "amasty/ajax-scroll": "~1.4.4",
        "amasty/gift-wrap": "~1.5.0",
        "bitexpert/magento2-force-customer-login": "~4.1.0",
        "outeredge/magento-bulk-actions": "~1.0.1",
        "yireo/magento2-emailtester2": "~1.6.19"

### Steps to reproduce

1.  Have a page of configurable products and filter by a low price
2.  Results display and the minimum price is set to £0

### Expected result

1.  Should have the lowest price filter as the lowest priced product and not show products outside of the pricing boundaries

### Actual result

<img width="298" alt="Screenshot 2022-04-04 at 16 40 14 (2)" src="https://user-images.githubusercontent.com/67915143/167624726-75f19446-bd27-497b-a929-15c49df66570.png">
<img width="293" alt="Screenshot 2022-04-04 at 16 40 01 (2)" src="https://user-images.githubusercontent.com/67915143/167624735-5907fd68-a4f1-4da6-abba-a10544ca3587.png">
<img width="811" alt="Screenshot 2022-04-04 at 16 44 35 (2)" src="https://user-images.githubusercontent.com/67915143/167624739-1a3edebb-4245-4732-866b-76f7d556dff6.png">

**Comment by vahonc** [comment]
Hello @ollyijb,

It's strange to see negative prices in the price filter. We haven't had any pricing issues for configurable products using the default Magento sample data. You could try to check how it works on our [demo site](http://demo.magento-elastic-suite.io/index.php/women/bottoms-women/pants-women.html). 

It seems that your issue is linked with a data problem, a bad/specific configuration of the prices, or something like that. 
Therefore we need some details from your environment. Please check and provide us with how it deals with the prices of products in your database by retrieving output from this table `catalog_product_index_price`. 

![Screenshot from 2022-05-12 16-38-44](https://user-images.githubusercontent.com/67791361/168089151-948fe34b-d240-4288-8634-a64a5eb6a968.png)

Maybe you should check if you have some rules for prices based on the Customer groups?

Also, provide info with screenshots about the configuration of your configurable products and give us an extract of the queries that are being sent to ES when you are browsing categories. You can get it from the `system.log` file if you activate the Debug mode of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`.

BR,
Vadym
