### ISSUE TITLE
admin - category page is hanging

### ISSUE THREAD

**Issue by akosglue** [Smile-SA/elasticsuite#2568]
When we want to open a category page via admin, this request keeps hanging:
/virtualcategory/category_virtual/preview/ajax/1/store/1/?isAjax=true

### Preconditions
A category tree is created

Magento Version : M2 2.4.3

ElasticSuite Version : 2.10.10 also 2.10.9

Environment : prod and dev

Third party modules : multiple

### Steps to reproduce

1. try to open a category page via admin
2. page keeps loading
3. in console: aforementioned ajax call is hanging

### Expected result

1. ajax request returns something

### Actual result

1. no response

**Comment by vahonc** [comment]
Hello @akosglue,

I don't see any issues with opening a category page via Magento BO on my test environment. Probably, your issue is linked to some third-party modules, try to disable some of them (if it's possible).

Also, try to investigate in Console where is the source of the problematic ajax call and check Magento logs.

BR,
Vadym
