### ISSUE TITLE
Replace "a" link by "button"

### ISSUE THREAD

**Issue by eBusinessAtlantique** [Smile-SA/elasticsuite#2569]
In attribute filters for price, the OK button is a "a" link.
It is better for SEO and CSS rules to have a button.
It is located in 
src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/slider.phtml
Line 28-30.
Replace "a" by "button"
I didn't dig into other files so other changes can be nice too.
Thanks for this great module !

**Comment by vahonc** [comment]
Hello @eBusinessAtlantique, thanks for your feedback.

In fact, I don't think we should replace the HTML `<a>` tag with `<button>` because many users have probably already defined some CSS rules for this element. 

Buy the way, `<button>` is usually used to submit a form, but there is no form on this page, so if we will do some changes here we probably have to do something "hacky" to make the button redirect to an URL. Imho, this is not a good idea. 
All other filters have `<a href=...>` because when you apply them, you go to another page.

For the time being, these changes are of low priority for us, so we may come back to this later.

BR,
Vadym

**Comment by romainruaud** [comment]
As explained by Vadym, we do not plan to change this actually due to this being legacy and probably re-styled for every existing Elasticsuite installs.

Since our templating system is open, you can do such replacement for you projects if you feel the need to.

regards
