### ISSUE TITLE
Categories sorting is reset after saving the category

### ISSUE THREAD

**Issue by abasanskii** [Smile-SA/elasticsuite#2578]
### Preconditions
Magento ver. 2.4.3-p1 EE
ElasticSuite Version : 2.10.9.1
Elastic Search Version: 7.10.2
Environment : Production

### Steps to reproduce
1. Open Magento admin panel.
2. Go to Catalog > Categories.
3. In the left sidebar change the position of a 3rd level category using drag-and-drop.
4. In the modal window with 'This operation can take a long time' warning click 'Ok'.
5. Wait for the operation to complete successfully. 
6. Click 'Save' for the category. 
7. Wait for the save action to complete successfully.
8. Pay attention to the categories sorting in the left sidebar.

### Expected result
Updated sorting of the categories is preserved in the left sidebar and reflected on storefront.

### Actual result
Sorting of the categories in the left sidebar is reset.

**Comment by vahonc** [comment]
Hello @abasanskii,

First of all, I'm not sure if your issue is caused by our module. You can check this by temporarily removing our module (if it's possible) and trying again to change the order (sorting) of the categories.

However, I tried to reproduce this issue according to your steps. Unfortunately, on my test environment (fresh Magento 2.4.3-p1 EE with default sample data and ElasticSuite 2.10.9.1), I did not notice any problems with changing the category sorting using drag-and-drop.

Here're my steps with screenshots:

1. Open Magento admin panel.

2. Go to Catalog > Categories.

3. Order the category before changing of sorting (**Hoodies & Sweatshirts** category on 2nd position).

![Screenshot from 2022-05-30 15-54-50](https://user-images.githubusercontent.com/67791361/170996807-719439d4-ce93-4015-b646-1c553fc94646.png)

4. In the left sidebar change the position of a 3rd level category using drag-and-drop. (**Hoodies & Sweatshirts** category is moving on 1st position).

5. In the modal window with 'This operation can take a long time' warning click 'Ok'.

6. Wait for the operation to complete successfully.

![Screenshot from 2022-05-30 15-23-51](https://user-images.githubusercontent.com/67791361/170994854-a9499dfa-cc24-43fe-b812-470c1129f6d4.png)

7. Click 'Save' for the category.
 
8. Wait for the save action to complete successfully.

![Screenshot from 2022-05-30 15-26-03](https://user-images.githubusercontent.com/67791361/170995280-74b223d8-98bc-4ebc-8f30-853af90b6591.png)

9. Check categories sorting in the left sidebar and result on the front-end.

![Screenshot from 2022-05-30 15-27-05](https://user-images.githubusercontent.com/67791361/170995442-d8b567a1-28b6-445f-b993-000a03a79b3b.png)

I guess that smth is wrong on your environment, try to check errors in the Console of your browser or clean the Magento cache.

BR,
Vadym

**Comment by abasanskii** [comment]
Hi vahonc,
We will try to disable the module and will follow up back.
Thx!
