### ISSUE TITLE
Virtual products breadcrumbs

### ISSUE THREAD

**Issue by ajzele** [Smile-SA/elasticsuite#2601]
Hi team,

I was wondering if there is a solution for having properly generated breadcrumbs for virtual categories?

Since they do not have entries in `catalog_category_product` table, and entries in `smile_virtualcategory_catalog_category_product_position` table are only for when manual position sorting is applied.

Or, are there any hints in that direction for how to approach the breadcrumb problem?

**Comment by romainruaud** [comment]
Hi @ajzele 

can you please describe more what you are willing to obtain, and what is currently happening ?

Regards

**Comment by stijnkuppens** [comment]
Hello [romainruaud](https://github.com/romainruaud),
we are trying to get a full breadcrumb path when you are landing on a PDP directly. So when a customer clicks on a product detail page from google, you don't see any breadcrumbs, since magento does not have the path data available. Since we are using mostly only virtual categories, this is almost true for every product.

**Comment by romainruaud** [comment]
@stijnkuppens 

Can you please give an example of a virtual category containing products, and some of those products. If you have a live URL it's even better.

Can you please also give us what is the URL reached by the customer from Google ? 

Is it something like http://www.website.com/sales/men/top/red-tshirt.html or http://www.website.com/red-tshirt.html ?

Regards
