### ISSUE TITLE
sorting error

### ISSUE THREAD

**Issue by bangln** [Smile-SA/elasticsuite#2617]
Attribute sorting result in product listing page of magento 2 is not correct.
this issue occurs with group and bundle product. i sort by name but it is result: https://imgur.com/a1iezzo. it hs sort by child product of group product

Magento Version : 2.4.3-p1 Magento CE
ElasticSuite Version : 2.10
Environment : developer mode
Third party modules :NO

**Comment by romainruaud** [comment]
Hi,

if the "name" attribute is merged from children in parent products, this can cause such behaviors.

Since recent modifications, this attribute should be excluded : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/di.xml#L216

Can you please provide the exact version of Elasticsuite you are using ?

Regards

**Comment by bangln** [comment]
tôi sử dụng phiên bản 2.10

**Comment by vahonc** [comment]
In this case, I'm closing this issue.
