### ISSUE TITLE
autocomplete count result issue

### ISSUE THREAD

**Issue by bangln** [Smile-SA/elasticsuite#2625]
I have a problem with count result:
I type tiguar and its show 26 results:https://i.imgur.com/OCPg0kQ.png  but its have 27 results? https://i.imgur.com/XS2o5ga.png
you can check in https://sklep.yes2move.com/ almost key search got this problem
regard!

**Comment by vahonc** [comment]
Hello @bangln

First of all, please respect the issue template and give detailed steps about how to reproduce the issue?

Otherwise, it's unlikely someone from the team will have a look at it.

As for your issue, probably it's something specific to your project because normally all is fine with it. So please check qty, visibility and prices of your products, make re-index and clear cache.

Or provide more details on how exactly we could reproduce your issue. 

Regards

**Comment by bangln** [comment]
First of all, I sincerely apologize for not following the issue template!

I checked DB and see that query search olimp odzywka has 16 results https://i.imgur.com/7ouKLLM.png from 2021. Search bar on frontend will show 16 results.

When search, DB is updated https://i.imgur.com/ODwj81U.png => no result. 

Magento version: CE 2.4.3-p2
Elasticsuite version: 2.10
enviroment: production
3rd-party module: no
Regards

**Comment by rbayet** [comment]
Hello @bangln,

The number of results shown in the autocomplete block for popular search terms are indeed pulled from the "search_query" table.
If you've just switched to Elasticsuite, it might contain "old" popular terms with a number of results that could be a bit different between the previous search engine you used and Elasticsuite.
Elasticsuite **does not** execute a query for each popular term to get an accurate "live" results count.

The number of results associated to a search term is indeed updated natively by Magento after a fulltext search (hitting enter to go to the results page).
That would explain your first example.

I'm not sure I understand the issue and/or its origin for your second comment :
> When search, DB is updated https://i.imgur.com/ODwj81U.png => no result.

I'm not sure I understand your question below
> I thinhk my issue is search result not update when product change?
but to my knowledge, no, there is not link between product data and search query data (num_results), so if there is a dramatic change in the number of products that match a query because their data change, the "popular terms" autocomplete block might not show accurate results until the query is actually re-run live.

Regards,
