### ISSUE TITLE
Selecting a category attribute should not reset the other attributes when searching!

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#263]
After searching using a text query and filtering with attributes, selecting a category resets the search attributes to the base query text and forces you to reselect new attributes!

Is this a function of magento, or something we can disable so you can continue to have your previous attributes selected when you select a category after you have begun searching?

**Comment by afoucret** [comment]
Hi @southerncomputer, this behavior is consistent with Magento standard behavior and we choose to keep this behavior unchanged. I am not sure of what is the right behavior. One side I think Magento standard behavior is not optimal. Other side changing the Magento standard can disturb people that are used to it.

I will let this open. If the community ask we will consider such a change.

**Comment by cykirsch** [comment]
I just noticed this issue as well and was surprised by it. I'm not sure what the implementation would entail, but it could potentially be configurable. So each store owner can decide whether to use standard functionality (clear filters) or to maintain existing filters.

**Comment by madonzy** [comment]
@afoucret is it possible in some easy way to implement this functionality? Any ideas?

**Comment by sambolek** [comment]
Changing "useUrlRewrites" from "true" to "false" should make category use URL parameter instead of category link/rewrite 

smile/elasticsuite/src/module-elasticsuite-catalog/etc/frontend/di.xml
smile/elasticsuite/src/module-elasticsuite-virtual-category/etc/frontend/di.xml

``` 
<virtualType name="categoryFilterUsingRewrite" type="Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category">
     <arguments>
         <argument name="useUrlRewrites" xsi:type="boolean">true</argument>
     </arguments>
</virtualType>
```

``` 
<virtualType name="categoryFilterUsingRewrite" type="Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category">
     <arguments>
         <argument name="useUrlRewrites" xsi:type="boolean">false</argument>
     </arguments>
</virtualType>
```

as this is injected via DI, if you need a more specific configuration for category filter (e.g. want to have category filter use parameters only on root level category), you can override category filter to not use `$url->getUrlRewrite`once certain condition is met in 
`smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Item/Category.php`

**Comment by romainruaud** [comment]
Will be worked upon #1320
