### ISSUE TITLE
Search latest product on top

### ISSUE THREAD

**Issue by avi-commerce** [Smile-SA/elasticsuite#2639]
I have implemented an elastic suite on my website http://upgrade.navyasfashion.com.
The website platform is Magento 2.4.4 version
I have tried to show the latest product in the search but it's showing old product first.
Any idea to resolve this issue.

**Comment by mohanlal37** [comment]
Hello Vahonc,

Thanks for the valuable reply.

**Comment by romainruaud** [comment]
@mohanlal37 may we close if this has been answered ?

**Comment by mohanlal37** [comment]
Hello Vahonic,

I have enabled the new attribute options in the products and also created the Optimizer then it's the right result on the Catalogsearch result page. but it's not showing the right result in the top search dropdown and also its suggestion.

I have shared a screenshot for it.

catalogsearch_result_page.png
![catalogsearch_result_page](https://user-images.githubusercontent.com/32094584/180102554-6a974b25-9326-4feb-b697-426bbe4019e5.png)

top_search_dropdown.png

![top_search_dropdown](https://user-images.githubusercontent.com/32094584/180102545-534bb329-af9a-4b8b-874b-43d8d345da9d.png)

**Comment by vahonc** [comment]
@mohanlal37

Firstly, as I can see from your screenshot you are using a custom theme. So we can't be sure that this theme is fully compatible with the ElasticSuite module, in other words if this theme doesn't have its own customizations including search/autocomplete features. And if it so, there is not much that we can do for this issue. You will have to resolve these conflicts by yourself (if they exist).

What you can do is checks the settings of your Optimizer and select all fields from the **Request type** parameter, as shown on the screenshot below:

![Screenshot from 2022-07-21 09-19-39](https://user-images.githubusercontent.com/67791361/180176885-dcf973e0-a143-4d91-82e1-2b3e3b0d2261.png)

Or you can try to switch to the default Magento theme Luma and check if your Optimizer is working as your expected, in this case, you will get proof if your problem is related to the custom theme issue.

Also, you could provide for us the screenshots with the settings of your Optimizer, it will help us more clearly understand your issue.

BR,
Vadym

**Comment by avi-commerce** [comment]
Thanks Support, It's working fine.
