### ISSUE TITLE
Message on top in backend

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2662]
![image](https://user-images.githubusercontent.com/17496183/181430344-a6b29e96-6900-4026-a3af-99b2dbacaaa2.png)
Hello, how can i remove this message please?

Dissmiss all button dont work.

Thank you.

**Comment by vncnt-mb** [comment]
Hello, it is possible to do that with the footer ad ?

<img width="285" alt="Capture d’écran 2022-07-28 à 09 22 38" src="https://user-images.githubusercontent.com/48125944/181445935-896a8269-b213-4f29-a682-fa8bc961b3bd.png">

You did this before with a footer link in the front end. Luckily you made a "consent" field. If necessary, connect this message and the ad on the footer on this field in question, that would be great.

<img width="1642" alt="Capture d’écran 2022-07-28 à 09 22 32" src="https://user-images.githubusercontent.com/48125944/181445969-7e3ba270-b1e6-4316-9fe4-92b46cf96f93.png">

**Comment by romainruaud** [comment]
Hello guys,

I agree that the backend message can be a bit intrusive. It's supposed to be displayed as a notice and not a warning (
you can check in the implementation class https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Model/System/Message/NotificationAboutVersions.php ).

So if you want to get rid of it, you know where it takes place in the code to shutdown it.

This message is part of our commercial strategy. As you know, we are not making any money on the free version of Elasticsuite, and this has been the case for years. 

While we strongly believe in Open Source and are quite happy to see the reach that Elasticsuite acquired in the Magento ecosystem during the last years, our revenue stream is not coming from this Open Source version that we are maintaining without compensation. Of course, we'll continue offering this version of Elasticsuite for free and to maintain it in the future.

We just need to be sure that merchants using Elasticsuite are aware of it. First of all, we need them to know which product they are using. Due to the fact that Elasticsuite is often installed by third-party agencies or developers, merchants are often not knowing that they are using our product. We also need them to know that they are using the free version of a freemium product, with all that it implies : not supported directly by Adobe or by their agency, but by a third-party company. And of course, the fact that they are missing a lot of features that they could possibly see as being business-critical for them.

We know that this might be seen as intrusive, but considering the added-value of Elasticsuite that merchants can benefit for free (in terms of features added, but also maintaining such a huge codebase), I still don't think that's a big counterpart. More than that, as said before, this is an open codebase, so anyone can easily remove this kind of message if they find it annoying.

We'll try to find a way for making it less-intrusive and less-scary (this should not be displayed by Magento as a warning message), but I'm not sure we'll provide a back-office switcher for that. The backlinck in Front-Office can be disabled because it's a way for us to acquire qualified traffic for our website and improve our SEO, and I'm fine with the fact that merchants might not want to help us this way, as long as not exposing to their competitors which tool they are using (even if nowadays, even Wappalyzer can detect Elasticsuite).

> Hello, it is possible to do that with the footer ad ?

No, there is no plan to disable this footer version block. We do not see this one as an "ad". It's an helper **for us** in fact, because very often, we are asking to people the exact version of Elasticsuite they are using, and it's always a struggle to find out. So we added this block so that it's clearly readable for anybody including non-technical people.

**Comment by achatpc** [comment]
Thank you for that answer.

I am really very happy to be able to use this extension which is free and has required and will still require many hours of work and investment.

So I fully understand your strategy of highlighting the possibility of upgrading to a higher version.

Also, personally, I feel no frustration or disappointment with this message. I just wanted to know if I could remove it for comfort reasons.

Good luck to you and your team in this magnificent project.

**Comment by eBusinessAtlantique** [comment]
> Thank you for that answer.
> 
> I am really very happy to be able to use this extension which is free and has required and will still require many hours of work and investment.
> 
> So I fully understand your strategy of highlighting the possibility of upgrading to a higher version.
> 
> Also, personally, I feel no frustration or disappointment with this message. I just wanted to know if I could remove it for comfort reasons.
> 
> Good luck to you and your team in this magnificent project.

Remove these 2 files
src/module-elasticsuite-core/Model/System/Message/NotificationAboutVersions.php
src/module-elasticsuite-core/etc/adminhtml/di.xml
And do compile procedure.

**Comment by OvalMedia** [comment]
Do you track or record any data about the stores using your module? I would guess you could keep records of referrers of links clicked in the backend.

**Comment by OvalMedia** [comment]
> Remove these 2 files src/module-elasticsuite-core/Model/System/Message/NotificationAboutVersions.php src/module-elasticsuite-core/etc/adminhtml/di.xml And do compile procedure.

Easier: create a module with a plugin for Smile\ElasticsuiteCore\Model\System\Message\NotificationAboutVersions

In that create this function:

`public function afterIsDisplayed()
    {
        return false;
    }`

...and the top message is gone. No need to hack into the module's core.

**Comment by rootindex** [comment]
This is extremely intrusive, staff members who do not make decisions nor is technical get a message that can not be dismissed, why? 

I understand one needs to hustle but this is not the way.

**Comment by ssx** [comment]
I've created a package to do this:

[composer require ssx/module-remove-elastic-suite-notification](https://packagist.org/packages/ssx/module-remove-elastic-suite-notification)

**Comment by romainruaud** [comment]
I close this, I think now everybody is aware of why the message is here, and how to remove it.

Regards

**Comment by hostep** [comment]
@romainruaud: sorry to comment on this old ticket.

But you mentioned earlier:
> We'll try to find a way for making it less-intrusive and less-scary (this should not be displayed by Magento as a warning message)

Would it be an idea to transfer the message from the top to the NotifierPool, so it can be dismissed "as read" after which it will no longer show up?
See screenshot below, so to move it into that alert bell notification section, like other modules are doing (in the screenshot the MultiSafepay module alerts people in this way about new versions for example, you can then mark the message "as read" after which it will disappear).

Would you be open to such a change in this module? I'm willing to send in a pull request to accomplish this if needed.

<img width="1145" alt="Image" src="https://github.com/user-attachments/assets/55222637-b3ee-4a9c-9915-82cf14d0309b" />
