### ISSUE TITLE
when we use optimizer then other custom sortings are stopped working on the list page.

### ISSUE THREAD

**Issue by manishgoswamig** [Smile-SA/elasticsuite#2676]
### Preconditions

Magento Version : Magento 2.3.7 EE

ElasticSuite Version : 2.9.0 

Environment : Developer

Third party modules : No any third party module

### Steps to reproduce

1. We installed the elastic suite and configured it and it is working fine.
2. After that we create a new optimizer with the decimal type of attribute which is also working fine on the category page.
3. But on the category page, other sorting options have stopped working.

### Expected result

1. All the other sorting options should work on the category page with the optimizer.

- For sorting, we have applied the ORDER BY  in the collection for the category page for our custom sorting which is  **last purchase date** but this collection is being overwritten by the optimizer.

- We can not create the optimizer for our custom sorting because we are applying sorting in the collection on the category page.

Please guide us so we can resolve this issue.

**Comment by vahonc** [comment]
Hello @manishgoswamig,

Could you please provide more details with screenshots about the configuration of your optimizer?

BR,
Vadym

**Comment by manishgoswamig** [comment]
Hi @vahonc,

Thanks for the active response, I am trying to apply sorting using collection and for that, I have updated the below files. When I am trying to print my query in direct sql I am getting the result as I want but on the frontend category page, there is a different result.



Path : app/code/Namespace/Modulename/etc/module.xml

`<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
	<module name="Namespace_Modulename"  setup_version="1.0.0">
		<sequence>
			<module name="Magento_Eav"/>
		</sequence>
	</module>
</config>`

Path : app/code/Namespace/Modulename/etc/frontend/di.xml

`
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Catalog\Block\Product\ProductList\Toolbar" type="Namespace\Modulename\Block\Catalog\Product\ProductList\Toolbar" />
    <preference for="Magento\CatalogSearch\Block\Result" type="Namespace\Modulename\Block\CatalogSearch\Result" />
</config>
`
<br/>
screenshot : 
![image](https://user-images.githubusercontent.com/46725562/183076711-ce9d92ae-862e-4e6f-8d39-ecf2c1a61355.png)


Path: app/code/Namespace/Modulename/Block/Catalog/Product/ProductList/Toolbar.php

`}elseif($this->getCurrentOrder() === 'previously_purchased'){
                $collection->addAttributeToSelect('score_precise','left');
                $collection->getSelect()->order('order_date DESC');
            }else{
                $collection->setOrder($this->getCurrentOrder(), $this->getCurrentDirection());
            }`

![image](https://user-images.githubusercontent.com/46725562/183072484-6454ab6c-f292-4e47-8b34-891a429134e5.png)

Please guide me so that I can resolve it :) .
`

**Comment by manishgoswamig** [comment]
Hi @vahonc,

Do you have any idea about this issue?

**Comment by rbayet** [comment]
Hello @manishgoswamig,

It looks like you have implemented your custom sort orders at the SQL level.

This is not the way to go with Elasticsuite since 
- Elasticsuite first performs an Elasticsearch request grabbing the desired amount of products per the toolbar pagination settings **and** applying the toolbar / customer selected sort order parameters 
- this results in a, say collection of 20 products, that are **then** hydrated against the Magento SQL DB

So your custom sort orders will only be able to re-sort "locally" those 20 products.
The way to go is to make sure the data you want to sort your products against is indexed into Elasticsearch along with the other product data.

If you want to have some secondary sorting options when you are sorting by an attribute (for instance when you sort by "brand", you seem to want to sort also by "part" number), you will need to do some additional trickery when Elasticsuite builds its sort parameters, by changing the behavior of \Smile\ElasticsuiteCore\Search\Request\SortOrder\SortOrderBuilder::buildSordOrders.

Regards
