### ISSUE TITLE
"Special" configuration

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2685]
Hello

I need for best client experience make somes little changes:

1. Mask or put on last sub category filters on layered navigation because my megamenu show it at top
2. Is it possible in filters to let users make multiple filter selection before click on a special button "filter results"? because for esch filter selection, page refresh and somes users click on multiple filters without understand how work this system.

Thank you in advance.

**Comment by Bashev** [comment]
This is a default Magento behavior, not related to elastic suite. You can check and modify Web200_ElasticsuiteAjax for inspiration

**Comment by achatpc** [comment]
> Hello @achatpc,
> 
> First of all, please clarify which versions of Magento and ElasticSuite you are using.
> 
> Also, provide more details (with screenshots) for the first question and what exactly you mean under `megamenu`.
> 
> BR, Vadym

Magento 2.4.4
Elasticsuite 2.10.11

**Comment by rbayet** [comment]
Hello @achatpc,

Concerning your question number 2
> Is it possible in filters to let users make multiple filter selection before click on a special button "filter results"? because for esch filter selection, page refresh and somes users click on multiple filters without understand how work this system.


Out of the box for Elasticsuite without third party modules, it's not possible by design : 
* the layered navigation is designed so you never lead the final user from a page with X produits to a page with 0 products
* by default (1) a logical "OR" is applied to values of the same filter (for example, if you select "blue" and "yellow" from a "color" attribute filter, the request will contain a "color=blue OR color=yellow" condition)
* a logical "AND" is applied between filters of different attributes (so for example if you selected a price range between 10 and 30 € from the previous example, the request will contain a " (price=[10, 30] AND (color=blue OR color=yellow)" 
* so when you apply your first filter, it's required to ask back to Magento+Elasticsuite the new content of the layered navigation filters, because maybe by applying a filter on colors, the price range of the remaining products changed (and for example you would no longer have products between 30 and 50 €) 
* * so if you **were** able to apply both a filter on price and select "blue" and "yellow" for the "color" attribute at the same time and submit all at once with a button, you **could** end up to a page with 0 products
* * **without knowing** which filter is the one removing the products you wanted to see

So concerning your issue, I would look for how to implement a mechanism (or for an existing third party module) that would
* either prevent the user on selecting another filter value as soon as he selected one 
* and/or perform an ajax request to pull the new content to be displayed in the layered navigation (I don't know about the module mentionned by @Bashev)

Please bear in mind that we offer limited support for Elasticsuite and third party modules, but any PR is welcomed !

(1) Since a few version, as it was asked by some users, there IS now an **option in admin per attribute** to allow to change the logical operator from an "OR" to an "AND"

Regards,

**Comment by rbayet** [comment]
Hello @achatpc,

Please provide additional context/screenshots for you question number 1 or even better yet open a specific issue for it so this one could be limited to your question about layered navigation and the provided answer.

Regards,
