### ISSUE TITLE
Search By SKU not working properly

### ISSUE THREAD

**Issue by ankurkinex** [Smile-SA/elasticsuite#2708]
Search By SKU not working. It is working fine in Autocomplete section. but we goes to the search page then that products goes to 2nd or 3rd page. We changed SKU weight higher and also lots of setting but it didn't works.

Our Magento EE. Version is 2.4.2

ElasticSuite Version : 2.10.4

Environment : Production

Third party modules : No third party module for Search

### Steps to reproduce
1. Search by SKU. Search first 3 letters of SKU
2. submit the search form.
3. You will not see that SKU's matching products on top. you will see that products on 2nd or 3rd page

### Expected result

1. Matching SKU's products should show on top.

### Actual result

1.  Matching SKU's products not showing on top.

**Comment by vahonc** [comment]
Hello @ankurkinex,

Could you please provide real examples with screenshots for this issue?

And by the way, what sorting you are using on the Search Results page?

BR,
Vadym

**Comment by ankurkinex** [comment]
HI,

Open this website 
https://www.master.ca/professional/

and search

**Comment by ankurkinex** [comment]
Hi @vahonc 
Any update on this issue.

**Comment by ankurkinex** [comment]
Why this issue was closed?

**Comment by romainruaud** [comment]
@ankurkinex , you closed this issue. That's why you can reopen it. If we had closed this, you wouldn't have been able to re-open.

I had a look at your website and understood your usecase, when searching for "w27", you expect the engine to find "w2728" or "w2717".

So please, take a look a those two wiki pages to better understand how it works : 

https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuBasics

https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuDetailled

And also, please find the solution that has been given in this comment : https://github.com/Smile-SA/elasticsuite/issues/970#issuecomment-594380109

Regards
