### ISSUE TITLE
is_filterable=0 error

### ISSUE THREAD

**Issue by EncoXXX** [Smile-SA/elasticsuite#2729]
### Preconditions
Magento Version : MEE 2.3.7 p3
The project is located on magento cloud

ElasticSuite Version : 2.9.10.1

Environment : production

### Steps to reproduce
1. Set is_filterable=0 to attribute, that used in virtual category
2. Go to virtual category page (frontend)

### Expected result
Normal virtual category page rendering (HTTP 200)

### Actual result
Current result: HTTP 503
Log: 
<pre>
[2022-10-03 15:53:22] report.CRITICAL: Field closure_type does not exists in mapping {"report_id":"report_id","exception":"[object] (LogicException(code: 0): Field closure_type does not exists in mapping at /app/project_id/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/Mapping.php:133)"} []
</pre>

**Comment by romainruaud** [comment]
Hello @EncoXXX 

To be usable in a virtual category rule, an attribute should be either "is_used_for_promo_rules=1" or "is_filterable=1".

If you want to make it usable for rules but not filterable, use the "is_used_for_promo_rules=1".

The behavior you are facing is normal, this is not possible to "disband" rules based on attribute when an user switch it to "is_filterable=0" because the rules are json-encoded into the database, there is no relationship between a rule and the attributes she uses.

Regards
