### ISSUE TITLE
Filters/layerednav display wrong results

### ISSUE THREAD

**Issue by qumuq-til** [Smile-SA/elasticsuite#2747]
Two custom fields: size (dropdown), warehouse (multiple select). Selecting size "XS" and "Dublin" gives me amongst other products a configurable product that is specifically _not_ in Dublin, but has size XS at other warehouses.

Display out of stock products: no,
All data inside a linked simple product is correct (i.e. no reference to Dublin)
Reindexing throws a strange error
`Integrity constraint violation: 1062 Duplicate entry '1039-217-1-212-1039' for key 'catalog_product_index_eav_temp.PRIMARY', query was: INSERT  INTO `catalog_product_index_eav_temp` (`entity_id`,`attribute_id`,`store_id`,`value`,`source_id`) VALUES (?, ?, ?, ?, ?)...`
where 217 is the warehouse attribute, but I had it fixed before and it still displayed wrong results.

**Comment by vahonc** [comment]
Hello @qumuq-til

First of all, please respect the issue template and give detailed details about your environment (versions of Magento and ElasticSuite, list of 3rd party modules), steps on how to reproduce the issue, what you have now and what you expect to have, etc. For a better understanding of your issue, you can also add some screenshots. Otherwise, it's unlikely someone from the team will have a look at it.

BR,
Vadym
