### ISSUE TITLE
Product list does not show in admin panel

### ISSUE THREAD

**Issue by VasyaTopalo** [Smile-SA/elasticsuite#2752]
After I updated Magento to the new version, the product list is not showing on the category page in the admin.

### Preconditions

PHP version - 8.1

Magento Version : 2.4.5 Enterprise edition

ElasticSuite Version : 2.10.12

Environment : Developer

### Steps to reproduce

1. Open category page in the admin panel

### Expected result

1. List is showing as it was before
2. 
![Screenshot (8)](https://user-images.githubusercontent.com/78264919/196932196-5633b425-7187-4b78-9d33-6f47fd62db39.jpg)

### Actual result

1. List is not showing 
![Screenshot (7)](https://user-images.githubusercontent.com/78264919/196930517-faf102e3-91a8-4ace-8fd2-b8535208f866.png)

There are no errors in the console.

**Comment by vahonc** [comment]
Hello @VasyaTopalo

What was the version of Magento before the update?

What do you see after clicking on the **Add/Remove Products** button?

Have you checked the logs of the Magento?

BR,
Vadym

**Comment by vahonc** [comment]
I think it can be related to some data issues that may have occurred during the Magento update, cause we don't get any reports with a similar problem.

You can try to disable/remove ElasticSuite and check what you will have in this case.

BR,
Vadym

**Comment by romainruaud** [comment]
Hello @VasyaTopalo 

The "Product Grid" you are expecting to see on the category page is now inside the popin that is opened when clicking on "Add/Remove Products".

In fact, that's how Magento Enterprise behave since a long time :) 

But Elasticsuite was "hiding" that because we had some explicit layout for the category page : we were overriding and hiding the "Visual Merchandiser" of Magento enterprise.

This was not good because we were preventing the users to benefit some features of the Magento Visual Merchandiser, like this one : https://github.com/Smile-SA/elasticsuite/issues/1765

That's why we made an appropriate development to be able to mix our Product Listing Preview with the capabilities of the legacy Visual Merchandiser.

Regards

**Comment by VasyaTopalo** [comment]
Ok, thank you for your reply :)
