### ISSUE TITLE
Can't run "indexer_update_all_views" manually when ElasticSuite is enabled

### ISSUE THREAD

**Issue by qsolutions-pl** [Smile-SA/elasticsuite#2759]
### Preconditions

Magento Version : Magento 2.4.3

ElasticSuite Version : 2.10

Environment : production + development

Third party modules : none

### Steps to reproduce

1. Set ElasticSuite as search engine
2. Download Magerun 2
3. Disable crons
4. Save a product in admin panel
5. Try to run cron task
```
php n98-magerun2.phar sys:cron:run indexer_update_all_views
```

### Expected result

1. No issues

### Actual result

```
Run Magento\Indexer\Cron\UpdateMview::execute 
                                                                                                      
  Cron-job "indexer_update_all_views" threw exception Magento\Framework\Exception\LocalizedException  
                                                                                                      

In IndexNameResolver.php line 70:
                                                                  
  The search failed because of a search engine misconfiguration.  
                                                                  
```

**Comment by romainruaud** [comment]
@qsolutions-pl what was the issue ? I'm glad if you close but if we missed something, let us know !

**Comment by nghiadxvn** [comment]
Hi @romainruaud,

I got the same issue. Magento has default cron to run index (indexer_reindex_all_invalid, indexer_update_all_views). When that cron runs, it throws this error message

[2022-11-14T10:22:15.523102+00:00] main.CRITICAL: Magento\Framework\Exception\LocalizedException: The search failed because of a search engine misconfiguration. in vendor/magento/module-elasticsearch/Model/Adapter/Index/IndexNameResolver.php:70
