### ISSUE TITLE
product missing on frontend and also on backend under product list preview section

### ISSUE THREAD

**Issue by gtrocks** [Smile-SA/elasticsuite#2768]
### Preconditions

When we assign product to category on specific store and someone updated its sorting in "all
store view" then product will not appearing on frontend  
if we update sorting under " Products List Preview and Sorting " for all store view then why it will not appear on frontend ?
it was only show on specific store in backend that was correct but why we are not showing it on frontend when its was assign to all store view as well ??

on  

Magento Version : 2.4.2-p1  EE

ElasticSuite Version : 2.10.7

Environment : developer mode

Third party modules :

### Steps to reproduce

1. Open category , switch scope to specific store and now assign product
2.now goto all store view from same category , update the sorting for few products from " Products List Preview and Sorting "
3. now you can see that product will not appear on front-end 

### Expected result

1. need to appear on front-end
2. when we update sorting on all store view it need to be appear  

### Actual result

1. not appering those products 
2. set condition to show out of stock product as well but it was not show on frontend if there sorting changed on "all store view "

**Comment by vahonc** [comment]
Hello @gtrocks,

From the description of your problem, it is not entirely clear whether you are working with real categories or virtual ones, and how exactly you assign products to a particular store.

>1. Open category , switch scope to specific store and now assign product
2.now goto all store view from same category , update the sorting for few products from " Products List Preview and Sorting "

Are you saving the category after your changes? What do you see on the Backend in the "Products List Preview and Sorting" section?

>2. set condition to show out of stock product as well but it was not show on frontend if there sorting changed on "all store view "

What do you mean by saying "set condition to show out of stock product" ? Are you using some rule condition for the virtual category? 

It will be easier for us to understand your problem if you add some screenshots.

Also please provide an extract of the queries that are being sent to ES when you are browsing categories. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`

BR,
Vadym

**Comment by msloboda-macopedia** [comment]
The problem seems  to be related with ancestor categories. If there is need to manually sort products on page with ancestor category and scope is **'All Store Views'** then to  table  `smile_virtualcategory_catalog_category_product_position` in column **'store_id' goes '0'.** 
I found that in this case store_id = 0, means admin store. 

![image](https://user-images.githubusercontent.com/114057111/217223944-e4cf9a50-61d6-4ab3-bde8-b70f85afc710.png)

So, if certain store view is selected, other then default, then products are visible on store front.

However it is misleading behaviour, maybe when All Store Views is selected, then multiple rows should be set up in `smile_virtualcategory_catalog_category_product_position` table, each for separate store?
