### ISSUE TITLE
Getting elasticsuite_categories_fulltext view does not exist. error while running setup:upgrade

### ISSUE THREAD

**Issue by jsjsvsvs** [Smile-SA/elasticsuite#2788]
### Preconditions

Composer 2
PHP7.4

Magento Version :
Magento 2.4.3

ElasticSuite Version : 
smile/elasticsuite": "~2.10.10

Environment :
Developer

Third party modules :

### Steps to reproduce

1. After module install
2. When running our deploy script bin/magento setup:upgrade
3.

### Expected result

1. Should run setup:upgrade with no issues 

### Actual result

1. [Screenshot, logs]2. 

Running schema recurring...
Module 'Magento_AmqpStore':
Module 'Magento_Config':
Module 'Magento_User':
Module 'Magento_Authorization':
Module 'Magento_Indexer':
Running schema recurring...elasticsuite_categories_fulltext view does not exist.

**Comment by vahonc** [comment]
Hello @jsjsvsvs

At the moment it's hard to say what exactly caused your problem because normally all should be fine with this. So we need more details about your environment.

- Have you checked the logs of Magento? Is there something that can help understand where is problem?

- Are you sure that ElasticSuite is selected as the default search engine?

- What is the status of your indices? Have you run a re-index?

- What did you mean when saying "when running our deploy script bin/magento setup:upgrade"? 

- Have you your issue during running "bin/magento setup:upgrade" command in manual mode, in other words without any deploy script, etc? 

BR,
Vadym

**Comment by Danieleeffe1** [comment]
good morning everyone

I agree with this post

after running the setup:upgrade command the terminal gives me the same error:

Running schema recurring...elasticsuite_categories_fulltext view does not exist.

I tried a second time and the terminal gave me the following error:

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason" :"Unknown filter type [phonetic] for [phonetic]"},"status":400}

if I refresh the browser to view the magento installation I see the following log:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteAdminNotification data: current version - none, required version - 0.0.1
Smile_ElasticsuiteCore data: current version - none, required version - 0.0.1
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.6.3
Smile_ElasticsuiteCatalogGraphQl data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.3.0
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteIndices data: current version - none, required version - 1.0.0
Smile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.5.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteAdminNotification data: current version - none, required version - 0.0.1
Smile_ElasticsuiteCore data: current version - none, required version - 0.0.1
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.6.3
Smile_ElasticsuiteCatalogGraphQl data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.3.0
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteIndices data: current version - none, required version - 1.0.0
Smile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.5.0
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#2 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#3 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#4 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#5 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#6 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

my installation

server
ubuntu 20.04
php 7.4
magento 2.4.5
elasticsearch 7.6.0

elasticsuite install command:
composer require smile/elasticsuite

installed elasticsuite version 2.10.12.1

**Comment by vahonc** [comment]
@Danieleeffe1,

Are you installing all the required plugins? 

Check our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x#installing-required-plugins) about this.

BR,
Vadym

**Comment by hgati** [comment]
> @Danieleeffe1,
> 
> 필요한 모든 플러그인을 설치하고 있습니까?
> 
> [이것에 대해 Wiki를](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x#installing-required-plugins) 확인하십시오 .
> 
> BR, 바딤

[Related Install PlugIn](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x#installing-required-plugins)

I encountered the above error in my Magento v2.4.6 + PHP 8.2 environment, but after referring to the Wiki above link and installing the necessary plugins, the error no longer occurs.

for ElasticsSearch
```
cd /usr/share/elasticsearch
sudo bin/elasticsearch-plugin install analysis-phonetic
sudo bin/elasticsearch-plugin install analysis-icu
sudo service elasticsearch restart
```

for OpenSearch
```
cd /usr/share/opensearch
sudo bin/opensearch-plugin install analysis-phonetic
sudo bin/opensearch-plugin install analysis-icu
sudo service elasticsearch restart
```

It appears that the issue occurred due to not installing the plugin.

**Comment by FadedOut** [comment]
> @Danieleeffe1,
> 
> Are you installing all the required plugins?
> 
> Check our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x#installing-required-plugins) about this.
> 
> BR, Vadym

Thank you for this info (and @hgati ) 🙂👍

Maybe I missed it (probably did, but if not...) I'd like to request maybe putting that info/link with the composer install info on the front page of the github repo - so anyone else trying to simply install using the composer command knows to also follow that wiki info (as I had no clue and needed to search/find this report).

**Comment by constancyGmbH** [comment]
I have the same problem. We use a deployment System on our servers. When we deploy a new version all steps are done like a new installation. When it comes to setup:upgrade, the process fails with "Running schema recurring...elasticsuite_categories_fulltext view does not exist." I can not do the setup:upgrade twice, because the first error stops our deployment. 
I double checked, that all plugins are installed in the elastic server, but it still fails. Any help on that?

**Comment by vahonc** [comment]
Hello @constancyGmbH,

Have you any details about your error from the Magento logs?

BR,
Vadym

**Comment by constancyGmbH** [comment]
I just see the error in the console. Before deployment I deleted all logs, but there are no exceptions after the deployment there. 

```Module 'Magento_AdminAdobeIms':
Module 'Magento_Backup':
Module 'Magento_Indexer':
Running schema recurring...elasticsuite_categories_fulltext view does not exist.```

**Comment by constancyGmbH** [comment]
@vahonc any idea?

**Comment by vahonc** [comment]
@constancyGmbH,

Most probably something is wrong with your configuration of the deployment system because normally all should be fine with this.

- Are you sure that you installed all the required plugins for Elasticsearch?

- Are you sure that ElasticSuite is selected as the default search engine?

- What is the status of your indices? Have you run a re-index?

- Have you your issue while running "bin/magento setup:upgrade" command in manual mode, in other words without a deploy script, etc?

BR,
Vadym

**Comment by constancyGmbH** [comment]
Hi Vadym,
1. Yes, all Plugins are installed. 
2. Elastic Suite is selected in the Database-Konfig. Is there a way to pre select it over the file system? Because the Problem is only on first run of setup:upgrade
3. Do i need to run the re-index before deployment?
4. If I copy the code to the new release directory and run it manually, I have the same problem.

BUT: We have a stage system with the same deploy mechanism for testing things out. The only difference between Live and Stage is the Developer Mode on Stage and the Live Mode on Live. If I run the same deploy on stage, it works.

**Comment by vahonc** [comment]
@constancyGmbH,

Could you please clarify which version of Magento and ElasticSuite you are using?

Do you use Magento Cloud instance for Live? If so, there could be some issue that you just can't override some variables.  

>Is there a way to pre select it over the file system? Because the Problem is only on first run of setup:upgrade

Not sure that I understand you correctly, but maybe you need to add the next command to your config file

`bin/magento config:set -le catalog/search/engine elasticsuite`

Also, as you pointed that the same deploy on stage works correctly, so there's definitely something wrong with the configs and not related to the ElasticSuite. 

BR,
Vadym

**Comment by Ruko2010** [comment]
We use magento 2.4.6. as a self hosted environment, no cloud. I can't see which version of ES I'm using, because in the Footer there is only: "[ElasticSuite](https://elasticsuite.io/) Open Source ver. UNKNOWN". The ES came with the claue theme and there was a folder for Updates of ES for Magento Version 2.4.6., so I assume, that it's quite a new version.

We do an Database Update from Live to Stage from Time To Time. We're done so last week and now the deploy problem is also in the stage system.

**Comment by constancyGmbH** [comment]
@vahonc 
We use magento 2.4.6. as a self hosted environment, no cloud. I can't see which version of ES I'm using, because in the Footer there is only: "[ElasticSuite](https://elasticsuite.io/) Open Source ver. UNKNOWN". The ES came with the claue theme and there was a folder for Updates of ES for Magento Version 2.4.6., so I assume, that it's quite a new version.

We do an Database Update from Live to Stage from Time To Time. We're done so last week and now the deploy problem is also in the stage system.

**Comment by vahonc** [comment]
>I can't see which version of ES I'm using, because in the Footer there is only: "[ElasticSuite](https://elasticsuite.io/) Open Source ver. UNKNOWN".

I assume that this problem is also on the stage server now?

Try to re-install ES at least on the stage server and check the deploy issue again.

BR,
Vadym

**Comment by constancyGmbH** [comment]
We just unzipped the theme and installed the Module without composer

**Comment by vahonc** [comment]
@constancyGmbH,

The Claue theme is not part of the ElasticSuite module, in other words, we don't support it, because it's a non-official/custom project for us. 

Compatibility with third-party modules is out of the scope of our Open Source support policy provided here. We don't support installing the ElasticSuite with a zip archive either, that's why the wiki is only speaking about installing through composer. So, if Elasticsuite is installed as an unproper/unsupported manner by a third-party solution, that's their responsibility to fix it. 

Unfortunately, there is not much we can do for your issue. If you are interested in dedicated (paid) support through professional services, please send a mail to elasticsuite@smile.fr

BR,
Vadym

**Comment by ebanolopes** [comment]
@vahonc please check my comment on the other thread https://github.com/Smile-SA/elasticsuite/issues/2564#issuecomment-2109050503
