### ISSUE TITLE
Set categories for search

### ISSUE THREAD

**Issue by Dathard** [Smile-SA/elasticsuite#2796]
Hello there,
We are using your Elasticsuite module, and we wanted to set the categories on top of the search. However, we did not find the corresponding setting on the backed, Is it at all possible with our version of the module or does it allow only setting the products?

**Comment by vahonc** [comment]
Hello @Dathard,

It's not clear what exactly you want to achieve. Could you add more details, a real example (if possible with screenshots of what you have and what you would like to get)?

BR,
Vadym

**Comment by Dathard** [comment]
Your module has the search optimizers, which provide the ability to customize the order of products in the search and autocomplete.
https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers

However, in addition to the list of products in the autocomplete block, you can display a list of categories
https://monosnap.com/direct/3trfdQSylgTNrWi5NF17CmtWU7D6aT
We are interested how to change the order of these categories, like how optimizers can change the order of products.

Regards

**Comment by rbayet** [comment]
Hello @Dathard,

Thanks for clearing up your question (I thought you wanted to have a callback of autocomplete-matched categories atop the products list of the fulltext search).

Indeed, it is not possible at the moment to create search optimizers to finetune the categories search from the admin interface.
What is available from the admin interface is to remove categories from the autocomplete on a per-category basis through the "Display Category in Autocomplete " category attribute available on the category edit form :
![image](https://user-images.githubusercontent.com/2353374/207779185-a6092c54-07eb-48ae-ab02-770a2f0610dd.png)

Programmatically, I guess you could take inspiration on the way the product search optimizers related queries are built and injected into the product search queries to injected "manually" constructed _function score_ queries in the category autocomplete request.

A simpler alternative would also be to (manually in DB or through a Magento setup) change the search weight of searchable category attributes (by default, 'name', 'description' and the 'url_path' attributes are made searchable through `\Smile\ElasticsuiteCatalog\Setup\CatalogSetup::updateCategorySearchableAttributes`) or remove for instance the description for being searchable for instance.
Category and Product attributes share the same Elasticsuite customization but since Magento only provide a catalog product attribute edit form, only those can be changed directly from the Magento admin.

Regards

**Comment by Dathard** [comment]
Thanks for the clarification and recommendations on customization
