### ISSUE TITLE
Unwanted products are loaded in wrong categories

### ISSUE THREAD

**Issue by supportA3WEB** [Smile-SA/elasticsuite#2797]
Unwanted products are showing in wrong categories in backend and frontend. Our product have no association with our current category. Not affected directly on product and does not correspond to the rules of the virtual category.

### Preconditions
Magento Version : 2.3.6-p1
ElasticSuite Version :2.9.13
Environment : Production Mode

### Steps to reproduce

1. Go to a category in our backend. Ex : Moteur
2. This is a virtual category based on another category. "piece technique > Moteur". (It's a shortcut for our Mega Menu)
3. When we search "Maillot" in the preview, we can see a lot of "maillot" but there are no jerseys associated with this category, they are all associated with the "equipement pilote" category. 

### Expected result

1. Load only product from the category but not jersey in the "moteur" category. 

### Actual result
We have jersey on a virtual category "moteur" but also on a category that is not configured as a virtual category : "pièce technique". 
![image](https://user-images.githubusercontent.com/10046331/207072723-98892521-8d22-49f2-b0b2-3f008d80f14b.png)
![image](https://user-images.githubusercontent.com/10046331/207073041-0540f287-9c41-406f-9e1c-7b4f3fff90c5.png)

Exemple of jersey :
![image](https://user-images.githubusercontent.com/10046331/207074167-34ffefc0-0f26-45c5-81e5-54a30a2f4e1d.png)

**Comment by Bashev** [comment]
Your filter in category 153 is for products which are NOT in the category yet?

**Comment by romainruaud** [comment]
Did you try to change "Root Category = Moteur" to "Root Category = Default" and a condition in the rule to say "Category is Moteur" ?

Regards

**Comment by supportA3WEB** [comment]
yes, we tried that too but it didn't work

**Comment by romainruaud** [comment]
Can you share the query that is generated for this problematic category ?

You can see the query in system.log if you enable debug mode of Elasticsuite

**Comment by supportA3WEB** [comment]
Hello @romainruaud,
[log_elastic.txt](https://github.com/Smile-SA/elasticsuite/files/10235688/log_elastic.txt)

**Comment by SKovbel** [comment]
Similar problem I have found in our system.
Problem was next - when you enable option `Catalog/Layer Navigation/Display Category Filte`, smile-elastic ignore filter with current category and all request to elastcisearch goes without must-category-id.
Many categories show wrong items and counts (ex. 1030 instead of 10 products in category).

@see Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\CurrentCategory::getFilterQuery

**Comment by romainruaud** [comment]
Hello @SKovbel ,

Category Filter is applied there during navigation : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php#L129

If you configure Magento to "Display Category Filter = false", then the category filter was not applied because the Layer Filter Model was never called. That's why in this case we rely on this file : https://github.com/Smile-SA/elasticsuite/blame/2.10.x/src/module-elasticsuite-catalog/Model/Product/Search/Request/Container/Filter/CurrentCategory.php

So I'm not sure you're having the same issue but rather something different.


@supportA3WEB 

According to your log file, there are ~1500 lines that are dedicated to the "category" filtering.

Considering the amount of clauses, it's likely a mess within virtual categories configuration : you probably have too much imbricated virtual categories that are built themselves with "categories" clauses. Which means the resulting query has a lot of category related combinations.

Regards

**Comment by supportA3WEB** [comment]
Thanks @romainruaud 
Our customer has making many imbricated virtual categories like you think.
This issu can be closed
