### ISSUE TITLE
Fatal error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in /var/www/html/new.lagergiganten.se/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 56

### ISSUE THREAD

**Issue by iyngaran** [Smile-SA/elasticsuite#282]
Why i am getting this error ?

Fatal error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 56

How can I fix it ?

**Comment by romainruaud** [comment]
Hello @iyngaran and thank your for submitting this issue.

Could you precise which version of the module and which version of Magento you are using ?

Best regards,

**Comment by iyngaran** [comment]
@romainruaud 

I am using "smile/elasticsuite": "^2.2" on Magento ver. 2.1.2. It was working, today I imported the categories from magento 1.9 using "ubertheme Data Migration Pro".

After that, when I go to sub categories, I am getting this error. I cleared cached and reindexed. But still I am getting the error.

**Comment by romainruaud** [comment]
Are you sure that the search engine is still configured to use Smile Elasticsuite ?

You can check this on **Stores > Configuration > Catalog > Catalog Search > Search Engine**

**Comment by romainruaud** [comment]
Also, please ensure that you did rebuild the DI correctly. Please clear the var/di and the cache if you are in developer mode, or re-launch the compilation process if you are in production mode.

Regards,

**Comment by iyngaran** [comment]
Yes, the search engine is configured to use Smile Elasticsuite.

And also, I rebuild the DI.

Please note that, I can go to category without any issues, but when I go to sub-category only, I am getting this error.

**Comment by metamasterplay** [comment]
I also have this problem. It may be because the option "display out of stock products" is enabled. I didn't have this error on the same setup a month ago.

**Comment by afoucret** [comment]
@iyngaran, @metamasterplay,

I have been trying to reproduce this bug on my own environment without success.
Can you be more specifics about your environment and especially the Magento and ElasticSuite version you are currently using.

Also, are you using a custom theme with customizations of the \Magento\LayeredNavigation\Block\Navigation component ?

**Comment by metamasterplay** [comment]
Close enough. For me it was a module (https://github.com/vovayatsyuk/magento2-alsoviewed) that was incompatible with yours. Disabling it removes the error. I'll try to see what exactly the problem is.

The full error for me was:
`[Tue Jan 17 05:10:35.627991 2017] [:error] [pid 1251] [client 54.239.167.90:42608] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor::addIsInStockFilter() in /var/www/e-motion/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:56\nStack trace:\n#0 /var/www/e-motion/vendor/magento/framework/Interception/Interceptor.php(123): Smile\\ElasticsuiteCatalog\\Plugin\\LayerPlugin->beforePrepareProductCollection(Object(Magento\\Catalog\\Model\\Layer\\Category\\Interceptor), Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor))\n#1 /var/www/e-motion/var/generation/Magento/Catalog/Model/Layer/Category/Interceptor.php(26): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->___callPlugins('prepareProductC...', Array, Array)\n#2 /var/www/e-motion/vendor/vovayatsyuk/magento2-alsoviewed/Block/ListProduct.php(70): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->prepareProductCollection(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor))\n#3 /var/www/e-motion/vendor/magento/module-catalog/ in /var/www/e-motion/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 56, referer: https://e-motion.ma/lady-motion/mode.html`

**Comment by romainruaud** [comment]
Hello @iyngaran 

Any update about this one ? Did you give a try to @metamasterplay answer : were you able to find if your problem comes from any other third party module ?

Regards,

**Comment by metamasterplay** [comment]
A little update, I got the same error when using Elasticsuite in another environnement (Magento 2.1.3, PHP7, Infortis Ultimo):
`[Tue Jan 31 16:42:12.711249 2017] [:error] [pid 20843] [client 172.31.33.179:51750] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor::addIsInStockFilter() in /var/www/safya/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:56\nStack trace:\n#0 /var/www/safya/vendor/magento/framework/Interception/Interceptor.php(123): Smile\\ElasticsuiteCatalog\\Plugin\\LayerPlugin->beforePrepareProductCollection(Object(Magento\\Catalog\\Model\\Layer\\Category\\Interceptor), Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor))\n#1 /var/www/safya/var/generation/Magento/Catalog/Model/Layer/Category/Interceptor.php(26): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->___callPlugins('prepareProductC...', Array, Array)\n#2 /var/www/safya/app/code/Infortis/Base/Block/Product/ProductList/Featured.php(231): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->prepareProductCollection(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection\\Interceptor))\n#3 /var/www/safya/vendor/magento/module-catalog/Block/Product in /var/www/safya/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 56`

When activating Infortis modules alone or Elasticsuite modules alone all works fine. When enabling both at the same time I get this error.

For both cases it's the same function call that generates the error: **->prepareProductCollection($collection);**. Or in the first case: https://github.com/vovayatsyuk/magento2-alsoviewed/blob/master/Block/ListProduct.php line 70.

**Comment by afoucret** [comment]
Hi @metamasterplay,

As this bug is caused by third party modules, I think the issue can be closed.

The module you pointed out https://github.com/vovayatsyuk/magento2-alsoviewed does some very bad things and break DI we installed by replacing the ElasticSuite product collection (based on ES) with it's own. It will break even with Magento EE ElasticSearch or SolR implementation.

**Comment by nurboja** [comment]
I got the same error Magento 2.1.5. fresh install without third party modules.

**Comment by tanolalano** [comment]
Any news on How we can handle this error?

**Comment by tanolalano** [comment]
Thanks for help @romainruaud. See the FAQ 1000 times to solve autocomplete O_o
-----OFF topic-------
About the autocomplete the FAQ needs to be update to work properly accordingly https://github.com/Smile-SA/elasticsuite/issues/272#issuecomment-324118481
---------------------
