### ISSUE TITLE
Unable to see the message when no results match 

### ISSUE THREAD

**Issue by vrajeshpatel4u** [Smile-SA/elasticsuite#2825]
### Preconditions

Magento Version : 2.4.5-p1

ElasticSuite Version : 2.10.12.1

Environment : Developer

Third party modules : No

### Steps to reproduce

1. Installed Smile-SA elasticsuite, configured in Magento. 
2. Created Three Categories, Three Products etc. 
3. When Search any random words, there is no message like 'No Results found'. 

### Expected result

1. It should be displayed "No Results found"

### Actual result

1. No message displayed

**Comment by vahonc** [comment]
Hello @vrajeshpatel4u,

I was not able to reproduce your issue on my test environment with Magento 2.4.5-p1 and ElasticSuite 2.10.12.1.

![Screenshot from 2023-01-18 11-10-06](https://user-images.githubusercontent.com/67791361/213130865-30227368-2424-46ec-88bc-f3a6eb835c69.png)

Are you sure that everything is configured correctly, cron is working, all data is re-indexed and no errors in the logs (Elasticsearch and Magento)?

Also, provide a screenshot of the search results on your website.

BR,
Vadym

**Comment by vrajeshpatel4u** [comment]
Hello, @vahonc 

When Search "Gea" : Here It should be displayed "No Results found"

![image](https://user-images.githubusercontent.com/40518060/213144448-b52fca14-d359-42d4-9a44-1129acf6b0ce.png)

When Search "Gear" : Here Results displayed. 
![image](https://user-images.githubusercontent.com/40518060/213144593-7e0fadf0-06ff-4af6-a60b-e8d7299e1c0d.png)

Thank you

**Comment by vahonc** [comment]
@vrajeshpatel4u,

First of all, it looks like you are using the custom theme. In this case, we can't guarantee compatibility of our module with third-party themes or modules because it is out of the scope of our Open Source support policy provided here.

You can try switching to the default Magento theme like Luma and test again your issue. But, If I'm not mistaken there is no logic for displaying a "No Results found" message in the minisearch form or autocomplete results. This message could be showing on the search result page as it showed on my screenshot.

What did you see when you typed smth that not existed and then pressed Enter, in other words, what is displayed on the Search result page?

BR,
Vadym

**Comment by vrajeshpatel4u** [comment]
It's not custom theme we have created child theme from Luma.  In search page working fine. So when results empty, It nothing displayed.

**Comment by vahonc** [comment]
Provide a screenshot cause it's not clear what exactly you have on the search page.

On the other hand, I showed you that it's not reproducible on the default theme, so probably smth wrong on your side.

Try to check logs or debug this issue on your side.

**Comment by vrajeshpatel4u** [comment]
Here is the Recorded Video tested in Luma Theme. 

URL : https://www.awesomescreenshot.com/video/14082280?key=e7cd5b421775af9e581a75797d5a2815

**Comment by vahonc** [comment]
Thank you for providing this video. As I told you before it's the default behavior of our module. The logic of an autocomplete search box is to display results if some are found and to not display anything if there aren't. So the idea is "if nothing is displayed then keep typing or try your luck". 

Your issue can be like a feature request, but for now it low priority for us. Also, it would be a bit difficult to do this since the autocomplete results box is divided between independent result blocks (product, categories, search terms, etc, depending on the Elasticsuite autocomplete settings). So to display "No results found" here, it needs to be sure that there are no results for every type of autocomplete results.

If you have only one type of autocomplete results (eg Products), then you can simply customize the corresponding template.

BR,
Vadym

**Comment by vrajeshpatel4u** [comment]
Thank you for your great response. 

Will customise as per requirements.
