### ISSUE TITLE
Module Breaks "All Products" Listing

### ISSUE THREAD

**Issue by nikonratm** [Smile-SA/elasticsuite#291]
Hi, not sure where to start with this one, with the module enabled when I choose "All" for the option _Show products per page_ I only get 20 products, as soon as I disable the module it works properly. No errors are being thrown that I can tell.

Any ideas where to start trying to debug this one?

Thanks!

**Comment by nikonratm** [comment]
Same issue seems to happen on demo store: http://demo.magento-elastic-suite.io/index.php/women/virtual.html?product_list_limit=all (though I dont know if 'all' option needs to be enabled in backend for it to work on frontend)

**Comment by nikonratm** [comment]
I think I tracked this down to `/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php` line 324:
```
$size = $this->_pageSize ? $this->_pageSize : 20;
```

Hack-y fix is to just change that 20 to 1000 but not sure if there is a more proper way to do this. Seems like `_pageSize` is null only when listing is set to 'All', in which case the limit should probably *not* be 20.

**Comment by romainruaud** [comment]
Hello @nikonratm and thank you for submitting this question.

Which version of ElasticSuite are you using ? I guess it's the 2.2, isn't it ?

I say so because this point was fixed on 2.3.x. The initial issue was #247 .

So imho you should upgrade to 2.3.x to get the "view all" feature working on product pages.

PS : I enabled the "all" option on the demo store, which is running 2.3.x. See the result here : http://demo.magento-elastic-suite.io/index.php/women/tops-women.html?product_list_limit=all

Best regards

**Comment by nikonratm** [comment]
Aha, youre correct, it was 2.2.x . Sorry about that, thanks!
