### ISSUE TITLE
Layered Navigation : Filter value encoding issue

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2924]
### Preconditions

Magento Version : 2.4.6

ElasticSuite Version : 2.11.1

Environment : Production

### Steps to reproduce

1. Create a filterable attribute, with selection, with an option having label "Zone 8b (-9.4°C à -6.7°C)"
2. Go to a front category page, and filter on that option

### Expected result

1. Category is filtered correctly
2. Url contains = `Zone%208b%20%28-9.4%C2%B0C%20%C3%A0%20-6.7%C2%B0C%29`

### Actual result

1. No products shown.
2. Url contains = `Zone%208b%20(-9.4%C2%B0C+C3%A0%20-6.7%C2%B0C)`

**Comment by vahonc** [comment]
Hello @Nuranto,

I tried to reproduce your issue on my test environment with fresh Magento 2.4.6 based on the Luma theme (with default sample data) and ElasticSuite 2.11.1.1. 

As you can see from my screenshot below, the category is filtered correctly, products are shown and the URL is properly encoded. But the encoding of the URL is a little bit different from yours, in my case URL contains `Zone+8b+%28-9.4°C+à+-6.7°C%29` 

![Screenshot from 2023-05-16 11-33-33](https://github.com/Smile-SA/elasticsuite/assets/67791361/343c7ec4-d696-4b07-9f00-917a9872223f)

Perhaps, you are using a custom theme that is not based on the Luma theme?

Also, your issue may be caused by the fact that you are using some 3rd party modules which may affect it.

BR,
Vadym

**Comment by Nuranto** [comment]
Thanks @vahonc, I use hyva theme indeed. I'll do some digging, and keep you informed.

**Comment by Nuranto** [comment]
I confirm the issue was on the theme. It seems that `encodeURIComponent` does not replace parenthesis and accentuated characters...

Sorry for the noise, no link with elasticsuite indeed, I should have looked better.
