### ISSUE TITLE
The virtual category is not working correctly for discounted products.

### ISSUE THREAD

**Issue by chaikivskyi** [Smile-SA/elasticsuite#2928]
### Preconditions
Magento 2.3.7-p3 with Elasticsuite/2.9.11 (Open Source)

### Steps to reproduce

1. Set up a discount for a product with a future date in the **Special Price From** and **To** fields.
2. Verify if the product remains in your virtual category after the date in **Special Price From** has passed without the need for manual reindexing.
3. Wait until the end of the sale period (as defined in the **To** field), and confirm that the product is no longer in your virtual category without manual reindexing.

### Expected result

The product should appear in the category after the **Special Price From** date and disappear from the category after the **To** date without requiring manual reindexing.

### Actual result
**Special Price From** and **To** are not being used to verify if a discount is active.
`\Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount::getSearchQuery`

**Comment by Bashev** [comment]
Update to version >= 2.10.14.

**Comment by vahonc** [comment]
Hi @chaikivskyi,

The fix mentioned by @Bashev is definitely not related to this issue. 

Yes, we don't take into account date limits for displaying **Special Price** **From** and **To** because there are some differences with this in the Open Source (CE) and Ecommerce (EE) of the Magento. This means that this stuff is on the Magento side.

Have you tried to test this on the real (not virtual) category or on the vanilla version of Magento?

BR,
Vadym

**Comment by chaikivskyi** [comment]
Hi @vahonc 
> Have you tried to test this on the real (not virtual) category or on the vanilla version of Magento?

I'm not sure what you meant. This issue is related only to a virtual category. In our case, the virtual category contains products without a discount because the 'To' date has ended. What do you suggest I test?

**Comment by vahonc** [comment]
@chaikivskyi,

Which condition rule did you set for your virtual category?

**Comment by chaikivskyi** [comment]
@vahonc 
**Only discounted products**

**Comment by romainruaud** [comment]
Hi @chaikivskyi 

I'm not sure how this works out-of-the-box with Magento Open Source (not Commerce).

1. You set a special_price to your product, then the special_price_from and the special_price_to.

2. At this time, what is stored in the catalog_product_index_price table as the final_price ? The special_price ?

3. Some days after, we are beyond the special_price_to, what is stored in the catalog_product_index_price table ?

I asked this because in order to determine if a product is discounted (ie has a special price or not), we rely on the price index table data.

So we probably initially designed this and considered that Magento himself is capable of putting the proper special_price into the price index table if the ending date is over.

Best regards

**Comment by indunie** [comment]
Hi @romainruaud,

I am also facing to the same issue in Magento ver. 2.4.6-p7 and [ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.11.9 (on elasticsearch ver. 8.15.1). 

Answers to your questions as below.
I created a virtual category with the only condition "Only discounted products " which loads products with the expired special price from and to dates.

_1. You set a special_price to your product, then the special_price_from and the special_price_to._
Yes, I set a special price for a specific store view of a simple product with expired from and to dates.
![image](https://github.com/user-attachments/assets/6da628c1-0ca7-4d37-9bff-9600da8f329d)

_3. At this time, what is stored in the catalog_product_index_price table as the final_price ? The special_price ?_
_4. Some days after, we are beyond the special_price_to, what is stored in the catalog_product_index_price table ?_
![image](https://github.com/user-attachments/assets/16f185c4-1798-4b49-a894-b57a34ead030)

IT seems like the catalog_product_index_price is holding correct prices but not virtual category is filtering well.

Thanks
