### ISSUE TITLE
Manual sort gets set back to automatic sort

### ISSUE THREAD

**Issue by mstoiber** [Smile-SA/elasticsuite#2948]
Our customer has a problem where when they change the sort order and/or change some products back to automatic search many products automatically get set back to automatic sort only some remain in manual sort.

We found out that a reload of the site may change it back.
Also sometimes after rearranging the sort order, the category does not show all products.

### Environment
Magento Version: 2.4.5-p1
ElasticSuite Version: 2.10.15.1

### Steps to reproduce
1. Change the sort order of products
2. Repeat as often as necessary

### Expected result
1. Manual sort order remaining

### Actual result
1. Many products get set back to automatic sort

**Comment by mstoiber** [comment]
> 

Hello, thanks for the reply!

It is also very difficult to reproduce for us.
The sorting disappeared right away and by reloading I managed to get it back instantly.

For reproduction of the error, I changed the sorting order multiple times and saved it, also sometimes I just changed a few items to automatic sort myself. After some tries, the occurred.

**Comment by pointia** [comment]
Are there any news on this topic?
To me it looks like as if there are some problems with the backend javascript but i did not investigate this.

**Comment by MTheProgrammer** [comment]
Same here, but it is really hard to reproduce. 

One possibility is that when jsonDecode throws an exception `$productPositions` is set to an empty array. In case of a large POST request payload, the "sorted_products" JSON field may be truncated.

https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php

```php
    private function unserializeProductPositions(\Magento\Catalog\Model\Category $category)
    {
        $productPositions = $category->getSortedProducts() ? $category->getSortedProducts() : [];

        if (is_string($productPositions)) {
            try {
                $productPositions = $this->jsonHelper->jsonDecode($productPositions);
            } catch (\Exception $e) {
                $productPositions = []; // This will reset products on exception
            }
        }

        $category->setSortedProducts($productPositions);

        return $this;
    }
```

**Comment by ganeddact** [comment]
We've incurred in a similar issue when upgrading from Magento 2.4.3-p3 with Elasticsuite 2.10, to Magento 2.4.6-p3 with Elasticsuite 2.11.
Categories with manually ordered items reverted back to automatic order, losing a lot of effort spent in ordering.
Not sure what could be the cause, if the Magento upgrade or the Elasticsuite upgrade.

**Comment by lytesaber** [comment]
Having a similar issue with a client trying to manually sort around 100 product items within their sale category.  Every so often the sale category will randomly revert back to automatic sort clearing the manual sort positions. The only solution we've been able to offer is to just persist with reconfiguring the manual sorting positions, this isn't ideal as it takes a fair amount of time to reconfigure 100+ product positions.

Not that this has any definitive basis but could this issue be due to the quantity of product items being manually sorted within a category? Our client doesn't experience this issue on any other category where they manually sort a smaller collection of product items whereas in their sale category, they sort 100+ products with manual positioning.

Magento Version: 2.4.5-p7
Elasticusuite Version: 2.10.19.3

**Comment by romainruaud** [comment]
@MTheProgrammer is right, this occurs when truncated data get sent to the backend.

As a security mechanism, @vahonc can you implement the following : 

on this line : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php#L158

Instead of setting the array to empty, just fallback to the previously existing list of Products. Maybe the existing list is in `$category->getSortedProducts()` or you'll have to fetch it from here : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-virtual-category/Model/ResourceModel/Category/Product/Position.php#L78

And add a warning message saying something like "Something went wrong while saving your product positions, they have been switched back to their last known state".

Regards
