### ISSUE TITLE
Magento 2.4.1 on Elasticsuite 2.10.x above 2.10.12 has di:compile issues

### ISSUE THREAD

**Issue by nicka101** [Smile-SA/elasticsuite#2949]
### Preconditions
Magento 2.4.1
Elasticsuite > 2.10.12

Environment : irrelevant
Third party modules : irrelevant

### Expected result
setup:di:compile should complete successfully

### Actual result

```
In ClassReader.php line 45:

  Impossible to process constructor argument Parameter #3 [ <required> Magento\Framework\GraphQl\Query\Uid $uidEnco
  der ] of Smile\ElasticsuiteCatalogGraphQl\Model\Resolver\Products\ContextUpdater class


In ClassReader.php line 34:

  Class Magento\Framework\GraphQl\Query\Uid does not exist
```

**Comment by romainruaud** [comment]
Hello,

we dropped 2.4.1 testing last year, that's why we did not spot your issue : https://github.com/Smile-SA/elasticsuite/commit/c88a7f047b93cc70b67397d89b713e9226a19533

On top of that, Magento 2.4.1 is not supported anymore : 

https://experienceleague.adobe.com/docs/commerce-operations/release/planning/lifecycle-policy.html?lang=en

so I don't think we'll fix this, you can apply a patch on your project if you want.

Regards
