### ISSUE TITLE
Strange behavior with in stock optimizer

### ISSUE THREAD

**Issue by MarcProvi** [Smile-SA/elasticsuite#2954]
### Preconditions
We have recently started using elasticsuite to improve or catalog pages and search results. And we have used optimizers to boost in stock products to be shown first and make the out of stock products last. The optimizer works well, but some products don't sort correctly and appear at the end despite being in stock in the website.

I have investigated a bit the problem and seems to be related to products that update their stock (we have an ERP that we synchronize with). We have the MSI activated and we don't use the default stock/source, we use custom_stock1, custom_stock2 and custom_source1 and custom_source2, products only have assigned custom_source1 and custom_source2.

When the product updates their stock the cataloginventory_stock_item table updates to out of stock (is the table that tracks default stock of magento) and the problem makes this strange behavior. Changing the value to in stock of the strange products and reindex the data solves the issue temporary if there are not more stock updates to that product.

Magento Version : Magento CE 2.3.4-p2

ElasticSuite Version : 2.8.19

Environment : Developer

Third party modules : Various third party modules and custom integrations that doesn't affect search results or indexers.

### Steps to reproduce

1. Create an optimizer to boost in stock products.
2. Create various sources and stocks and assign it correctly to some products.
3. Remove default stock and sources from some products.
4. Reindex everything.
5. Update stock of sources in product.

### Expected result
1. Products should be sorted by in stock first and out of stock last.

### Actual result
![image](https://github.com/Smile-SA/elasticsuite/assets/95677511/ed822918-54fa-462a-a2df-0572163afcfc)
![image](https://github.com/Smile-SA/elasticsuite/assets/95677511/e291622c-b348-4c6b-b47a-deeaacb7c73e)

**Comment by vahonc** [comment]
Hello @MarcProvi,

First of all, you should understand that you are using an outdated version of Magento which is no longer maintained by the Magento team, the same goes for an outdated version of our module. Although I'm not sure if the problem is in our module cause you mentioned that an optimizer works well, so it may be due to bugs in the MSI module. Since this outdated version has changed or fixed a lot of things, including the MSI module.

Therefore, I would advise you to consider about migrating your environment to more recent versions.

We can try to reproduce your problem, but this is a very low priority for us at the moment because, as I have already said, you are using very outdated versions.

BR,
Vadym

**Comment by MarcProvi** [comment]
Hello @vahonc,

We are aware that we are using an outdated version and we are currently working in updating our Magento. After investigating a bit more I have seen that is a Magento behaviour in this version with MSI and the only solution is using the default stock and source for our main stock to solve this strange behaviour. 

Best Regards,
MP
