### ISSUE TITLE
search by attribute

### ISSUE THREAD

**Issue by ia-Gaury** [Smile-SA/elasticsuite#2967]
Hi, we have attribute name apprel with values like - shirts , trouser. When i am searching for product name - "linen shirts" it shows linen trouser and linen shirts, it should not show trouser. Please help in this

**Comment by vahonc** [comment]
Hello @ia-Gaury,

Unfortunately, the information that you provided is not enough to understand exactly what the problem is, since there are so many factors that can influence this. Please provide us with more details about the configuration of your attribute and your products (maybe by adding screenshots, etc).

Also, specify which version of Magento and ES you are using.

BR,
Vadym

**Comment by myselfgaurav** [comment]
**Preconditions**
Magento 2.4.1

**Steps to reproduce**
Create attribute name "Apparel" with values - Shirts , Trousers and Ties
Create product with below names 

- Linen Tie
- Linen Shirts
- Linen Trouser

Now search for "Linen Shirts"

**Expected result**
Output should be only "Linen Shirts"

**Actual result**
Output are "Linen Shirts" , "Linen Ties", "Linen trouser"

**Comment by vahonc** [comment]
@ia-Gaury,

Could you elaborate on exactly what you want to achieve by creating the "Apparel" attribute, it's a little blurry for me right now.

Are you assign your attribute with values to your products? 

Also, what about the version of ElasticSuite that you are using?

BR,
Vadym

**Comment by myselfgaurav** [comment]
@vahonc - we have created apparel attributes and assigning them to products like - Shirts, Trousers, Ties

Elastic Search version - can you tell me how to check version , as i have used zip based installation

**Comment by romainruaud** [comment]
replaced by #2974
