### ISSUE TITLE
Undefined array key "elasticsuite"

### ISSUE THREAD

**Issue by ektapuri88** [Smile-SA/elasticsuite#2969]
After the Magento Upgrade to 2.4.5-p2, started having issues when search engine is elasticsuite, logs files throwing errors for search misconfiguration. 
Project is using elasticsearch 7, search engine is elasticsuite
### Preconditions

Magento Version : EE

ElasticSuite Version :2.10.14

Environment :2.4.5-p2

Third party modules :
Aheadworks Blog
"aheadworks/module-blog":  2.15.2,
"aheadworks/module-blog-graph-ql": 1.2.1,
"aheadworks/module-blog-search": 1.1.2,
### Steps to reproduce

1. search engine should be elastic suite
2. install AW blog
3. try reindexing php bin/magento indexer:reindex

### Expected result

1. the indexers should be success

### Actual result

1.
report.CRITICAL: Exception: Warning: Undefined array key "elasticsuite" in /app/6scxj3r4ug7lw_stg/vendor/magento/module-elasticsearch/Elasticsearch5/Model/Client/ClientFactoryProxy.php on line 44 in /app/6scxj3r4ug7lw_stg/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:

report.CRITICAL: RuntimeException: Elasticsearch client is not set. in /app/6scxj3r4ug7lw_stg/vendor/magento/module-elasticsearch/SearchAdapter/ConnectionManager.php:90

Failed indexer
![Screenshot 2023-06-15 at 1 29 24 pm](https://github.com/Smile-SA/elasticsuite/assets/117137061/7d0f5ce4-0949-4787-9626-74902cf192ce)

**Comment by vahonc** [comment]
Hello @ektapuri88,

According to your failed indexer screenshot, it seems that there is some issue with the Ahedworks Blog extension or some misconfiguration issue. And as you can see all is fine with ElasticSuite indexes.

We don't test the compatibility of this module with ElasticSuite because compatibility with third-party modules is out of the scope of our Open Source support policy provided here. So there is not much we can do for your issue.

You can try to use another extension for the blog or check [add-ons for ElasticSuite](https://github.com/Smile-SA/elasticsuite#community-add-ons).

BR,
Vadym
