### ISSUE TITLE
Can SKU attribute be excluded from search?

### ISSUE THREAD

**Issue by shochdoerfer** [Smile-SA/elasticsuite#3003]
For one of our merchants, I'd like to not use the SKU attribute for search. I configured the attribute as being non-searchable, but it is still used in the search query. Is there any other way to exclude the SKU attribute from search?

We are using version 2.10.15.1 of the module.

**Comment by romainruaud** [comment]
The XML file has precedence : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L33

Since the sku is set to `isSearchable=1` through the XML file, disabling it through the back-office is likely to have no effect.

You should try to disable it via XML, ensure that the cache is purged correctly (caching for XML file in Magento is sometimes hard to clean), and then give it another try.

Regards

**Comment by shochdoerfer** [comment]
Ah stupid me. That makes sense. Awesome, will give it a try. Thanks for the fast feedback.
