### ISSUE TITLE
Graphql products endpoint does not return products correctly sorted in category

### ISSUE THREAD

**Issue by jurvi** [Smile-SA/elasticsuite#3046]
### Preconditions

Magento Version : 2.4.4-p3

ElasticSuite Version : 2.10.15.1

Environment : Production in magento cloud

Third party modules : Akeneo connector, mageplaza language packs, ulmod/module-ordercomment

### Steps to reproduce

1. Order some products in category so that some are manually sorted, save changes
2. Clear cache
3. Request products via graphql api with sort = position, just like it used to work before installing elasticsuite

### Expected result

1. Products returned in the items array, sorted correctly by position

### Actual result

1. Products are returned no the in defined order, but by what looks like the automatic sort order, not taking the manual changes into account at all.

**Comment by vahonc** [comment]
Hello @jurvi,

Could you please share your query for GraphQL?

BR,
Vadym

**Comment by vahonc** [comment]
@jurvi,

>Request products via graphql api with sort = position, just like it used to work before installing elasticsuite

It looks like your issue is not related to GraphQL directly. After installing ElasticSuite the products positions (and blacklist status) are no longer written to `catalog_category_product` table but in the dedicated table `smile_virtualcategory_catalog_category_product_position`.

Take some expiration from the [#1851](https://github.com/Smile-SA/elasticsuite/issues/1851) issue. There you will find one trick and if I'm not mistaken it should help you, but don't forget to run full or partial re-index after that.

BR,
Vadym
