### ISSUE TITLE
Can auto-complete queries be recorded for the "Search Usage Analytics"?

### ISSUE THREAD

**Issue by FadedOut** [Smile-SA/elasticsuite#3059]
Hello,

I notice that the search queries are only recorded into the "Search Usage Analytics" when the customer hits the enter button on the keyboard and the actual search page is loaded. 

Would it be possible to add the ability for the auto-complete queries to also be recorded? The auto-complete is extremely helpful where many may not even hit the enter button - so in that case us merchants have no clue what was actually searched. 

I used to use the [MageWorx - Search Autocomplete](https://github.com/mageworx/search-suite-autocomplete) module and it had this ability, something I really miss. This module (elasticsuite) has the fantastic analytics, but it's missing the ability to record the auto-complete searches and would be very helpful for every merchant.

Thank you for your time

**Comment by rbayet** [comment]
Hello @FadedOut,

The issues with registering the auto-complete queries are that 
* by definition, auto-complete queries may well be incomplete, like searches for "bru", "bruich", "bruichla", "bruichladdich" when searching for that whisky brand, so "incoherent" queries could be recorded more often than not
* if one has enabled the `standard_edge_ngram` analyzer for product name, then "incoherent" or partial queries will definitely be recorded since simply typing "bru" or "bruich" could make the auto-complete provide "bruichladdich" results and the user will stop there
* the sheer volume of autocomplete queries could have a significant impact on the size of the behavioral data indices
* it would slow down (ever so slightly) a bit the autocomplete response
* last and not least, out of the box, it would be probably better to record those queries with a specific flag so as to be able to distinguish them in the "Search Usage Analytics" dashboard

But, at the core, I agree that sites that rely heavily on the autocomplete search could miss out on users behaviors with very few actual searches recorded when it's not the case.
That's probably a feature we can think about.
@romainruaud what do you think ?

**Comment by FadedOut** [comment]
Hello @rbayet sorry just saw these.

> * by definition, auto-complete queries may well be incomplete, like searches for "bru", "bruich", "bruichla", "bruichladdich" when searching for that whisky brand, so "incoherent" queries could be recorded more often than not

I kind of feel like this is okay. If we could have a delay on making the query (like 500ms or 1000ms - but configurable in the backend) that would help here. Then as people are trying to type into the box, it won't record non-finished searches. And also, if everyone is searching for "bru" and getting the result they are looking for, wouldn't that help with filling in the thesaurus? Isn't that kind of the point of the thesaurus? To see incomplete searches and add them to the system for future common searching.

> * if one has enabled the `standard_edge_ngram` analyzer for product name, then "incoherent" or partial queries will definitely be recorded since simply typing "bru" or "bruich" could make the auto-complete provide "bruichladdich" results and the user will stop there

Sorry I don't really follow here. If someone is typing "bru" and getting the results they are looking for then the system did as intended. But if they don't find what they are looking for, then they will search again and I will see what the customer is searching for both times. This is all I am looking for, is a way to see what customers are searching for without hitting enter.

> * the sheer volume of autocomplete queries could have a significant impact on the size of the behavioral data indices

Hmm that is true. Maybe a "truncate" option that we as merchants can run if it gets too large? Maybe a truncate by date or something?

> * it would slow down (ever so slightly) a bit the autocomplete response

I wonder if we truncate and keep it at a certain number of records maybe it wouldn't have much effect on the autocomplete then?

> * last and not least, out of the box, it would be probably better to record those queries with a specific flag so as to be able to distinguish them in the "Search Usage Analytics" dashboard

A way to track these types of searches would probably be great. Then we could see if anyone is actually going to the full search. But in the end if this is a bit of a task to flag these it would also probably be okay to not flag them - just being able to see all search requests would be very helpful in having a pulse on what people visiting the site could be looking for (and which I may not have). 

> 
> But, at the core, I agree that sites that rely heavily on the autocomplete search could miss out on users behaviors with very few actual searches recorded when it's not the case. That's probably a feature we can think about. @romainruaud what do you think ?

Yup I think this would help every merchant. It would help gather very important data on the sentiment/feeling/wishes of visitors of the site. If there are 1000 searches [out of 2000] in one day for a certain item that you don't have, it's probably best to look into offering it.
