### ISSUE TITLE
Impossible to process constructor error in Magento 2.4.1

### ISSUE THREAD

**Issue by EvasBa** [Smile-SA/elasticsuite#3076]
Hello,

When I execute the Magento 2.4.1 command: bin/magento setup:di:compile, I get an error:
In ClassReader.php line 45:
  Impossible to process constructor argument Parameter #3 [ <required> Magento\Framework\GraphQl\Query\Uid
  $uidEncoder ] of Smile\ElasticsuiteCatalogGraphQl\Model\Resolver\Products\ContextUpdater class

In ClassReader.php line 34:
  Class Magento\Framework\GraphQl\Query\Uid does not exist

Please help me to understand why this error occurs and what to do?

**Comment by rbayet** [comment]
Hello @EvasBa,

Indeed it seems this class does not exists in 2.4.1 and 2.4.1-p1, so our compatibility matrix is not up-to-date anymore.
We probably missed this since 2.4.1* is no longer part of our code quality/unit tests scopes for 2.10.x.

So

- either you can upgrade to a Magento version >= 2.4.2 and <2.4.6 and you can stick with your current requirement of Elasticsuite in ~2.10.0
- or you'll need to downgrade to Elasticsuite 2.10.12.1

Regards,

**Comment by EvasBa** [comment]
Hi @rbayet ,
unfortunately, the same error occurred when I installed version 2.10.12.1

**Comment by vahonc** [comment]
Hello @EvasBa, 

You need to downgrade Elasticsuite to the 2.10.11 version because in the 2.10.12.1 we introduce updating the search context according to support category_uid.

BR
Vadym

**Comment by EvasBa** [comment]
The issue has been resolved, extension was downgraded to version 2.10.11

**Comment by vahonc** [comment]
Great, I close this issue.

**Comment by vahonc** [comment]
Great, I close this issue.
