### ISSUE TITLE
Product attribute autocomplete > Number of products displayed

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#308]
When I search "Black" the autocomplete suggests: black (62), indoor (50), warm (37). If I click "indoor (50)" then a page "indoor" is displayed with... 105 products.

For me in such situation it's OK to display all indoor products, but it's not OK to display 50 products in autocomplete and then display 105 products.

I think the best solution would be to display "black (62), indoor (105), warm (78)" in autocomplete.

If it's too bad for performances (I could easily understand why) then I suggest to hide the number of products: "black, indoor, warm"

**Comment by romainruaud** [comment]
Hello @PierrickOlivier ,

this is impossible to solve actually, because the first number shown in the autocomplete can be explained by : Search on 'black' and make a facet on 'indoor'.

Whereas the second number displayed after clicking is : Search on 'indoor'.

We will remove the number of products from the display.

regards

**Comment by PierrickOlivier** [comment]
OK, removing the number of product is fine :-)

**Comment by afoucret** [comment]
PR have been merged

**Comment by afoucret** [comment]
@romainruaud : Please release a new 2.3.x version. I close the ticket.
