### ISSUE TITLE
Auto learn not populating the autocomplete list for all word fragments starting from the first letter after 3 letters typed

### ISSUE THREAD

**Issue by vlad1992** [Smile-SA/elasticsuite#3104]
### Preconditions
Magento Version: EE 2.4.6
ElasticSuite Version : 2.11.3.1
Environment : Production
Third party modules : hyva-themes/magento2-smile-elasticsuite
Elasticsearch version: 7.6.2

### Steps to reproduce
1. Create a product called `DEHYDROEPIANDROSTERONE (Dhea) 25mg`
2. Make sure it's active and visible 
3. Search for fragments of the word starting from the very beginning, nothing in the middle.

### Expected result

1. After the first search for the full word every fragment of the product name shows it in the autocomplete list starthing from the third character

### Actual result

1. Searching for DEH adds the word in the list of autocomplete words 
![Screenshot 2023-11-03 at 11 42 58](https://github.com/Smile-SA/elasticsuite/assets/7978194/a3d7f5b5-8177-456c-b737-ceb5cf0358b8)
2. So does DEHY, DEHYD, DEHYDR 
![Screenshot 2023-11-03 at 11 43 14](https://github.com/Smile-SA/elasticsuite/assets/7978194/8f003b8a-6b33-452b-b6ab-99362014b45a)
![Screenshot 2023-11-03 at 11 43 30](https://github.com/Smile-SA/elasticsuite/assets/7978194/17dba6eb-66df-43be-9396-3eaa1a934832)
3. However when reaching DEHYDRO and DEHYDROE no results are shown in autocomplete
![Screenshot 2023-11-03 at 11 50 08](https://github.com/Smile-SA/elasticsuite/assets/7978194/d83f9759-c4f1-4e1f-bc77-89fcd01bc0f5)
![Screenshot 2023-11-03 at 11 50 16](https://github.com/Smile-SA/elasticsuite/assets/7978194/6e591941-c608-4229-a7a9-59598a7e6d09)

 This is also the case when actually searching for the word and hitting the search results page: 
![Screenshot 2023-11-03 at 11 48 41](https://github.com/Smile-SA/elasticsuite/assets/7978194/2060c18d-2988-4f29-a3d1-0b0161c262de)
4. The from DEHYDROEP forward until the end of the word each fragment reveals the product in the autocomplete values. 
![Screenshot 2023-11-03 at 11 53 40](https://github.com/Smile-SA/elasticsuite/assets/7978194/508b884a-98ee-4986-8d1c-ff25c7d8be4f)

I also turned on fuzziness with a value of 2 and a prefix length of 0 and a max expansion of 50(default recommended by the document listed by the elasticsuite module). Am I missing something obvious here? I was thinking that given the auto-learn feature of the module once I searched for the full word the product would start showing up in the autocomplete list for all combinations, especially if I turn on fuzziness.

**Comment by rbayet** [comment]
Hello @vlad1992,

Yes, if "DEHYDROEPIANDROSTERONE" has been searched before and is visible in the Magento admin (under Marketing > SEO & Search > Search Terms) with 
* a number of results > 0
* has "Yes" in Suggested Terms

then searching for "DEH" or "DEHY" should 
* pull DEHYDROEPIANDROSTERONE as a popular query
* generate a search request searching for "DEH" (or "DEHY") or "DEHYDROEPIANDROSTERONE".

On the other hand, if you typically have such long product names/searches by pharmaceutical/chemical component which are both long and complicated to remember the spelling, please be aware that the fuzziness will only address up to 2 (yes, two !) misplaced/missing/interchanged letters.
PS: I'm pretty sure Elasticsearch/OpenSearch will ignore a fuzziness prefix of 0.

That's why we reintroduced in [2.11.3](https://github.com/Smile-SA/elasticsuite/releases/tag/2.11.3) the ability to configure "real" autocompletion on fields which will allow for completing "DEH" to "DEHYDROEPIANDROSTERONE" without someone having actually searched for it first.

I would suggest you switch the default analyzer of your product names to "standard_edge_ngram", and switch the following settings to Yes 
* "Elasticsuite > Search Relevance > Exact matching configuration > Use default analyzer in exact matching filter query" (introduced in 2.11.3)
* "Elasticsuite > Search Relevance > Spellchecking configuration > Term Vectors Configuration > [Experimental] Use edge ngram analyzer in term vectors," (introduced in **2.11.4.1** so you will have to upgrade Elasticsuite)

And then perform a full reindex.
It should be much, much, much better in your situation.

Regards,

**Comment by vlad1992** [comment]
Thanks @rbayet I will try those suggestions and come back to you with an update regardless.
