### ISSUE TITLE
Typo in the class name introduced by 2.4.6 compatibility

### ISSUE THREAD

**Issue by rajeev-k-tomy** [Smile-SA/elasticsuite#3134]
See this commit https://github.com/Smile-SA/elasticsuite/commit/9a797be579189027a11ab1c85e400c5fab72326a which is created for making compatibility with Magento version 2.4.6. The old Zend class used is `Zend_Filter_NormalizedToLocalized`. However, when the compatibility made, the class now used is `\Magento\Framework\Filter\LocalizedToNormalized`. This is actually the opposite of the actual intention. I think the correct class would be here: `\Magento\Framework\Filter\NormalizedToLocalized`?
### Preconditions
Compare release `2.10.12.1` with the latest version `2.11.4.2`

Magento Version : Magento CE 2.4.6-p3

ElasticSuite Version : 2.11.4.2 & 2.10.12.1

Environment : In any environment

**Comment by rbayet** [comment]
Hello @rajeev-k-tomy,

Yes, you're right, before the disappearence of the old Zend classes 
* `\Magento\Framework\Filter\LocalizedToNormalized` extended `Zend_Filter_NormalizedToLocalized`
* `\Magento\Framework\Filter\NormalizedToLocalized` extended `Zend_Filter_LocalizedToNormalized`

Good catch !

That will probably fix a bug when playing with the display precision of decimal attribute introduced by the oversight.

Regards,

**Comment by rbayet** [comment]
Humm, well actually it will simply make sure the long standing bug/functional there still exists.

`Zend_Filter_NormalizedToLocalized` has (never ?) not for a long time be able to do what it was supposed to do when the precision is defined.
And neither does `\Magento\Framework\Filter\NormalizedToLocalized`.

See : 
```
    /**
     * Defined by FilterInterface
     *
     * Normalizes the given input
     *
     * @param string $value
     * @return string
     * @throws Exception
     */
    public function filter($value)
    {
        if (is_array($value)) {
            $formatter = new IntlDateFormatter(
                $this->_options['locale'],
                IntlDateFormatter::SHORT,
                IntlDateFormatter::NONE
            );
            $formatter->setPattern($this->_options['date_format']);
            return $formatter->format(strtotime($value['month'] . '/' . $value['day'] . '/' . $value['year']));
        } elseif ($this->_options['precision'] === 0) {
            $numberParse = new NumberParse($this->_options['locale'], NumberFormatter::PATTERN_DECIMAL);
            return (string) $numberParse->filter($value);
        } elseif ($this->_options['precision'] === null) {
            $numberParse = new NumberParse($this->_options['locale'], NumberFormatter::DECIMAL);
            return (string) $numberParse->filter($value);
        }

        return $value;
    }
```

* If the value is an array, the method assumes it's a date and tries to format it
* otherwise if the precision equals 0, then it might actually format the number correctly (so, the thousand separator maybe ?)
* same thing if the precision is null

But if you configured the attribute with a precision of 3, the value will be left untouched.
This will impact the label "From - To" displayed when a filter is applied: even the thousand separator will not be shown.
Considering the values comes from the slider filter (see below), the decimal digits would be '0' anyway.

The full localized format (thousand separator, decimal separator) will still be applied on the slider,
* because the mentioned PHP code above is not responsible for formating it, it is done in javascript
* but considering the values come from an histogram with integer step, the decimal separator + number of digits is purely cosmetics to display a properly localized "X.999" for the right/upper bound of the slider.

And of course, if the precision IS zero, then the block of code is not executed so not even the thousand separator will be applied properly.
So, meh.

I'll fix the obvious typo, at least it will "not work totally as expected" as it used to be, but we will have to do something to have a proper behavior.

Regards,
