### ISSUE TITLE
Use only elastic search functionality no layered navigation?

### ISSUE THREAD

**Issue by mcyrulik** [Smile-SA/elasticsuite#319]
I'm wondering if it's possible to use just the search features of this module?

We have another module that we want to use to handle the layered navigation functionality, but when I have both modules installed enabled, I get dependancy injection errors/conflicts.

**Comment by afoucret** [comment]
Hi @mcyrulik,

By design the layered navigation is built on the search engine feature since it is only faceting the search result. Magento implementation of ElasticSearch or SolR is very similar.

I am afraid that there is no good solution for using another module that is modifying this area of Magento with Elasticsuite.
