### ISSUE TITLE
Smile_ElasticsuiteVirtualCategory module take more than 80% of the transaction time on PLP

### ISSUE THREAD

**Issue by magentoman2024** [Smile-SA/elasticsuite#3200]
The Smile_ElasticsuiteVirtualCategory module affect performance on PLP and search on our website. The page can take more than 10s to load. The principal method who cause this issue are:
       ●  #Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product::getCategorySearchQuery (44%)
       ● #Smile\ElasticsuiteVirtualCategory\Model\Rule::addChildrenQueries (28.45%)
       ● #Smile\ElasticsuiteVirtualCategory\Model\Rule::getVirtualCategoryQuery (7.57%)
       ● #Smile\ElasticsuiteVirtualCategory\Model\Rule::getCategorySearchQuery (6.79%)

### Preconditions

Magento Version : 2.4.4-p2 (cloud)

ElasticSuite Version : 2.10.17.2

Environment : Production

Third party modules : none that should affect catalog/search

### Steps to reproduce

1. Go the any PLP page on the website, check the page loadinng time analyse this method and you will see that they consume a lot of time (more than 10s)

### Expected result
Page loading time should take some seconds(2 or 3 max)

### Actual result

This is the screenshot of new relic report for one of our PLP page:
![image](https://github.com/Smile-SA/elasticsuite/assets/22107990/27ed7da4-ced4-4486-bec3-68a48a5ab7c5)

**Comment by romainruaud** [comment]
Hi, the PR #3193 is intended to mitigate this by adding a local cache for the query building.

However, it can't be miraculous if you are having thousands of virtual categories with complex imbrications. How much virtual categories do you have actually ?

Regards

**Comment by magentoman2024** [comment]
Hi @romainruaud ,

We have more than thousands of virtuals categories on our website. We have a lot and many rules on that. So now, what is your recommendation? What is the best practice to setup many virtuals categories and many rules?

Do you know when the PR https://github.com/Smile-SA/elasticsuite/pull/3193 will be merge and in which release?

Let me know.

Thank You.

**Comment by romainruaud** [comment]
You have to keep in mind that when computing category/product association for a high-level category (or the search result page), the engine will build a complex query to assemble all the products belonging to the currently viewed category:

- products belonging to non-virtual children of the current category
- products matching one of any virtual children of the current category

The resulting query could end up being quite complex and adding pressure to the computation mechanism done by Elasticsearch. That’s why, due to the current situation, we strongly recommend not using them for the whole category tree.

That's not the purpose behind virtual categories: they are designed to build ephemeral categories, such as dynamic corners: “special father day”, “actually discounted products”, “new products” and so on.

They are not a tool to automatically attach products to categories but a merchandising mechanism.

Let’s take a common misconception as an example: using some field that will never change to build virtual categories based on that. The most often occurring is the “create virtual categories based on brand”. A brand will never change, a Weber barbecue will always be a Weber: if you want to define brand categories, it should be done either during the import process (with a brand/category mapping), or even earlier into the Product Management system.

Virtual categories are here to help the merchants to create either an ephemeral category or a category based on something that will often change: discount, stock, total number of sales, etc…

And on top of that, since those categories are "virtual", the relationship between them and the products they contain is not materialized in the database, making them unable to be used for promotion rules, sitemap export, etc...

Therefore, try to reduce the number of virtual categories.

BR,

**Comment by magentoman2024** [comment]
Thank you very much @romainruaud , we will wait until the PR  https://github.com/Smile-SA/elasticsuite/pull/3193 is merged to update our elasticsuite. On the other hand, review the structure of our virtual categories as well as their use.

Thank You
