### ISSUE TITLE
How to use optimizer on parent categories?

### ISSUE THREAD

**Issue by jackjackde** [Smile-SA/elasticsuite#3202]
I want to use a optimizer for products of a special brand. In the sub categories it works as expected but in the parent categories, the items are still mixed. Did I missed something?

e.g.
Category A
boost by brand > not working, items are still somewhere in the middle.
![Screenshot 2024-03-04 at 09 23 53](https://github.com/Smile-SA/elasticsuite/assets/2054008/7c0c1b06-30c6-46fd-8c0d-1e13dc45711e)

Category A > AA
boost is working

Should i set a special sorting value?

Thanks for help!
best!

**Comment by romainruaud** [comment]
On your screenshot, we can see the score of the product is changing from 1 to 1.2 so the boost is definitely working.

The products are not moving, most probably because they are pinned to a particular position on this category. (set to Manual sort and pinned to a particular location).

Can you check this ? 

Regards
