### ISSUE TITLE
"type" is not a valid parameter on upgrade

### ISSUE THREAD

**Issue by ebgreen** [Smile-SA/elasticsuite#3205]
Products not showing when added

Products when updated disappear.

backlogs starts to show up after 30 minutes

### Preconditions

Adobe Commerce Cloud

post upgrade

Magento Version : Magento 2.4.6-p4

ElasticSuite Version : 2.11.5.1
AWS opensearch 1.2.4

Environment : Production

Third party modules : NA test without 

### Steps to reproduce

1. rebuilt indexes "renamed"
2. after rebuilding indexes search all logs nothing but the repeated error in the system.log
3. crons all show successfully finished.
4. bin/magento indexer:reindex no errors

### Expected result

1. product show on cron scheduled runs.

### Actual result

1. report.ERROR: "type" is not a valid parameter. Allowed parameters are "_source", "_source_excludes", "_source_includes", "allow_no_indices", "allow_partial_search_results", "analyze_wildcard", "analyzer", "batched_reduce_size", "ccs_minimize_roundtrips", "default_operator", "df", "docvalue_fields", "error_trace", "expand_wildcards", "explain", "filter_path", "from", "human", "ignore_throttled", "ignore_unavailable", "lenient", "max_concurrent_shard_requests", "opaqueId", "pre_filter_shard_size", "preference", "pretty", "q", "request_cache", "rest_total_hits_as_int", "routing", "scroll", "search_type", "seq_no_primary_term", "size", "sort", "source", "stats", "stored_fields", "suggest_field", "suggest_mode", "suggest_size", "suggest_text", "terminate_after", "timeout", "track_scores", "track_total_hits", "typed_keys", "version" [] []
2. crons all show successfully finished.
3. bin/magento indexer:reindex no errors

**Comment by rbayet** [comment]
Hello @vahonc,

Could you try to reproduce using the exact same versions of Magento, Elasticsuite and OpenSearch ?
The "type" parameter should have been removed everywhere in the code in 2.11.x since we introduced Elasticsearch 8 compatibility in the first place.

Regards,

**Comment by rbayet** [comment]
Hello @ebgreen,

I was not able to reproduce your issue on a **fresh install** of EE 2.4.6-p4 + Elasticsuite 2.11.5.1 + OpenSearch 1.2.4 (official docker image).

But since you mentionned an upgrade (Elasticsuite ? Magento ?), please run this command `composer info opensearch-project/opensearch-php`.
We've switched the Elasticsearch/OpenSearch PHP client requirement in 2.11.5 due to too many quirks in the legacy Elasticsearch PHP one.
You might not have upgraded all Elasticsuite dependencies when moving from an older version.

Regards
