### ISSUE TITLE
Backend Category CatalogOptimizer preview slow to load

### ISSUE THREAD

**Issue by yasser-moudouani** [Smile-SA/elasticsuite#3232]
Hi, question regarding of loading of preview component on category edit backend page 

When a category contains a huge amount of manual sorting the ui component are very slow to load and sometimes the browser cache due to a lot of product position setting for the current categorie
Is there any tips or advice in order to allow to the category even if there is a lot of manual sorting ?

Example : 
at the first loading page 
![image](https://github.com/Smile-SA/elasticsuite/assets/56895261/3cf7adfb-04aa-4d6d-8c80-032ebe153e0e)
We have already more than 1K sorted products.

**Additional context**
Magento cloud 2.4.6-p4
Elasticsuite 2.11.5.1

**Comment by yasser-moudouani** [comment]
Hi, 

Any updates please

Regards,
Yasser

**Comment by romainruaud** [comment]
Hello @yasser-moudouani 

sorry for the delay on answering. Our position here is that this component is meant to pin _some_ products to the top of each category.

It was not designed to pin thousands of products (because no human could do this manually) and I'm not really surprised that the Javascript part is struggling with such a high volume.

I understand that you are importing these sort order, most probably because they are coming from a third-party solution which is computing product positions per category.

The good way to manage this would be to rely on the Elasticsuite Boosts to compute the product sorting among all categories, and avoid to import such a high number of products positions from an external solution.

For now, there's nothing we can do to mitigate your issue, because it's due to a "mis-usage" of our tool, or at least, it's a specific usage which is hijacking one of our existing features.

Best regards
