### ISSUE TITLE
Catalog Search Reindex not working after 247 upgrade

### ISSUE THREAD

**Issue by sethkgx** [Smile-SA/elasticsuite#3271]
### Preconditions

Magento Version : 247 EE (Adobe Commerce)

ElasticSuite Version : 2.11.6.1

Environment : Developer

Third party modules : N/A

### Steps to reproduce

1. Upgrade to Magento 247
2. Do Reindex

### Expected result

1. Reindex successfully, products showing in the frontend

### Actual result

1. Reindex encountered an error
<img width="1220" alt="Screenshot 2024-05-07 at 13 41 58" src="https://github.com/Smile-SA/elasticsuite/assets/17714161/ad85c888-4b0e-4656-a075-eb83be03cce7">

**Comment by rbayet** [comment]
Hello @sethkgx,

From which version of Magento + Elasticsuite did you made the upgrade from ?

Regards,

**Comment by sethkgx** [comment]
Hi @rbayet We were on Magento 2.4.5-p2 and using version 2.10.0 of ElasticSuite

**Comment by vahonc** [comment]
Hi @sethkgx,

What is the full stack of this error message? You can find it in the Magento logs (`exception.log` or `system.log`) and maybe in Elasticsearch logs (`/var/log/elasticsearch/`).

Also, have you tried to deselect ElasticSuite as the default search engine, e.g. back to `Elasticsearch 7` and try run reindex again? 

BR,
Vadym

**Comment by sethkgx** [comment]
Hi @vahonc 

There is no log unfortunately, that's why it's hard to debug what file or what's causing the reindex error.
We can't go back to Elasticsearch 7 because this is no longer supported in Magento 247.

Ideally, we still want to use ElasticSuite because there's some customisations we've done already in the module.

**Comment by vahonc** [comment]
@sethkgx

In Magento 2.4.7 they remove the `Magento_Elasticsearch` module (for Elasticsearch 5) and add support for Elasticsearch 8. Yes, the `Magento_Elasticsearch7` module is being deprecated because Elasticsearch 7 reached end-of-life in August 2023. However, it is still the default option for 2.4.7 so you can still use them.

As for this:
>Also, have you tried to deselect ElasticSuite as the default search engine, e.g. back to Elasticsearch 7 and try run reindex again?

I mean try temporary select Elasticsearch 7 as the default search engine here:

![Screenshot from 2024-05-10 11-41-18](https://github.com/Smile-SA/elasticsuite/assets/67791361/312f3e76-3c1c-41a6-a0d0-3aa2a5e04e1e)

and try to run reindex and check if errors will still be present. 

I have a test environment with Magento 2.4.7 with default sample data, Elasticsearch 7.17.20 and ElasticSuite 2.11.6.1. I don't have any errors during reindex, so probably your issue is quite specific to your project/environment. 

If you don't want to use Elasticsearch 7 you can install the Opensearch, ElasticSuite also supports it.

BR,
Vadym

**Comment by rbayet** [comment]
Hello @sethkgx,

The error seems to be generated on the server side by your OpenSearch/Elasticsearch instance, it's a java.util.regex.PatternSyntaxException related to having unescaped characters "[" and/or "]" inside a regex character class.
The "near index 1" means that you have probably somewhere in your configuration a string "[]" that is interpreted by the search engine as a regex.

The only place I can think of might be related to the [recently introduced token filters to remove trailing/leading zeroes from SKUs](https://github.com/Smile-SA/elasticsuite/blob/a191ce8f3376b3cf989ccf2308b84511caa9a1d2/src/module-elasticsuite-core/etc/elasticsuite_analysis.xml#L185-L196).
Have you enabled any of the settings in Stores > Configuration > Elasticsuite > Analyzer settings ?

Also, could you provide us the results of the following commands executed in your magento directory ?
`composer info | grep -i elasticsearch`
and
`composer info | grep -i opensearch`

And also the exact flavour and version of your Elasticsearch or Opensearch server.

Regards,
