### ISSUE TITLE
Product sorting doesn`t work for 1column template

### ISSUE THREAD

**Issue by deiserh** [Smile-SA/elasticsuite#332]
If a one column template is used for the category view page the sorting doesn`t work. The reason for that is, that the filter will be moved from sidebar.main container to content.top container. The elastic module loads the collection on _renderFilterBefore.

The Problem is, that on a one column template the _renderFilterBefore will be called before the sort order from toolbarblock (part of content container) is added to the query.

Magento Version: 2.1.3
Elasticsuite Version: 2.3.1

**Comment by romainruaud** [comment]
Hello @deiserh,

I just tested it by switching a category layout to "1 column", and I don't see any problem regarding the sorting.

Do you use the standard "1 column" layout or are you using a custom one ?

**Comment by deiserh** [comment]
Hi,

I thought that the 1 column layout are the standard one. But after your comment I tried to switch the layout in the category from 1 column to 2 column and this doesn`t work neither, so I assume the fault is on our site. I am Sorry for the effort.

**Comment by romainruaud** [comment]
No problem,

issues concerning sorting/filtering are often due to the same causes : 

- you have a layout which is moving the ```product_list_toolbar``` block outside the ```ListProduct``` block.
- you have a layout which is removing the ```product_list_toolbar```.
- you have a layout which is rendering the layered navigation blocks before the product listing.

This is a known problem which is also occuring on the Magento's native search implementation and is due to the strong dependency between the product_list block and the toolbar. You can see the Magento's internal issue tracked here : https://github.com/magento/magento2/issues/7253

Best regards,

**Comment by scher200** [comment]
@romainruaud We are newest version of you module and on Magento 2.1.6 and experience a page-reload on changing an order- of sort- option on both catalog- and search-page, but nothing changes to the product order or sorting.
