### ISSUE TITLE
The cart price rules are not applying.

### ISSUE THREAD

**Issue by chiragprajapatiaureatelabs** [Smile-SA/elasticsuite#3332]
Hello,

I am facing an issue with the Cart Discount Rule. We have added a cart rule based on the category ID (virtual category ID). However, since this category ID is not assigned to the products, the cart rule is not being applied to the products. Can anyone please guide me on how to resolve this?

### Preconditions
Magento Version : 2.4.5-p8
ElasticSuite Version : [2.11.7.1](https://github.com/Smile-SA/elasticsuite/releases/tag/2.11.7.1)
Environment: Both (Local have Developer and Production have Production mode)

### Steps to reproduce
1. Create a virtual category with the necessary rules.
2. Create cart price rules with product subselection conditions.
3. Add the category ID to the product subselection conditions.
4. Perform a full reindex.

### Expected result
1. The discount should be applied to the cart on the products that have been assigned to the category.

### Actual result
Currently, the discount is not being applied because the condition is added for the virtual category, and the product is not directly assigned to that category.
1. Created Test Category
![Screenshot (62)](https://github.com/user-attachments/assets/77b6ef15-6dae-4e57-aef7-881589f3e642)
2. Created Cart Rule
![Screenshot (63)](https://github.com/user-attachments/assets/196de645-e0f1-4d74-add5-54b29b23cf1f)
3. Checkout Order Summary.
![Screenshot (64)](https://github.com/user-attachments/assets/a0dca7b7-cadc-4147-ba43-3cfb607b6cf7)
4. Products are showing on the category page.
![Screenshot (65)](https://github.com/user-attachments/assets/fbfd0532-d53d-4e59-8967-9a9544b3c52c)
5. Category is not assigned in ES
![Screenshot (68)](https://github.com/user-attachments/assets/9bc95fba-0b69-49b2-a984-580d3793ae0b)

Thank You

**Comment by vahonc** [comment]
Hello @chiragprajapatiaureatelabs 

>Currently, the discount is not being applied because the condition is added for the virtual category, and the product is not directly assigned to that category.

You are right it's not working from out-the-box because we have some limitations for using virtual categories. The virtual categories are not a tool to automatically attach products to categories but a merchandising mechanism. They are here to help the merchants to create either an ephemeral category, or a category based on something that will often change: discount, stock, total number of sales, etc…

And on top of that, since those categories are "virtual", the relationship between them and the products they contains is not materialized in the database, making them unable to be used for cart rules, promotion rules, sitemap export, etc...

Virtual categories are supposed to be used for limited, marketing oriented merchandising operations, but NOT to be used as the foundations for a catalog.

BR,
Vadym

**Comment by chiragprajapatiaureatelabs** [comment]
Hello @vahonc 

Thank you for the information.

I managed to do that by adding the same rules I had added to the virtual category. So, we need to add the rules as we did for the virtual category instead of adding the category ID condition. For example, if we have `Created (Days) equals and greater than 7` for the virtual category, then we need to add the same rule to the Cart Price Rules: `Created (Days) equals and greater than 7`.
