### ISSUE TITLE
Cannot instantiate interface Smile\ElasticsuiteCore\Api\Index\IndexOperationInterface

### ISSUE THREAD

**Issue by PascalBrouwers** [Smile-SA/elasticsuite#335]
Tried to install version 2.3. Enabled Smile_ElasticsuiteCatalog and Smile_ElasticsuiteCatalogRule.
During setup:upgrade I got: Cannot instantiate interface Smile\ElasticsuiteCore\Api\Index\IndexOperationInterface

Seems to be coming from:
Smile\ElasticsuiteCatalog\Setup\InstallData->install()
Magento\Indexer\Model\Indexer->reindexAll()

**Comment by PascalBrouwers** [comment]
Enabled Smile_ElasticsuiteCore and now there is no problem.
Maybe you can add a depend on this on the submodules.

**Comment by romainruaud** [comment]
Hello @PascalBrouwers 

The documentation states to enable all modules : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#enable-the-module--and-run-elasticsuite-setup

The dependency is clearly declared in Smile_ElasticSuiteCatalog : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/module.xml#L22

Maybe Magento did not properly handle it in your case (not properly cleaned cache or something like this).

You cannot run ElasticSuiteCatalog without ElasticSuiteCore, this is a clear fact.

But you are free to disable other modules like VirtualCategories or Thesaurus if you think they do not fit your need.

Since this is not an issue for you anymore, I close it.

Regards,

**Comment by kingshukdeb** [comment]
Hey man, I was trying to disable elasticsuite to check few magento search behaviors. But when i disbaled those i started getting 
Fatal error: Uncaught Error: Cannot instantiate interface Smile\ElasticsuiteCore\Api\Index\IndexOperationInterface in 

I disabled all those using `php bin/magento module:disable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker`

After that ran setup:upgrade and cleared cache but stil getting the same.
