### ISSUE TITLE
Merchandiser Products List Preview and Sorting

### ISSUE THREAD

**Issue by PaulWatt** [Smile-SA/elasticsuite#3387]
Hi support,
Our client has a Magento instance with many stores.

In the feature "Products List Preview and Sorting" is it possible to revert back to just using the default scope for a category as we see this message on some root categories.

"Your product selection is empty for the selected Store View. If you are running a multi-store setup, please check this [manual page](https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories#previewing-virtual-categories-on-a-multi-store-setup) for more informations."

 If we change the scope we get the merchandiser feature but our client has said they have never had to change the scope before to user this feature and changing the scope will add a lot more time to the task as there are many store scopes.
 
 Can you please advise.
 Thanks
 Paul
 
 pwatt@objectsource.co.uk

**Comment by vahonc** [comment]
Hello @PaulWatt,

Could you provide more details about your environment, especially the versions of Magento and ElasticSuite that you are using? And, also provide your multi stores relations (screenshots are welcome)

As for this:
>"Your product selection is empty for the selected Store View. If you are running a multi-store setup, please check this [manual page](https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories#previewing-virtual-categories-on-a-multi-store-setup) for more information."

That's not possible, we create an index per-store, due to the fact that data may differ per store (it can be due to the store locale, different categories or just attribute scoped values that may differ). So even if everything would be merged into an unique index, the amount of data would be the same.

BR,
Vadym
