### ISSUE TITLE
Product indexation fail if an attribute "stock" is created on BO

### ISSUE THREAD

**Issue by zkliouel** [Smile-SA/elasticsuite#340]
In a native Magento 2.1.3 and ElasticSearch module 2.3 : 
I created a product on the BO -> it's indexed on elastic
Then, I created an attribute "stock" in the BO -> all products are not indexed  

Here the errors logged : 

`[2017-03-02 08:27:07] report.DEBUG: Response {"0":{"took":1,"errors":true,"items":[{"index":{"_index":"magento2_default_catalog_product_20170302_082707","_type":"product","_id":"1","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [stock]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [is_in_stock]"}}}},{"index":{"_index":"magento2_default_catalog_product_20170302_082707","_type":"product","_id":"5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse [stock]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [is_in_stock]"}}}}]},"is_exception":false} []`

This is due to mapping : 
`"stock":{"type":"string","doc_values":true,"norms":{"enabled":false},"index":"not_analyzed","copy_to":["spelling","autocomplete"]}`

It could be useful if a controle is done when an attribute is create with a specique name

Regards

**Comment by romainruaud** [comment]
Well ok I do now understand more the issue you talked about yesterday.

It is therefore impossible to create an attribute which is named "stock" since this keyword is reserved to the specific stock indexation system.

I am wondering why you are needing an attribute which is called "stock". If you need to add additional stock information on products, it may be a better idea to add them to cataloginventory table and then index it inside the already existing "stock" nested object : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L50

But yes, we may consider triggering a warning/exception when creating an attribute using a reserved keyword like "stock" or "categories" etc...

Since this is the only thing we'll be able to do, you'll have anyway to change your attribute name to something else if you want it to work.

Best regards,

**Comment by afoucret** [comment]
Creating an attribute with the name stock is now forbidden (PR #358 merged).
