### ISSUE TITLE
Widget collection position_by_sku not applying

### ISSUE THREAD

**Issue by ttraskback** [Smile-SA/elasticsuite#3401]
After update from 2.4.6-p5 to 2.4.7-p2 pagebuilder widget carousel no longer works with position_by_sku.

### Preconditions

Magento Version : EE 2.4.7-p2

ElasticSuite Version : 2.11.8.3

Environment : Developer and Production both

### Steps to reproduce
1. Crate a block that contains a carousel widget
2. Add by sku
3. Add skus at random in a order that is nether ascending or descending
4. Set "Sort By" to Position

### Expected result
1. src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php:143 should get true
2. Elasticsearch query should contain script to order them this way
3. Products should be orders as you entered

### Actual result
1.  src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php:143 Is true
2. No script tag in elasitcsearch request
3. Products are ordered in descending order

This is the log for the request:
curl -XPOST 'http://elasticsearch:9200/magento2_2_finnish_catalog_product/_search?pretty=true' -d '{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"bool":{"must":[],"must_not":[],"should":[{"match":{"sku.untouched":{"query":"19843","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"19844","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"19858","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"19884","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"181264","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"194488","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"198599","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"220158","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"224904","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"253491","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"253493","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"304010","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"615925","minimum_should_match":"100%","boost":1}}}],"minimum_should_match":1,"boost":1}}],"must_not":[],"should":[],"boost":1,"_name":"Jos KAIKKI n\u00e4ist\u00e4 olosuhteista on TOTTA:\n   SKU (sku) on yksi 19843,19844,19858,19884,181264,194488,198599,220158,224904,253491,253493,304010,615925"}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":true}'

**Comment by joacols** [comment]
Hi, i found the problem with this. 
src/module-elasticsuite-virtual-category/Plugin/PageBuilder/Catalog/Sorting/OptionPlugin.php
position_by_sku sorting happens on a afterGetCollection plugin. After that plugin, magento will also try to sort using the vendor/magento/module-page-builder/Model/Catalog/Sorting/SimpleOption.php  
![image](https://github.com/user-attachments/assets/82133f6b-d335-405d-8ad8-48f24301e442)
![image](https://github.com/user-attachments/assets/44ee24c6-1ee4-4606-b4dd-a7aab82b4ba6)

as you can see, nothing is done because the virtual type for position_by_sku does not meet the conditions. 
as you can see, smile plugin is just reseting collection when it is not required

**Comment by joacols** [comment]
also, 
The plugin itself is no longer needed. 
Here are the 3 classes that implement this method
![image](https://github.com/user-attachments/assets/9b378125-cf1a-43b4-b7a3-c48add08a930)
![image](https://github.com/user-attachments/assets/dbf78c18-c301-4766-93f7-50ad7ecf487d)
![image](https://github.com/user-attachments/assets/37b13406-05cc-4ed1-89e0-6d24e4d1b390)
![image](https://github.com/user-attachments/assets/6fef27d5-774d-4f71-a31d-902b00c80b1a)

as you can see, every class is responsible of reseting the collection when necesary

ill work on a pr, not sure if i can contribute directly

**Comment by romainruaud** [comment]
turns out that Magento moved a plugin from global di.xml to adminhtml.xml and frontend.xml : https://github.com/magento/magento2-page-builder/commit/979c95999463b00cd21f4730161cce90dfe887f6

Therefore, our plugin which was supposed to go after the Magento one, was triggered before, and our sort order was reset.

The PR #3422 contains a proposal for a fix, can you give it a try ? It's easy to report it locally.

Regards

**Comment by BeardTech** [comment]
Hello,

The fix doesn't seem to have any effect for me. I’m looking for the correct configuration for inline scripts, as referenced here: [Inline Script Configuration Guide](https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#ensure-proper-elasticsearch-configuration-is-set-for-inline-scripts).

Since I’m using OpenSearch, I believe the configuration might differ. Could you provide the appropriate settings for OpenSearch?

Thank you!

**Comment by romainruaud** [comment]
@BeardTech as far as I know, the configuration is the same for inline script in OpenSearch.

Could you share with us the Elasticsearch query you're seeing when using this widget ?

Regards

**Comment by BeardTech** [comment]
@romainruaud When I apply the settings you recommended, I encounter the following issue:

`org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown script context [search] found in setting [script.allowed_contexts]`

query : 
`curl -XPOST 'http://opensearch:9200/magento2_rdp_catalog_product/_search?pretty=true' -d '{"size":"4","sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"bool":{"must":[],"must_not":[],"should":[{"match":{"sku.untouched":{"query":"radiateurplus-bahamas-c-1000-blc","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"radiateurplus-maldives-700W","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"radiateurplus-maupiti-s-500-blc","minimum_should_match":"100%","boost":1}}},{"match":{"sku.untouched":{"query":"radiateurplus-hawai-500W","minimum_should_match":"100%","boost":1}}}],"minimum_should_match":1,"boost":1}}],"must_not":[],"should":[],"boost":1,"_name":"Si TOUTES de ces conditions sont VRAIES:\n   SKU (sku) fait partie de radiateurplus-bahamas-c-1000-blc,radiateurplus-maldives-700W,radiateurplus-maupiti-s-500-blc,radiateurplus-hawai-500W"}},{"terms":{"visibility":[2,4],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":0}'`
