### ISSUE TITLE
"Only discounted products" Virtual category rule is not reading "special from and to dates"  in  discounted products to load products

### ISSUE THREAD

**Issue by indunie** [Smile-SA/elasticsuite#3430]
### Preconditions
Magento ver. 2.4.6-p7 and [ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.11.9 (on elasticsearch ver. 8.15.1).
in both production and developer modes

### Steps to reproduce
1. Set up a discount for a product with a future date in the Special Price From and To fields.
2. Create a virtual category with the virtual rule "Only discounted products".
3. Verify if the product remains in your virtual category after the date in Special Price From has passed.
4. Wait until the end of the sale period (as defined in the To field), and confirm that the product is no longer in your virtual category.

### Expected result
1. The product should appear in the category after the Special Price From date and disappear from the category after the To date

### Actual result
1. Discounted product is not disappear after the "special to date" passed.
![image](https://github.com/user-attachments/assets/2ec7fe50-94ad-4648-8ebd-c1ec41438dc9)
It seems like Special Price From and To are not being used to verify if a discount is active.
![Screenshot from 2024-10-15 15-42-21](https://github.com/user-attachments/assets/d43c3556-88a8-4210-8aaa-48198fac92de)
![Screenshot from 2024-10-15 15-44-23](https://github.com/user-attachments/assets/df0db3c3-ed18-45cf-b12c-397e0db12835)

The below issue is related to this but I couldn't find it as resolved.
https://github.com/Smile-SA/elasticsuite/issues/2928

**Comment by vahonc** [comment]
Hello @indunie,

I tried to reproduce your issue according to your steps. So, I create a virtual category with the virtual rule `Only discounted products` and set up a discount for some products (in my case three first) with a future date in the Special Price `From` and `To` fields, as from 8 to 11 November.

![ScreenShot Tool -20241108190044](https://github.com/user-attachments/assets/a7a80c6d-b70b-482d-9a94-10adaa1416dc)

![ScreenShot Tool -20241108190835](https://github.com/user-attachments/assets/31967c38-bcb1-4504-894e-beb96e8ccfa6)

![Screenshot from 2024-11-08 19-05-55](https://github.com/user-attachments/assets/f813e8bc-38f5-4aca-8c69-0ba521f2c715)

Indeed, when the "special to date" passed the discounted products did not disappear from the virtual category and the prices didn't change in the database. But after running reindex this issue was fixed, the products disappeared from the category, and `catalog_product_index_price` table was updated.

![Screenshot from 2024-11-13 14-41-23](https://github.com/user-attachments/assets/77c53367-bbcc-445e-a023-16947d14f62b)

So you may need to check the Magento cron job to make sure that the price index updating is configured correctly.

Also, clarify what exactly version of Magento you are using, I mean OS, CE or EE.

BR,
Vadym

**Comment by indunie** [comment]
Hello @vahonc ,

Thank you for checking the issue.

The version I am using is Magento CE 2.4.6-p7.

Reindexing crons are working well, but it doesn't fix the issue.

**Comment by vahonc** [comment]
@indunie,

>Reindexing crons are working well, but it doesn't fix the issue.

Have you tried to run a manual re-index? 

This is very strange because I couldn't reproduce your issue on the fresh Magento, at least it was fixed by manual re-index, and products with the passes "special to date" disappeared from the virtual category.

Could you provide more details about your Magento instance, especially if you are using any third-party extension?

Also please provide an extract of the queries that are being sent to ES when you are browsing categories. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`.

BR,
Vadym

**Comment by indunie** [comment]
Hello @vahonc ,

Thank you for your attension on this issue.

I am having multiple stores and special prices have been set store wise.

Please see the below example and let me know if I am having any wrong data inserted in my database related to the below example.

Ex : Arapahoe Boot

I am displaying one of simple products from this Arapahoe Boot example in the category page.  (Please note that I am not displaying any parent products in my category views)
SKU : RLBARONG-07
![Screenshot from 2024-11-25 20-18-35](https://github.com/user-attachments/assets/a4fc414f-b457-4392-940a-c3325d779778)

Check the 8th row which was related to my AU store product. All dates are expired and it will not removed from the category with mannual reindex either.
![image](https://github.com/user-attachments/assets/57eab39d-7bb5-4075-8bb7-0f0c12d822d5)

Virtual category configurations as below.
![image](https://github.com/user-attachments/assets/5c1e138e-24c3-421a-8d24-92d75315cabc)

Could you please review these configurations and let me know if I did anything wrong?


Also please find the extracted query from the system.log file for the category load.
[system log in the category load.txt](https://github.com/user-attachments/files/17905129/system.log.in.the.category.load.txt)

Thank you.

BR,
Indunie Florence

**Comment by vahonc** [comment]
@indunie

How many virtual categories are you using in your store? Are all child categories of the Sale category from the screenshots is virtual?

And what about assigning your test product in websites?

![ScreenShot Tool -20241126150449](https://github.com/user-attachments/assets/a5a8cc84-a58d-4a8e-a59a-14f9f95deba1)

BR,
Vadym

**Comment by indunie** [comment]
Hello @vahonc ,

There are 5 child categories set for the "Sale" parent category. 
3 of them are virtual with different conditions and there are 2 non virtual categories. 

I don't think it has more than 5 virutal categories for the store.

![image](https://github.com/user-attachments/assets/9ee0c290-dc82-42b4-aebe-f00c272adb53)

Let me know if you need further information.
Thank you

BR,
Indunie Florence

**Comment by indunie** [comment]
Hello @vahonc ,

I just figure out all the products which don't have special prices set which were displayed with the virtual category have been come from the non virtual subcategory of the "Sale" parent category. Once I detach that non virtual subcategory from the parent issue was fixed.

i really appreciate your support and cooperation in this matter.

Thank you.

Best regards,
Indunie Florence
