### ISSUE TITLE
Wrong products are appeared as search results

### ISSUE THREAD

**Issue by indunie** [Smile-SA/elasticsuite#3448]
Search results are appeared with correct results but seeing some wrong results even the search term doesn't exist in any product field of them.

Magento Version :
Magento CE  ver. 2.4.6-p7

ElasticSuite Version :
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.11.9 (on elasticsearch ver. 8.15.1)

Environment :  Issue is exists in both developer and production modes.

Third party modules : No any module used to overlap Elastic suite featues.

### Steps to reproduce
Searched "Yard" keyword in the searchbar.
https://ridgelineclothing.com.au/catalogsearch/result?q=yard

### Expected result
Only products with "Yard" term in name or related content fields. It shouldn't display "Monsoon Jacket"

### Actual result
Displaying all yard products, but with the wrong "Monsoon Jacket"
![image](https://github.com/user-attachments/assets/64789ecd-82a9-444e-9ff1-e223cd552952)

Tried by indexing mannually, but the issue is still there. 
Searched the "Yard" text in all parent and child products of "Monsoon Jacket" but couldn't find.

**Comment by vahonc** [comment]
Hello @indunie,

The existence of the word "Yard" somewhere in the description (params, URL, etc.) of this specific product is the first thing that comes to mind. On the other hand, this problem is more likely quite specific to your environment and it will be difficult for us to reproduce it. Therefore, we need more information.

The first thing you can try to do is provide the queries that are being sent to ES when you are searching smth on the frontend. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`.

Also, double-check whether this word is indeed not in the configuration of your problematic product.

BR,
Vadym

**Comment by indunie** [comment]
Hello @vahonc,

Thank you  for attending to this.

Is this what you after.

[2024-11-25T16:02:25.650976+00:00] main.INFO: curl -XPOST 'IP_ADDRESS/_mtermvectors?pretty=true' -d '{"docs":[{"_index":"magento2-ridgeline-live_ridgeline_au_store_view_catalog_product_20241125_144203","term_statistics":true,"fields":["spelling","spelling.whitespace","search.whitespace"],"doc":{"search":"yard","spelling":"yard"},"routing":"[magento2-ridgeline-live_ridgeline_au_store_view_catalog_product_20241125_144203][0]"}]}' [] []


Thank you.

BR,
Indunie Florence

**Comment by vahonc** [comment]
@indunie,

I see that now if I tried to search "Yard" keyword in the searchbar on your website (https://ridgelineclothing.com.au/catalogsearch/result?q=yard)

It displays all yard products, without the wrong "Monsoon Jacket".  Are you was able to fix your issue?

BR,
Vadym

**Comment by indunie** [comment]
Yes @vahonc 
It has been fixed by my colleague yesterday.
He has identified a category called "Yard" was assigned to the Monsoon Jacket which caused the issue.

Thank you for attending to the issue and appreciating your time. You can close the issue.

BR,
Indunie Florence

**Comment by indunie** [comment]
Yes @vahonc
It has been fixed by my colleague yesterday.
He has identified a category called "Yard" was assigned to the Monsoon Jacket which caused the issue.

Thank you for attending to the issue and appreciating your time. You can close the issue.

BR,
Indunie Florence
