### ISSUE TITLE
Support for Elasticsearch 5.X Release

### ISSUE THREAD

**Issue by larsroettig** [Smile-SA/elasticsuite#375]
As Developer, i need  Elasticsearch 5.X Release Support. 
Because the end of life of Elasticsearch Release 2.X will be at 2017-09-30. 

Is it possible to communicate the release date public?

**I write a email on Monday but nobody answers!**

best regards

Lars

**Comment by Koc** [comment]
relates to #216

**Comment by afoucret** [comment]
This question have been replied already (#216) and to be honest we can not give a release date because the decision is not in our hands.

Actually we could add the ES 5.x support very quickly but it would make the module incompatible with Magento EE (since Magento EE embed an ES 2.x client in it's composer dependencies). Our plan is to support fully both Magento version, so we won't.

We will have to wait a little more and see if Magento is supporting ES 5.x anytime soon. This is something I will spoke to with the dev team next week at Imagine.

BR,

PS : 
* the end of life for 2.4.x branch is 2018-02-28. We will try to achieve the migration before.
* your email sent monday have just reached our dev team today, sorry for the delay
