### ISSUE TITLE
How difficult would it be to use -optimizer module with 2.2 elastic suite?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#377]
How difficult would it be to back-port -optimizers to 2.2 elastic suite?
### Preconditions

2.2 elastic suite modified

Magento Version :
2.1.2 EE

ElasticSuite Version :
2.2

Environment :
Production

Third party modules :
Lots of customizations
### Steps to reproduce

1. I would like to use optimizer module with 2.2 codebase to avoid refactoring existing working system.
2.
3.

### Expected result

1. In theory - What would break if you were to install the -optimizer module on 2.2 codebase?
2. What would require modification to make it work?
### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Hello @southerncomputer 

I don't know which kind of custom enhancement you made on top of Elasticsuite, but maybe you should try to update your system to Elasticsuite 2.3 ?

There should not be massive changes since the main feature introduced in 2.3 was the Optimizers module. You would also benefit for several bugfixes that have been added to the 2.3.x branch.

**Comment by southerncomputer** [comment]
Well i have implemented the custom stock availability filter and REFERENCE (SKU SEARCH) field patch to 2.2 and it works. I'm not so sure how these would be implemented on 2.3/2.4!
