### ISSUE TITLE
Optimizer in 2.4 does not have access to add rules to stock.qty or any reserved attributes!

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#386]
So I upgraded to latest 2.4 release, and go to try creating optimizer rule on stock.qty<1 for -90% and this option is missing from the ruleset! just attribute names are shown.

Can you work out a way to add this variable in ? Along with has_image and the other few reserved attributes!

Thanks!

**Comment by southerncomputer** [comment]
p.s. i ran into this error today:
[2017-04-09 01:28:25] report.ERROR: query_phase_execution_exception: Result window is too large, from + size must be less than or equal to: [10000] but was [27859]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter. [] []

I had to up the value to 500K in elasticsearch.yml but you may wish to consider the effects of this. My ajax navigation "More Values +" would silently disappear when you hit +

**Comment by romainruaud** [comment]
Hello @southerncomputer 

I do not understand if your second comment is related with this issue ? If it's not the case, please open a new issue for it.

I will take a look on the behavior you describe for the Optimizers.

Regards,

**Comment by romainruaud** [comment]
Hello @southerncomputer ,

I just took a look and all is working properly on 2.4 branch.

But you are right, this is not possible to create rules like "if stock qty is <operator> <given qty>"

Is this what you want us to add ?

We may consider this in a future release but for now, I think you shoud use the following workaround for your use case : instead of "boosting down" the out of stock products, why don't you consider "boosting up" the in stock products ? 

You could do this via an optimizer built like this one : 

![selection_293](https://cloud.githubusercontent.com/assets/15340849/24902839/c2efe1f4-1eab-11e7-8057-ac645dfb2531.png)

**Comment by afoucret** [comment]
"Special attributes" can be accessed with :

* has_image : Only products with image
* stock.is_in_stock : Only in stock products
* price.is_discount : Only discounted products

It may be interesting to have a stock.qty access to filter out low stock products.

**Comment by southerncomputer** [comment]
Yeah we have a ton of products with 0 stock due to the dropship nature of IT electronics and software/licensing/services/warranty's - Right now I have placed a fixed sort-order by stock.qty into the code default sort to help push them down lower. Since they are technically in-stock and available to order but at a 10:1 ratio of stock=0 to stock>1 - we still need to show these products but need to lower their priority. They are technically is_in_stock = true !

**Comment by romainruaud** [comment]
This is technically easy to add a custom condition on ```stock.qty``` field.

BUT, this can not work "as is" with configurable products : their stock.qty field is always set to 0. This is due to the fact that the value is pulled from ```cataloginventory_stock_status```.

In this table, for composite products, Magento always indicates a qty of 0 even if they are salabe, he just put the stock_status to 1 to indicate they can be bought.

So this will not be an easy going step.

Regards

**Comment by southerncomputer** [comment]
How about add stock.qty with stock_status during import? Kill both problems simply!

**Comment by romainruaud** [comment]
That's not as easy, since Magento does not compute the qty (which would be the sum of all the quantities of children products) before, we would have to do it on your own.

Two problems here : 

- This is not the responsibility of a Search Engine module to compute proper stock quantities of products, but rather the Magento's stock module to do this (and to index it on the stock index table) properly.

- Doing this during the Search index phase would cause huge impact on the performances and the processing time of the reindexation.

That's why I do not consider this one as an easy-doing for us. You could write it on your own with a Plugin on the Datasource : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/InventoryData.php

Let us know if you try it.

**Comment by romainruaud** [comment]
And of course, if you are using only simple products, you will not face this problem and could use the two commits of my branch : https://github.com/romainruaud/elasticsuite/tree/feature_optimizer-stock-qty

You may prefer adding these pieces of code via an override or Plugin instead of patching the module core, obviously.

This is working for simple products since the qty is properly computed and indexed. And I repeat, this is NOT working for composites products.

Regards,

**Comment by southerncomputer** [comment]
Thanks! Since we override stock/prices via XML calls to our supplier(s) to fetch updated costs and stock - this works well! thanks closing!

**Comment by rbrown** [comment]
@romainruaud Sorry, 5 years later I'm being really lazy, do you still have a copy of  [this branch](https://github.com/romainruaud/elasticsuite/tree/feature_optimizer-stock-qty)?
