### ISSUE TITLE
Install ElasticSuite through composer :

### ISSUE THREAD

**Issue by baokhoa1080** [Smile-SA/elasticsuite#408]
![screenshot from 2017-04-26 00-37-39](https://cloud.githubusercontent.com/assets/14296456/25399126/9576484e-2a18-11e7-92b0-091d51f06df2.png)
When i composer, have a bug.
Can you help me?

**Comment by romainruaud** [comment]
Hello.

Elasticsuite is a module for Magento2. So first of all, you have to install a working copy of Magento 2. I'm not sure you did this first step because it seems that you are installing elasticsuite in an empty directory ?

Please refer to the Magento2 [documentation](http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html) to know how to proceed.

Once you are done with Magento, you'll be able to install ElasticSuite by following our wiki.

Best regards,

**Comment by afoucret** [comment]
I also think this one is a misusage of composer.
I close the issue.
