### ISSUE TITLE
is_anchor attribute hidden and set to true

### ISSUE THREAD

**Issue by adamj88** [Smile-SA/elasticsuite#425]
Hi,

Just a question really, in the InstallData for the `Elasticsuite_Catalog` module there is the following function which hides the `is_anchor` attribute and sets it to true for all categories here: 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Setup/InstallData.php#L145-L155

The problem this brings about is we lose the ability to target types of categories based on layout handle, i.e. we would use the `catalog_category_view_type_default` handle to say this is a Category Landing Page (subcategory listing with a select few products) and we would use `catalog_category_view_type_layered` to say this is a regular filterable Category page.

With losing `is_anchor` we lose the ability to target these pages based on layout handle - how come the module needs to disable this attribute and remove it? And what would be the work around to create a category landing page?

Potentially noteworthy, in the [uninstallation wiki post](https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall) there is no mention of reverting this behaviour as well to restore this functionality.

Thanks

**Comment by romainruaud** [comment]
Hello,

first of all, you are right about the uninstall guide. We may provide an SQL query to set back the is_anchor attribute as not being hidden anymore.

This is a functional and design choice of our own to ensure a product will be correctly mapped into the Elasticsearch index as belonging to all categories from lower level to the upper. This way, we are able to find all products belonging to a level 1 category (let's say "Men") by searching for "men". We are also able to propose a category filter which will correctly display all products in any category below "Men" when filtering on this category. This also allow us to have virtual categories working properly at any level.

If you want to distinguish between top and lower level categories, you may want to explore these options : 

- Since the layout of any category is configurable, you may want to write your own piece of layout for the top level ones, and use it by setting it to the concerned categories.

- If you just plan to remove the "leftnav" part on top level categories, to prevent filtering, you may just want to use the "one column" layout which removes this block.

Let me know,

Best regards,

**Comment by afoucret** [comment]
As explained by @romainruaud it is by design

**Comment by Viper9x** [comment]
Hi @romainruaud , could you please tell me how to display only products that belong to the parent category, not include products from sub-categories? That equal is_anchor set to 0 in magento default.
