### ISSUE TITLE
Problems with Index - Products disappear after a day or so

### ISSUE THREAD

**Issue by samc2810** [Smile-SA/elasticsuite#429]
Hello Smilelabs,

we are having severe problems with the ES-Indexes right now. The Category and Search gives 0 result after a day. ie. once we reindex the products are visible, but the very next day the category and search dont deliver any products. I assume it has something to do with the "indices_pattern" for the problem doesnt exist one I change the pattern to "idx" but this wont allow me to reindex any more "Catalog Search indexer process unknown error: index_already_exists_exception: already exists". Where does the module store the index-name for the queries?

Is this behaviour known or do you a suggestion as to how I could fix this

Thanx and Cheers
Sam

### Preconditions

Magento Version : 2.1.4

ElasticSuite Version : 2.3.5

Environment : Developer

Third party modules : Custom

### Steps to reproduce

1. Reindex the Search
2. Wait till next morning

**Comment by romainruaud** [comment]
Hello.

The indices patterns is only here to ensure unicity of index names during a full reindex. That's why you should not change the pattern to a fixed one, this would prevent you from reindexing.

In fact, the default index pattern should be kept for all usages of the module, except the case where you would have production and staging indexes on the same ES cluster, where the index pattern should be prefixed to avoid collisions.

There is no problem having an index named with a 15 days ago date, since it is always aliased properly, and queried by it's alias from Magento, it could potentially be used "forever" and only using partial updates.

Does it answer your question ? 

Please try to fallback to the default ElasticSuite settings for the index naming and let us know if you have more details : How are rebuilt your indexes ? Do you use Magento's builtin "Update on Schedule" indexes ? Or "Update on save" ?

Best regards

**Comment by samc2810** [comment]
Hi there
thanks for the reply

its set to "Update on Save". I have set the indices-suffix to default again. Well its been 4 days now the products are still there. Kind of weird

**Comment by romainruaud** [comment]
I consider this one as resolved for now and I close it for our visibility on issues.

Of course, feel free to reopen it if you are still facing problems, I will take a look at it again.

Best regards,
