### ISSUE TITLE
Can I use Elasticsuite without Catalog* modules?

### ISSUE THREAD

**Issue by icbrg** [Smile-SA/elasticsuite#446]
I'm using Amasty Layered Navigation. Due to conflict I would like to use Elasticsuite only for the instant search and advancedsearch results.

I would dissable Catalog* and Virtualcategory modules (due to dependency between them)

It's possible to use elasticsuite only with the others?

**Comment by romainruaud** [comment]
Hello,

unfortunately, you are not able to disable the "ElasticsuiteCatalog" module, which is responsible for product indexing into ElasticSearch : you would have an empty index, and then no result in instant and advanced search.

Also, you may have to take a deep look into both ElasticSuiteCatalog and the Amasty module to check if they are conflicting rewrites (or preference) and conflicting layout to disable some parts of the ElasticSuiteCatalog module.

But since we cannot provide support about integrating ElasticSuite with any other third-parties extensions, especially the ones which are rewriting standard part of Magento, like the layered navigation, I won't be able to help you more. And so I close this issue for now.

Best regards, let us know how you managed to get the both working if you succeed.
