### ISSUE TITLE
A/B Testing Elastic Search vs. Default Search

### ISSUE THREAD

**Issue by jkruczynski** [Smile-SA/elasticsuite#455]
This is not a bug. 

I am trying to split test the default magento autocomplete and search results vs. the elastic search autocomplete and search results.

My first thought was to change the file below, such that it adds the two search boxes to each page.

module-elasticsuite-core/view/frontend/layout/default.xml

The problem I ran into is that both searches are using catalogsearch/result/?q=term and search/ajax/suggest/?q=term and probably the same underlying functions.

Is it possible to modify this plugin such that I would have both searches on each page, each pointing to a different url? Is it possible to change the urls for elastic search to something like this?

catalogsearchelastic/result/?q=term and searchelastic/ajax/suggest/?q=term.

Another thought is to use a new website, store or store view.

Please let me know your thoughts on this. Basically just want to know if something like this is feasible.

**Comment by romainruaud** [comment]
Hello, thank you for submitting this question, and for using our module.

AB testing is feasible. Not easy, but this can be done.

We already done it for one of our customers on Magento 1, because he wanted to AB-test our module compared with his actual Search Engine.

This was on Magento 1, but this could be done the same way in Magento 2 : 

- put a randomizer on top of the App (we did it in Varnish) : this will set a cookie (1hour) for each customer, with a 50%/50% (or something else, depending on our need) value of "elasticsuite" and "standard".

- add something in Magento, possibly in the FrontController, to set what is the search engine to use for the current session : this will require to override any part where magento is retrieving the selected search engine from the configuration, to retrieve it from the cookie value.

- same thing for the layout, you will have to write a "conditional loader" for the layout file to switch between standard Magento and the "Elasticsuite version" of the layout.

- idem for all Magento classes which are overriden by Elasticsuite : in each of them, you have to put a logical block saying : "if the random draw cookie is not elasticsuite, fallback to standard behavior".

- and of course, add as much tracking as you need in your website, to be able to compare both engines in Google Analytics or any other solution.

This way, we did not have to change the URLs. Since Elasticsuite is also used for catalog navigation, this is not possible to have different URLs for categories and to AB-test them.

Best regards,

**Comment by romainruaud** [comment]
I close the issue for our internal visibility, do not hesitate to ask any other questions if you feel you need to.

Regards,

**Comment by jkruczynski** [comment]
I think the first and the last bullet points I can handle, setting a cookie and collecting the data, but the middle three seem very difficult as I am new to Magento. 

Ideally, I would want to change the modules for elasticsuite only and not the modules for search or catalogsearch. But, I would be open to changing both if needed. 

For the changes you outlined, I understand the concept of wrapping one of the configuration settings in an if block to check for the cookie. 

You outlined three specific sections, front controller, layout and classes. Could you be a bit more specific about which files exactly?

Is it possible for you to send me the branch you did this on Magento 1? So I can see what the changes were?
