### ISSUE TITLE
Smile_ElasticsuiteCatalog schema: current version - 1.2.2, required version - 1.2.1

### ISSUE THREAD

**Issue by raybogman** [Smile-SA/elasticsuite#458]
### Preconditions

Magento Version : CE 2.1.7

ElasticSuite Version : composer require install [latest]

Environment : default

Third party modules : 

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by raybogman** [comment]
after removing the rows in "setup_module" and reinstalling it works, but not from a upgrade procedure.

**Comment by romainruaud** [comment]
Hello,

if Magento is saying the current version is "1.2.2" this means you did previously install the module version from the 2.4.x branch.

Since Magento does not provide any downgrade capability for modules, you "cannot" revert to a previous version of Elasticsuite.

But this is true for any other third party module (or even Magento core modules).

You could process the following query to fix your problem : 

`update setup_module set schema_version='1.2.1', data_version='1.2.1' where module='Smile_ElasticsuiteCatalog'

Regards

**Comment by raybogman** [comment]
thanx, everything is working
