### ISSUE TITLE
Changing category to virtual not triggers reindex

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#465]
### Preconditions

Magento Version : 2.1.7

ElasticSuite Version : 2.3.6

Environment : PHP 7.0.x

Third party modules :

### Steps to reproduce

1. Change some category to virtual
2. Apply some rules
3.

### Expected result

1. Some indexes marked as required reindex and will update by cron

### Actual result

1. no updates, all indexes are green, should run reindex manually by cli

not sure, maybe happens not only on mode switching but also when rules changed.

**Comment by romainruaud** [comment]
Hello,

I will check this one.

For me : 

- when switching a category from "standard mode" to "virtual category" : we should invalidate the index, to ensure products previously assigned to this category are correctly set out of the category.

- when creating a virtual category, or changing a previous rule : there is no need to invalidate the index, since nothing is indexed for virtual categories : The query is processed in real time when navigating to the category page, which allow the category to evolve by itself when products matching the rule are changing (Eg. a category set to "Sale : Yes" will automatically display products that have just been set as "Sale : Yes").

Regards

**Comment by Koc** [comment]
Agreed with both. Thanx for fast response

**Comment by romainruaud** [comment]
PR merged.

Please use 2.3.x branch or wait for the next minor release.

Regards
