### ISSUE TITLE
Price slider does not consider Special price

### ISSUE THREAD

**Issue by shrinet** [Smile-SA/elasticsuite#467]
Price slider filters wrong price

I checked on your demo, on http://demo.magento-elastic-suite.io/index.php/men/bottoms-men.html?price=40-83

I filtered price from 40 to 83 but it also shows products have $38.40 as special price and original $48.

My question is how can I make it to consider special price too?

**Comment by romainruaud** [comment]
Hello @shrinet and thank you for submitting this issue.

However, this is inexact.

The products which are shown are in fact impacted by a "Catalog Price Rule" saying "20% off on Women and Men pants".

Since Magento's catalog price rules are calculating apart the standard price index, we are not able to index the prices which are computed from the Catalog Price Rules into the search index.

This is due to the fact that we index prices from the `catalog_product_index_price` table, which does not contain the prices resulting from the Catalog Price Rule application.

We consider this as a native bug : Magento does the same with their Solr/ES or event MySQL fulltext search implementation and this results in the same bug. This is essentially due to the fact that the "price with catalog rule applied" is not stored anywhere by Magento. Only the value of the discount percentage is stored, which leads to the impossibility of indexing the computed price into the search engine (compute the price of each product during indexing is not a viable option because it would cause massive performance leak).

Since Magento does not fix the behavior of Catalog Prices Rules by their side, we are not able to overcome this issue.

I hope my explanation is clear enough. I close this issue for now since it's a "wontfix" for us.

Feel free to reopen it if you need more informations.

PS : I have set the Catalog Price Rule as inactive on our demo website, and all is working as intended for now.

Best regards,
