### ISSUE TITLE
How would one tickle the indexer to index new products? sql?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#486]
say If I. import 500 new products using sql-based technology - the indexer update on save does not fire off until one tries to "re-enable" a group of products by the backend interface. This is kind of cumbersome!

What equivalent sql call would also force the indexer to take action and fire off and grab only the new items to be updated/added?

Followed by a weekly full reindex.

I use index on save to avoid importing/reindexing collisions typically!

**Comment by romainruaud** [comment]
Hello @southerncomputer 

I would say : Use the "Scheduled" mode which would automatically put the new products into the changelog tables, but it seems you don't want to use this...

If your import is "pure SQL", I do not have any solution.

If you are using just a bit of PHP (maybe to read a file and launch SQL queries), you are able to retrieve the indexers via the IndexerRegistry and launch their ```execute($ids)``` method.

I close this one for now, for our internal visibility, since it is not directly related to Elasticsuite.

But do not hesitate to continue the discussion.

Best regards,
