### ISSUE TITLE
Allow prepend optimizers before sorting

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#501]
### Preconditions

Magento Version : 2.1.8

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules :

### Steps to reproduce

1. Create optimizer: only in stock products, boots 100% for all (category view, search results, etc)
2. Open category and order by price
3.

### Expected result

1. Products ordered by price, out of stock products below in stock

### Actual result

1. Products ordered by price, out of stock products above in stock

It would be nice add setting for optimizers: add optimizer before or after standard magento sorting.

**Comment by afoucret** [comment]
Let me first explain how optimizer works.

1. Optimizer modify the score of products that are targeted by rules.
   The product score are multiplied by the optimizer value (jf you have set up an opmizer to 100% the score will be doubled)

2. There is only one score per product.

3. Primary sort (price, name) is applied first and then we sort by score (desc)

Given that you can optimizer that apply before and after sorting at the same time.
By design we choose to apply optimizer after the primary score.

There is nothing we can do on this one.
