### ISSUE TITLE
Fuzzy search with 2 letters got an issue

### ISSUE THREAD

**Issue by rinjin** [Smile-SA/elasticsuite#554]
I have 3 products with description like below:
Bottle DH1
Bottle DH3
Bottle DHX
When i try to search with term "DH" or "Bottle DH", i only got Bottle DH1 and Bottle DH3 as result.
Bottle DHX is missing. It should be appears as well with Fuzziness from "DH" to "DHX"

The configuration of my fuzziness search in magento is:
![image](https://user-images.githubusercontent.com/5639592/31271610-5c50765a-aab2-11e7-9aea-f84730afbe4e.png)

I'm using Mangento CE 2.1.8 with elasticsuite 2.4.5 under PHP 7.0.24 with Apache Server 2.4.

I really need your help on this. please let me know if i miss some configuration. Thanks.

**Comment by afoucret** [comment]
In your example, fuzzy search is not triggered.

The search index is configured (by default) to tokenize the on whitespace and when non alphabetic characters are present.

So in your example you will have the following string indexed :

* `Bottle DH1` -> `["bottle", "dh", "1", "dh1"]`
* `Bootle DH3` -> `["bottle", "dh", "3", "dh3"]`
* `Bootle DH3` -> `["bottle", "dhx"]`

`dh1` is indexed as `dh`, `1`  and `dh1` (original string) because there is a numeric char in the input string.
`dhx` is indexed only has a `dhx` because it contains only letters.

As a result you have two exact matches in the index for the string `DH` and fuzziness is not used at all.

A good workaround would be to use a `-` symbol in the name of the product :

* Bottle DH-1
* Bottle DH-3
* Bottle DH-X

You may also try to tune the analysis of the strings by overriding the filters in `elasticsuite_analysis.xml` but it require a solid understanding of ElasticSearch ... and you may have to struglle with othe side effects.

Using a thesaurus of expansions is another option you should consider.

From my POV the behavior is expected.

**Comment by rinjin** [comment]
Nice explanation. Now i understand. Thank you @afoucret.
