### ISSUE TITLE
Show price filter similar to basic magento 2 layered navigation price filter

### ISSUE THREAD

**Issue by roomantsov** [Smile-SA/elasticsuite#555]
In smile elsticsearch on catalog page appears price range, but I need to make list of price options like:
![screenshot from 2017-10-06 13-01-41](https://user-images.githubusercontent.com/16782639/31273271-8e8cca54-aa96-11e7-884d-6e825c790881.png)

Can anyone tell me how to do this?

**Comment by pkbhadkoliya** [comment]
@roomantsov have you resolved this yet? I am also interested in it.

**Comment by blueflykeelo** [comment]
I also need the price ranges. How do you disable the price slider?

**Comment by romainruaud** [comment]
@roomantsov did you manage to code it by your side ? Wanna show a Pull Request or how it's done ?

Regards.

**Comment by ezest-rajesh** [comment]
Hi,

I want to remove price slider from left layered navigation, please provide a patch to remove the slider.

Best Regards,
Rajesh

**Comment by kp-bv** [comment]
Hello,

Any solution for the same? I also want to use default price filter of M2 in layered navigation.

**Comment by kp-bv** [comment]
@romainruaud Why did you close issue without solution? Can you please let me know for the same?

**Comment by romainruaud** [comment]
Hi,

we will not provide any solution for this, because : 

- we did a different implementation (and we think it's a better one)
- providing that kind of support here is out of the scope of open source maintenance policy
- nobody helped about this issue in 3 years
- frontend "legacy" implementation will slowly be replaced by GraphQl/headless and we'll deleverage on legacy frontend features.

Regards
