### ISSUE TITLE
Where to configure Ngram? 

### ISSUE THREAD

**Issue by petrich** [Smile-SA/elasticsuite#597]
Dear @all

can someone help me, i'm looking where to enable/configure ngram search in the frontend (autocomplete search)

Could not find it.

Thank you for any help/tips

Greetings

**Comment by afoucret** [comment]
We do not use the ngram search to bring the autocomplete feature.

In the past we were used to but we decided it was not precise enough and we are now using the following method :

1. We try to detect popular searches that match the use query (eg : if the user type ap -> "apple", "apple juice" and "apple pie")

2. We run a query for all products that match "apple", "apple juice" or "apple pie". The hits are suggested products and some aggregation are used to suggest relevant attributes

3. We do the same with categories

This method is not perfect, since it have to learn for popular queries and the result can be disapointing in the early days (cold start). But after few days the result is quite good and the relevance / precision is better than when you are using ngram (especially it is easier to deals with mispelling and fuzziness without sacrificing precision).

So, enabling/configuring ngram is not something you can do without coding it into ElasticSuite.
