### ISSUE TITLE
Elastic Rating

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/elasticsuite#621]
@romainruaud Please update php version 7.1 for module-elasticsuite-rating, I can't install module via composer because it required php 7.1
https://github.com/Smile-SA/magento2-module-elasticsuite-rating/issues/3

Many thanks.

**Comment by afoucret** [comment]
Hi @minhluan259 ,

I close this one since not posted in the right repo.

If @romainruaud haven't yet merged your PR or answered, it is because we have other things to get done. It is an Open Source project and by nature free of charge. If you want a guarenteed response time you should ask commercial support from our team.

BR,
