### ISSUE TITLE
Feature in Docu: What does the tracker do?

### ISSUE THREAD

**Issue by jackjackde** [Smile-SA/elasticsuite#625]
What does the tracker do and why does it submitting order details to an external domain?!

best wishes

**Comment by romainruaud** [comment]
Hello @jackjackde and thank you for using our module and submitting an issue.

The tracker does two things : 

- it collects data through a local domain (you are the only one having access to this data) about customer navigation (product view, bought, facet usage, etc...). This part is meant to be used later on our roadmap to build behavioral optimizers (boost most viewed products and things like this).

- it sends a ping to a smile domain, with the url of the website using elasticsuite. Nothing more. It is just a way for us to track the module usage. Since it's published free and does not require any subscription or account anywhere to use it, it's a way for us to have statistics about the number of websites the module is deployed on.

I hope to have answered your question. Do not hesitate if you want to know more.

**Comment by GuiltyNL** [comment]
I've disabled Tracking as a test, but it still pings the smile domain? I think with a transparent pixel? Shouldn't this be disabled too?

**Comment by DocOlson** [comment]
That ping is gone if you remove the tracker module: bin/magento module:disable Smile_ElasticsuiteTracker

**Comment by romainruaud** [comment]
You should not disable completely the Tracker module.

In future versions it will allow you to exploit the collected data (and respect the EU GDPR) to influence search results more than we did ever do.

Ping to smile.fr is only for our internal purposes and nothing more than your domain name is recorded.

Regards

**Comment by DocOlson** [comment]
It is a form of external tracking that you should be more upfront about. In germany as a shop owner you need to disclose ANY kind of tracking or use of the customers data no matter what.

**Comment by romainruaud** [comment]
The tracker will be refactored in the 2.6 version, especially to be compliant with GDPR policy (we are in concern since we are a french company with mostly european customers) : 

- customer data tracking will require customer consent with a default and extendable implementation.

- our internal tracking (the ping to t.smile.eu) will be moved inside adminhtml part exactly the same way than Magento is doing its own tracking with the AdminNotification module. Doing this will prevent us being asked about frontend/customer data tracking.

But I repeat, nothing belonging to the customer is tracked by the ping to t.smile.eu. We just collect the domain names where elasticsuite is deployed. I hope you'll understand this is the only way for us to measure the module usage, since we distribute it for free, and even with no registration needed anywhere.

Best regards.

**Comment by elvinristi** [comment]
Hello.

I'm not worried about Smile to get the data but I'm more worried that it sends on each customer request request to elasticsuite/tracker/hit/image/h.png which is executed thru Magento controller and adds one entry to elasticsuite_tracker_log_event and second to elasticsuite_tracker_log_customer_link .

Similar behaviour was on MAgento's customer logging and is known bottleneck for issues.

**Comment by GuiltyNL** [comment]
@elvinristi just disable the tracking module. The tracker in in a separate Magento Module and can be disabled.

**Comment by sharpcommerce** [comment]
We're also disabling that tracking code. However; I really like the idea of using that onsite search data to optimize the customer experience in the future. I've never gotten any updates from Smile on anything via email or online. I'd love to know when that tech is available paid or free. There are some really excellent boutique services charging bank for that type of AI. It would need to be setup with some pretty bulletproof best practices. 

Before any of that Smile should probably develop a preset for best sellers and new items to auto display at the head of each category. That would eliminate a lot of the manual work we're doing.
Powerful tool for sure when it works, thanks Smile for putting this out.
