### ISSUE TITLE
Search By SKU is not working if SKU contains any digit

### ISSUE THREAD

**Issue by ashokdubariya** [Smile-SA/elasticsuite#626]
Hello,

We are using this extension with our Magento store and we have notice that Search By SKU is not working if SKU contains any digit.

For example if we search by this SKU `EZDB` then it's return search result with valid products but if we search by `EZDB002` or `EZDB0` then it's not return any search result.

We are using SKU pattern with alphanumeric for all products.

Magento Version: 2.1.9 and 2.2
ElasticSuite Version: 2.4.1
Environment: Production

Please let us know how can we resolve this issue?

Thanks & Regards
Ashok Dubariya

**Comment by romainruaud** [comment]
Hello @ashokdubariya and thank your for using our module and submitting an issue.

Can you explain a bit more and give me some examples of your SKUs ? It sounds like you are searching only for "parts" of your SKUS, am I right ?

Regards

**Comment by ashokdubariya** [comment]
Hello @romainruaud 

Thanks for your reply.

We are trying to search with full SKU as well as part of SKU also.
You can check on our dev site here: http://devm22.easylocks.co.uk/
Please check below full SKUs.
`EZOF173`
`EZOF225`
`EZML8433`
`EZML4605`
`p5292`

So please check on our dev site and let us know if you need any further information.

**Comment by romainruaud** [comment]
I do not understand which Magento version is running on this dev site ?

First of all, SKU search has been improved in Elasticsuite 2.4 (which requires Magento 2.2). Please ensure you are testing on this version.

Another point, which has not been clearly documented, is that you must process a cache clear + a full reindex once you update the module to 2.4. This is due to the fact that the Elasticsearch mapping was changed, and the mapping is only put to the index when doing a full reindex. So if you are using Update on Save, this may have never been applied.

Could you ensure these steps are properly processed ? If the problem persists, please copy/paste your mapping here.

You can retrieve the mapping via doing a curl to your elasticsearch like this : 

`curl localhost:9200/_mapping?pretty`

Regards

**Comment by ashokdubariya** [comment]
Just for your information we are using Magento Version 2.2 and ElasticSuite Version 2.4.1 with Production environment.

As per your request we have flushed / clear cache and full re-index.

After full re-index search by SKU is seems working fine on our dev site.

Can we use ElasticSuite Version 2.4.1 with Magento version 2.1.9 ?

Thanks

**Comment by romainruaud** [comment]
Great to see that reindexing fixed your issue !

And unfortunately, no, you are not able to use Elasticsuite 2.4.1 with Magento 2.1.x You should consider upgrading Magento if you want to use latest version of Elasticsuite.

Best regards,

I close the issue since it is now fixed. Do not hesitate to reopen it if you're still facing the problem.

**Comment by inelukipg** [comment]
Hi!
Is the opposite possible?
Magento 2.2 and elasticsuite <= 2.4.1
