### ISSUE TITLE
Price Slider: Invalid number of product

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/elasticsuite#630]
### Preconditions

Php 7.1

Magento Version : 2.2.1 CE

ElasticSuite Version : 2.4

Environment : Developer

### Steps to reproduce

1. Create a Catalog Price Rule and applied rule.
2. Reindex all data
3. Go to category page and use Price Slider to filter product

### Expected result

The filter displays the correct number of products

### Actual result

1. [Screenshot, logs]
https://prnt.sc/hfrkw5
![filter slider](https://user-images.githubusercontent.com/7834473/33258579-a9e7cae6-d38c-11e7-82cb-b029d07b6fe3.png)

**Comment by romainruaud** [comment]
Since Magento's catalog price rules are calculating apart the standard price index, we are not able to index the prices which are computed from the Catalog Price Rules into the search index.

This is due to the fact that we index prices from the catalog_product_index_price table, which does not contain the prices resulting from the Catalog Price Rule application.

We consider this as a native bug : Magento does the same with their Solr/ES or even MySQL fulltext search implementation and this results in the same bug. This is essentially due to the fact that the "price with catalog rule applied" is not stored anywhere by Magento. Only the value of the discount percentage is stored, which leads to the impossibility of indexing the computed price into the search engine (compute the price of each product during indexing is not a viable option because it would cause massive performance leak).

Since Magento does not fix the behavior of Catalog Prices Rules by their side, we are not able to overcome this issue.

I hope my explanation is clear enough. I close this issue for now since it's a "wontfix" for us.

Feel free to reopen it if you need more informations.

Best regards
