### ISSUE TITLE
Custom Tool Bar Sorter is not working

### ISSUE THREAD

**Issue by varun-jyothi** [Smile-SA/elasticsuite#632]
I have already created an attribute "as_low_as" to show the custom smallest price. I have add this "as_low_as" in the toolbar so that the user can sort products based on "as_low_as". But when I try to sorting by "as_low_as", it is giving product collection sorted by "entity_id". I have override "Magento\Catalog\Block\Product\ProductList\Toolbar" to get the custom collection sort by "as_low_as" and everything is correct when I dump here. But there is a "_afterLoad" function in the "Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection" which is resorting again and sort the result according based on "entity_id". For the other options like name, popularity the sorting is working perfect. Only problem with custom sorting option.
### Preconditions

Magento Version : 2.1.7

ElasticSuite Version : 2.3.11

Environment : Developer

Third party modules : Amasty Xlanding 

### Steps to reproduce

1. Create new option in toolbar by overriding Magento\Catalog\Model\Config.
2. Override Magento\Catalog\Block\Product\ProductList\Toolbar to make the custom sorter is working
3.

### Expected result

1. When selecting on the custom sorter from toolbar, it should sort based on the selected sort method rather than sorting based on entity_id 

### Actual result

1. [Screenshot, logs] Collection getting sorted based on "entity_id".

**Comment by romainruaud** [comment]
Hello @varun-jyothi and thank you for submitting this issue.

The sort by entity_id is a fallback for other sorts. I'm pretty sure your will to sort on your "as_low_as" is just ignored because the field is not sortable in the Elasticsearch index.

Are you sure you made your attribute "Used for Sort By" as *true* in the Back Office ? When I read your steps to reproduce it looks like you are just adding it to the list of the sortable fields by overriding `Magento\Catalog\Model\Config`.

This is not the proper way to do.

Please try to : 

- Set your attribute to "Used for Sort By" : *true* in the Back-Office via the *Store > Attributes > Product* edition.

- Remove your rewrite of \Magento\Catalog\Model\Config, this is not how you should do it. Your attribute should already appear in frontend when it is set to be used for sort by.

- Process a full reindex so Elasticsearch will compute properly attribute values to sort on this field.

This should work at this step.

Regards

**Comment by varun-jyothi** [comment]
Hi @romainruaud ,

I have already set the "as_low_as" to "yes" in Used for Sort By option. However, if I remove the override, it will not appear in the tool bar option.
Below is the function from "\Magento\Catalog\Model\Config"
`/**
     * Retrieve Attributes Used for Sort by as array
     * key = code, value = name
     *
     * @return array
     */
    public function getAttributeUsedForSortByArray()
    {
        $options = ['position' => __('Position')];
        foreach ($this->getAttributesUsedForSortBy() as $attribute) {
            /* @var $attribute \Magento\Eav\Model\Entity\Attribute\AbstractAttribute */
            if ($attribute->getAttributeCode() == 'price') {
                continue;
            }
            $options[$attribute->getAttributeCode()] = $attribute->getStoreLabel();
        }
        $options['as_low_as'] = __('Price');
        return $options;
    }`
Here I am replacing the price sort with "as_low_as".

and in the "Block\Product\ProductList\Toolbar.php", I have override the method as

`/**
     * Set collection to pager
     *
     * @param \Magento\Framework\Data\Collection $collection
     * @return $this
     */
    public function setCollection($collection)
    {
        $this->_collection = $collection;
        $this->_collection->setCurPage($this->getCurrentPage());
        $asLowattributeId = $this->_eavAttribute->getIdByCode('catalog_product', 'as_low_as');

        // we need to set pagination only if passed value integer and more that 0
        $limit = (int)$this->getLimit();
        if ($limit) {
            $this->_collection->setPageSize($limit);
        }
        if ($this->getCurrentOrder()) {
            if ($this->getCurrentOrder() == 'as_low_as') {
                if ($this->getCurrentDirection() == 'asc') {
                    $this->_collection
                    ->getSelect()
                    ->joinLeft(
                            ['cpe' => $collection->getTable('catalog_product_entity_varchar')], 'e.entity_id = cpe.entity_id')->where('cpe.attribute_id ='.$asLowattributeId);
                    $this->_collection->getSelect()->order(new \Zend_Db_Expr('cpe.value+0 ASC'));

                }  elseif ($this->getCurrentDirection() == 'desc') {
                    $this->_collection
                    ->getSelect()
                    ->joinLeft(
                            ['cpe' => $collection->getTable('catalog_product_entity_varchar')], 'e.entity_id = cpe.entity_id')->where('cpe.attribute_id ='.$asLowattributeId);
                    $this->_collection->getSelect()->order(new \Zend_Db_Expr('cpe.value+0 DESC'));
                }
            } else {
                $this->_collection->setOrder($this->getCurrentOrder(), $this->getCurrentDirection());
            }
        }
        
        return $this;
    }`

I have perform a full reindex but no luck. In the mean time I have upgrade magento to 2.1.10.

**Comment by romainruaud** [comment]
@varun-jyothi you are doing it wrong.

You do not have to rewrite the Toolbar to add an attribute to sort. You also do not have to sort directly via SQL since you are using Elasticsearch engine...

Please remove all of your rewrites and just do this : 

- Set the attribute as "Used for sort By"

Look here, it should be added to the toolbar automatically : 

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/Config.php#L454

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/ResourceModel/Config.php#L144

The engine will then do the trick when you select this attribute for sorting.

Regards

**Comment by varun-jyothi** [comment]
@romainruaud ,
Thanks, It is fixed
