### ISSUE TITLE
Incorrect HTTP method for uri [/catalog_product_20171201_124200]......

### ISSUE THREAD

**Issue by salmanazeez786** [Smile-SA/elasticsuite#642]
While installing the ElasticSuite module 

after running  'bin/magento setup:upgrade' command im getting the below error and the upgrade stops.

**Module 'Magento_Variable':
Module 'Magento_Braintree':
Module 'Magento_Version':
Module 'Magento_Webapi':
Module 'Magento_WebapiSecurity':
Module 'Magento_Weee':
Module 'Magento_CatalogWidget':
Module 'Magento_Wishlist':
Module 'Shopial_Facebook':
Module 'Shopmonk_Common':
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Incorrect HTTP method for uri [/smk_global_local_default_catalog_product_20171201_124200] and method [POST], allowed: [HEAD, DELETE, PUT, GET]**
### Preconditions

Magento Version : 2.2.1

ElasticSuite Version : 2.4.0

Environment : Developer

Third party modules : None

**Comment by afoucret** [comment]
This one is due to an invalid ES version.
You are using ES >= 5.0 which is unsupported. You have to use ES 2.x instead.

We hope to achieve ES 5.x support (see PR #623) in few days and it will be part of the next stable release.
It depends on an issue posted on the ES PHP client.

Closed for working as expected with ES 5.x
