### ISSUE TITLE
Facet coverage rate only accounting attribute set hits?

### ISSUE THREAD

**Issue by reviskar** [Smile-SA/elasticsuite#645]
### Preconditions

Magento Version : 2.1.9CE

ElasticSuite Version :  "2.3.6"

Environment : Production / Developer

### Steps to reproduce

1. Have thousands of products divided over 6 main attribute sets
2. Create a new product attribute in Admin (in our case it's an option list) and set the field for ~100 products that can be in any attribute set.
3. Set the facet to lets say 50%

### Expected result

1. The filter not shown when all products are listed
2. The filter should not be shown when there are less than 50% products in the list that have the field set. (For example with these results, no list with more than 200 products could be logically valid to show the filter)

### Actual result

1. The filter IS shown in all category views

When I dug into the code that is responsible for this, I found `Smile\ElasticsuiteCatalog\Block\Navigation::addFacets()`, where every filter candidate is counted using the `$countBySetId` count. This couldn't logically work for anything other than attribute_set_id facets, because for every filter, the count for the specific attribute set only is used. Every filter gets the same `facetCoverageRate` and therefore the specific hit rate for that attribute is totally pointless. Looking at the code the problem should be worst when all products are in the same attribute set, because then all the filters must have the same `$currentCoverageRate` (if it's not 0) and therefore yield the same results.

I do hope, I've terribly misread something, but for now, I definitely need help with this one.

**Comment by romainruaud** [comment]
You are right, we do count the "expected number of products" having a value for a given attribute according to the attribute sets.

This is essentially done like this for performance issues, because processing a query with a facet on all filterable attributes could be costly.

But I do not understand what do you mean by "Every filter gets the same facetCoverageRate and therefore the specific hit rate for that attribute is totally pointless".

That's not exactly the case. Lets say you have the following attributes sets : 

 Attr. set | Attributes
-----------|--------------
 A | attr1, attr2
 B | attr1, attr2, attr3
 C | attr2, attr3

If your search query matches 10 products of A, 5 products of B, and 5 products of C (25 results), you will have : 

attr1 : 15
attr2 : 25
attr3 : 10

I hope this part is clear enough for you, do not hesitate if you need more informations.

However, for PR #602 I did introduce a new field on the ES index, called "indexed_attributes" which will contains an array of all attributes indexed for each product, and also a `CoverageProvider` class which will allow us to proceed a refactoring of the coverage system later once this PR would have been merged.

Regards

**Comment by reviskar** [comment]
Thanks for your quick response.
Yeah you are right as to how The counts for different sets are calculated. I guess we are using attribute sets differently than we should, I guess? We have basically 5 attribute sets where 3-4 of them cover in total 20% and the other cover remaining 80% of the products (in total 10k+ products). 
What I meant by "same coverrate" was strictly in our context, I guess, because we would like to have groups of 10-200 products with specific attributes. I'll bring an example:

Lets say one attribute set is "Non-medicine product" and the attribute is SPF factor for a suncream. You don't want to see the facet in the product-list view for a mere 100 products out of 8000, otherwise we will have most of the minor filters shown all the time (but you do want to see the facet when listing, lets say, tanning-cremes). The query would return all of the products in the attribute set, because that is where most of the products are. At this point there is no way we could divide the products in 100+ attribute sets in order to implement this faceting system. 

I hope my explanation was understandable. I do however understand Your point and I'm getting, that what we are after is not optimal for the system point of view. Well this is hardly an issue for the product owners sadly :). Will need some thinking on how to implement this.

**Comment by afoucret** [comment]
I have merged the #694 PR into the master branch.

Coverage rate are now computed using product attributes and not only attribute sets and potential attributes.

You can test the master branch or wait for the 2.5.0 release.
