### ISSUE TITLE
Price Slider Search through the product's original price not the discounted price?

### ISSUE THREAD

**Issue by zhangong0001** [Smile-SA/elasticsuite#651]
Price Slider Search through the product's original price not the discounted price?

**Comment by afoucret** [comment]
Hi @zhangong0001,

I do not understand your issue. Both observed and expected behavior is unclear for me.
Using a verb may help us to qualify the issue. By the way :

- I want the price to use the original price instead of the discounted price

- The price slider should use the discounted price instead of the original price

At last, please respect the issue reporting template.

**Comment by afoucret** [comment]
Closed for being poorly redacted and not understandable.
