### ISSUE TITLE
Question about ES Index

### ISSUE THREAD

**Issue by ngocdb** [Smile-SA/elasticsuite#664]
We have :
Magento 2.1.8
ElasticSearch: 2.4.5.
"lucene_version" : "5.5.4"
Smile/Elasticsuite: 2.4.x

In the request, I can see Smile send only index name without the post fix ({{YYYYMMdd}}_{{HHmmss}}), but ES still can return the correct data from the Index.

My question is how to set explicitly the index name of a type (e.g index name of product) to have ES return the data from the exact index.

For example: At first time I created a product index as
magento2_storeview_test_com_catalog_product_20171006_104603 (1)

After I want to do an re-index into a new index (manually create in ES) with some modifications
magento2_storeview_test_com_catalog_product_20171007_104603 (2)

But ES always use data from the old one (1), not the new one (2).

====>
How can I tell ES to use (2) instead of (1) (without deleting any index) ?

**Comment by afoucret** [comment]
magento2_storeview_test_com_catalog_product is an alias for the horodated version.
The alias is installed once the full reindex is finished and is used for all operation but full reindex (diff indexing or querying the index).
The framework automatically things so querying the catalog_product index for the store my_store will result to querying magento2_my_store_catalog_product and the alias mechanism will point out the last full reindex magento2_storeview_test_com_catalog_product_20171007_104603.

IMHO there is no reason you should use the real index name instead of the alias since the name of the index is quite unpredictable (it use the datetime of the full reindex launch). Using the real index name can cause unexpected bugs.

If you want to have some modification in the data indexed, you have to modify the reindex process to handle this modification.

BR,
