### ISSUE TITLE
How do i setup the module that it search in all store views/indices

### ISSUE THREAD

**Issue by minikist** [Smile-SA/elasticsuite#709]
### Preconditions

Magento Version : 2.2.2

ElasticSuite Version : 5.4

Environment : 

Elasticsuite modules : 2.4

### Steps to reproduce

1. setup search and works great, very nice plugin.
2.
3.

### Expected result

1. it search only in 1 store view, i hope i can set _all or prefix with wildcard (production*) for the indices 
like  curl -XGET 'http://localhost:9200/production*/_search?q=searchquery' but then from the plugin.

i'm new on the elasticsearch so i hope i will find some results here. 
Thanks already.

Let me know when you need more information.

**Comment by afoucret** [comment]
All search request are built using the `Smile\ElasticsuiteCore\Search\Request\Builder:create` method.

The first param `storeId` is mandatory here.
You can still forge your own search request without using the builder but it can be quite tricky since you will have to reproduce some logic of the search request builder to get something easy to use.
It include converting index identifier to index name (catalog_product is converted in something like magento_default_catalog_product).

What is the functionnal use case you try to achieved ?
I close as not being a bug but a support question.

**Comment by minikist** [comment]
Thanks for the fast response, is it better to override the store id with one name our is it better to have multiple indices and change the search query with _all (when it is the search query how can i do that)?

**Comment by minikist** [comment]
Sorry any suggestions? or do you have a place where i can place this kind of questions?

**Comment by minikist** [comment]
Thanks, I finally found the way how i could change. I set the index to "_all". But i have a speed issue before i did this and after. The demo store is serieusly fast with 250ms response.

The store that we use has +/- 100K products 64G mem and 24 Threads. The heap is set to 2G but the response time +/- 6 sec. can you give me advise how i can speed this up. 

The server is less then 25% cpu use and 20G is used witouth chace and with cache 42G.

Thanks again.
