### ISSUE TITLE
Search in words (wildcard)

### ISSUE THREAD

**Issue by markusbengel** [Smile-SA/elasticsuite#710]
### Preconditions

Magento Version : CE 2.1.9

ElasticSuite Version : 2.3

Environment : Developer and Production

### Steps to reproduce

1. Install this awesome module
2. perform search for "acryl"

### Expected result

1. results should include entries that contain "acryl" in name, no matter in what position.

### Actual result

1. result only contains products that start with "acryl" or name is exactly the searchphrase. names containing e.g. "fugenacryl" are not found.

Is there a way to configure a 'wildcard search' to perform a search query like "\*acryl\*"?

**Comment by markusbengel** [comment]
@afoucret : Will this feature be implemented in near future? Or could you provide a quick&dirty fix respectively a little hint where we could start to fiddling in a temporary workaround?

In the meantime we're using ElasticSuite Version 2.4 and still struggling. :-\\

**Comment by afoucret** [comment]
Hi @markusbengel,

Sadly, we did not plan anything on this one and it is a low priority.

As far as I understand, you don't really want to be able to search by partial match ...
Your need would be to be able to have a viable decomposition for german word. It can be a little tricky to get things done but it is not impossible using custom analysis plugin like this one : https://github.com/jprante/elasticsearch-analysis-german

We can assist you in setting such a solution as part of our commercial support. If you are interested in such a support you can mail me at aurelien.foucret@smile.fr.

BR,

**Comment by markusbengel** [comment]
Thanks for the offer, I will gladly come back to it if needed! :)
Well in fact I want to be able to search by partial match, the above case was just an example.
Another example to clarify: a product named **Exampleproduct** will be found if i search for _exam_, _exampleprod_, etc. but unfortunately it won't be found by searching for _product_ or _amplepro_ or whatever part of the product name not matching the beginning.
I'm desperately searching for a solution to that requirement...

**Comment by afoucret** [comment]
To be fully honest with you, ElasticSearch is not designed to work on partial search.
That's why you won't find so mush litterature on this point.

You can implement it but it will be at the expense of performance since the only method is to implement a regexp matching which looks lke a brute force attack on the index to try every word combination (the equivalent of a LIKE %text% clause in SQL).

More generally people that design search engines prefer to index meaningful tokens and map the user query on this tokens (that is why I have proposed a decomposition based on the german language rule in your case).

In the end, there is very few big online shop that allows partial match. The question have already been raised internaly and after a few benchmarking we conclude that no big player (such as Amazon) are doing well with partial search. That's why I put this one as a low priority feature.

**Comment by romainruaud** [comment]
Discarded, we won't implement this for reasons explained above.

**Comment by onepack** [comment]
Not implementing partial search is like running a car that only drives straight. clients have product names that are hard to remember or too long to write for some customers. Hemoglobin will be searched like Hemo. Not giving any results is like not caring about your customers. Frankly i'm angry. I just implemented elasticsearch on 8 shops as search by mysql is stopping. Now what to do?
How can I explain my customers that their customers need to search for the complete word or else 0.
This is out of this world in sense en logic.

**Comment by LiamKarlMitchell** [comment]
So I've got something like this.
```
curl -s -XPOST 'localhost:9200/magento2_default_catalog_product/_search?pretty&size=10000' -d '
{
    "query": {
        "wildcard" : { "sku.untouched" : "*123*" }
    }
}' | jq .hits.hits[]._source.sku
```

Ideally would map a sku.clean with only alpha numeric non analyzed/tokenized whatever its called.

Then wildcard search would work even if it starts or ends with letters. (Currently it has weird results)

The hard part is implementing it, what files and plugin/method should I extend in my own module to add this into the catalog product search?
