### ISSUE TITLE
Unable to connect ElasticSearch server : No alive nodes found during setup

### ISSUE THREAD

**Issue by krisdante** [Smile-SA/elasticsuite#726]
It is not possible to perform a clean install of Magento. Error is visible on console:
Unable to connect ElasticSearch server : No alive nodes found during setup

### Preconditions

Magento Version : 2.2

ElasticSuite Version : 2.5

Environment : Dev, does not matter

### Steps to reproduce

1. Clean database (fresh Magento install with ElasticSuite added (via composer))
2. Execute 
bin/magento setup:install --backend-frontname=admin --session-save=db --db-host=127.0.0.1 --db-user=vagrant --db-password=vagrant --db-name=vagrant --use-rewrites=1 --admin-user=admin --admin-password=vagrant0 --admin-email=admin@vagrant.me --admin-firstname=foo --admin-lastname=bar --language=en_US --currency=EUR --key=1234567890 --base-url=http://vagrant.me/

### Expected result

1. Shop will set up (create initial DB) (at this point shop do not have to know anything about Elasticsearch

### Actual result

1. There is an error thrown to console:
Unable to connect ElasticSearch server : No alive nodes found in your cluster

**Comment by romainruaud** [comment]
Hello @krisdante 

You should use the dedicated parameters that elasticsuite is offering for setup:install : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-not-installed-yet-

**Comment by afoucret** [comment]
@krisdante 

The extension comes with ElasticSuite configured as default search engine. So by default and during the setup, we assume you have an ElasticSearch server running and we create all required indices in it. 

With ElasticSuite >= 2.5.0, you have new params that allow as pointed out by @romainruaud in his response.

It is something the community have asked for a while (see #692 but there is others issues related). And we consider that nobody is installing ElasticSuite in order to keep it disabled, so if you install ElasticSuite, you need an ElasticSearch server running at install time ... just as you need a MySQL server ...

BR

**Comment by afoucret** [comment]
For MTFSee PR #693 by @careys7
It explained how to add params to the integration tests.

Note : 
* you need ES running during the tests (just as you need MySQL is running)
* replace `es-server` with `es-hosts`
