### ISSUE TITLE
Show out of stock at last in category and search page

### ISSUE THREAD

**Issue by rahul-bhandary** [Smile-SA/elasticsuite#754]
Show out of stock at last in category and search result page

### Preconditions
Magento Version: 2.1.8 CE
ElasticSuite Version : 2.3.0
Environment: Developer mode
Third party modules: No

### Expected result
1. Go to any category or search result page
2. The out of stock products should show at last by default

I tried working with functions _renderFiltersBefore and prepareSortOrders in file 'module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php' but with no success

Kindly suggest how can I achieve this.

**Comment by romainruaud** [comment]
You could achieve it easily with an Optimizer : https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers

You just have to apply a boost on products that are in stock.

Regards

**Comment by afoucret** [comment]
I close since the feature can be achieved using optimizers

**Comment by rahul-bhandary** [comment]
It is working fine when default sort is applied. The above method doesn't work when any other sort is applied in category toolbar.

I had overwrite the class \Magento\Catalog\Block\Product\ProductList\Toolbar and applied my custom sort logic under setcollection method .

Does this effect the optimizer logic for sorting . I want to apply the Out OF Stock at last for all the sorting .

**Comment by afoucret** [comment]
It is by design. Boost will be applied on product that are equals.
e.g : For two products with the same price, in stock products will be sorted first.

The sort order priority is :
- manual sort by the admin for pinned products (both for search and category)
- sort order required by the customer if specified (name, price, ...)
- score of the product
- entity_id desc (help to keep result predictable) 

Boosts have an effect on the product score.
In categories the base score is '1'.
In fulltext searches it represents fulltext relevance.

We do not advice to change this behavior since it quite surprising for the customer that can feel flooded by ranking manipulation.

If you want to achieve this anyway, you can still had a plugin on the `Magento\Catalog\Model\Layer::prepareProductCollection` method and add the sort order with something like :

```
$collection->setOrder('stock.is_in_stock')
```

**Comment by southerncomputer** [comment]
What about using stock.qty and is_in_stock from the optimizer at the same time? Are both variables provided to the ui?

What happens if stock is negative? Numeric search or string search? 

What if stock.qty and is_in_stock are either null value?
