### ISSUE TITLE
How to remove checkbox load in filters layered navigation magento2

### ISSUE THREAD

**Issue by sanganagouda1** [Smile-SA/elasticsuite#766]
we are using magento 2.1.0  CE with smile elasticsuite version 2.2.3.
so we customized our code and showing layered navigation top of list page.and now we are working on "MULTIPLE SELECT "filters with ajax so if change "default.phtml" of smile elasticsuit page for updated checkbox which not effect to filters ???

so please do the needful.

### Steps to reproduce
1.go to category page wherelayered navigation with filters.
2.
3.

### Expected result

1.it should not reload when we select single filter.rather than select multiple filters and click apply filters button 
![pcaeo0i](https://user-images.githubusercontent.com/11024606/36419117-08879542-1657-11e8-9be7-0b49f194289f.gif)

### Actual result

1. when we click each filter select box it will reloading, so we are not able select multiple filters.

so help me to remove checkbox

**Comment by afoucret** [comment]
Closed because :

1. I don't see what you mean by "do the needful". I mean there is no bug here and you have the full ability to use your own template to fulfill your requirement. We will not change this behavior in elasticsuite

2. You are using an outdated version of elasticsuite. The template is easier to override on the later version as long as you are easy with knockout and js templating

**Comment by sanganagouda1** [comment]
yeah,
i am not asking for change in change this behavior in elasticsuite,in smile elasticsuite version 2.2.3. we customized code so we dont want to upgrade now, so is any other way to overide template and do the stuff
