### ISSUE TITLE
Configurable product won't filter based on associated product SKU's

### ISSUE THREAD

**Issue by pankajpragma** [Smile-SA/elasticsuite#791]
If I try to search product using associated SKU then I am not getting any result.  

All associated products are not visible individually, can you please help urgently to fix this issues? 

It should show Configurable products in the list because the SKU I am searching belongs to the Configurable product.

**Comment by afoucret** [comment]
@romainruaud Can you take a look at this one and how children SKUS could be indexed for composite products.

**Comment by romainruaud** [comment]
acknowledged, I'll take a look on this one

**Comment by romainruaud** [comment]
`sku` is not part of the `$forbidenChildrenAttributeCode`, however, it is not fetched from children either (since it's not an attribute but a column of the catalog_product_entity table).

We could add it to the documents in ES, but I'm not sure in which field we should add it. Imho adding it directly to the `sku` field is a bit risky because it would imply that this field become an array, and could also occur improper filtering when using this field.

Let me know your opinion on this one @afoucret .

More generally, I'm not sure grouping children fields values in fields is the best thing, because it can cause issues, eg. when using the field for sorting : I'm pretty sure sorting on "name" on a whole list of bundle products will be inconsistent, due to the fact that each product will have several values on the "name" field.

Maybe it's time to build something better on this point.

Your thoughts ?

**Comment by afoucret** [comment]
I was also thinking to a children attributes few days ago but it would be very difficult to build facets. By example the color.

The sorting problem is real and we need to address.
For this issue I think you can use the sku field safely since it is almost never used by the code.

**Comment by romainruaud** [comment]
Ok for me then, I'll provide a fix using the sku field.

**Comment by afoucret** [comment]
PR is merged in branch 2.5.x.
Will be part of the upcoming maintenance release 2.5.5
