### ISSUE TITLE
in-stock configured products do not appear on in catalog or search

### ISSUE THREAD

**Issue by caesarcxiv** [Smile-SA/elasticsuite#808]
### Preconditions

PHP 7.0

Magento Version : Magento 2.2.3

ElasticSuite Version : 2.5.4

Environment : Production

Third party modules : Porto

### Steps to reproduce

1. Install module and complete full index
2. Configured products do not appear in catalog, search or category preview on admin
3. Setting the configured products children (simple products) to visible in catalog and search cause the simple products to appear
4. products appear with module disabled

### Expected result

1.  Configured products appear in search and catalog pages

### Actual result

1. testing query directly on elastic:

{"from":0,"size":20,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"should":[{"nested":{"query":{"bool":{"must":[{"bool":{"must_not":[{"term":{"category.is_virtual":{"value":true,"boost":1.0}}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},{"terms":{"category.category_id":["5655"],"boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},"path":"category","ignore_unmapped":false,"score_mode":"none","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"minimum_should_match":"1","boost":1.0}},{"terms":{"visibility":[2,4],"boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},"boost":1.0}},"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"string"}}]}

Only produces the 2 simple products and not the configured products. There is no filter for stock status on query, only visibility of 2 and 4. Configured products are set to 4.  I'm thinking the configured products are missing from index all together.

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "magento2_us_catalog_product_20180308_064504",
        "_type" : "product",
        "_id" : "126515",
        "_score" : 1.0,
        "_source" : {

**Comment by schiedl77** [comment]
Hello,

we experience the same issue on M 2.2.2 - this also includes bundle products.

Is there a solution to this or is this expected behavior?

**Comment by romainruaud** [comment]
@schiedl77 the bug reported by @caesarcxiv was due to the fact that the "status" attribute was not configured to be "used in search : true".

This was causing the drop of all configurable products (because all of their childrens were considered inactive due to the fact we are not able to fetch their status).

A workaround for this one is to put the "status" attribute to "used in search : true" and to launch a full reindex.

If you are not able to update the "used in search" of the status attribute via the back-office (due to magento disabling the field), you can just set the "status" attribute to "Used for promo rules conditions" which is enough to get it indexed into ES.

This workaround should resolve the issue for now.

We are also working on this issue by our side and this one should be part of the next 2.5.5 release of Elasticsuite.

Regards

**Comment by schiedl77** [comment]
Thank you for the quick response - this resolved it perfectly!
