### ISSUE TITLE
Ran composer require smile/elasticsuite ^2.5.0 - then what?

### ISSUE THREAD

**Issue by KirbyFox** [Smile-SA/elasticsuite#816]
No other options appear within the Admin navigation and the filter options within the Category pages don't show the checkboxes.

What else do I need to do please?

Am I missing something.

**Comment by afoucret** [comment]
Hi @KirbyFox,

You will find the full install guide here : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

Basically you have to :

* Have an ElasticSearch server running
* Optionally configure ElasticSearch location if not running on localhost:9200 (see `bin/magento config:set -l` in the doc)
* Run `bin/magengento cache:clean`and `bin/magento setup:upgrade`
* Reindex all `bin/magengento indexer:reindex`

I close since the response is already in the documentation.
