### ISSUE TITLE
Engine configured to elasticsearch on Magento Starter Edition

### ISSUE THREAD

**Issue by etenclin** [Smile-SA/elasticsuite#820]
When I run a deployment on Magento Starter Edition the generated env.php set the search engine to "elasticsearch" instead of "elasticsuite".

### Preconditions
Magento Version : Magento Starter Edition 2.2.2
ElasticSuite Version : 2.5.0
Environment : Production/Developer mode

### Steps to reproduce
1. Install ElasticSuite into the project
2. Deploy to a Magento Cloud environment

### Expected result
1. Search engine is set to "elasticsuite" in the app/etc/env.php

### Actual result
1. Search engine is set to "elasticsearch" in the app/etc/env.php

**Comment by etenclin** [comment]
Problem solved by setting up the project variable SEARCH_CONFIGURATION with the json value below.
`{"engine":"elasticsuite","elasticsearch_server_hostname":"elasticsearch.internal","elasticsearch_server_port":"9200"}`

**Comment by etenclin** [comment]
Problem solved by setting up the project variable SEARCH_CONFIGURATION with the json value below.
`{"engine":"elasticsuite","elasticsearch_server_hostname":"elasticsearch.internal","elasticsearch_server_port":"9200"}`

**Comment by romainruaud** [comment]
Glad to see this was resolved.

Please pay attention to two things : 

- you'll have to ensure the elasticsuite host and port are properly binded to **elasticsearch.internal** : https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#ensure-proper-configuration-for-elasticsuite-host

- please do not forget to set different indices alias for staging and production, since in Magento Cloud they share a unique Elasticsearch instance : https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#ensure-proper-configuration-for-elasticsuite-indexes-alias

Feel free to keep us in touch in a separate issue if you are encountering new problems.

Regards

**Comment by afoucret** [comment]
@romainruaud : can you please have a look if there is something missing in the doc (https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall) regarding this issue.
