### ISSUE TITLE
"es-enable-ssl" is always overwritten when you use CLI "setup:config:set"

### ISSUE THREAD

**Issue by pravalitera** [Smile-SA/elasticsuite#832]
es-enable-ssl is always changed when you use CLI "setup:config:set"

### Preconditions
Magento Version : 2.2.2 CE
ElasticSuite Version : 2.5.5
Environment : Developer 

### Steps to reproduce
1. use the CLI command "setup:config:set"

### Expected result
1. to not modify es-enable-ssl if not specified

### Actual result
1. always ask to overwrite es-enable-ssl

![smile_elasticsearch_cli_bug](https://user-images.githubusercontent.com/16425832/37714952-164ef6e0-2d1b-11e8-8bae-bf757331097f.png)

**Comment by afoucret** [comment]
Hi @pravalitera,

I spotted a bug in the config:set command that make the Magento\Framework\Setup\Option\FlagConfigOption almost impossible to use.

I will report to Magento and propose a PR for this.

Thx for reporting.

**Comment by afoucret** [comment]
Seems that using the `Magento\Framework\Setup\Option\FlagConfigOption` is not a good idea since it does not allow to disable the SSL through the `config:set` once enabled.

I changed the implementation and the `--es-enable-ssl` param now take a value (0 or 1).

PR #835 implement the fix and will be part of release 2.5.7.

**Comment by pravalitera** [comment]
If only bug fixes were as fast on official Magento2 Github ^_^

Thx for your commit 👍
