### ISSUE TITLE
Layered Navigation does not display when a product is not set attributes

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/elasticsuite#842]
### Preconditions

Magento Version : 2.2.3 CE

ElasticSuite Version : 2.5.6

Environment : Developer

Third party modules :

### Steps to reproduce

1. Install new magento with elasticsuite
2. Add some new products for catalog
3. Set attributes Manufacturer, Color, Size for products
4. A product not set attributes (Manufacturer: null, Color: null, Size: null)
5. Go to catalog product on frontend

### Expected result

1. Layered Navigation displayed (Manufacture, Color, Size)

### Actual result

1. [Screenshot, logs]
Layered Navigation (Manufacture, Color, Size) does not display (only Catalog and Price Slider displayed)

When all products set attributes, Layered Navigation displayed

**Comment by romainruaud** [comment]
Hello @minhluan259 

This could be working as intended, since each attribute has a "coverage rate". Cf the documentation here : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration

This feature is here to hide some filters if not enough products in the current category/search have this attribute.

How many products do you have totally in your category ? 

Eg : if you have 5 products, 4 only are having a manufacturer, the coverage here is 80% => attribute is not displayed because of the default coverage rate being set to 90.

Regards

**Comment by minhluan259** [comment]
Thanks for your information.
This issue can be close.
