### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#847]
### Preconditions

Magento Version : 2.2.3 CE - Fresh install, no sample data

ElasticSuite Version : 2.5.6

Environment : Dev

Third party modules : None

### Steps to reproduce

1. Follow install guide https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall
2. Get to `bin/magento setup:upgrade` step and error is produced
```
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_used_in_spellcheck' in 'field list', query was: UPDATE `ys4_catalog_eav_attribute` SET `is_used_in_spellcheck` = ? WHERE (attribute_id = '73')
```

### Expected result

1. Complete install without error

**Comment by romainruaud** [comment]
Hello @refueledinc 

Are you able to tell me which attribute has the id "73" on your setup ?

**Comment by refueledinc** [comment]
Product Name

**Comment by romainruaud** [comment]
That's kinda strange, the column should have been created during the "Install Schema" part of the setup, along with the other additional columns (`is_displayed_in_autocomplete`, `facet_min_coverage_rate`, `facet_max_size` and `facet_sort_order`).

Did you give a try to removing the Smile_ElasticsuiteCatalog line from the setup_module table and try to reinstall ?

**Comment by refueledinc** [comment]
I followed https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall to remove a prior failed attempt to install. I will try now and report back shortly.

**Comment by romainruaud** [comment]
If you are removing the module to reinstall, please ensure to clean also all references to Elasticsuite in the `setup_module` table, otherwise you could be locked in with old versions and the setup will not re-play all install steps from zero.

So please ensure you did execute the following queries prior to re-installing : 

```
DELETE FROM setup_module where module='Smile_ElasticsuiteCore';
DELETE FROM setup_module where module='Smile_ElasticsuiteCatalog';
DELETE FROM setup_module where module='Smile_ElasticsuiteCatalogRule';
DELETE FROM setup_module where module='Smile_ElasticsuiteSwatches';
DELETE FROM setup_module where module='Smile_ElasticsuiteCatalogOptimizer';
DELETE FROM setup_module where module='Smile_ElasticsuiteThesaurus';
DELETE FROM setup_module where module='Smile_ElasticsuiteTracker';
DELETE FROM setup_module where module='Smile_ElasticsuiteVirtualCategory';
```

**Comment by refueledinc** [comment]
Ok, I executed delete operations and followed install guide. Now I have the error I originally had that caused me to do a reinstall the first time. Here is the original error:

```
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}
```

**Comment by romainruaud** [comment]
Ok fine,

this is due to the fact that you are not having the `phonetic` plugin on your Elasticsearch instance.

Please check this part of the installation guide about how you should configure your Elasticsearch server : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-5.x#installing-required-plugins

You have to install the `analysis-phonetic` and `analysis-icu` Elasticsearch plugins for the module to run properly.

Regards

**Comment by refueledinc** [comment]
Yes, sorry for that, that was it. Thanks for the help.

**Comment by romainruaud** [comment]
You're welcome, 

thank you for using our module.

Best regards
