### ISSUE TITLE
Can't find "Set product as new from/to" attribute in Optimizer & Virtual Category

### ISSUE THREAD

**Issue by TenzinNKhando** [Smile-SA/elasticsuite#849]
### Preconditions

When I try to create an optimizer rule, i can't find new from and to attribute. I do see a list of custom attributes and tried to replicate the same settings but still doesn't appear. I have "Use Sorting in Product Listing" enabled but still nothing.

Magento Version : 2.1.5

ElasticSuite Version : ^2.3

Environment : Developer

**Comment by romainruaud** [comment]
They do not appear because of their "complex" nature. This is mostly due to the fact they are date time attribute.

Please read the discussion on https://github.com/Smile-SA/elasticsuite/issues/410 to know why we did not support them.

You will also be able to find an example of how to implement them on PR #595 

Best regards
