### ISSUE TITLE
Product attributes missed values

### ISSUE THREAD

**Issue by Nix-id** [Smile-SA/elasticsuite#856]
Magento Version : 2.2.3

ElasticSuite Version : 2.5.6

Environment : Developer

Third party modules : Porto theme

### Steps to reproduce
I have many config product with many simple childproduct
in filter i see some attribute (not included in configuration product attributes) with missed values
for example:
attribute 1 (included in configurable): val1, val2, val3
attribute 2 (not included in configurable): val2

but i know - attribute 2 in childproducts have many different values, and inside elasticsearch records for config product have information about this values.  but i see only one value (i think it is value only from configurable product record)

**Comment by romainruaud** [comment]
Hello @Nix-id 

Unfortunately we are not able to provide open-source support for paid third-party modules, since we are not able to run it by ourselves.

For now I cannot know how the Porto theme is using the `Layer` and `Filter` blocks and models. It may be possible that he is using the legacy Magento PHP classes for these objects, or maybe even extending/rewriting them, which could cause Elasticsuite to be working non-properly.

Could you give a try with every Porto module disabled and tell me if your issue is still hapenning ?

Also can you give me a bit more details about what do you see, and where ?

- a screenshot / copypaste of data in the ES index
- screenshot of the product in the Back-Office
- screenshot of the layered navigation filters that are displayed in Front-Office.

Best regards

**Comment by afoucret** [comment]
This work just as expected by design.

Attribute are index in the parent product only if they are configuration options (the color in your case). The size is read only from the parent product (configurable) during indexing since it is not a configuration option.

You will need custom dev if you wish a different behavior on this one.

**Comment by Nix-id** [comment]
@afoucret
I make some code review about this problem.

'This work just as expected by design.'

in standart fresh copy of magento it work as you discribe
but with little difference
./vendor/magento/module-catalog-search/Model/Layer/Filter/Attribute.php
persist line in method _getItemsData()
$optionsFacetedData = $productCollection->getFacetedData($attribute->getAttributeCode());

that method return array with all values (included values from child products)
and then that array filtered.

for example - popular megaplaza layered navigation redefine method _getItemsData()
and change filtering this array - leave all values from child product.

in you modul - you ignoring data from childs and dont store that info in elastic.
./vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php
_getItemsData()
$optionsFacetedData = $productCollection->getFacetedData($this->getFilterField());

you getFacetedData  return different result if compare with same method for mysql search engine

**Comment by Nix-id** [comment]
@afoucret
pls confirm you see this

**Comment by Nix-id** [comment]
![image](https://user-images.githubusercontent.com/5024034/38917764-5db84876-42f4-11e8-81c5-eb43f2a590ef.png)

color - configurable attribute
size - not use for create config product - but exist in all product records

**Comment by simonrl** [comment]
Hi @Nix-id did you find a workaround for this? I am also interested in having it working for child products.
