### ISSUE TITLE
Product sorting doesn't work for 1column template

### ISSUE THREAD

**Issue by mageho** [Smile-SA/elasticsuite#864]
Reference : Closed Issue #332.

----------------------------------------

Good evening,

I have the same problem as @scher200.

When I pass the template to one column, whether by xml directive or by category configuration, any sort applied doesn't work at all.

I tried to disable all third modules & extensions but it still not working.

I do not have any clue, if you have coded this configuration, you must have tested it yourself, do you meet the same difficulties in your environment ?

----------------------------------------

Magento version : 2.2.3
ElasticSuite version : 2.5.6

**Comment by romainruaud** [comment]
Hello, I am able to reproduce this issue on 2.5 branch with Magento sample data.

However, issue is not occuring on Master.

I will check what differs and give you an update.

Regards

**Comment by romainruaud** [comment]
From what I can see on my environment, there might be an incorrect sequence / order in the Magento 1 column layout.


When using a 2-column layout I have : 

- we go through the Toolbar block which applies the `setOrder` to the product collection.
- collection get loaded (and so it does have the proper sortOrder at this step).


On the 1-column layout I have : 

- collection get loaded : this is triggered by `Magento\Catalog\Model\Layer\Category\AvailabilityFlag` when this model iterates on collection filters to check if they can be displayed.

- we go to the toolbar block next to this, so at this step, the collection has already been fetched from ES without any sort order, and cannot be changed.


So that's for the explanation part. I will have a look to see where is exactly positioned the Toolbar block on the 1-column layout because I guess it's actually after the layer navigation block, which is causing this issue.

I keep you in touch,

Regards

**Comment by romainruaud** [comment]
Ok,

for me it appears that this legacy layout is not doing good : https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/LayeredNavigation/view/frontend/page_layout/1column.xml

If I override it on Elasticsuite and set this directive instead (as it's already done on the `empty.xml` layout file) : 

`module-elasticsuite-catalog/view/frontend/page_layout/1column.xml`

```xml
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_layout.xsd">
    <move element="catalog.leftnav" destination="category.product.list.additional" after="-"/>
</layout>
```

Then the sorting is working properly, and the filters remain displayed on the proper location.

However, I'm not sure we should arbitrary fix it on Elasticsuite, but we may rather propose a PR to Magento for this one.

@mageho can you test this workaround by your side ? We will see how we handle it then with @afoucret 

Regards

**Comment by mageho** [comment]
I did not receive any notification from this thread, sorry for my late response.

I just checked your purposal and it works for this problem.

The only concern is about the placement of the block catalog.leftnav which is now just after the catalog toolbar.

**Comment by afoucret** [comment]
If understood, the problem is a layout one.
I close since you were able to deal with it.
