### ISSUE TITLE
Filter Attribute_name and attribute_code to remove invalid characters to elasticsearch?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#87]
Right now attributes with a period (.) in their name cause a full document failure after pushing to bulk_search indexer.

How hard would it be to filter out invalid characters before submitting to elasticsearch?

Is it possible to overload fields to cause extraneous functionality like sql-injection due to non-filtering of fields before bulk_add/edit/search?

**Comment by afoucret** [comment]
I don't know how your attribute have been created but having such a symbol is not valid in Magento as you can see here :

<img width="1003" alt="capture d ecran 2016-03-03 a 06 01 33" src="https://cloud.githubusercontent.com/assets/529238/16989555/f54615e8-4e94-11e6-8ad3-f21d1cab3640.png">

I think it have been created programmaticaly and the checks have been bypass. But it should not exists.

There is not any risk of injection in this case since control can only be bypassed by developers ...

**Comment by afoucret** [comment]
I closed the issue since such a case should never happen.
Attribute name are not used during indexing. Only code are used.
