### ISSUE TITLE
Duplicating category using virtual category returns all products

### ISSUE THREAD

**Issue by shavounet** [Smile-SA/elasticsuite#878]
In our setup, we have 2 main category roots: one internal, the other used in frontend.

### Preconditions

Magento Version : 2.2.1 EE B2C
ElasticSuite Version : 2.5.6
Environment : testing
Third party modules : the only impacting could be the Mirakl connector

### Steps to reproduce

See attached screenshot, for setup details
- we only use a "product in category" rule to replicate a category content from one root to the other
- other rules seems to work fine

### Expected result

1. only 5 products in preview

### Actual result

1. All products seems to display in preview (and in FO)
![capture d ecran 2018-04-17 a 17 22 04-fullpage](https://user-images.githubusercontent.com/2323369/38880957-3869bfb0-4267-11e8-97fd-fab986782e63.png)

**Comment by romainruaud** [comment]
First of all, I do not think that having a "shadow category tree" and mimic it with virtual rules on an other category tree used for the frontend is a good idea...

But we'll have a look on this one.

However, I'm not sure this could work in your case, because products are indexed in Elasticsearch on a store-based index : When we build your "Main store" index, we are filtering on products that belongs to "Main store root" root category. Therefore we cannot go "upper" to catch products attached under the "internal root".

So when you decide to have a rule : "product belonging to category X", this implies that the products are effectively attached to the category X for the current store.

If the category X is actually under another root-category than the current store root one, your products are probably not flagged properly.

I'm not sure if this is clear, do not hesitate if you have other questions.

**Comment by afoucret** [comment]
Hi @shavounet,

You should not have been able to use a category that is not under the current main category root ti compose your rule. It is impossible for us to generate a cross tree rule.

Our solution (you probably won't like) will be to forbid the selection of category that are not under the current root.

BR,

**Comment by afoucret** [comment]
PR #887 merge this one and will be part of release 2.5.9.

BR,
