### ISSUE TITLE
catalog Price  cache issue with magento2

### ISSUE THREAD

**Issue by sanganagouda1** [Smile-SA/elasticsuite#882]
### Preconditions

we are using magento2.1.0 with redis cache and elastci suite and varnish cache 

Magento Version :2.1.0

ElasticSuite Version :elastic-suite 2.3.0

Environment :Developer

Third party modules cedcommerce,LOF All AJAX scroll,etc

### Steps to reproduce

1.go to admin and add special price to product then cache clean,redis cache,indexing,varnish restart
2.then frontend search bar search for that product which shows old price in autocomplete but in detail page showing update ..
3.when update catalog product with "special" price then after cleaning magento cache and radis cache,indexing then varnish restart, then updated price not showing in elastic autocomplete(old price)
### Expected result

1.when special price added and updated catalog in search autocomplete it should show updated special price..

### Actual result

1.It crosses MSRP and showing "Price " rather than "Special Price"

**Comment by romainruaud** [comment]
Hello @sanganagouda1 

First of all, you are using an outdated version of Elasticsuite. Please update at least to the latest 2.3.11 release to benefit all of our fixes.

Your bug is not a cache issue, it's due to the special price attribute not being selected when building autocomplete results. This has been resolved in #685 for 2.4.x releases.

If you cannot update your Magento & Elasticsuite version to the latest, please try this workaround via the DI : 

```xml
    <type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig">
        <arguments>
            <argument name="additionalSelectedAttributes" xsi:type="array">
                <item name="special_price" xsi:type="string">special_price</item>
                <item name="special_from_date" xsi:type="string">special_from_date</item>
                <item name="special_to_date" xsi:type="string">special_to_date</item>
            </argument>
        </arguments>
    </type>
```

Regards
