### ISSUE TITLE
Class Elasticsearch\ClientBuilder does not exist

### ISSUE THREAD

**Issue by efimov-ivan** [Smile-SA/elasticsuite#883]
Magento Version : 2.2.3
ElasticSuite Version : 2.5
Environment : developer

Third party modules :

### Steps to reproduce

I'm trying to install modules on existing magento 2, but I always getting message "Class Elasticsearch\ClientBuilder does not exist"

**Comment by afoucret** [comment]
Hi @efimov-ivan,

It is very hard for us to handle this issue since your description of how to reproduce the bug is not precise enough. 

If you want some help from us, you should follow the install guide available here https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall and notify us what precise step is failing. 

Feel free to reopen if you can provide enough detail.
