### ISSUE TITLE
ShopByAttribute, 3rd Party

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#888]
Hey there,

I need some help fixing a 3rd party extension to make it run with elastic suite enabled. It directly calls `prepareProductCollection` to create an attribute filtered collection which results in a white page (still could log nothing related)

https://gist.github.com/gewaechshaus/463b3f745967bfcc179fc64b709b944f#file-layer-php-L87

https://gist.github.com/gewaechshaus/6ea15e5799fb775074be5def3d0bc8e8

It's unclear to me how to handle this, I need some more information as I didn't fully understand the related FAQ.

Thanks + Regards
Jan

**Comment by afoucret** [comment]
Hi @gewaechshaus,

The problem you have met is due to the poor quality of the MageDelight extension.

They are squatting the Layer model and it can not work with any other extension that require a modification of this model. IMHO :
- It is a very dangerous assumption to say that nobody will modify Magento Layered navigation when you are an extension developer
- There is better way to get this done. We have done much of our layer modification (and you can believe me when I say some are huge) through plugins or by using composition and DI.

So I fear there is nothing we can do for this one.
Especially when considering that supporting third party paid extension is not part of our community support commitment. You can contact us for commercial support if it is critical for you.

**Comment by gewaechshaus** [comment]
Hi @afoucret 

thanks for clarifying...

Greetings
Jan

**Comment by gewaechshaus** [comment]
@afoucret  - We decided to drop this and rewrite a custom module from the scratch. The goal should be to surf through attribute filtered listings like shop by manufacturer (brand). Can you recommend a good starting point or any resources? We would make this available for all as a public Repo.
