### ISSUE TITLE
Want to have the categories be part of the layered nav

### ISSUE THREAD

**Issue by blueflykeelo** [Smile-SA/elasticsuite#896]
Is there a way to also include the categories in the layered nav similar to attributes?

Magento Version : 2.2.3
ElasticSuite Version : 2.5
Environment : N/A

**Comment by romainruaud** [comment]
Hello @blueflykeelo 

Could you please provide a bit more details ? 

I'm not sure to understand what you are willing to do ? Is the legacy category filter not enough for you ? 

Or maybe the category filter does not appear on your website frontend ?

**Comment by blueflykeelo** [comment]
I want the be able to multi select the categories, same way you can select attributes. Mageplaza has a good demo of this here.
http://lnpro.demo.mageplaza.com/women/tops-women.html?cat=23

**Comment by romainruaud** [comment]
Ok I understand better now.

This is not a feature that we actually provide. It's probably a custom module made by MagePlaza.

I flag your issue as a feature request for now.

Regards

**Comment by blueflykeelo** [comment]
Thank you. If I buy the mageplaza module will it conflict with the layered nav in elastic suite? I would basically want to override the functionality in elasticsuite.

**Comment by afoucret** [comment]
Closed because of the above comment.

**Comment by jaxtheking** [comment]
If I may add a comment... I too am looking for this feature. Why not being able to look at shirts and jumpers at the same time??
Under an SEO standpoint, does it really matter to have also the `?cat=xx` param (since a canonical metatag is set on category pages anyway)?

More importantly, currently for me the Categories facet disappears once I've selected a category - even if that category contains sub-categories of its own.
For example, I have Women > Jackets > Blazers.
On the Women page, the Categories facet only show 1 level of subcategories. If I choose Jackets, the facets disappears. How do I further filter products by sub-categories?
However, if I visit the Jackets page directly, the Categories facet does show the subcategories.

There's something odd in this, at the very least incohesive. 
Just my 2 cents.
Regards
