### ISSUE TITLE
Error in Product Filtering in Layered Navigation with 3rd Party Extension

### ISSUE THREAD

**Issue by divakarsingh** [Smile-SA/elasticsuite#905]
Hey,
I am using a 3rd party shop by brand extension and It was working fine before installing this extension. Now  It is showing 0 products in product listing by brand while I have the products with the associated brand .
![por](https://user-images.githubusercontent.com/20340857/39755689-7560fc16-52e4-11e8-95c2-8d10bce0b2b9.png)

![bad](https://user-images.githubusercontent.com/20340857/39755646-4e39db3a-52e4-11e8-97a0-a53a1ba98ebb.png)

This is my store url https://cairosapparel.com/ and shop by brand section is at bottom of the homepage named Featured Brand
![image](https://user-images.githubusercontent.com/20340857/39755857-01ddcebc-52e5-11e8-959b-e1e09dc2be80.png)
 I also tried to disable your module but after disabling any of the category page is not showing any product.

![image](https://user-images.githubusercontent.com/20340857/39756026-9605c248-52e5-11e8-8fea-a4cc52c0c47f.png)

**Comment by rikwillems** [comment]
@divakarsingh I'm investigating the same issue on my installation for the Amasty Shop by Brand extension. What I can see now the extension uses the core catalog search resource module to create a collection of products. This seems to be non-functioning with Elasticsuite. I'm working on a solution.

**Comment by divakarsingh** [comment]
I am gettting this error in my system.log file 
[2018-05-08 12:12:55] main.CRITICAL: Block catalog.leftnav throws exception and cannot be rendered. [] []
[2018-05-08 12:13:03] main.CRITICAL: There is no such adapter: elasticsuite [] []

**Comment by afoucret** [comment]
Hi @rikwillems,

There is several ticket about Amasty extensions (both for Advanced Layer Navigation and Shop By brand) already. My response is always the same. We do not support third party extensions (especially proprietary ones) as part of our community support commitment.

To be more specific about Amasty extensions, they are incompatible with ElasticSuite by nature :

- Both ElasticSuite and Amasty extensions are playing in the same functionnal field (layered navigation improvement). The functionnal collision result in the same code being overriden by both extensions and make them incompatible.

- From what I know the Amasty extension is not clean from a technical point of view and the bug seems to be caused by the fact they do not assume the search engine implementation can be different of the Magento standard one. You will have the same problem with Amasty and most search engine extensions that are not bundled in Magento. TL;DR : their implementation is flawed ...

I close for being related to a third party extensions support.

**Comment by rikwillems** [comment]
@afoucret that makes a lot of sense and I know this. Thanks for the extra clarification. The Amasty Shop by brand module injects the 'standard' url parameter for brand based on the slug they create. This is different than the parameter Elasticsearch uses which is why that part goes wrong. 

Although I did run into a situation where the getFacetedData method of the Fulltext Collection did not return the response I would expect.
