### ISSUE TITLE
Error when running di:compile

### ISSUE THREAD

**Issue by jordanvector** [Smile-SA/elasticsuite#908]
### Preconditions

Magento Version : 2.2.4 EE

ElasticSuite Version : 2.5.9

Environment : Local

Third party modules :

### Steps to reproduce

1.  Enable All Elasticsuite Modules
2. Configure Modules Per Documentation
3.  Run php bin/magento setup:di:compile

### Expected result

1.  Successful php bin/magento setup:di:compile

### Actual result

1. [Screenshot, logs]

jordanschinella@jordans-MBP ~/S/m2ee> php bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 4 mins 294.0 MiB
                                                                                 
  [ReflectionException]                                                          
  Class Smile\ElasticsuiteCore\Api\Client\ClientFactoryInterface does not exist  
                                                                                 

                                                                                 
  [ReflectionException]                                                          
  Class Smile\ElasticsuiteCore\Api\Client\ClientFactoryInterface does not exist  
                                                                                 

setup:di:compile

Elasticsearch is configured correctly and it does reindex correctly locally.  The compilation is the only part that fails

**Comment by jordanvector** [comment]
This looks like a duplicate of https://github.com/Smile-SA/magento2-module-elasticsuite-targetrule/issues/10.

Seems target rule is not yet compatibile with elasticsuite 2.5

**Comment by afoucret** [comment]
Hi @jordanvector,

This module is not supported anymore with ElasticSuite 2.5.x.
It is very unlikely that we will fix it since:
* The ElasticSearch percolation API we were using has changed a lot in ES 5.x and supporting the new version would require a lot of work
* We prefer stay focus on automated recommenders, that use target rules as an hint when available. It will come in a future release of ElasticSuite.

I close because this bug is related the target rule module which is not in the scope of the main ElasticSuite project.

BR,
