### ISSUE TITLE
Elastic search burning disk space 

### ISSUE THREAD

**Issue by faisalirfan361** [Smile-SA/elasticsuite#912]
Hi, 
  I am using magento 2 with elastic search and elasticsuite. I noticed that in 10-12 days the elastic search instance consumed 90+% of space we have 180Gb disk space on that instance. I see a lot of following indices:

magento2_default_tracking_log_event_20180510       18.2mb
magento2_default_tracking_log_event_20180419      116.7kb
magento2_default_tracking_log_event_20180423         83kb
magento2_default_tracking_log_session_20180423     43.3kb
magento2_default_tracking_log_session_20180509       191b
magento2_default_tracking_log_session_20180427       49kb
magento2_default_tracking_log_session_20180505       191b

we have less than 200 products, but I think all the space is being consumed by above tracking logs.
any ideas?

**Comment by afoucret** [comment]
Hi @faisalirfan361,

Since it records every user action in a quite exhaustive way, the tracking logs size depends of your traffic, not of your catalog size. 
But given the data you have sent it should be a several gb magnitude (18mb for the larger index * 10 days * 2 (event and sessions) = 180mb).

Depending the version of ElasticSearch you are using, there can be significant warning into your logs because we are trying to manage several versions of ES at the same time. So you should check the size of your ElasticSearch logs directory (usually `/var/log/elasticsearch`but it depend on your setup). Maybe indexing of the event data can flood the logs with warning. If so, you should lower the ES log level.

Can you check the log file size and report us please ?

**Comment by faisalirfan361** [comment]
Thank @afoucret for quick reply, I noticed that and fixed the issue  with log files, thanks a lot.

**Comment by afoucret** [comment]
@romainruaud could you please have a look at the ES server doc. We should ask user to lower their log level with ES 5.x
