### ISSUE TITLE
How to: search filtering on some children attributes

### ISSUE THREAD

**Issue by fcazalet** [Smile-SA/elasticsuite#915]
Hello everybody, 
This issue is more like a question on how to.

We are using Magento2 EE 2.2.2 with the elasticsuite 2.5.9 for fast faceted search. Our product schema is: a configurable product has 2 simple products (new and used products) wich have both a different price and stock.
Attributes state (new/used), price and stock are indexed to ES like this (just interesting fields):

`{
"entity_id":"11111111",
"attribute_set_id":"1",
"price":[
  {
	 "price":"7.7000",
	 "original_price":"14.0000",
	 "is_discount":true,
	 "customer_group_id":"0"
  },
  {
	 "price":"7.7000",
	 "original_price":"14.0000",
	 "is_discount":true,
	 "customer_group_id":"1"
  }
],
"stock":{
  "is_in_stock":false,
  "qty":0
}
}`

We are facing a problem: If a user add a filter on state (used for example) and a filter on price then results are not pertinent. Because of elasticsearch document have only one price (by customer_group).
Expected result is: Configurables products displayed have the used simple product with a price in asked range. So filters on price and state are cummulative.

Is it possible to do like that? How can we manage to filter on children attributes ?

One idea we had was to create anothers attributes on configurable to represent searching filters. But it's probably bad to modify model just for search.

Your suggestions are welcome

**Comment by afoucret** [comment]
Hi @fcazalet,

Basically you problem is a modelisation one. Configurable product are not suitable for your use case which is : 2 different offers for the same product. 

It seems to me that @romainruaud had a talk few years ago with your team and his advice was to use an offer model. Our advices remain unchanged over time.

An example of how it could be implemented is in our retailer offer (https://github.com/Smile-SA/magento2-module-offer) module which allows to filter offer by physical webshop. It is based on the offer module (https://github.com/Smile-SA/magento2-module-offer) which provides some abstractions to manage offers.

I close since it is not related to ElasticSuite core features but rather to custom dev.
