### ISSUE TITLE
Filter not visible in side bar

### ISSUE THREAD

**Issue by pankajpragma** [Smile-SA/elasticsuite#919]
The filter is not visible on the front end until we assigned to all products.

### Preconditions

We have one attribute called "Application" as Multi Select and around 40 products belong to the category where I am getting an issue.

If Application attribute assigned to all 40 products then the filter is visible in the front end. If I assign to only a few products around 30 then Application filter won't get visible. It's happening with another filter as well.

Magento Version: 2.2.3

ElasticSuite Version : 2.5.9

Environment :Development

Third party modules: No

**Comment by romainruaud** [comment]
Hello @pankajpragma 

This is working as expected and explained in the documentation, look the "Facet coverage rate" field : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration

By default, the coverage rate is set to 90, you may want to lower it a little to ensure your filter is appearing much often.

Please also note that you can configure the display and coverage rate of each attribute also by category here : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration-by-category

Best regards, I close the issue since it's working as expected.
