### ISSUE TITLE
Index Boolean Attributes as Text

### ISSUE THREAD

**Issue by wgriffiths** [Smile-SA/elasticsuite#921]
Is there a reason why when indexing boolean attributes into elastic search they are indexed as strings "0" and "1" instead of false and true?

I believe this is not supported in Elasticsearch 6. I realize that the project does not 
yet support elasticsearch 6

### Preconditions
Magento Version : Magento-EE-2.2.4_sample_data
ElasticSuite Version : 2.5.10
Elasticsearch Version : 5.5.2 

### Steps to reproduce
Standard install. Log messages seen when we re-index
```bash
 magento index:reindex catalogsearch_fulltext
```
### Expected result
```json
"has_options": false,
"required_options": false,
```
### Actual result
```json
"has_options": "0",
"required_options": "0",
```

### Elasticsearch logs
```
Expected a boolean [true/false] for property [has_options] but got [1]
Expected a boolean [true/false] for property [required_options] but got [0]
```

**Comment by afoucret** [comment]
Hi @wgriffiths,

The main reason is : it is the format stored in the MySQL database. As long ElasticSearch was supported this format we do not see any reason to process values before indexing since it would have a cost.

Since ES 6.x boolean parsing is more strict. Our current stable version (2.5.x) support both ES 2.x and ES 5.x as explained in the doc. The next major release (2.6.0) will drop support for ES 2.x and bring ES 6.x support. The code for the boolean fields is already merged on the master branch.

BR,

**Comment by afoucret** [comment]
Closed since already fixed in the master branch.

**Comment by dgtllion** [comment]
@afoucret but is there a fix or workaround for it?
We are facing this issue too. Our log file is full of those errors.

ES: 5.6.11
ElasticSuite: 2.5.14
Magento: EE 2.2.4
