### ISSUE TITLE
Issue / Lack of Facet Navigation in Admin 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#924]
I have this module on installed a few demo stores / in progress builds and I'm noticing that within one website, Catalog -> Catagories -> Select Category -> Display Settings -> Layered Navigation Filters are completely missing on all categories of one of my Magento installs.  As I looked at the others, I noticed that some categories display this, and others do not.   I'm trying to see if this is an Extension Bug or a user bug.  

### Preconditions
Magento 2.2.4, Elastic Suite 2.5 Latest

Magento Version : 2.2.4 

ElasticSuite Version : 2.5 

Environment : Production Mode

Third party modules : One, Mageworx custom options suite on the store that is completely broken 

### Steps to reproduce

1.  Go to Categories Grid 
2. Select Display Settings 

### Expected result

1. I should see Layered Navigation Filters

### Actual result

1. Layered Navigation Filters are missing 

As you'll see from the screen shot, the product sorting feature is visible, but the layered navigation seciton is completely missing. 

![screenshot-witsendmosaic test-2018 05 23-11-31-25](https://user-images.githubusercontent.com/7387019/40438142-ebca4f62-5e7c-11e8-8b5e-1153d5c8f30e.png)

**Comment by romainruaud** [comment]
Hello @duffner 

The panel is hidden on two cases : 

- You are creating a new category : in this case you have to save the category first, and then edit the layered navigation settings.

- You are editing a top level category (like root categories of websites) : This is hidden here because it has no sense to be able to edit these settings on a category which is never shown directly in front.


If your categories are not in any of these 2 cases, well I'm afraid that it could be a bug.

Could you provide more details about the concerned categories topology if it's the case ?

Regards

**Comment by duffner** [comment]
@romainruaud , 

Thank you for the update,  I found a conflicting piece of Javascript from the Mageworx module Custom Options Pro.  While I didn't notice the JS issue immediately, I caught it shortly after.  

The bug is due to poor injection on Mageworx behalf, not a fault of Elastic. 

You can close this ticket.
