### ISSUE TITLE
Magento 2 Enterprise Edition problem when Schedule Category

### ISSUE THREAD

**Issue by blindek** [Smile-SA/elasticsuite#925]
In the Magento 2 Enterprise Edition with the last ElasticSuite 2.5.x when you try to Schedule a category you get these exception: error: : Requested type does not have corresponding implementation.

### Preconditions

Linux server
Magento 2 Enterprise Edition 2.2.3
ElasticSuite 2.5.10

Magento Version : Magento 2 Enterprise Edition 2.2.3

ElasticSuite Version : ElasticSuite 2.5.10

Environment : Developer

Third party modules : /

### Steps to reproduce

1. In the Magento admin on the category editor click "Schedule new update"
2. After saving schedule you get the exception: error: : Requested type does not have corresponding implementation
3.

### Expected result

1. Succesfull schedule save.

### Actual result

1. Exception: error: : Requested type does not have corresponding 

In the log:

/var/www/merkur.stage.creatim.net/public/vendor/magento/module-staging/Model/EntityStaging.php:62)"}

**Comment by romainruaud** [comment]
Hello @blindek 

For now, I am unable to reproduce this issue on the same component version as yours.

I can click on "Schedule new update" on a category, enter a dummy name and set an update date. Then I click Save and the update appears on top of the category edit page. I am also able to save the category.

Could you please provide an extended stack trace instead of just one line ?

Are you sure that you are not using third party modules that could be adding attributes or something to the categories ? 

Regards

**Comment by afoucret** [comment]
We were not able to reproduce the issue with the detail provided.
Feel free to reopen if you are able to give us more detail.
