### ISSUE TITLE
Missing 'Show more' in navigation filter for text swatch attributes

### ISSUE THREAD

**Issue by sibhis** [Smile-SA/elasticsuite#931]
Missing 'Show more' in navigation filter for text swatch attributes
### Preconditions

Magento Version : CE 2.2.2

ElasticSuite Version : 2.5.1

Environment : Developer

Third party modules : No

### Steps to reproduce

1. Enable any text swatch attribute to filters list and set Facet max size to any value (Ex:10)
2. Load any category page or search results page
3. Check the filter items list for the corresponding attribute (Make sure that you have more number of filter items for the same text attribute than the facet max value)

### Expected result

1.It should display 10(Configured Facet max size) text swatch attribute items with 'Show more' link at the bottom to see remaining items.

### Actual result

1. It displays only 10 (Facet max size value) items for the text swatch attribute filter items

Platform independent

**Comment by romainruaud** [comment]
I agree that capping the swatches and not being able to display more items is a bug, since it's not functioning as attended.

However, in terms of UX, I'm not sure this is good to be able to cap list of swatches and if they should be searchable inside via a text field.

We'll have to thought about this one to provide the best solution regarding the UX concerns.

For now, you have probably already found the workaround, you should leverage the facet max size to ensure the swatched display will not be capped anymore, and to display the full values.

And just for us to know, are you using a huge number of values for a swatch attributes, or are you just above 10 ? What is the exact use case that you have for this attribute on your website.

Regards

**Comment by sibhis** [comment]
@romainruaud We have around 40 values to be listed. I have set Facet max size as 10 so that on the page load it would list 10 values with 'show more' link to show the remaining values.

For now we can make the workaround by leveraging the facet max size to the maximum values, But the considering point here is, it would load all values on loading the page itself, and it won't be in a same UX as other attributes. Anyway I have done this workaround now.

**Comment by afoucret** [comment]
Not sure if this issue will be easy to fix.
If it can be fixed quickly we could add the fix to version 2.5.12 planned this week.
Anyway, I let @romainruaud decide.

**Comment by romainruaud** [comment]
We decided that swatches attributes should not be capped by the facet max size. So we will : 

- disable the "facet_max_size" field for swatches attributes in the back-office.
- make it unused "by the code" when the facet are rendered.

**Comment by afoucret** [comment]
PR #1047 have been merged and will be part of the next bugfix release (2.5.15).
I close since we won't do much more on this one.

Feel free to propose a PR if you think you can introduce the show more feature and the text search in facet value in a better way. We will consider it.

**Comment by sibhis** [comment]
We managed to show the text swatches like drop down attributes, it is fine in the case of searching the facet value also. But I'm not sure about the image and colour swatch attributes.
