### ISSUE TITLE
Request size exceeded 10485760 bytes

### ISSUE THREAD

**Issue by adamrandazzo** [Smile-SA/elasticsuite#968]
While attempting to run the  `bin/magento index:reindex catalogsearch_fulltext` command, I receive an error:

```Catalog Search indexer process unknown error: {"Message":"Request size exceeded 10485760 bytes"}```

I believe this is happening because Amazon AWS limits the Elasticsearch packet size to 10MB. 

Magento Version : EE 2.2.4 B2B 

ElasticSuite Version :  Latest + B2B Extension

Environment : Developer

Third party modules : Nothing pertinent

### Steps to reproduce
1. Brand new Elasticsearch 5.5 Amazon Web Services Instance
2. Fresh installation via composer of Smile 2.5 + B2B extension for shared catalogs
3. Configuration works fine - and it is creating Indices on the elasticsearch server. However, it never populates any products.
4. There are approximately 2600 products in 100 shared catalogs on M2 B2B

### Expected result
1. It should complete the indexing

### Actual result
1. Catalog Search indexer process unknown error: {"Message":"Request size exceeded 10485760 bytes"}

<img width="518" alt="screen shot 2018-06-21 at 4 34 22 pm" src="https://user-images.githubusercontent.com/8340768/41744176-fcee5b16-7570-11e8-8bbd-715a244f59ad.png">

Any help would be greatly appreciated

**Comment by afoucret** [comment]
Hi @adamrandazzo,

As explained in many issue we do not officially support AWS ElasticSearch implementation since there is several API limitation with this implementation.

For your issue, you may be interested in reducing the batch size until it allow you to index smoothly.
You can override the default config in the module `Smile_ElasticsuiteCore` (`smile_elasticsuite_core_base_settings/indices_settings/batch_indexing_size`) in your own module 

Here is what you config.xml file should looks like :
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <smile_elasticsuite_core_base_settings>
            <indices_settings>
                <batch_indexing_size>100</batch_indexing_size> <!-- Default is 1000 -->
            </indices_settings>
        </smile_elasticsuite_core_base_settings>
</config>
```

Don't forget to load your module AFTER Smile_ElasticsuiteCore :
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MyCompany_ElasticSuiteConfig" setup_version="1.0.0">
        <sequence>
            <module name="Smile_ElasticsuiteCore" />
        </sequence>
    </module>
</config>
```

Closed since AWS is not officially supported and a workaround is provided.

BR,
