### ISSUE TITLE
Geo search Filter condition

### ISSUE THREAD

**Issue by alakhdeveloper** [Smile-SA/elasticsuite#973]
We have index the geolocation values at the elasticsearch. Now, we need to filter geolocation with the elasticsuites. how can we filter the geo location with nested condition. Please help
### Preconditions

Magento Version : CE 2.1

ElasticSuite Version : 2.3.10

Environment : developer

Third party modules :

### Steps to reproduce

1. we use nested type to store the geo location :
EX: 
field name="hyperlocal.sellerid" type="integer" nestedPath="hyperlocal" 
field name="hyperlocal.location" type="geo_shape" nestedPath="hyperlocal"
2. its indexing fine. But we are not able to add filter for the geo location with nested.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by afoucret** [comment]
Hi @alakhdeveloper,

Your issue is related to an outdated version of ElasticSuite (2.3.x) and we don't support it as part of our community / open source version support.

That being said, geo_shape and geo filters are not implemented by ElasticSuite and if you need it you will need:
    1. Implement a new query type (`Smile\ElasticsuiteCore\Search\Request\QueryInterface`)
    2. Register it against the `Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory` using DI
    3. Create a new query builder into our ElasticSearch adapter (`Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query\BuilderInterface`
    4. Register it against `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query`

Then you will have the ability to use your new query types in building queries.

I close since it does not concern a  existing feature of ElasticSuite and we do not plan to work on this.
