### ISSUE TITLE
Synonyms creates huge (hanging) query

### ISSUE THREAD

**Issue by bartdelvaux** [Smile-SA/elasticsuite#980]
### Steps to reproduce

1. Create 5 different synonyms types with 10 options
2. Reindex the thesaurus index
3. Do a search with a query that contains 5 words of the 5 synonym types. 

### Expected result

1. The synonyms should be indexed to Elasticsearch during a catalogsearch_fulltext reindex. This is how it should work in Elasticsearch with large amounts of synonyms. More info: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/analysis-synonym-tokenfilter.html 

### Actual result
1. In the query that is sent to Elasticsearch, all the synonym combinations are listed. This means that you get a query that is huge because a boolean filter is created for every synonym combination. 

- If your query contains 5 words and each word has 10 synonyms, you will get 5*10*10*10*10 = 50 000 combinations

2. Elasticsearch will be overloaded with this query and all the following queries must wait until this query is complete. This causes that PHP processes are waiting for Elasticsearch response and the site becomes unresponsive. 

3. With large amounts of synonyms, Elasticsearch will throw the error `nested: TooManyClauses[maxClauseCount is set to 1024];`. This means that 1024+ combinations are generated in Magento. Raising this limit is not the solution because the query is too large

The solution is to configure the synonyms in the catalogsearch_fulltext index during a reindex like described here: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/analysis-synonym-tokenfilter.html . Elasticsearch will handle the synonyms and Magento doesn't have to generate a huge query for this.

**Comment by afoucret** [comment]
We have chosen to not  apply synonyms at index time because this method have some drawbacks :

* On large catalog (> millions products), updating synonyms require to reindex the full catalog. It is a very costly op that can take a lot of time.

* It is not possible to have a difference between the original word and the synonym. It means losing relevance and precision (we are using an algorithm that reduce the weight of the query at every rewrite).

That being said, I think changing to index time synonyms is not the best option for your issue. Another option would be to stop generating new queries when the weight is under some treshold. This could act as of short-circuit breaker to avoid your issue (very rare when dealing with real setup ...).

This proposal allow to keep the logic of relevance in place and should be quick to develop.

**Comment by afoucret** [comment]
To test the proposed behavior (with a max number of substitution hardcoded to 2) you can edit 

`Smile\ElasticsuiteThesaurus\Model\Index` and change l.248 :

```php
if (!empty($synonymByPositions) && $substitutions < 2) {
```

**Comment by afoucret** [comment]
PR #986 is a clean implementation of the proposed solution with a configurable treshold for the max number of rewrite (default to 2).

Should be available with ElasticSuite 2.5.12.

**Comment by afoucret** [comment]
Wait for your feedback on this.

**Comment by afoucret** [comment]
The PR have been merged.
I close the issue but feel free to reopen if not happy with the solution provided.

**Comment by afoucret** [comment]
Hi @bartdelvaux,

Any feedback ?

**Comment by bartdelvaux** [comment]
Thank you for the fix.

**Comment by pinkeen** [comment]
Even with the max rewrites set to default of 2 the app manages to produce hundreds of megabytes  elastisearch queries (each one) which slow down elasticsearch, which then logs the whole query clogging the disk after a while. I am still not sure why it is.  There are around 30 thesaurus entries, the biggest one having ~40 synonyms. So even 40x40 shouldn't produce that big (hundreds of MB) of a query.

Anyway 40x40 alone is enough to produce queries big enough to be not executable at all, so it's still a problem. I'd recommend at least displaying some kind of warning when user enters big thesaurus entries.
